---
# folio-assistant-uvfs
title: 'Agent memory target: Cursor (not implemented — owner 2026-10-06)'
status: todo
type: task
created_at: 2026-10-06T18:35:16Z
updated_at: 2026-10-06T18:35:16Z
parent: folio-assistant-31ni
---

Owner 2026-10-06: bean up, DO NOT implement yet. Target format: .cursor/agents/<agent>.md and .cursor/rules/*.mdc — UNVERIFIED; may also read .claude/agents (check for duplication first). Generated by the shared memory assembler into a marked region, with a --check gate and a per-target budget that drops lowest-priority nodes and reports them. Research: see parent bean 31ni.
