---
# folio-assistant-kye5
title: 'TWO README GENERATORS claim bootstrap-tools/README.md: folio-assistant''s readme:sync:all strips the generated-by notices bootstrap-tools'' own writes'
status: in-progress
type: bug
priority: normal
created_at: 2026-10-01T09:30:25Z
updated_at: 2026-10-01T11:22:38Z
parent: folio-assistant-iirv
---

Found 2026-10-01 (PR #1769). At the bootstrap-tools pin c5e5e25, bun run readme:sync:all:check is red: folio-assistant's cat-harness/content/pipeline/readme-sections.ts rewrites the kg:roles row (adds glossary links) in a SUBMODULE this repo cannot commit to. At bootstrap-tools main (9c00c53) its own scripts/readme-sections.ts adds 'generated by bootstrap-tools' notices, which folio-assistant's generator then REMOVES. Either way the check is red, and a fix pushed upstream from here would regress bootstrap-tools.

The question is ownership, not content: D3 (owner 2026-10-01) says each instance hosts the generated outputs about itself, so a submodule's README is generated by that submodule's tools and folio-assistant should CHECK it only through bootstrap-tools' generator, or not at all.

## Done when
- [x] readme:sync:all skips (or delegates for) READMEs inside a submodule instance
- [x] readme:sync:all:check green at the current bootstrap-tools pin
- [ ] the bootstrap-tools branch claude/fervent-brahmagupta-rbwhzm (commit 2ec5eab, pushed, no PR, would regress it) deleted with the owner's ok


## 2026-10-01 — fixed in PR #1769
readme-sections --all now skips an instance whose root is a git submodule (its .git is a file) and SAYS so per README; bootstrap keeps its explicit readme:sync:bootstrap:check (green). isSubmoduleRoot is tested (file / directory / absent / this checkout's bootstrap-tools). readme:sync:all:check green. Remaining: delete bootstrap-tools branch claude/fervent-brahmagupta-rbwhzm (2ec5eab) with the owner's ok.


## 2026-10-01 — branch deletion refused by the session's git proxy
Owner said delete it. git push --delete returned HTTP 403 (organisation egress policy; not retried, per the proxy rules), and the GitHub MCP tools have no delete-ref. The owner deletes it at https://github.com/litlfred/bootstrap-tools/branches (branch claude/fervent-brahmagupta-rbwhzm, commit 2ec5eab, no PR).
