---
# folio-assistant-xsrv
title: 'ROUTE-KEYED CUTOVER, FIRST FAMILY: move docs/uml/ off main onto a route-keyed branch — one generator, one gate, bisectable'
status: in-progress
type: task
priority: normal
created_at: 2026-10-03T13:28:54Z
updated_at: 2026-10-04T13:50:14Z
parent: folio-assistant-fs43
blocked_by:
    - folio-assistant-1j3q
---

The follow-on to `1j3q` (PR #1996), which built `storage.keyedBy: "route"` and
deliberately flipped nothing. This is the first family that uses it.

## Why `docs/uml/` and not the other 48

**A-narrow, chosen over A-full.** Measured on #1966: **49 of 94** gated checks
write page files. Flipping them together cannot be bisected — a red tells you
"some page moved wrong" and nothing more. `docs/uml/` is the smallest family
that exercises every part of the mechanism:

| | |
|---|---|
| files | 126 (the `uml` auto-doc type reports 129 items across 1 sub-graph) |
| generators that write it | **1** (`scripts/gen-uml-overview.ts`, via `skill:register`) |
| gates that read it | **1** (`uml:overview:check`) |
| authored files among them | 0 — the source is `uml/`, which stays on `main` |

The single writer is the point, not a convenience: route-keying's premise is
that a route has one writer, and a family with two would be the premise failing
(see `1j3q`, "Stated falsifier").

## Done when
- [ ] a `docs-auto` sub-directory is DECLARED with `storage: { branch: …, keyedBy: "route" }` — the owner's ruling of 2026-10-03, *"auto-docs is one declared subgraph, with declared sub-sub-graphs per writer"*, which is still unimplemented: `cat-harness.json` declares ONE `docs` directory whose own description admits it holds *"some written by people and some generated from the graph"*
- [ ] the branch is seeded with a hash-verified manifest, as `2h76` seeded its two — tree ids compared against `main` before the push and again from a cold reader
- [ ] `uml:overview:check` reads the branch, and a branch it cannot fetch reports `unknown`, never a pass
- [ ] the 126 files are removed from `main` only on the owner's explicit go (`deletion-requires-confirmation`)
- [ ] measured AFTER: a merge of a branch that regenerates these pages against a `main` that also did produces 0 conflicts, where today it produces one per changed page

## Blocked on — LIFTED 2026-10-03, #1996 merged (`abe8d8253b`)

The condition this block named has been met, and the handoff below said exactly
what to do when it was: unblock and start at the first Done-when, which is the
`docs-auto` DECLARATION rather than the branch. Verified on `main`:
`cat-harness.ts:1461` reads `keyedBy: z.enum(["commit", "tip", "route"])`.

**One Done-when is NOT startable by an agent and that is deliberate** — *"the
126 files are removed from `main` only on the owner's explicit go"*. That is
`deletion-requires-confirmation`, and it means this bean can be carried as far
as declare-seed-and-read-from-the-branch while `main` keeps its copy, with the
removal a separate act the owner performs or authorises. A cutover that deletes
on its own initiative is the `plj1` shape.

The original block, kept for the record:

- **waits on:** `1j3q` / PR #1996 merging — the `keyedBy: "route"` enum value
  and `branch-store.ts`'s route write path. Nothing here is startable before
  the enum exists, because the declaration this bean writes would not parse.
- **since:** 2026-10-03T13:40Z
- **expires:** 2026-10-10T13:40Z
- **handoff:** if #1996 has merged, unblock and start at the first Done-when —
  the `docs-auto` declaration, which is the owner's 2026-10-03 ruling and is the
  real prerequisite rather than the branch. If #1996 is still open after the
  expiry, read it before assuming it is stuck: it is a schema widening with no
  declaration flipped, so a long-open PR means review capacity rather than a
  design problem, and the right move is to say so on the PR, not to rebuild it.

## Not here
`gh-pages` and `lake-cache` — `fs43`'s own last Done-when, and a different
keying (`commit`, the build stamp, per proposal §3.1).

## The eventual set is wider than "the auto-doc families" — measured on #1996

`docs/uml/` stays the first family, for the bisectability reason above. But the
conflicts #1996 itself took while waiting show the set this will eventually cover
is broader than the auto-doc output, and recording that here beats discovering it
at cutover:

| writer | artefact it made conflict | regenerated by |
|---|---|---|
| `gen-docs-auto.ts` | `docs/cat-harness/docs-auto/index/index.html` — conflicted as a **binary** file | `bun run docs:auto` |
| `subgraph-readmes.ts` | `cat-harness/docs/README.md`, on a file-COUNT row | `bun run readme:subgraphs` |
| `gen-lsi-viz.ts` | `cat-harness/docs/lsi/index.md` | `bun run lsi:viz` |
| `lsi.ts` | `test/results/lsi/cat-harness/skills.lsi.json` | `bun run lsi:skills` |
| `lsi.ts` (tool-run record) | `test/results/tool-runs/lsi-index/cat-harness/skills.tool-run.json` | `bun run lsi:skills` |
| `prov-qaqc.ts` | `docs/prov-qaqc/index.md` + a per-instance `.prov.jsonld` | `bun run prov:qaqc` |

Three separate occurrences on one PR in one afternoon, and **not one was a
decision anybody needed to make** — every resolution was "take `main`'s side,
re-run the owning generator, verify with its `:check`".

Two of these are NOT under a `docs` directory at all (`test/results/**`), which
matters for this bean's first Done-when: declaring an `auto-docs` subgraph covers
the page families and leaves the QA-sidecar and tool-run writers where they are.
Whether those belong here or with the `qa` directory's own `storage` (arc `3fva`,
commit-keyed) is a question for the cutover, not an assumption: a QA verdict is
addressed by the commit it judges, so `route` is the wrong keying for it and
`commit` is probably right. **Stated as the open question rather than answered.**

`docs/README.md` is the awkward one: its conflicting content is a generated
file-COUNT row inside an otherwise authored README. That is a file both authored
and derived, which neither `route` nor `main` cleanly owns — flagged here because
it will not fall out of the mechanism and needs a person's ruling.

## HOW the first Done-when is implemented — the mechanism already exists (2026-10-03)

The first box says the `docs-auto` declaration is *"still unimplemented"*. It is
— but **nothing has to be designed for it.** Read before building, and the
registry already carries the exact relation the owner's ruling describes.

`schemas/graph-kind-registry.ts` gives a graph kind three relevant fields:

| field | what it does | precedent already using it |
|---|---|---|
| `within` | *"the kind this one is a SUB-GRAPH of"* | declared general by the owner 2026-09-23 (#1164), for `docs/proposals/` |
| `declarationFile` | the kind's own nested declaration, naming its groups **from within** | `skills` → `skills.json`, `processes` → `processes.json` |
| `storage` (on the directory) | `{ branch, keyedBy: "route" }` | this arc |

So the owner's *"auto-docs is one declared subgraph, with declared sub-sub-graphs
per writer"* is:

- a `docs-auto` kind with **`within: "docs"`** — one declared subgraph, sitting
  inside `docs` rather than beside it;
- **`declarationFile: "docs-auto.json"`** — the sub-sub-graphs named from within,
  one per writer;
- `storage` on that directory, `keyedBy: "route"`.

`check:graph-kind-within` already holds the relation and forbids a cycle, so the
invariant is gated the day the entry lands.

### This does NOT contradict the correction above, and the distinction matters

§"CORRECTION, 2026-10-03" on `06e3` records that `docs-auto` is deliberately
**not** a graph kind. Read in full, what it rejects is a kind *handled by
`state-visualizer.ts`* — a **one-axis viewer generator**, where docs-auto is
two-axis (TYPE × SUB-GRAPH) and *"there is nowhere to put the second axis
without it becoming this file anyway"*.

That is a claim about **which generator renders it**. `within` /
`declarationFile` are about **how the graph is declared and navigated**. A kind
can be registered, related and declared from within while still being rendered
by its own generator — `gen-docs-auto.ts` stays exactly as it is, and the
correction's reasoning is untouched.

**Stated explicitly because the two readings are one word apart**, and taking the
broader one would mean inventing a parallel mechanism beside a general relation
the owner already ruled for.

### The one trap, for whoever implements it

`gen-docs-auto.ts` already holds the 11 types in `TYPES`, with `collect()`
functions that cannot live in JSON. So `docs-auto.json` must be **generated from
`TYPES`** with a `:check`, never hand-written — a hand-kept copy would be a
second answer to "what auto-doc types exist", which is the failure this
repository has paid for most often. The derivable fields are there: a type's
`id` gives the path segment, `title` the description, and `graph` names the
source graph it indexes.

**Falsifier, stated before building:** if a sub-sub-graph needs a field that
cannot be derived from `TYPES`, the manifest needs hand-authored content and the
one-source claim fails — at which point the right shape is `TYPES` reading the
manifest rather than the reverse.

## The eventual scope is ALREADY ENUMERATED — `merge-conflict-patterns.ts` (2026-10-03)

The §"eventual set is wider" note above lists six writers I happened to hit on
#1996. That was the wrong source: `scripts/merge-conflict-patterns.ts` is a
**maintained catalogue of 24 patterns**, each a family whose merge conflicts
somebody has already declared mechanically resolvable — and `merge-main.yml`'s
own header says the resolution is *"mechanical BY DECLARATION"*, so the patterns
ARE that declaration. Observed live on #1935 the same day: one bot push resolved
`docs-auto` ×1, `readme-generated-regions` ×1 and `site-data` ×3.

**And the catalogue carries its own discriminator.** `strategy` separates exactly
what `route` separates:

| `strategy` | n | what it means | keying |
|---|---|---|---|
| `take-base` | **20** | the newer generation is right; nothing to settle | **`route`** |
| `refuse` | **2** | a person must settle it — `beans`, `uploads` | `tip`, or stays on `main` |
| `qa-sidecar` | 1 | `kg-qa-sidecar`, merged by its own rule | `commit` (arc `3fva`) |
| `generated-regions` | 1 | `readme-generated-regions` — generated regions inside AUTHORED prose | **neither, and see below** |

That is not a coincidence. `take-base` and `route` are the same assertion made in
two places: *the content is a pure function of its source, so the newer one wins.*
`refuse` and `tip` are the other same assertion: *somebody decided this, so a
collision is theirs to settle.* The catalogue reached it from merge behaviour and
this arc reached it from storage; they agree, which is the strongest evidence
either is right.

### What this changes for this bean

- **The family list is not mine to invent.** `docs/uml/` stays first (one
  generator, one gate, bisectable), and the eventual set is the `take-base`
  twenty — read from that file, not restated here, because a list in a bean is a
  second answer that drifts.
- **`beans` and `uploads` are explicitly OUT**, with reasons already written:
  bean defs are *"authored work-plan state, so it is resolved by a person"*;
  uploads are *"provenance-bearing input, never regenerated"*.
- **`readme-generated-regions` is the genuinely hard one**, and the catalogue
  says why better than my earlier note did: *"their generated regions carry file
  counts and listings that every concurrent addition changes; the prose around
  them is authored, so only a hunk INSIDE a region resolves."* A file that is
  authored and derived at different offsets cannot be keyed as a whole by either
  mechanism. Still a person's ruling; now with the precise reason.

### A measurement this suggests, not yet taken

If route-keying removes the `take-base` twenty from `main`, those twenty patterns
have nothing left to resolve. **Whether the patterns should then be retired is
NOT this bean's call** — they would become harmless no-ops rather than wrong, and
a pattern that fires on nothing is the `xom7` shape this arc keeps meeting. Worth
asking the owner at cutover rather than deciding here.


## INVENTORY CORRECTED 2026-10-03, before the seed was built — 666 files, not 126, and `uml/` is an OUTPUT

Counted on `origin/main` before seeding, because a seed built from a wrong
inventory verifies its own mistake. The table in §"Why docs/uml/ and not the other
48" is wrong in both of its load-bearing rows.

`gen-uml-overview.ts` declares **three** output roots — `gen-uml-overview.ts:70`,
`:74`, `:76` — and its own run line says so: *"wrote 401 file(s) under
`cat-harness/uml/overview` and `cat-harness/docs/uml/overview`"*.

| root | const | files | a route? | declared? |
|---|---|---|---|---|
| `cat-harness/uml/overview` | `UML_ROOT` | 266 | no | yes — directory `uml`, kind `uml`, `cat-harness.json:583` |
| `cat-harness/docs/uml/overview` | `DOCS_ROOT` | 134 | **yes** | no |
| `cat-harness/docs/assets/img/uml/overview` | `SVG_ROOT` | 266 | **yes** | no |

So: **"files | 126" → 666 across three roots**, and **"the source is `uml/`" → `uml/`
is an OUTPUT of this same generator**, with a declared kind of its own. The real
source is the declarations the generator reads.

### What this does and does not change

**The premise holds and is strengthened.** "One route, one writer" was the reason
this family was chosen over the other 48; one writer owns all three roots, so the
`1j3q` falsifier ("a family with two writers would be the premise failing") is
further from being met, not closer.

**The cutover is a different shape.** Done-when 1 is asking for the two
**undeclared** roots, both of which are routes:

- two sibling entries in `cat-harness/docs/docs.json` — `path: "uml/overview"` and
  `path: "assets/img/uml/overview"` — reusing `graphKinds: ["docs-auto"]`, on the
  shared-kind precedent already cited in #2022 (`beans.json`'s `defs` and `archive`
  both declare `bean-defs`);
- then `storage: { branch: …, keyedBy: "route" }` on each.

**`cat-harness/uml/overview` stays on `main` — for a different reason than this
bean gave.** Not because it is authored (it is not), but because **it is not a
route**, which makes `keyedBy: "route"` wrong for it by definition: a route-keyed
write refuses `expect` on the grounds that a rendered page has one writer, and
`uml/` is a graph other generators read. If it is ever moved off `main` it is a
`tip` question, under `9ofm`, not this bean.

### Two things checked rather than assumed

**`docs.json` paths are relative to the declaring directory.** `proposals` declares
`path: "proposals"` and resolves to `cat-harness/docs/proposals` (38 files);
`requirements` likewise (1). So #2022's `path: "cat-harness/docs-auto"` resolves to
`cat-harness/docs/cat-harness/docs-auto`, which **exists and is populated** — as
that entry's own description explains via `viewerPlacement`. I had briefly read it
as repo-relative and so as absent, which would have been the `dh4f` defect. It is
not one.

**No `../` is needed, and none is available.** `GraphNodeDirectory.scope` carries
the note *"why it is a field rather than a `../` in the path"*, and its enum is
`instance | repository` — neither reaches a sibling of the declaring directory.
Both uml routes are inside `docs/`, so `docs.json` is the right declaring file and
both paths are plain.

### Where Done-when 1 actually stands

#2022 declared the `docs-auto` KIND and the `docs-auto` directory with its 11
sub-sub-graphs — one per `gen-docs-auto.ts` TYPE. Measured: its `uml` sub-sub-graph
holds **2 files**, the docs-auto index pages *about* the uml graph, which are not the
134 pages this bean is about. So Done-when 1 is **half done**: the kind exists and
is judged, the two route directories are still undeclared and carry no `storage`.
Not ticked.


## DONE-WHEN 2 DONE 2026-10-04 — `cat/cat-harness/uml-overview` seeded, hash-verified

Owner chose this on 2026-10-04 ("1 2 3", xsrv first) once #2032 went green. Seeded
with `2h76`'s plumbing — private index, `read-tree --prefix`, `commit-tree` with no
parent, a plain push, never `-f`.

| | |
|---|---|
| branch | `cat/cat-harness/uml-overview` (orphan) |
| commit | `ae5fb4d608437dbf022d7fbe7379daa5183771f0` |
| tree | `8fbfc3c682efeaf7d119b4a85baff9c81d709b18` |
| seeded from | `main@066efdbfa2` |
| author | `folio-state-bot`, the identity `branch-store.ts` exports as `STATE_BOT` |

**One branch for both directories, deliberately.** One generator owns them and the
pages reference the SVGs, so a single branch makes an update atomic across both.
Paths mirror the checkout, so a reader finds a file where `main` holds it.

### Hash-verified, twice, as `2h76` requires

Tree ids per path, computed locally **before** the push and again from a cold
`git init` reader with none of my objects (`fetch --depth=1 --filter=blob:none`):

    cat-harness/docs/uml/overview               5bb59f46274733a0c14533d9d048b05238a03b13
    cat-harness/docs/assets/img/uml/overview    620de680926d6282fdb12013915b9f3b9470f624

Identical in all three places, and the root tree `8fbfc3c6…` matched too. **0
mismatches.** A tree id rather than a byte-compare because a byte-compare passes on a
tree reassembled wrongly.

### And verified FUNCTIONALLY, which the hash check cannot do

`branch-store.ts` opened against the real branch, three states and all three distinct:

| opened as | result |
|---|---|
| `keyedBy: "route"` | **`hit`** — 8002 bytes, blob `abbef49926c4` |
| `keyedBy: "tip"`, same branch | **`corrupt`** — *"is keyed by route, not tip"* |
| a branch that does not exist | **`miss`** — *"does not exist on the remote"* |

The middle row is the one worth having. `BranchStoreOptions.keyedBy`'s docblock says
the keying is passed rather than sniffed because *"a reader that adopted whatever
keying the branch claimed would read a route-keyed branch as state the moment somebody
pushed the wrong manifest"* — so a mismatch must be `corrupt`, not `hit` and not
`miss`. Measured, not assumed.

### Counts moved, and that is the point of recording the base

132 pages and 262 SVGs at `main@066efdbfa2` — not the 134/266 measured hours earlier,
and not this bean's original 126. The generator reruns on every declaration change, so
a count is only meaningful beside the commit it was taken at.

### `main` is still authoritative

`manifest.json` carries `"status": "seed"`, `"authoritative": false`. Nothing reads the
branch, `main` keeps its copy, and the README on the branch says so and says not to
merge it. Next: Done-when 3, `uml:overview:check` reads the branch and an unfetchable
branch reports **unknown**; then `storage`; then — owner only — the removal.


## DONE-WHEN 3 IS NOT A STANDALONE STEP — a route-keyed branch has no WRITER, measured

Stopped before building it, because the step as written cannot stand on its own and
the missing piece is a design decision rather than an omission.

**Measured, not read.** `mountTip` and `pushMount` — the only write path with a CLI —
both call `BranchStore.open(loc.branch, { repoRoot, ...opts.store })` with **no
`keyedBy`**, so it defaults to `"tip"`. Against the branch just seeded:

    mountTip on a route-keyed branch -> corrupt
      cat/cat-harness/uml-overview is keyed by route, not tip

That is `verifiedTip` doing its job: the keying is passed rather than sniffed
precisely so a reader cannot adopt whatever a branch claims. The mount/push pair is
tip-shaped all the way down — a marker, `expect` from the mounted tip, and a refusal
for *"a directory the checkout still tracks"* — and a route-keyed `write()` **refuses
`expect`** by construction (bean `1j3q`).

### Why that blocks the reader rather than merely inconveniencing it

`uml:overview:check` compares the generator's fresh output against the authoritative
copy. Point it at the branch and the first declaration change anywhere makes the
generator's output differ from the seed, so the gate goes **red with no remedy**: no
command regenerates onto a route-keyed branch. A gate whose fix does not exist is
worse than the gate not existing — it is the `1xhc` shape, a red that trains people to
ignore reds.

So the real order is: **writer, then reader, then `storage`.** This bean's Done-when 3
assumed the writer.

### Three shapes the writer could take — the owner's call, not an agent's

| | what it is | against it |
|---|---|---|
| **(a)** pass `loc.keyedBy` through `mount`/`push` | smallest diff, one mechanism | mount semantics are tip's: a marker, `expect`, and a refusal while the checkout still tracks the path. A route store refuses `expect`, so "push the mount" has no meaning |
| **(b)** a separate `branch-store publish --id <id>` | matches the keying's own words — *"one entry per published SITE ROUTE, each replaced wholesale by the single generator that owns it"* — no mount, no marker, no `expect` | a second CLI verb, and the question of who runs it (CI on `main`? the generator?) |
| **(c)** the generator calls `BranchStore.write()` directly | no CLI at all | every future route-keyed generator rebuilds the same loop, and nothing can run it by id |

**(b)** is what the keying's definition reads like, and I have not built it: inventing
a publish mechanism unasked is the opposite of what this arc has been doing one
declared step at a time.

### What is NOT blocked

Nothing already done is affected. The branch is seeded and hash-verified, `main` stays
authoritative, `manifest.json` says `"authoritative": false`, and no declaration sets
`storage`. The repository is in a state somebody can leave it in indefinitely — which
is the whole reason the seed came before the flip.

One more thing the writer question will reach: `offCheckoutFindings` in
`check-declared-dirs.ts` skips `route`, with its reason in the docblock. The moment
`storage` is set while the files are still on `main`, that silence becomes the
`not-cut-over` state `9ofm` added for `tip` — two copies and nothing saying which is
authoritative. Extending it to `route` belongs with the flip, and the extraction done
on #2032 means there is one place to do it.

_2026-10-04T13:47:14Z_ — Claimed by claude/lucid-shannon-o8zop1-gz47-ruling — pushed to main so sibling sessions see it before this branch has a PR (bean 35nj).


---

## Measurements from another session, 2026-10-04 — NOT a claim

Appended by a sibling session that read this bean, found it claimed 13 minutes
earlier ("Claim only, no work"), and stood down. The claim is yours; this is
only what I measured before stopping, so you do not re-derive it. Status and
holder untouched.

**1. The branch is already fully seeded — Done-when "the branch is seeded with
a hash-verified manifest" is satisfied and unticked.**
`git ls-tree -r --name-only origin/cat/cat-harness/uml-overview | wc -l` = 396:
133 `.md`, 262 `.svg`, 1 `.json` (a manifest) and a README. Against `main`:
`cat-harness/docs/uml/overview` = 132 `.md`, and
`cat-harness/docs/assets/img/uml/overview` = 262 `.svg` — 394 files, 6.8 MB.
So every byte already exists at the destination, which `docs/docs.json` says is
deliberate: "BOTH during the window where the same bytes live in two places on
purpose."

**2. `gen-uml-overview.ts`'s comment about the SVGs is STALE, and it is
load-bearing for this arc.** Its `--check` block says:

> "Everything OUTSIDE the pages — the .puml model and the SVGs — stays an
> on-disk comparison: neither is a published route, so neither is route-keyed."

But the route branch carries all **262** SVGs. Somebody seeded them as a route,
so that sentence and the seeded branch disagree, and the sentence is the one
that is wrong. Consequence: the flip is TWO declarations
(`uml-overview-pages` and `uml-overview-svgs`), not one, and `compareRoute` is
called for the pages only (line 926) — there is no
`compareRoute("uml-overview-svgs", …)`.

**3. There is no `authoritative` field.** `DirectoryStorageSchema` is
`{ branch, keyedBy }` and `.strict()`, so a declaration carrying
`authoritative: true` throws rather than being ignored. Recorded because a
subagent report in my session asserted "set `storage` plus
`authoritative: true`" as the next step, which is a plausible-sounding field
that does not exist. The one live example on `main` is `cat-harness.json`'s
`qa`: `{"branch": "cat/cat-harness/qa-reports", "keyedBy": "commit"}`.

**4. `docs/docs.json` quotes a docblock section that no longer exists.** Its
`uml-overview-svgs` entry cites `DirectoryStorageSchema`'s
§"Not yet set on any declaration". That docblock now reads
§"Set on every `qa` directory since bean `5hox`". The ORDER it states
("declare, seed the branch, migrate `uml:overview:check`, and only then flip")
still holds and is still the right sequence; only the "not yet set anywhere"
premise is stale.

### Two things I did NOT establish

- Whether flipping `storage` while the 394 files remain tracked is acceptable
  as an intermediate step. `directory-storage.test.ts` ("not-cut-over: route
  gets the two-copies finding, because two copies is two copies") says it is a
  FINDING, so declaration and deletion look like one change — which is what
  `check-declared-dirs`'s own remedy text calls "ONE change". I did not run the
  gate to confirm.
- Anything about the declaration restructure your first Done-when names (the
  owner's "auto-docs is one declared subgraph, with declared sub-sub-graphs per
  writer", still unimplemented because `cat-harness.json` declares ONE `docs`
  directory). I stopped before touching it.

### One neighbour that is stale, if you are updating beans anyway

`xu0t` still says "auto-docs branch: none yet". `cat/cat-harness/uml-overview`
exists on origin at `ae5fb4d6`. Not edited here — it is not this bean.
