---
# folio-assistant-xsqm
title: 'BOOTSTRAP-TOOLS: re-create as a sibling instance; Zod, generators and checks move down; import cone to zod only'
status: completed
type: feature
priority: high
created_at: 2026-09-29T23:42:57Z
updated_at: 2026-10-01T06:58:48Z
parent: folio-assistant-vke6
---

Owner rulings, 2026-09-29 (answers to the separation analysis, Q7/Q1/Q10/Q5):

- **Zod moves DOWN into bootstrap-tools** — reverses `319n`'s placement. Across repos, Zod in cat-harness makes a bootstrap release depend on cat-harness, which depends on bootstrap. bootstrap still knows no zod (`etg1`).
- **bootstrap-tools owns content checks AND the README/SVG writers** (options 1+2), not a whole harness. Owner: *"i dont think we need 3 b/c no seperate visualizers/declared directories, just a content KG … should be swappable content — someone wants a different visualizer they can use different toolset"*.
- **Discussion `$id`s change to the file path**, and *"make QA gate for KG nodes"*: a published node's identifier must match where its file sits.
- **CI:** reusable workflow described but DISABLED; npm package yes; *"all scripts … should be in bootstrap-tools, but can also be directed to agent to play a role in a process in a chat discussion. i dont want to pay $, so can describe github actions but dont implement unless explicit user request. assume primarily agentic"*.
- **No initial commits to litlfred/bootstrap or litlfred/bootstrap-tools yet.** Staged here as a sibling directory.

Analysis: session scratchpad `separation-process-analysis.md` (94 beans, cone measurements, 11 owner questions).

## Phase 1 — core (one PR)
- [x] `bootstrap-tools/` sibling instance: declaration, package.json (zod only), not nested in bootstrap
- [x] move Zod sources (graph, model-registry, glossary-ledger, requirement, discussion), gen-bootstrap-schemas, bootstrap-schema-page, release-iri, iri-sync, term-links, check-bootstrap-concepts, dependency-order's checkDeclaredOrder
- [x] cuts E1–E4: minimal declaration reader over KnowledgeGraphDeclarationSchema; `--root`; git ls-files instead of git-corpus
- [x] repoint cat-harness's 11 import sites
- [x] generated bootstrap/schemas byte-identical before/after (except the $id fix)
- [x] discussion $ids = file path; QA gate: published node IRI = release base + its path
- [x] closure gate: bootstrap-tools imports only its own files + zod + node builtins
- [x] tests move (split graph.test.ts per the analysis §3.6)

## Phase 2 — README + SVG writers
- [x] subgraph-readmes, readme-sections (kg:processes/kg:files), render-bpmn into bootstrap-tools with cones cut — output byte-identical (78 SVGs, every README but the two template rows); standalone writes only `supports` graphs

## Owner rulings, 2026-09-30 ("go A", confirmed "yes, continue phase 3")
- Q3 publication: A — bootstrap's own site serves only what bootstrap-tools generates, the `bs:` vocabulary included; `bootstrap.jsonld` and the swimlane glossary stay harness artefacts on cat-harness's site, naming bootstrap as subject.
- Q4 tags: A — plain `v<major>.<minor>.<patch>` in each standalone repository; `check:version-bump` learns that form.
- Q2 glossary ledger: A — hosted in cat-harness beside the kg-qa sidecars; it leaves `bootstrap/glossary/`.
- Q8 history / Q9 consumption: defaults stand — `git filter-repo`; submodule at `bootstrap/`, pinned.
- #1537 (Phases 1–2) merged as 99371e8.

## Owner rulings, 2026-09-30 (second round)
- bs: vocabulary: A — exactly bootstrap's 22 defined terms + its graph kinds, generated by bootstrap-tools; cat-harness's export stops minting `bootstrap:Directory`/`KGraph` (uses bootstrap's Subgraph/KnowledgeGraph) and moves the `*Graph` classes + `performerVaries` to its own namespace.
- swimlane-glossary kind + glossary-ledger schema: A — move up to cat-harness with the hosted ledger.
- bootstrap.jsonld: "should be in bootstrap-tools. check related." — the exported graph of bootstrap is produced by bootstrap-tools (this narrows Q3 A: it is no longer a harness artefact).
- site publisher: A — publish-instance-files moves to bootstrap-tools WITHOUT remark; GitHub Pages' Jekyll renders .md.

## Phase 3 — publication + docs gaps
- [x] bs: vocabulary generated by bootstrap-tools from BOOTSTRAP_TERMS — `bootstrap/ns.jsonld`, exactly 22 terms + 5 graph kinds (owner ruled it NOT byte-identical: the harness's classes moved to its own namespace); union retired (#1538)
- [x] bootstrap.jsonld written by bootstrap-tools `export-graph.ts`, standard properties (#1538)
- [x] kg-export aligned to standard properties; retired terms deprecated + isReplacedBy (#1538)
- [x] gen-bootstrap-graph.ts + cat-harness/schemas/bootstrap-graph.ts removed (owner 2026-09-30); bootstrap:validate builds and parses the graph
- [x] one SKOS — owner 2026-09-30 chose option A, ONE IDENTITY: the glossary's bootstrap concepts ARE ns.jsonld's IRIs (term `iri`, read from the declared `vocabulary` asset); no `…ns#glossary/terms/*` minted; the c592 translations stay hosted in cat-harness as language-tagged labels on those concepts; .po `#.` comments refreshed, msgstr untouched
- [x] generated-by notes: every file bootstrap-tools writes into bootstrap (schemas `$comment`, schema page, ns.jsonld rdfs:comment + prov:wasAttributedTo, SVGs) names bootstrap-tools; one wording in `scripts/generated-by.ts`; `generated-by.test.ts` derives the set from disk and checks authored files do not claim it
- [x] publish-instance-files: the COPY moved to bootstrap-tools `publish-files.ts` (no remark; Pages renders .md on bootstrap's own site); cat-harness keeps only the .md→.html rendering for its hosted copy. Output byte-identical (46 files)
- [x] role names authored on the role (owner 2026-09-30, option 1, "model both retired names and alternative names"): `otherNames` (smart-base Generic Persona; skos:altLabel) and `formerNames` {name, retiredOn} (skos:hiddenLabel; old concept dcterms:isReplacedBy the role); one name one role, enforced at read; `kg:roles` README section written by bootstrap-tools; Initiator recorded on Bootstrapping Agent
- [x] glossary ledger hosted in cat-harness (glossaryHomeFor → cat-harness/glossary/bootstrap/); the swimlane-glossary kind and the glossary-ledger schema moved up with it (owner, second round, A); bootstrap defines 5 graph kinds
- [x] check:version-bump reads plain `v<semver>` tags for a standalone repository
- [x] docs: instance-publication release site per Q3; kg-export namespace table; hosted outputs in kg-audit (role-model) and translation skills; release/tag mechanics. OPEN: bootstrap-graph-publication/emission skills describe a harness artefact from inside bootstrap
- [x] described (disabled) CI workflow + no npm publish (private) ; which lane runs each tool (bootstrap-tools/AGENTS.md), every command verified from the directory
- [x] ~~migration-plan Phase II: left as a record (default B), pointer to kg-separation only~~ — NOT done here (measured 2026-10-01: `cat-harness/docs/architecture/migration-plan.md` on origin/main names no `kg-separation`); carried forward unchanged to `folio-assistant-syzb` (cat-harness split stage 6), which adds the pointer for both splits

## Owner ruling, 2026-09-30 — seeding carries NO history

"I dont want all the clutter in git history on bootstrap (still retained in
folio-assistant)". Supersedes the earlier `git filter-repo` default: each new
repository starts from ONE commit of its tracked files, whose message names the
folio-assistant commit it was taken from. The history stays here; the pointer
is how to reach it. Seeding still waits on the owner's go.

## Phase 4 — the replicable separation process
- [x] kg-separation BPMN + skills (done, 433d3c5)
- [x] gate: served-name collision — publish step fails on a DIFFERENT file at a taken address unless the workflow names it (`--allow-collision bootstrap.json`)
- [x] gate: standalone rehearsal — `check:bootstrap-standalone`, CI step; first run found two split defects (leak test walked .git; iri-sync asked git at a non-repo parent), both fixed

**Port from #1514 (2026-09-30):** the two pieces unique to the overtaken PR #1514 (bean `81tw`, now scrapped) — the `bootstrap-contract-semver` skill with `scripts/schema-semver.ts` (`bootstrap:semver`), and `scripts/validate-bootstrap.ts` (`bootstrap:validate`, a CI step beside `bootstrap:schemas:check`) — are ported onto this bean's `bootstrap-tools/` under child task `folio-assistant-l9d5`, adapted to the zod-only closure; the validator's graph-document target is not ported because its Zod is still in cat-harness.

## 2026-09-30 — seeded, QA'd, and carried as submodules

- litlfred/bootstrap and litlfred/bootstrap-tools seeded from 3aa7917, one
  commit each, no history; QA'd from scratch on fresh clones (both pass,
  self-contained). Fixes found by that QA are in each repository's log.
- folio-assistant carries them as submodules at bootstrap/ and
  bootstrap-tools/ (owner: root paths, option B); the staged copies are
  packed in fsh-guts/retired/bootstrap-split.tar.gz with a manifest.


## Summary of Changes (closed 2026-10-01, on evidence re-derived from the remote)

The split this bean set out to make is done: bootstrap and bootstrap-tools are standalone repositories carried here as submodules.
- `.gitmodules` on origin/main has two entries, `bootstrap` → https://github.com/litlfred/bootstrap and `bootstrap-tools` → https://github.com/litlfred/bootstrap-tools
- the tree of origin/main (`b0ca040`) holds gitlinks `bootstrap` @ `f70a56c` and `bootstrap-tools` @ `920c772`
- both remote repositories answer ls-remote (HEAD `ebfa406` / `03832a8`)
- `fsh-guts/retired/bootstrap-split.md` + `bootstrap-split.tar.gz` present on origin/main

Child `l9d5` closed the same day on its own re-measured gates. The one item not done — the migration-plan Phase II pointer — is carried to `syzb`. The cat-harness / cat-harness-tools separation (epic `iirv`) follows this bean's method stage for stage.
