classDiagram
  direction TB
  namespace smart_base__library {
    class n_smart_base_library_library["library: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_base_library_library" fa_uml_kind_library
  cssClass "n_smart_base_library_library" fa_uml_undetermined
