classDiagram
  direction TB
  namespace smart_base__methodologies {
    class n_smart_base_methodologies_methodology["methodology: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_base_methodologies_methodology" fa_uml_kind_methodology
  cssClass "n_smart_base_methodologies_methodology" fa_uml_undetermined
