classDiagram
  direction TB
  namespace smart_base__qa {
    class n_smart_base_qa_qa["qa: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_base_qa_qa" fa_uml_kind_qa
  cssClass "n_smart_base_qa_qa" fa_uml_undetermined
