classDiagram
  direction TB
  namespace smart_base__smart_base_qa_checkers {
    class smart_base_smart_base_qa_checkers_folio_qa_checker_v1_folio_qa_checker_v1["folio-qa-checker/v1"] {
      <<json: QaCheckerNodeSchema>>
      $schema [1] 'folio-qa-checker/v1'
      criterion [1] string
      check [1] string
      rationale [0..1] string
    }
  }
  cssClass "smart_base_smart_base_qa_checkers_folio_qa_checker_v1_folio_qa_checker_v1" fa_uml_kind_qa_checkers
