classDiagram
  direction TB
  namespace smart_base__smart_base_scenarios {
    class smart_base_smart_base_scenarios_FormerName["FormerName"] {
      <<json: RoleGraphSchema>>
      name [1] string
      retiredOn [1] string
    }
    class smart_base_smart_base_scenarios_Role["Role"] {
      <<json: RoleGraphSchema>>
      persona [0..1] string
      id [1] string
      title [1] string
      description [1] string
      actorKinds [1..*] list~person | agent | system | external~
      otherNames [0..*] string[]
      formerNames [0..*] FormerName[]
      skills [0..*] string[]
      inherits [0..*] string[]
      actedUpon [0..1] boolean
      judgementOnly [0..1] boolean
    }
    class smart_base_smart_base_scenarios_Actor["Actor"] {
      <<json: RoleGraphSchema>>
      id [1] string
      title [1] string
      kind [1] person | agent | system | external
      description [0..1] string
      roles [0..*] string[]
    }
    class smart_base_smart_base_scenarios_Extension["Extension"] {
      <<json: RoleGraphSchema>>
      role [1] string
      skills [1..*] string[]
    }
    class smart_base_smart_base_scenarios_RoleGraph["RoleGraph"] {
      <<json: RoleGraphSchema>>
      name [1] string
      roles [0..*] Role[]
      actors [0..*] Actor[]
      extensions [0..*] Extension[]
    }
  }
  smart_base_smart_base_scenarios_Role *-- "0..*" smart_base_smart_base_scenarios_FormerName : formerNames
  smart_base_smart_base_scenarios_RoleGraph *-- "0..*" smart_base_smart_base_scenarios_Role : roles
  smart_base_smart_base_scenarios_RoleGraph *-- "0..*" smart_base_smart_base_scenarios_Actor : actors
  smart_base_smart_base_scenarios_RoleGraph *-- "0..*" smart_base_smart_base_scenarios_Extension : extensions
  cssClass "smart_base_smart_base_scenarios_FormerName" fa_uml_kind_scenarios
  cssClass "smart_base_smart_base_scenarios_Role" fa_uml_kind_scenarios
  cssClass "smart_base_smart_base_scenarios_Actor" fa_uml_kind_scenarios
  cssClass "smart_base_smart_base_scenarios_Extension" fa_uml_kind_scenarios
  cssClass "smart_base_smart_base_scenarios_RoleGraph" fa_uml_kind_scenarios
