classDiagram
  direction TB
  namespace smart_base__smart_base_findings {
    class n_smart_base_smart_base_findings_docs["docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_base_smart_base_findings_docs" fa_uml_kind_docs
  cssClass "n_smart_base_smart_base_findings_docs" fa_uml_undetermined
