classDiagram
  direction TB
  namespace folio_assistant_core__core_methodologies {
    class n_folio_assistant_core_core_methodologies_methodology["methodology: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_core_core_methodologies_methodology" fa_uml_kind_methodology
  cssClass "n_folio_assistant_core_core_methodologies_methodology" fa_uml_undetermined
