classDiagram
  direction TB
  namespace folio_assistant_core__core_schemas {
    class n_folio_assistant_core_core_schemas_schemas["schemas: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_core_core_schemas_schemas" fa_uml_kind_schemas
  cssClass "n_folio_assistant_core_core_schemas_schemas" fa_uml_undetermined
