classDiagram
  direction TB
  namespace folio_assistant_core__folio_assistant_core_validators {
    class folio_assistant_core_folio_assistant_core_validators_folio_validator_v1_folio_validator_v1["folio-validator/v1"] {
      <<json: ValidatorNodeSchema>>
      $schema [1] 'folio-validator/v1'
      id [1] string
      validates [1] object
      schema [1] string
      rationale [0..1] string
    }
  }
  cssClass "folio_assistant_core_folio_assistant_core_validators_folio_validator_v1_folio_validator_v1" fa_uml_kind_validators
