/**
 * `check:nav-names`: one navigation destination, one name, on every surface.
 *
 * Owner, 2026-10-01, bean `ob3m` finding 6, "One name everywhere". Measured
 * before on PR #1762's head: 10 of 42 destinations carried two names.
 *
 * ## What these tests hold
 *
 * **The live surfaces pass, and the run read them.** A check that read nothing
 * also "finds nothing", so the denominator is asserted: every railed viewer
 * page, the sidebar include and `harness.json`.
 *
 * **A planted second name fails, from either side.** The data (`harness.json`)
 * and the rail (written into viewer pages) are generated by different scripts,
 * so each is planted separately in a COPY of the site. Neither can drift alone.
 *
 * **The template is read too.** The landing prints the data's label. A landing
 * anchor printing `{{ v.kind }}` would compose a second name with the data
 * unchanged, and only the template check sees it.
 *
 * **Reading nothing is not a pass** (bean `dh4f`): no rail and no include
 * returns `undetermined`, and the CLI exits 2.
 */
import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

import { siteDirFor } from "../../../cat-harness/schemas/cat-harness.js";
import {
  checkNavNames,
  conflicts,
  sightingsFromHarnessData,
  sightingsFromNavHtml,
  templateFindings,
} from "../check-nav-names.js";

const REPO = resolve(import.meta.dir, "..", "..", "..");
const INSTANCE = join(REPO, "cat-harness");
const SITE = join(INSTANCE, siteDirFor(INSTANCE));
const SCRIPT = join("cat-harness-tools", "scripts", "check-nav-names.ts");

/** The railed viewer pages `check:viewer-nav` counts, read off its committed sidecar. */
function railedCount(): number {
  const qa = JSON.parse(readFileSync(join(INSTANCE, "test", "results", "viewer-nav", "viewer-nav.qa.json"), "utf-8")) as {
    totals?: { railed?: number };
  };
  return qa.totals?.railed ?? -1;
}

/**
 * A copy of the parts of the site the check reads: the data, the include, the
 * landing templates and ONE railed page. A plant goes into the copy, so the
 * live tree is never edited (the restore-by-copy discipline in
 * `navbar-consistency.test.ts` exists because a restore once went wrong).
 */
function siteCopy(railed = "cat-harness/schemas/cat-harness/index.html"): { root: string; site: string; files: string[] } {
  const root = mkdtempSync(join(tmpdir(), "nav-names-"));
  const site = join(root, "site");
  for (const rel of ["_data/harness.json", "_data/stickies.json", "_includes/generated/navbar-footer.html", "_includes/harness_details.html", "_includes/landing.html", railed]) {
    mkdirSync(join(site, rel, ".."), { recursive: true });
    cpSync(join(SITE, rel), join(site, rel));
  }
  return { root, site, files: [`site/${railed}`] };
}

describe("the live surfaces", () => {
  const r = checkNavNames(REPO, SITE);

  test("every destination carries one name", () => {
    expect(r.undetermined).toBeUndefined();
    expect(r.conflicts).toEqual([]);
    expect(r.templates).toEqual([]);
  });

  test("the run read what it claims to have compared", () => {
    expect(r.read.harnessData).toBe(true);
    expect(r.read.include).toBe(true);
    expect(r.read.stickies).toBe(true);
    expect(r.read.templates).toBe(2);
    // Every page `check:viewer-nav` counts as railed, no fewer.
    const railed = railedCount();
    expect(railed).toBeGreaterThan(0);
    expect(r.read.railPages).toBe(railed);
    expect(r.destinations).toBeGreaterThan(20);
  });

  test("`--check` passes as committed, sidecar included", () => {
    const p = spawnSync("bun", ["run", SCRIPT, "--check"], { cwd: REPO, encoding: "utf-8" });
    expect(`${p.stdout}${p.stderr}`).toContain("every destination carries one name");
    expect(p.status).toBe(0);
  });
});

describe("a planted second name fails", () => {
  test("in the DATA: one tile renamed", () => {
    const c = siteCopy();
    const path = join(c.site, "_data", "harness.json");
    const d = JSON.parse(readFileSync(path, "utf-8")) as { tiles: { id: string; title: string; href?: string }[] };
    const skills = d.tiles.find((t) => t.id === "skills")!;
    expect(skills.title).toBe("Skills");
    skills.title = "Skills — cat-harness";
    writeFileSync(path, JSON.stringify(d));
    const r = checkNavNames(c.root, c.site, c.files);
    const hit = r.conflicts.find((x) => x.href === skills.href);
    expect(hit).toBeDefined();
    expect(hit!.names.map((n) => n.label)).toEqual(["Skills", "Skills — cat-harness"]);
  });

  test("on the RAIL: one row's label changed in a viewer page", () => {
    const c = siteCopy();
    const page = join(c.site, "cat-harness/schemas/cat-harness/index.html");
    const html = readFileSync(page, "utf-8");
    const planted = html.replace('<span class="fa-nav-label">Methodologies', '<span class="fa-nav-label">methodology');
    expect(planted).not.toBe(html);
    writeFileSync(page, planted);
    const r = checkNavNames(c.root, c.site, c.files);
    const hit = r.conflicts.find((x) => x.href === "/methodologies/");
    expect(hit).toBeDefined();
    expect(hit!.names.map((n) => n.label)).toEqual(["Methodologies", "methodology"]);
  });

  test("in the TEMPLATE: a landing anchor printing the kind word", () => {
    const c = siteCopy();
    const tpl = join(c.site, "_includes", "harness_details.html");
    const text = readFileSync(tpl, "utf-8");
    const planted = text.replace("{{ v.label | default: v.kind }}", "{{ v.kind }}");
    expect(planted).not.toBe(text);
    writeFileSync(tpl, planted);
    const r = checkNavNames(c.root, c.site, c.files);
    expect(r.templates.map((t) => t.expression)).toEqual(["v.kind"]);
  });

  test("a harness row linking a graph's page is a second name for that page", () => {
    // Bootstrap's row linked `/processes/` until it was given its own landing
    // section, so the page was "Bootstrap" and "Processes" one row apart.
    const s = sightingsFromHarnessData(
      {
        harnesses: [
          { name: "bootstrap", label: "Bootstrap", href: "/processes/", instantiated: true, visualisations: [{ kind: "processes", label: "Processes", path: "/processes/" }] },
        ],
      },
      "x",
    );
    expect(conflicts(s).map((c) => c.href)).toEqual(["/processes/"]);
  });
});

describe("what is and is not a name", () => {
  test("the qualifier and the hidden description are not part of the base label", () => {
    const html =
      '<nav class="fa-nav"><a href="../../tools/"><span class="fa-nav-label">Tools<span class="fa-nav-qualifier"> · C@T Harness</span>' +
      '<span class="fa-nav-sr"> — Tool definitions</span></span></a></nav>';
    expect(sightingsFromNavHtml(html, "/a/b/", "rail", "x")).toEqual([{ surface: "rail", source: "x", href: "/tools/", label: "Tools" }]);
  });

  test("an in-page anchor and an external link are not destinations", () => {
    const html =
      '<nav class="fa-nav"><a href="#top"><span class="fa-nav-label">Top</span></a>' +
      '<a href="https://example.org/"><span class="fa-nav-label">Out</span></a></nav>';
    expect(sightingsFromNavHtml(html, "/", "rail", "x")).toEqual([]);
  });

  test("the include's Liquid hrefs resolve to the site path", () => {
    const html = `<a href="{{ '/beans/' | relative_url }}" class="fa-nav-kind"><span class="fa-nav-label">Beans</span></a>`;
    expect(sightingsFromNavHtml(html, "/", "sidebar", "x").map((s) => s.href)).toEqual(["/beans/"]);
  });

  test("a sticky link is compared only where navigation links the same page", () => {
    const s = [
      { surface: "sticky card links", source: "x", href: "/content-types.html", label: "Content" },
      { surface: "sticky card links", source: "x", href: "/content-types.html", label: "Know which kind of thing you are writing" },
      { surface: "sticky card links", source: "x", href: "/who-iris/", label: "The IRIS replica" },
      { surface: "harness rows", source: "y", href: "/who-iris/", label: "WHO IRIS" },
    ];
    expect(conflicts(s).map((c) => c.href)).toEqual(["/who-iris/"]);
  });

  test("a template that prints the label is clean", () => {
    expect(templateFindings('<a href="x">{{ v.label | default: v.kind }}</a>', "t")).toEqual([]);
    expect(templateFindings('<a href="x">{{ v.kind }}</a>', "t")).toEqual([{ file: "t", line: 1, expression: "v.kind" }]);
  });
});

describe("reading nothing is not a pass", () => {
  test("no rail and no include is undetermined", () => {
    const root = mkdtempSync(join(tmpdir(), "nav-names-empty-"));
    const site = join(root, "site");
    mkdirSync(join(site, "_data"), { recursive: true });
    writeFileSync(join(site, "_data", "harness.json"), JSON.stringify({ tiles: [] }));
    const r = checkNavNames(root, site, []);
    expect(r.undetermined).toContain("no railed page");
  });

  test("an unreadable harness.json is undetermined", () => {
    const root = mkdtempSync(join(tmpdir(), "nav-names-bad-"));
    const site = join(root, "site");
    mkdirSync(join(site, "_data"), { recursive: true });
    writeFileSync(join(site, "_data", "harness.json"), "{ not json");
    expect(checkNavNames(root, site, []).undetermined).toContain("will not parse");
  });
});
