import { test, expect } from "@playwright/test";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { AxeBuilder } from "@axe-core/playwright";

import { siteDirFor } from "../schemas/cat-harness.ts";

/**
 * Every generated state dashboard, audited — bean `5wrg`.
 *
 * ## The gap this closes, measured rather than assumed
 *
 * `a11y.e2e.ts` audits ONE page: `/_kg/folio-assistant/index.html`, plus an
 * i18n fixture and two sticky fixtures it builds itself. Grepping every
 * `*.e2e.ts` for a `goto` at `qa/`, `beans/`, `todos/`, `uploads/`, `health/`
 * or `issue-marks/` found **no match** — six generated pages that nothing
 * end-to-end visited.
 *
 * They were clean when this was written: **0 violations across all six** at
 * the same tags. So this is a coverage gap with no defect behind it, which is
 * the version worth closing — cheap now, expensive once something has broken.
 * The repository's own thesis, from the `1xhc` epic: *a gate that does not
 * fire is indistinguishable from one that passes.*
 *
 * ## The set is DISCOVERED, never listed
 *
 * A literal list of six would leave a seventh dashboard uncovered on the day
 * it is generated, and nothing would say so — the stale-gap failure
 * `AGENTS.md` opens by warning about. The discriminator is the same one the
 * pruner uses: a directory under the site whose `index.html` carries the
 * generator's marker. Ownership is read off the FILE, never inferred from the
 * directory, because the site also holds `guides/`, `reference/` and much else
 * this must not touch.
 *
 * ## Why the marker is duplicated here
 *
 * `state-visualizer.ts` cannot be imported from a Playwright spec: line 150 is
 * `instanceRootFor(import.meta.dir)`, and `import.meta.dir` is a **Bun**
 * extension that is `undefined` under Node, which is what Playwright runs
 * specs with. `action-tiles.e2e.ts` carries the same warning in its own
 * header.
 *
 * So the string is copied, and `state-visualizer.test.ts` — which runs under
 * Bun and CAN import the generator — asserts the two agree. That is this
 * repository's rule applied literally: **an unavoidable duplicate is fine
 * while an unchecked one is not.**
 */
const MARKER = "Generated by scripts/state-visualizer.ts. Do not hand-edit";

/** Same tags `a11y.e2e.ts` uses. Level AAA is not the bar being claimed. */
const TAGS = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"];

// `import.meta.dir` is a Bun extension and is undefined under Node, which is
// what Playwright runs this with — hence the URL dance. Same as the sibling
// specs.
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = siteDirFor(ROOT);
/** The instance's own segment, so the served path is composed and not spelled. */
const INSTANCE = ROOT.split("/").filter(Boolean).pop() ?? "";

/** Directories under the site whose `index.html` this generator wrote. */
function dashboards(): string[] {
  const site = join(ROOT, SITE);
  if (!existsSync(site)) return [];
  return readdirSync(site, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => {
      const page = join(site, name, "index.html");
      if (!existsSync(page)) return false;
      try {
        return readFileSync(page, "utf8").includes(MARKER);
      } catch {
        return false;
      }
    })
    .sort();
}

const IDS = dashboards();

test.describe("every generated state dashboard is accessible", () => {
  test("there is at least one to audit", () => {
    // Without this the suite below is vacuously green: zero dashboards means
    // zero tests, and a run over nothing reports exactly like a clean sweep.
    // That is the `check:l1-complete` failure — "nothing to check", exit 0 —
    // which `a6kl` already paid for once.
    expect(IDS.length).toBeGreaterThan(0);
  });

  for (const id of IDS) {
    test(`${id} has no WCAG A/AA violations`, async ({ page }) => {
      await page.goto(`/${INSTANCE}/${SITE}/${id}/index.html`);
      const { violations } = await new AxeBuilder({ page }).withTags([...TAGS]).analyze();
      expect(
        violations.map((v) => `${v.id} [${v.impact}] ×${v.nodes.length} — ${v.help}`),
      ).toEqual([]);
    });

    test(`${id} does not scroll sideways at phone width`, async ({ page }) => {
      // The declared interaction profile here is low-dexterity. A page that
      // needs horizontal scrolling to read is a page that needs a drag, and a
      // drag is the affordance this instance's own UI rules avoid.
      await page.setViewportSize({ width: 390, height: 844 });
      await page.goto(`/${INSTANCE}/${SITE}/${id}/index.html`);
      const { scrollW, clientW } = await page.evaluate(() => ({
        scrollW: document.documentElement.scrollWidth,
        clientW: document.documentElement.clientWidth,
      }));
      expect(scrollW).toBeLessThanOrEqual(clientW);
    });
  }
});
