/**
 * An agent's summary of a library block, kept BESIDE the block — the QA
 * sidecar the owner asked for on 2026-09-24.
 *
 * > on library/ page, the extract of a node is shown, but no agentic summary
 *
 * and, on scope:
 *
 * > Make as QA sidecar as part of general doc ingestion to slowly drain.
 *
 * ## Why a sidecar, and not a field on the block
 *
 * A prose block is the source's own text: `provenance: "ingested"`, extracted
 * verbatim, regenerated by re-ingestion and never re-authored in place
 * (`library` is `holds: "derived"`). A summary is somebody's account of that
 * text. Writing it into the block would make the block carry an authored
 * claim under an `"ingested"` stamp, and it would be dropped the next time
 * the rung ran. So the block stays verbatim and the summary lives in
 * `library/<slug>/summaries.json`, one file per entry — the same placement
 * `images.json` uses for image descriptions, and for the same reason.
 *
 * ## One vocabulary for the state and the author
 *
 * Each summary IS a {@link NarrativeSchema}: `draft`, `confirmed`,
 * `rejected`, with `drafted_by` an {@link AttributionSchema} that must name its
 * `model` when the author is an agent, and `confirmed_by` that must be a
 * human. Nothing here restates those rules, so nothing here can drift from
 * them. `bun run narratives` reviews these drafts exactly as it reviews image
 * descriptions.
 *
 * ## `source_hash` — so a changed source reads as STALE, not as right
 *
 * The kg-qa sidecars (`schemas/kg-qa.ts`) record the hash of the subject they
 * judged, because a verdict that outlives its subject silently describes
 * something else. A summary has the same failure: re-ingest a document, a
 * section's text changes, and the old summary goes on sitting beside the new
 * text looking current. The hash is of {@link proseBody} — the text the
 * summariser was actually shown — so a change to the section's front matter
 * alone does not mark a summary stale, and a change to one word does.
 *
 * ## Absence is the "not yet summarised" state
 *
 * A record whose narrative is `not-authored` is refused. An empty slot would
 * be a second spelling of "no record", and two spellings of one fact is how a
 * count comes to disagree with itself.
 *
 * @module schemas/block-summary
 * @graphNode schema
 */
import { createHash } from "node:crypto";

import { z } from "zod";

import { NarrativeSchema } from "./narrative.ts";

/** The `$schema` tag every summaries sidecar carries. */
export const BLOCK_SUMMARIES_SCHEMA = "folio-block-summaries/v1" as const;

/** The sidecar's file name inside a library entry. */
export const SUMMARIES_FILE = "summaries.json";

/** Block kinds that enter the summary queue. Only prose carries text to summarise. */
export const SUMMARISABLE_KINDS: readonly string[] = ["prose"];

/**
 * Where a prose block stands, derived — never stored.
 *
 * - `not-summarised` — no record.
 * - `stale` — a record exists, but the block's text has changed since.
 * - `draft` — an agent (or a person) wrote one against the current text.
 * - `confirmed` — a HUMAN accepted it, against the current text.
 * - `rejected` — a human turned the last draft down, and said why.
 * - `unreadable` — the block names a text file that cannot be read, so there
 *   is nothing to summarise and nothing to compare. Not counted as prose.
 * - `empty` — the text file reads, and holds nothing once its front matter is
 *   stripped (a heading whose content the rung filed under the next section).
 *   There is nothing to summarise, and a summary of nothing would be invented.
 *   Not counted as prose either.
 */
export const SUMMARY_STATUSES = [
  "not-summarised",
  "stale",
  "draft",
  "confirmed",
  "rejected",
  "unreadable",
  "empty",
] as const;
export type SummaryStatus = (typeof SUMMARY_STATUSES)[number];

/**
 * Statuses that put a block in the drain's backlog.
 *
 * `rejected` is in it: a person said this draft is wrong, so the block still
 * has no summary anybody stands behind. The rejection's reason travels with
 * the block into `summaries:next`, so the next draft can answer it rather
 * than repeat it.
 */
export const BACKLOG_STATUSES: readonly SummaryStatus[] = ["not-summarised", "stale", "rejected"];

/** Statuses that count as summarised: a draft or a confirmation of the CURRENT text. */
export const SUMMARISED_STATUSES: readonly SummaryStatus[] = ["draft", "confirmed"];

const SHA256_HEX = /^[0-9a-f]{64}$/;

export const BlockSummarySchema = z
  .object({
    /** The block's `@id`, e.g. `library/<slug>/blocks/prose-sec-000`. */
    block: z.string().min(1),
    /** The text file summarised, ENTRY-relative, e.g. `sections/sec-000-intro.md`. */
    source: z.string().min(1),
    /** sha256 of {@link proseBody} of `source` when the summary was drafted. */
    source_hash: z.string().regex(SHA256_HEX, "`source_hash` is a 64-hex sha256"),
    /** The summary itself, with its state and its author. */
    narrative: NarrativeSchema,
    /**
     * Earlier narratives this one replaced — a rejected draft, or one whose
     * source changed. Kept so a rejection's reason is not lost when the block
     * is redrafted: a rejection that vanishes lets the next agent write the
     * identical thing again.
     */
    superseded: z.array(NarrativeSchema).optional(),
  })
  .refine((s) => s.narrative.state !== "not-authored", {
    message: "a summary record must hold a summary — absence of a record already means not summarised",
    path: ["narrative", "state"],
  });
export type BlockSummary = z.infer<typeof BlockSummarySchema>;

export const BlockSummariesSidecarSchema = z
  .object({
    $schema: z.literal(BLOCK_SUMMARIES_SCHEMA),
    /** The library entry's slug — the directory this file sits in. */
    entry: z.string().min(1),
    summaries: z.array(BlockSummarySchema),
  })
  .refine((s) => new Set(s.summaries.map((x) => x.block)).size === s.summaries.length, {
    message: "a block has at most one summary record — two would disagree about which is current",
    path: ["summaries"],
  });
export type BlockSummariesSidecar = z.infer<typeof BlockSummariesSidecarSchema>;

/**
 * The text of a section file as a reader and a summariser see it: front
 * matter stripped, surrounding whitespace trimmed.
 *
 * ONE definition, used by the viewer's excerpt (`library-graph.ts`), by the
 * queue that hands text to an agent, and by the hash below — so the text that
 * was summarised, the text that is hashed and the text a reader is shown
 * cannot be three different strings.
 */
export function proseBody(markdown: string): string {
  return markdown.replace(/^---[\s\S]*?---\n/, "").trim();
}

/** sha256 of text ALREADY passed through {@link proseBody}, hex. */
export function bodyHash(body: string): string {
  return createHash("sha256").update(body, "utf8").digest("hex");
}

/**
 * sha256 of {@link proseBody} of a whole section file, hex.
 *
 * Two functions rather than one that strips "if needed": stripping twice is
 * not a no-op when a section's text itself opens with a `---` rule, and a
 * hash that depends on how many times it was asked would mark a summary
 * stale for no change at all.
 */
export function sourceHash(markdown: string): string {
  return bodyHash(proseBody(markdown));
}

/**
 * The status of one block, from its record and its text NOW.
 *
 * `body` is {@link proseBody} of the block's text file, or `null` when that
 * file could not be read — `unreadable`, never `not-summarised`, because a
 * block with no readable text cannot be summarised and must not sit in a
 * backlog nobody can drain. An empty body is `empty` for the same reason.
 */
export function summaryStatus(record: BlockSummary | undefined, body: string | null): SummaryStatus {
  if (body === null) return "unreadable";
  if (body === "") return "empty";
  if (!record) return "not-summarised";
  // Rejected is checked BEFORE stale: either way the block is back in the
  // backlog, and the rejection is the more useful thing to tell the drafter.
  if (record.narrative.state === "rejected") return "rejected";
  if (record.source_hash !== bodyHash(body)) return "stale";
  if (record.narrative.state === "confirmed") return "confirmed";
  return "draft";
}

/** Statuses that are not summarisable prose at all — excluded from every count but their own. */
export const NOT_PROSE_STATUSES: readonly SummaryStatus[] = ["unreadable", "empty"];

/** True when this status puts the block in the drain's backlog. */
export function inBacklog(status: SummaryStatus): boolean {
  return BACKLOG_STATUSES.includes(status);
}
