/**
 * JSON-LD projection of the content block model.
 *
 * Blocks are authored as TypeScript manifests and stay that way — the
 * builders in `builders.ts` are where author-time type checking lives, and
 * `content/pipeline/block-module.ts` treats a manifest that throws on import
 * as a *finding*. This module does not replace any of that. It defines the
 * **published** form: a `.jsonld` sibling next to each `.ts`, generated by
 * `content/pipeline/gen-block-jsonld.ts`, so that
 *
 * 1. an external consumer can reference a block without a TypeScript
 *    toolchain, and
 * 2. authored blocks and *ingested* documents (`library/**`) carry the same
 *    `@context`, the same `@type` vocabulary and the same edge terms — so one
 *    graph loader serves both populations instead of two.
 *
 * ## Why labels are not emitted as IRIs
 *
 * This is the hazard the whole module exists to route around, so it is worth
 * stating plainly.
 *
 * A folio label looks exactly like a JSON-LD compact IRI: `def:foo` has the
 * shape `prefix:reference`. It is not one. The `def:` part names a **block
 * kind**, not a namespace, and JSON-LD splits a compact IRI on its **first**
 * colon. Emitting labels directly as IRI values therefore goes wrong in two
 * different ways:
 *
 * - `def:quantum-universe` would need a `def` prefix in the context, which
 *   would place the block in a per-*kind* namespace. The same block referenced
 *   cross-paper as `some-paper:def:quantum-universe` would then expand under a
 *   per-*paper* namespace instead. **Two IRIs for one block** — every graph
 *   join silently under-counts, with no error anywhere.
 * - `unital-groebner-bases:thm:bar` splits into prefix
 *   `unital-groebner-bases` and suffix `thm:bar`. With no such prefix defined,
 *   JSON-LD falls back to treating the whole string as an absolute IRI — and
 *   `unital-groebner-bases:thm:bar` *is* syntactically valid, with
 *   `unital-groebner-bases` as its scheme. The result is a well-formed IRI
 *   that means nothing and joins with nothing.
 *
 * So `@id` is **minted** by {@link resolveLabel}, which resolves all three
 * authored reference forms to one canonical relative IRI, and the label is
 * additionally preserved verbatim in `folio-assistant-core:label` for grep and round-tripping.
 * Nothing in `content/**` has to change.
 *
 * ## Why `@id` is relative
 *
 * Emitted IRIs are relative (`papers/<paper>/blocks/def-foo`). `@base` lived
 * only in the published context, so that a base-URL change would not rewrite
 * thousands of committed files. JSON-LD 1.1 §4.1.3 ignores `@base` in a remote
 * context, so since bean `bh4q` it is ALSO in each document's own context
 * ({@link CONTENT_DOCUMENT_CONTEXT}) — and a base change does rewrite them.
 *
 * @module schemas/jsonld
 * @graphNode schema
 *
 * @conformsTo hl7-fhir
 * @conformsTo spar-doco-deo-cito
 * @conformsTo w3c-csvw
 * @conformsTo w3c-web-annotation
 * @conformsTo who-smart-base
 * @conformsTo w3c-prov-o
 * @conformsTo w3c-skos
 * @conformsTo w3c-xsd11-datatypes
 */

import { BLOCK_KINDS, type BlockKind } from "./block-kinds";
import type { ContributionRegistry } from "./contributions";

// ── Namespaces ───────────────────────────────────────────────────

/**
 * Folio's own terms — the relations no published vocabulary models.
 *
 * Defined in `./namespaces` and re-exported here so existing importers are
 * unaffected. It moved because `schemas/cat-harness.ts` needs it too, and a
 * harness-layer module must not import the content vocabulary — see that
 * module's note.
 */
import { z } from "zod";

import { CORE_NS, FOLIO_BASE, ownNamespace } from "./namespaces";

// Content terms are folio-assist-core's, so they hang off core's namespace —
// the same layer that owns block kinds, voices and the library.
export { CORE_NS };
/** SPAR Document Components Ontology — structural document parts. */
export const DOCO_NS = "http://purl.org/spar/doco/";
/** SPAR Discourse Elements Ontology — rhetorical roles. */
export const DEO_NS = "http://purl.org/spar/deo/";
/** SPAR Citation Typing Ontology. */
export const CITO_NS = "http://purl.org/spar/cito/";
/** W3C Web Annotation — the anchoring layer for ingested candidates. */
export const OA_NS = "http://www.w3.org/ns/oa#";
/** W3C PROV-O — derivation chains from source PDF to block. */
export const PROV_NS = "http://www.w3.org/ns/prov#";
export const SKOS_NS = "http://www.w3.org/2004/02/skos/core#";
export const DCTERMS_NS = "http://purl.org/dc/terms/";
/** OMG BPMN 2.0's model namespace — its element and attribute names as IRIs (`sourceRef`, `incoming`, …). */
export const BPMN_MODEL_NS = "http://www.omg.org/spec/BPMN/20100524/MODEL#";
/** HL7 FHIR — the health-policy semantics of the ingest side. */
export const FHIR_NS = "http://hl7.org/fhir/";

/**
 * CSV on the Web — W3C Recommendation, and the tabular model this instance
 * adopts rather than inventing one (bean `ulqj`, decided by the owner).
 *
 * It models table → column → datatype and nothing else: no formulas, no
 * merged cells, no styling. That is the reason it was chosen — "no full Excel
 * complexity" is a property of the vocabulary, not a rule we have to enforce.
 *
 * What it CANNOT say is where a table sits, because in CSVW the table IS the
 * file. `fac:anchor`, `fac:headerRow` and `fac:extent` carry that, as
 * annotations ON a valid CSVW document rather than a replacement for one.
 */
export const CSVW_NS = "http://www.w3.org/ns/csvw#";

/**
 * WHO's canonical base for the SMART Guidelines base IG.
 *
 * `smart-base` `sushi-config.yaml` declares `canonical: http://smart.who.int/base`,
 * and its logical models publish under `<canonical>/StructureDefinition/<Name>`.
 */
export const SMART_BASE_NS = "http://smart.who.int/base/StructureDefinition/";

/** Where the published `@context` lives. Emitted files reference this URL. */
export const CONTENT_CONTEXT_URL =
  "https://litlfred.github.io/folio-assistant/ns/content/v1.jsonld";

/**
 * Base every minted `@id` is relative to. Declared in the published context
 * AND in each document's own context — see {@link CONTENT_DOCUMENT_CONTEXT}.
 */
export { FOLIO_BASE };

/**
 * The `@context` every emitted content document carries: the published
 * context by URL, then `@base` in the document's OWN context (bean `bh4q`,
 * owner 2026-10-01, option 2).
 *
 * JSON-LD 1.1 §4.1.3 says `@base` in a remote context is ignored, so a
 * conforming processor resolves our relative `@id`s against each document's
 * own URL. jsonld.js applies it anyway — measured — which is why this went
 * unnoticed. Rule `ld-no-base-in-a-remote-context` in the `linked-data` voice.
 *
 * The cost, accepted: a base-URL change now rewrites every emitted file,
 * which is what keeping `@base` only in the context had avoided.
 */
export const CONTENT_DOCUMENT_CONTEXT = [CONTENT_CONTEXT_URL, { "@base": FOLIO_BASE }] as const;

/**
 * The published docs site's root — `_config.yml` `url` + `baseurl`, from the
 * own-namespaces code list (`docs-site`). The same value `library-iri.ts`
 * mints library assets under.
 */
export const DOCS_SITE_BASE = ownNamespace("docs-site");

/**
 * The `@context` the DOCS SITE's own nodes carry (`gen-site-jsonld.ts`) —
 * issue #1908.
 *
 * {@link FOLIO_BASE} is `https://litlfred.github.io/folio/`, which is not
 * where anything is served, so a site node's `@id` named nothing a reader
 * could open — and a todo's `target`, an IRI edge to that node, could not be
 * followed. The site's nodes ARE published (at {@link siteNodeSitePath}), so
 * their base is the site, and each `@id` is the address of its own JSON-LD:
 * the `kg-viewer` rule from #1881, that an asset's IRI dereferences to it.
 *
 * Only the site's nodes move. The corpus and library documents keep
 * {@link FOLIO_BASE} — thousands of committed files whose ids key summaries,
 * LSI indexes and kg-qa sidecars, and none of which is a published file yet.
 */
export const SITE_DOCUMENT_CONTEXT = [CONTENT_CONTEXT_URL, { "@base": DOCS_SITE_BASE }] as const;

/**
 * A content document's `@context`, as a record schema accepts it: the
 * two-part form above, the site form, or the bare URL that records written
 * before bean `bh4q` carry. Any other context would bind their keys to terms
 * nobody declared, so nothing else is accepted.
 */
export const ContentContextSchema = z.union([
  z.literal(CONTENT_CONTEXT_URL),
  z.tuple([z.literal(CONTENT_CONTEXT_URL), z.object({ "@base": z.literal(FOLIO_BASE) }).strict()]),
  z.tuple([z.literal(CONTENT_CONTEXT_URL), z.object({ "@base": z.literal(DOCS_SITE_BASE) }).strict()]),
]);

// ── Block kind → RDF types ───────────────────────────────────────

/**
 * `folio-assistant-core:` type for each block kind. These are folio's own classes because
 * no published vocabulary distinguishes a theorem from a lemma from a
 * conjecture in the way this project's editorial machinery needs.
 */
export const BLOCK_KIND_TO_FOLIO_TYPE: Record<BlockKind, string> = {
  definition: "folio-assistant-core:Definition",
  theorem: "folio-assistant-core:Theorem",
  lemma: "folio-assistant-core:Lemma",
  proposition: "folio-assistant-core:Proposition",
  corollary: "folio-assistant-core:Corollary",
  algorithm: "folio-assistant-core:Algorithm",
  conjecture: "folio-assistant-core:Conjecture",
  example: "folio-assistant-core:Example",
  remark: "folio-assistant-core:Remark",
  proof: "folio-assistant-core:Proof",
  simulator: "folio-assistant-core:Simulator",
  prose: "folio-assistant-core:Prose",
  equation: "folio-assistant-core:Equation",
  diagram: "folio-assistant-core:Diagram",
  table: "folio-assistant-core:Table",
  figure: "folio-assistant-core:Figure",
};

/**
 * DoCO co-type, where one is *unambiguously* right.
 *
 * Deliberately partial. A `doco:` co-type is what lets an ingested WHO
 * section and an authored block answer the same query, so it earns its place
 * — but only where the mapping is a fact rather than a stretch. A theorem is
 * a section-like component in DoCO's terms and gets `doco:Section`; a
 * `simulator` block has no DoCO counterpart at all and gets none. Guessing
 * here would put wrong triples in a published graph, which is worse than
 * leaving a kind untyped.
 */
/**
 * Types for the DOCS SITE's own graph.
 *
 * The site is not a folio — `gen-block-jsonld` declines to run here for
 * exactly that reason ("folio-assistant is the platform; papers live in the
 * folio repo") — but its pages are still nodes, and a reader asking
 * `corpus_search` where the ingestion pipeline is documented should find the
 * page as readily as they find a block.
 *
 * `folio-assistant-core:WebPage` is a NEW term rather than a borrowed one. schema.org has
 * `schema:WebPage`, and this corpus has never used schema.org anywhere — the
 * committed vocabularies are DCTERMS, SPAR (DoCO/DEO/CiTO) and one PROV term.
 * Introducing a whole namespace for one class, when the house rule is
 * "generalising is sound; inventing is not", would be inventing by import. A
 * `folio-assistant-core:` term for a folio-specific concept is what that rule allows.
 *
 * The DoCO half is borrowed and verified: a page is `doco:Section` (its own
 * containment is `dcterms:hasPart`, per the note on `contains` below), an
 * asset node is `doco:Figure` — the same class `diagram` blocks already get.
 */
export const SITE_PAGE_TYPES = ["folio-assistant-core:WebPage", "doco:Section"] as const;
export const SITE_NARRATIVE_TYPES = ["folio-assistant-core:Prose", "doco:Section"] as const;
export const SITE_ASSET_TYPES = ["folio-assistant-core:Figure", "doco:Figure"] as const;

/**
 * Relative IRI for a docs-site node, against {@link DOCS_SITE_BASE}:
 * `site/<slug>.jsonld` for a page and `site/<slug>/nodes/<id>.jsonld` for one
 * of its children — the same document/section/block shape `gen-library-jsonld`
 * mints for an ingested source, so both populations read the same way when the
 * graph is walked.
 *
 * It IS the node's published path ({@link siteNodeSitePath}), so the IRI
 * dereferences to the node's JSON-LD (#1908; the `kg-viewer` rule of #1881).
 * The rendering — `<slug>.html#<id>` — is a different resource, and the node
 * does not name it.
 *
 * The slug keeps its slashes: `guides/writing-a-paper` publishes at that path
 * and an IRI that flattened it would no longer say where the page is.
 */
export function siteIri(slug: string, nodeId?: string): string {
  return siteNodeSitePath(slug, nodeId);
}

/** Where a site node's JSON-LD is published, SITE-relative. One function names both the `@id` and the file. */
export function siteNodeSitePath(slug: string, nodeId?: string): string {
  return nodeId ? `site/${slug}/nodes/${encodeURIComponent(nodeId)}.jsonld` : `site/${slug}.jsonld`;
}

/** A site node's absolute IRI — what an edge from outside the site graph (a todo's `target`) points at. */
export function siteNodeIri(slug: string, nodeId?: string): string {
  return `${DOCS_SITE_BASE}${siteNodeSitePath(slug, nodeId)}`;
}

export const BLOCK_KIND_TO_DOCO_TYPE: Partial<Record<BlockKind, string>> = {
  equation: "doco:Formula",
  diagram: "doco:Figure",
  // A FACT, not a stretch: DoCO's Figure is a figure in a document, which is
  // exactly what an extracted `figure` block is. `diagram` already maps here,
  // and `SITE_ASSET_TYPES` already pairs `folio-assistant-core:Figure` with `doco:Figure`.
  figure: "doco:Figure",
  table: "doco:Table",
  prose: "doco:Section",
  definition: "doco:Section",
  theorem: "doco:Section",
  lemma: "doco:Section",
  proposition: "doco:Section",
  corollary: "doco:Section",
  algorithm: "doco:Section",
  conjecture: "doco:Section",
  example: "doco:Section",
  remark: "doco:Section",
  proof: "doco:Section",
};


/**
 * Every `@type` for a block, most specific first.
 *
 * A built-in kind is typed from the two tables above. A CONTRIBUTED kind — the
 * `dak` adapter's, which smart-base contributes (bean `1335`) — carries its own
 * `folioType` and `docoType` on its `BlockKindContribution`, so this reads them
 * from the registry rather than from a table naming another harness's kinds.
 * Built-ins are consulted first, which is the order `register` already
 * guarantees by refusing a contribution that redefines a built-in kind.
 *
 * With no registry, a contributed kind gets no type — the same answer an
 * unknown kind gets, because without the registry it IS unknown here.
 */
export function typesForKind(kind: string, contributions?: ContributionRegistry): string[] {
  const contributed = contributions?.kindEntry(kind);
  const folio = BLOCK_KIND_TO_FOLIO_TYPE[kind as BlockKind] ?? contributed?.folioType;
  const doco = BLOCK_KIND_TO_DOCO_TYPE[kind as BlockKind] ?? contributed?.docoType;
  const out: string[] = [];
  if (folio) out.push(folio);
  if (doco) out.push(doco);
  return out;
}

// ── Label ↔ IRI segment ──────────────────────────────────────────

/**
 * Label prefixes recognised as *kind* markers, without their colon.
 *
 * Mirrors `KNOWN_LABEL_PREFIXES` in `constraints.ts`, which is the
 * authoritative list; kept here without the trailing colon because every use
 * below is a segment comparison. {@link assertPrefixesInSync} is the guard
 * against the two drifting, and the test suite calls it.
 */
export const KIND_PREFIXES: readonly string[] = [
  "def", "thm", "lem", "prop", "cor", "rem", "ex", "conj",
  "prf", "sim", "eq", "fig", "tbl",
  "alg", "prose",
  "sec", "chap", "app", "bib",
  // The `dak` adapter's prefixes were spread in here until bean `1335`. They
  // are a contributed adapter's now, carried as `labelPrefix` on each
  // contributed kind (`ContributionRegistry.contributedLabelPrefixes()`), so
  // this list is the BUILT-IN prefixes and nothing a harness adds.
];

const KIND_PREFIX_SET: ReadonlySet<string> = new Set(KIND_PREFIXES);

/**
 * Throws if `KIND_PREFIXES` has drifted from `constraints.ts`.
 *
 * Takes the constraints list as an argument rather than importing it, so
 * this module stays free of the Zod dependency chain (it is imported by the
 * generator and by tooling that has no reason to pull in schema validation).
 */
export function assertPrefixesInSync(knownLabelPrefixes: readonly string[]): void {
  const theirs = new Set(knownLabelPrefixes.map((p) => p.replace(/:$/, "")));
  const missing = [...theirs].filter((p) => !KIND_PREFIX_SET.has(p));
  const extra = KIND_PREFIXES.filter((p) => !theirs.has(p));
  if (missing.length || extra.length) {
    throw new Error(
      `KIND_PREFIXES is out of sync with KNOWN_LABEL_PREFIXES: ` +
        `missing [${missing.join(", ")}], extra [${extra.join(", ")}]`,
    );
  }
}

/**
 * A parsed reference. `kind: "unresolvable"` is a first-class outcome, not an
 * error path: it is exactly the input that would otherwise become a
 * well-formed but meaningless IRI, and callers must be able to see it.
 */
export type ParsedReference =
  | { form: "absolute"; iri: string }
  | { form: "same-paper"; prefix: string; slug: string }
  | { form: "cross-paper"; namespace: string[]; prefix: string; slug: string }
  | { form: "bare-label"; label: string }
  | { form: "unresolvable"; raw: string; reason: string };

/**
 * Parse one `uses[]` / `foreshadows[]` / `proofs[]` entry.
 *
 * The grammar, per `schemas/types.ts` and `constraints.ts:citesProvable`,
 * admits an arbitrary namespace path before the kind prefix:
 *
 * ```
 *   def:quantum-universe                          same paper
 *   unital-groebner-bases:cor:pbw                 cross-paper
 *   some-ns:unital-groebner-bases:cor:pbw         nested namespace
 *   https://folio.example.org/papers/foo#def:bar  cross-folio
 * ```
 *
 * The kind prefix is the pivot: everything before it is namespace, everything
 * from it onward is the local label. A slug may itself contain colons
 * (`def:foo:bar`), which is why the *first* kind prefix wins rather than the
 * last colon losing.
 */
export function parseReference(ref: string, contributedPrefixes: readonly string[] = []): ParsedReference {
  if (/^https?:\/\//i.test(ref)) return { form: "absolute", iri: ref };
  if (!ref.includes(":")) {
    // NOT unresolvable. A colon-free reference is a same-paper label that
    // happens to carry no kind prefix, and `mintNodeId` already turns exactly
    // that into an `@id` — so the reference and the target's own identity are
    // computable by one shared rule, with nothing guessed.
    //
    // It used to be reported `unresolvable` and the edge was DROPPED. Measured
    // on the qou corpus that silently deleted 35 real edges pointing at five
    // real `prose` blocks whose labels are legitimately prefix-less (the Type
    // system table gives `prose` no required prefix). The graph's whole value
    // is its edges, so losing them to a convention check is the wrong trade.
    //
    // A typo is not hidden by this: it mints an IRI no node claims, which
    // surfaces as a dangling edge in `neighbors` — visible, rather than
    // absent. The two genuinely ambiguous cases below stay strict, because
    // there the namespace/label split cannot be determined at all.
    return { form: "bare-label", label: ref };
  }

  const parts = ref.split(":");
  // A contributed kind's prefix is a pivot too (bean `1335`): core's set is
  // the built-in prefixes only, so a registry-holding caller passes the rest.
  const contributed = new Set(contributedPrefixes.map((p) => p.replace(/:$/, "")));
  const pivot = parts.findIndex((p) => KIND_PREFIX_SET.has(p) || contributed.has(p));
  if (pivot < 0) {
    return {
      form: "unresolvable",
      raw: ref,
      reason:
        `no known kind prefix (${KIND_PREFIXES.slice(0, 4).join("/")}/…) — ` +
        `cannot tell namespace from label`,
    };
  }

  const prefix = parts[pivot]!;
  const slug = parts.slice(pivot + 1).join(":");
  if (!slug) {
    return { form: "unresolvable", raw: ref, reason: "empty slug after kind prefix" };
  }

  if (pivot === 0) return { form: "same-paper", prefix, slug };
  return { form: "cross-paper", namespace: parts.slice(0, pivot), prefix, slug };
}

/**
 * `def:quantum-universe` → `def-quantum-universe`.
 *
 * The colon is replaced rather than kept. RFC 3986 would permit it in a
 * non-first path segment, but a colon there trips relative-reference
 * resolution in enough consumers to be not worth defending. Reversible: no
 * kind prefix contains a hyphen, so the first hyphen is the boundary.
 */
export function labelToSegment(prefix: string, slug: string): string {
  return `${prefix}-${slug}`;
}

/** Inverse of {@link labelToSegment}. Returns undefined for a foreign segment. */
export function segmentToLabel(segment: string): string | undefined {
  const dash = segment.indexOf("-");
  if (dash < 0) return undefined;
  const prefix = segment.slice(0, dash);
  if (!KIND_PREFIX_SET.has(prefix)) return undefined;
  return `${prefix}:${segment.slice(dash + 1)}`;
}

/**
 * Resolve an authored reference to the canonical relative IRI for its block.
 *
 * `paper` is the directory name of the paper the reference was written in —
 * it supplies the namespace for the same-paper form, which is why the caller
 * must pass it rather than this being a pure string function.
 *
 * Returns `undefined` only for a reference whose namespace/label split cannot
 * be determined at all — an unknown kind prefix, or an empty slug. Callers
 * should report those rather than drop them: silently omitting the edge is how
 * a graph loses edges without anyone noticing.
 *
 * A reference with NO kind prefix is not in that category and does resolve,
 * by the same rule {@link mintNodeId} uses for a prefix-less label. It is a
 * convention deviation worth REPORTING (`prose` aside, labels carry a prefix)
 * but not worth DROPPING AN EDGE over — see the note in {@link parseReference}.
 */
export function resolveLabel(
  ref: string,
  paper: string,
  contributedPrefixes: readonly string[] = [],
): string | undefined {
  const parsed = parseReference(ref, contributedPrefixes);
  switch (parsed.form) {
    case "absolute":
      return parsed.iri;
    case "same-paper":
      return `papers/${paper}/blocks/${labelToSegment(parsed.prefix, parsed.slug)}`;
    case "cross-paper":
      return (
        `papers/${parsed.namespace.join("/")}/blocks/` +
        labelToSegment(parsed.prefix, parsed.slug)
      );
    case "bare-label":
      // The same segment rule `mintNodeId` applies to a prefix-less label, so
      // a reference and its target agree by construction rather than by luck.
      return `papers/${paper}/blocks/${bareLabelSegment(parsed.label)}`;
    case "unresolvable":
      return undefined;
  }
}

/**
 * The IRI for a block's OWN label. Never fails.
 *
 * Deliberately more forgiving than {@link resolveLabel}, and the asymmetry is
 * the point. A *reference* is a claim that must resolve, so an unparseable one
 * is reported rather than guessed at. A block's own label is definitionally
 * that block's identity — it cannot be "wrong", only unconventional — so a
 * label with no kind prefix still has to yield a unique `@id`.
 *
 * Measured on the qou corpus: emitting a shared `…/blocks/UNRESOLVED`
 * placeholder for these gave **12 blocks the same `@id`**, and the graph index
 * correctly refused to let one overwrite another, so twelve real blocks
 * disappeared from the graph while the generator reported success. Fixtures
 * could not surface it; every fixture label had a prefix.
 */
export function mintNodeId(label: string, paper: string): string {
  const resolved = resolveLabel(label, paper);
  if (resolved) return resolved;
  // No kind prefix. Use the label verbatim as the segment: unique within a
  // paper because labels are, and readable, which an opaque hash would not be.
  return `papers/${paper}/blocks/${bareLabelSegment(label)}`;
}

/**
 * The `@id` segment for a label with no kind prefix.
 *
 * Shared by {@link mintNodeId} and {@link resolveLabel} on purpose: a block's
 * own identity and a reference to it must be computed by ONE rule, or an edge
 * lands on an IRI the target never claimed.
 */
function bareLabelSegment(label: string): string {
  const segment = label.replace(/[^A-Za-z0-9._~-]+/g, "-").replace(/^-+|-+$/g, "");
  return segment || "unlabelled";
}

/** The IRI for a bibliography key (`cites[]` entries are not labels). */
export function resolveReferenceKey(key: string): string {
  return `references/${key}`;
}

// ── The published @context ───────────────────────────────────────

/**
 * The `@context` served at {@link CONTENT_CONTEXT_URL} and referenced by every
 * emitted `.jsonld` — authored siblings and ingested nodes alike. Written as
 * a value here so `ns/content/v1.jsonld` is generated rather than hand-kept.
 */
export const CONTENT_CONTEXT = {
  "@version": 1.1,
  "@base": FOLIO_BASE,
  "folio-assistant-core": CORE_NS,
  doco: DOCO_NS,
  deo: DEO_NS,
  cito: CITO_NS,
  oa: OA_NS,
  prov: PROV_NS,
  skos: SKOS_NS,
  dcterms: DCTERMS_NS,
  fhir: FHIR_NS,
  csvw: CSVW_NS,

  // Identity. `label` is the authored string, kept verbatim alongside the
  // minted `@id` so a grep hit in .jsonld matches a grep hit in .ts.
  label: "folio-assistant-core:label",
  title: "dcterms:title",
  kind: "folio-assistant-core:kind",

  // Editorial relations — folio's own, because no vocabulary models the
  // reader-facing prerequisite relation these encode.
  uses: { "@id": "folio-assistant-core:uses", "@type": "@id", "@container": "@set" },
  interprets: { "@id": "folio-assistant-core:interprets", "@type": "@id" },
  foreshadows: { "@id": "folio-assistant-core:foreshadows", "@type": "@id", "@container": "@set" },
  proofs: { "@id": "folio-assistant-core:proofs", "@type": "@id", "@container": "@set" },
  examples: { "@id": "folio-assistant-core:examples", "@type": "@id", "@container": "@set" },

  cites: { "@id": "cito:cites", "@type": "@id", "@container": "@set" },
  tags: { "@id": "folio-assistant-core:tag", "@container": "@set" },
  defines: { "@id": "folio-assistant-core:defines", "@container": "@set" },

  // Formal side. `leanRef` stays a literal: a Lean declaration is not a web
  // resource, and minting an IRI for one would imply a dereference that does
  // not exist.
  leanRef: "folio-assistant-core:leanRef",
  sorryFree: "folio-assistant-core:sorryFree",

  // Companions, by PATH rather than inlined content. Inlining prose would
  // duplicate the corpus and make every prose edit a two-file diff.
  //
  // LITERALS, not `@id` — bean `589f`, the owner's choice (2026-09-23) for the
  // least drift. The values are paths relative to the DOCUMENT
  // (`../sections/sec-001-intro.md`, `thm-foo.md`). Coerced to `@id`, a
  // JSON-LD processor resolves them against the context's `@base` instead, and
  // `../sections/x.md` became `https://litlfred.github.io/sections/x.md` —
  // a well-formed link to nowhere, on all 1,323 committed prose blocks.
  //
  // A literal has ONE reading: a path, resolved by our tools against the file
  // that carries it, exactly as they already did. Nothing is regenerated and no
  // reader changes.
  //
  // THE UPGRADE RULE, so this does not become the next thing nobody revisits:
  // these become links — `@type: @id` with ABSOLUTE IRIs minted by the one
  // function that mints block IRIs — when, and only when, the files they name
  // are SERVED at a URL an instance declares. Until then any link would be a
  // promise nothing keeps. `check:context-emission` fails if a path is put
  // back under an `@id` term (`checkPathsAreNotLinks`).
  text: { "@id": "folio-assistant-core:text" },
  leanSource: { "@id": "folio-assistant-core:leanSource" },

  meta: { "@id": "folio-assistant-core:meta", "@type": "@json" },

  // ── Ingest-arm records, and the narrative they share — bean `yh6u` ──────
  //
  // `tabular.jsonld` (folio-tabular-records/v1) and `contents.jsonld`
  // (folio-archive-contents/v1) were named `.jsonld` and carried an `@id`, but
  // no `@context`, so a JSON-LD processor dropped every key. And the
  // `narrative` object on 392 committed figure blocks used keys this context
  // did not declare, so every agent-drafted figure narrative was dropped too.
  // Owner's choice, 2026-09-23: make them real JSON-LD, not rename them.
  //
  // THE SPLIT, and why. A fact a consumer queries across documents gets a
  // real term: what the record conforms to, its format, its counts, its
  // header vocabulary. A structure that is OURS and nested — a narrative with
  // its attribution, a sheet's shape, an archive's entry list, a file's
  // technical metadata — is `@json`: kept verbatim, NULLS INCLUDED. That is
  // not a shortcut. The three-state rule lives in those nulls — `text: null`
  // means "nobody has written one", `rows: null` means "could not be counted"
  // — and JSON-LD DROPS a null in any other position, which would make
  // "determined absent" and "never recorded" the same fact. The same reason
  // bean `792y` kept the CSVW record as plain JSON.
  //
  // Datatypes are written as full IRIs rather than through an `xsd` prefix: a
  // prefix spoken only inside this context is one `check:context-emission`
  // correctly reports as bound-and-never-emitted.
  $schema: { "@id": "dcterms:conformsTo" },
  format: { "@id": "dcterms:format" },
  narrative: { "@id": "folio-assistant-core:narrative", "@type": "@json" },
  source: { "@id": "folio-assistant-core:sourceTechnicalMetadata", "@type": "@json" },
  archive: { "@id": "folio-assistant-core:archiveTechnicalMetadata", "@type": "@json" },
  sheets: { "@id": "folio-assistant-core:sheets", "@type": "@json" },
  entries: { "@id": "folio-assistant-core:archiveEntries", "@type": "@json" },
  n_sheets: { "@id": "folio-assistant-core:sheetCount", "@type": "http://www.w3.org/2001/XMLSchema#integer" },
  n_entries: { "@id": "folio-assistant-core:entryCount", "@type": "http://www.w3.org/2001/XMLSchema#integer" },
  n_files: { "@id": "folio-assistant-core:fileCount", "@type": "http://www.w3.org/2001/XMLSchema#integer" },
  n_directories: { "@id": "folio-assistant-core:directoryCount", "@type": "http://www.w3.org/2001/XMLSchema#integer" },
  uncompressed_bytes: { "@id": "folio-assistant-core:uncompressedBytes", "@type": "http://www.w3.org/2001/XMLSchema#integer" },
  // The findable surface — `p67i`: "a grep for a column header finds the
  // dataset that has it". A SET on the record (deduplicated, sorted); an
  // ordered LIST on a table block, where column order is a fact.
  header_vocabulary: { "@id": "folio-assistant-core:headerVocabulary", "@container": "@set" },
  headers: { "@id": "folio-assistant-core:headers", "@container": "@list" },
  // A figure block's image, as a path RELATIVE TO THE BLOCK (`../images/…`).
  // A LITERAL, deliberately — `kg-export`'s rule for a path. Coerced to `@id`
  // it would resolve against `@base` rather than against the block, and name
  // `https://litlfred.github.io/images/…`, which is not where the image is. That
  // is what `text` above does today (bean filed with `yh6u`); it is not copied.
  file: { "@id": "folio-assistant-core:file" },

  // Ingest side. Declared in the shared context precisely so that an
  // ingested node and an authored block are the same kind of thing.
  //
  // `contains` maps to `dcterms:hasPart` rather than DoCO's own containment
  // property. DoCO does not define one: it imports `po:contains` from the
  // Pattern Ontology, which is documented as a sub-property of
  // `dcterms:hasPart`. The Pattern Ontology namespace could not be verified
  // from this sandbox (`sparontologies.github.io` is egress-blocked), and a
  // published context is the wrong place to guess an IRI — so this uses the
  // verified super-property. Generalising is sound; inventing is not.
  // Narrow it to `po:contains` once the namespace can be checked.
  contains: { "@id": "dcterms:hasPart", "@type": "@id", "@container": "@set" },
  refs: { "@id": "folio-assistant-core:refs", "@type": "@id", "@container": "@set" },
  derivedFrom: { "@id": "prov:wasDerivedFrom", "@type": "@id" },
  sourceDocument: { "@id": "folio-assistant-core:sourceDocument", "@type": "@id" },
  provenance: "folio-assistant-core:provenance",
  pageStart: "folio-assistant-core:pageStart",
  pageEnd: "folio-assistant-core:pageEnd",
  strength: "folio-assistant-core:strength",
  // No `certainty` term yet. It must bind to FHIR's GRADE value set
  // (`QualityOfEvidenceRating` on HL7 Terminology), and the exact predicate
  // wants checking against a real IG rather than guessed — it lands with the
  // ingest writer, which is the first thing that will emit one.
} as const;

/** Kinds with no DoCO counterpart — surfaced by the generator's summary. */
export const KINDS_WITHOUT_DOCO_TYPE = BLOCK_KINDS.filter(
  (k) => !BLOCK_KIND_TO_DOCO_TYPE[k],
);

// ── Graph edges ──────────────────────────────────────────────────

/**
 * Context terms that are **graph edges** — a reference from one node to
 * another that a traversal should follow.
 *
 * Not simply "every term typed `@id`": `text` and `leanSource` are also
 * `@id`-typed, but they point at companion *files* rather than at nodes.
 * Following them would put a Markdown file in the middle of a dependency
 * path. So the list is explicit, and `assertEdgeTermsAreIdTyped` guards it
 * against typos and against a term losing its `@id` typing in the context.
 */
export const GRAPH_EDGE_TERMS = [
  "uses",
  "interprets",
  "foreshadows",
  "proofs",
  "examples",
  "cites",
  "contains",
  "refs",
  "derivedFrom",
  "sourceDocument",
] as const;

export type GraphEdgeTerm = (typeof GRAPH_EDGE_TERMS)[number];

/** Terms that point at companion files, deliberately excluded from traversal. */
export const FILE_LINK_TERMS = ["text", "leanSource"] as const;

/**
 * Throws if a graph edge term is missing from the context or is not
 * `@id`-typed there — which would mean the emitter writes a plain string
 * where a traversal expects a node reference.
 */
export function assertEdgeTermsAreIdTyped(): void {
  const ctx = CONTENT_CONTEXT as Record<string, unknown>;
  const bad: string[] = [];
  for (const term of GRAPH_EDGE_TERMS) {
    const def = ctx[term];
    if (!def || typeof def !== "object" || (def as Record<string, unknown>)["@type"] !== "@id") {
      bad.push(term);
    }
  }
  if (bad.length) {
    throw new Error(
      `GRAPH_EDGE_TERMS entries missing or not "@id"-typed in CONTENT_CONTEXT: ${bad.join(", ")}`,
    );
  }
  const overlap = FILE_LINK_TERMS.filter((t) => (GRAPH_EDGE_TERMS as readonly string[]).includes(t));
  if (overlap.length) {
    throw new Error(`file-link terms must not be traversed as edges: ${overlap.join(", ")}`);
  }
}
