/**
 * Wrap a generated page body as a THEMED Jekyll page (2026-10-07).
 *
 * Only pages on the theme's `default` layout get the top band — search,
 * Folio, language — which `docs-ui.js` builds and
 * `_includes/head_custom.html` delivers. A generator that writes a standalone
 * `<!doctype html>` document opts out of it, so the viewer families move onto
 * the layout through this one helper rather than five copies of it.
 *
 * The shape:
 *
 * - **front matter** — `layout: default`, a quoted title, `nav_exclude: true`.
 *   `renders` / `rendered-by` are added afterwards with
 *   `withRendersFrontMatter` (`viewer-declarations.ts`), which is how
 *   `viewerPages` reads a themed page;
 * - **a generated-by note**, outside the raw block;
 * - **the body, LIQUID-RAW.** On the layout Jekyll runs Liquid over the file,
 *   and generated text may carry a double brace or a brace-percent — which
 *   would be evaluated, or fail the build. `wrapRaw` (`liquid-raw.ts`) escapes
 *   the one sequence that would close the block early, byte-identically.
 *
 * What the BODY owes, which this helper cannot enforce: CSS scoped under a page
 * class, with no rule on `body`, `:root` or `a` (on the layout those would
 * restyle the theme); colours that read on the theme's dark ground and its
 * light one (`currentColor`, opacity, a neutral translucent edge); and an
 * explicit `id` on the `h1`.
 *
 * Write the result through a plain emit. `withViewerNav` passes a page with
 * front matter through unchanged — the theme's sidebar is its navigation — so
 * there is no rail to inject.
 *
 * @module scripts/lib/themed-page
 */
import { unescapeRaw, wrapRaw } from "./liquid-raw.ts";

/** A YAML double-quoted scalar: the two characters it treats specially, escaped. */
export function yamlQuoted(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

export interface ThemedPageOptions {
  /** The page title, as the theme shows it in the tab and the search index. */
  title: string;
  /** Repository-relative path of the generator, named in the generated-by note. */
  generator: string;
  /** The command that regenerates the page, e.g. `bun run schema:viz`. */
  command: string;
  /** The page's scoped `<style>` block and markup — everything inside the layout's content column. */
  body: string;
  /**
   * Further front-matter keys, in order: a string is written YAML-quoted, a
   * boolean bare, and an `undefined` value is left out. For keys a family
   * needs and the others do not — `search_exclude`, `alternate_jsonld`.
   */
  frontMatter?: Readonly<Record<string, string | boolean | undefined>>;
}

/** A themed Jekyll page: front matter, a generated-by note, then the body in a Liquid raw block. */
export function themedPage(o: ThemedPageOptions): string {
  const extra = Object.entries(o.frontMatter ?? {})
    .filter((kv): kv is [string, string | boolean] => kv[1] !== undefined)
    .map(([k, v]) => `${k}: ${typeof v === "string" ? yamlQuoted(v) : String(v)}\n`)
    .join("");
  return `---
layout: default
title: ${yamlQuoted(o.title)}
nav_exclude: true
${extra}---
<!--
  GENERATED by ${o.generator}: the next run of
  ${o.command} overwrites it, and its --check fails on the
  difference. A hand-edit here is a change nothing else in the tree knows about.
-->
${wrapRaw(o.body.replace(/\n+$/, "")).join("\n")}
`;
}

const escHtml = (s: string): string =>
  s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);

/**
 * The in-page list of a viewer family's SUBJECT pages — the index and one page
 * per instance — for a themed page.
 *
 * Standalone, these pages listed their subjects in the injected harness rail
 * (`subjectSection`, #1757). Themed, the theme's sidebar is the navigation and
 * the pages are `nav_exclude`d from it, so without this a reader on the index
 * has no way to a subject page but the URL. Relative hrefs, so the same bytes
 * serve the canonical base and a staging slug. The page being read is plain
 * text with `aria-current`, not a link to itself.
 */
export function subjectNav(o: {
  /** Every subject with a page, in display order. */
  subjects: readonly string[];
  /** The subject this page is scoped to; `undefined` on the index. */
  current?: string;
  /** What the index is called, e.g. "All instances". */
  allLabel?: string;
  /** The class the page's CSS is scoped under, e.g. `up-page`. */
  cls: string;
}): string {
  if (o.subjects.length === 0) return "";
  const up = o.current === undefined ? "" : "../";
  const item = (label: string, href: string, here: boolean): string =>
    here ? `<li><span aria-current="page">${escHtml(label)}</span></li>` : `<li><a href="${escHtml(href)}">${escHtml(label)}</a></li>`;
  const items = [
    item(o.allLabel ?? "All instances", up === "" ? "./" : up, o.current === undefined),
    ...o.subjects.map((s) => item(s, `${up}${s}/`, s === o.current)),
  ];
  return `<nav class="${o.cls}-subjects" aria-label="Instances"><ul>${items.join("")}</ul></nav>`;
}

/** CSS for {@link subjectNav}, scoped under the page's wrapper class. */
export function subjectNavCss(cls: string): string {
  const w = `.${cls}`;
  return `${w} .${cls}-subjects ul { list-style:none; display:flex; flex-wrap:wrap; gap:.25rem 1rem; margin:0 0 1rem; padding:0; font-size:.9rem; }
${w} .${cls}-subjects li { margin:0; padding:0; }
${w} .${cls}-subjects li::before { content:none; }
${w} .${cls}-subjects [aria-current] { font-weight:600; }`;
}

/**
 * Every selector in the page's `<style>` blocks that is NOT under `wrapper`
 * (a class, e.g. `.dk-page`), with an allowance for scheme-keyed palettes:
 * `:root[data-fa-scheme="light"] .dk-page …` is scoped. For a test to pin
 * that a themed page restyles nothing of the theme's; `[]` is the pass.
 */
export function unscopedSelectors(html: string, wrapper: string): string[] {
  const css = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)].map((m) => m[1]!).join("\n").replace(/\/\*[\s\S]*?\*\//g, "");
  const out: string[] = [];
  for (const m of css.matchAll(/([^{}]+)\{/g)) {
    const sel = m[1]!.trim();
    if (sel === "" || sel.startsWith("@")) continue;
    // A keyframe step ("from", "50%") is not a selector.
    if (/^(from|to|[\d.]+%)(\s*,\s*(from|to|[\d.]+%))*$/.test(sel)) continue;
    for (const part of sel.split(",").map((p) => p.trim())) {
      const rest = part.replace(/^:root\[data-fa-scheme="(light|dark)"\]\s+/, "");
      if (!(rest === wrapper || rest.startsWith(`${wrapper} `) || rest.startsWith(`${wrapper}.`) || rest.startsWith(`${wrapper}:`) || rest.startsWith(`${wrapper}[`) || rest.startsWith(`${wrapper}>`))) out.push(part);
    }
  }
  return out;
}

/** The body of a themed page: front matter, the generated-by note and the raw tags stripped. */
export function themedBody(page: string): string {
  return unescapeRaw(
    page
      .replace(/^---\n[\s\S]*?\n---\n/, "")
      .replace(/^<!--[\s\S]*?-->\n/, "")
      .replace(/^\{% raw %\}\n/, "")
      .replace(/\n\{% endraw %\}\n?$/, ""),
  );
}
