classDiagram
  direction TB
  namespace detangle__detangle_scripts {
    class n_detangle_detangle_scripts_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_detangle_detangle_scripts_code" fa_uml_kind_code
  cssClass "n_detangle_detangle_scripts_code" fa_uml_undetermined
