import type { TranslationNode } from "../../schemas/translation";

/**
 * Français (fr) translation of the knowledge-graph viewer's chrome.
 *
 * Generated by `bun run translate-kg-viewer --extract`. The source is the
 * string table in `scripts/kg-viewer-strings.ts`, not the page the generator emits —
 * see that module for why a generated artefact is never the translation
 * source.
 *
 * The graph's own content is NOT covered by this node: node names,
 * descriptions and property names come from the corpus and reach the page in
 * whatever language the corpus is written in.
 */
const node: TranslationNode = {
  label: "trans:fr/kg-viewer",
  locale: "fr",
  sourceFile: "scripts/kg-viewer-strings.ts",
  sourceHash: "c9d38dea48c1",
  potFile: "translations/fr/kg-viewer.pot",
  poFile: "translations/fr/kg-viewer.po",
  status: {
    locale: "fr",
    official: false,
    generator: "folio-assistant translate-kg-viewer",
  },
  coverage: { translated: 0, total: 40, pct: 0 },
  title: "Français — knowledge-graph viewer interface",
  description:
    "Interface strings for the knowledge-graph viewer. Not yet translated: the .po carries every msgid with an empty msgstr, awaiting a translator. The page falls back to the English msgid string by string, so nothing renders blank in the meantime.",
};
export default node;
