---
# folio-assistant-9hfi
title: 'smart-immunizations codings.html: CodeSystems and ValueSets show ''not rendered: list-simple-*.xhtml'''
status: completed
type: bug
priority: normal
created_at: 2026-10-06T05:56:52Z
updated_at: 2026-10-06T18:30:00Z
parent: folio-assistant-uhkv
---

Owner, 2026-10-06: on https://litlfred.github.io/smart-immunizations/codings.html both lists render as placeholders:

    CodeSystems ✎ 📣
    ⟦not rendered: list-simple-codesystems.xhtml⟧ — the IG Publisher renders it from a source this build does not hold; no renderer was given to this build.
    ValueSets ✎ 📣
    ⟦not rendered: list-simple-valuesets.xhtml⟧ — (same)

The owner asked "what to do to fix?". Investigation started in session https://claude.ai/code/session_01EcBv3uwKYcnNbCC6BcPG92.

## Done when
- [x] root cause recorded here, with the fix options and the owner's choice — §"Root cause", §"Options", and the owner's choice of (a) below
- [x] codings.html on the built smart-immunizations site lists its CodeSystems and ValueSets, checked on a built page — PR #2294: the fork's folio-site.yml steps were reproduced locally against litlfred/smart-immunizations (Jekyll 4.4.1 with the local just-the-docs gem in place of remote_theme). The built codings.html lists 6 CodeSystems and 192 ValueSets, the index's counts, and all 198 links resolve on the built site. Before and after screenshots were taken with Playwright (Chromium).
- [x] a gate or test fails when a list-simple-* include on a published IG page renders as the placeholder — `build-ig-site.test.ts` › "the Publisher's artefact lists, written from the artefact index (bean 9hfi)" › "a list-simple include on a published IG page lists that type's artefacts, never the placeholder". With the renderer disabled, 4 of its tests fail and the marker appears in the received output. With it restored, 58 of 58 pass.

Related: jut3 (smart-* via just-the-docs, which defines how IG includes render).

## Root cause (measured 2026-10-06, from source)
`stageIgSite()` in fhir-harness/scripts/build-ig-site.ts (~L1011-1035) gathers every {% include X %} the IG pages name. For each one missing from the staged _includes/, it tries a PlantUML render (.svg only), then a copy from the Publisher's <src>/temp/pages/_includes/X. If both miss, it writes notRenderedMarker (L557). list-simple-codesystems.xhtml and list-simple-valuesets.xhtml are generated by the IG Publisher. The fork's CI (fhir-harness/templates/ig-repo-site/folio-site.yml, via stage-ig-sites.ts) runs neither SUSHI nor the Publisher, so temp/ never exists. There is no renderer for list-* includes.

The data is already in hand: smart-immunizations/fhir-artifact-index/index.json holds 748 artefacts (6 CodeSystems, 192 ValueSets), each with a title, description and Publisher category, and it reaches stageIgSite as opts.artifacts.

## Options
- (a) recommended: render list-(simple-)?<kind>.xhtml from the artefact index, following the precedent of templates/ig-site/artifacts.liquid. This is ~60-100 lines plus tests, and it also clears smart-trust's list-structuremaps.xhtml marker (beans bamf, 4475).
- (b) run SUSHI and the IG Publisher in the fork's CI: a ~22 min cold build (bean wnhh), it needs packages.fhir.org and tx.fhir.org, and it runs against jut3's aim.
- (c) scrape WHO's published page: fragile, and it shows upstream content rather than the fork's.
Awaiting the owner's choice.

## Owner, 2026-10-06: "use AST cache? indexing should be there, no?"
Yes. The index exists from two sources:
- smart-immunizations/fhir-artifact-index/index.json, ingested from the published IG, which reaches stageIgSite as opts.artifacts;
- fhir-harness/scripts/ast-to-artifact-index.ts, which derives the same folio-fhir-artifact-index/v1 from an AST restored with ig-cache.sh restore. It is used by stage-ast-sites.ts but NOT by stage-ig-sites.ts or the fork's folio-site.yml.

So the fix is option (a), with the index as the single input: a list-(simple-)?<kind>.xhtml renderer over the artefact index, whichever source produced it, and no IG Publisher run. One caveat from that script's own docblock: an AST does not carry the Publisher's editorial CATEGORY, so publisherCategory() applies the default grouping by resource type. For CodeSystem and ValueSet lists that default is exact, because the grouping is by type.

## Fix, 2026-10-06 (PR #2294)
`stageIgSite` now writes each `list-(simple-)?<types>.xhtml` a page includes as a Liquid include (`templates/ig-site/artifact-list.liquid`) over `site.data.fhir.artifact_lists`, which `artifactVariables` computes from the same artefact index `artifacts.md` reads. The Publisher's own `temp/` copy still wins when it exists. A name that is no FHIR resource type (e.g. `list-simple-profiles.xhtml`) stays a reported marker. smart-trust's `list-structuremaps.xhtml` marker (beans bamf, 4475) is cleared too: its index holds no StructureMaps and its `input/maps-src/` is empty, so the built maps.html says so instead of showing the marker.

_2026-10-06T15:43:51Z_ — Claimed by claude/9hfi-list-simple-renderer — pushed to main so sibling sessions see it before this branch has a PR (bean 35nj).

## Merged 2026-10-06 (session https://claude.ai/code/session_01EcBv3uwKYcnNbCC6BcPG92)
#2294 merged as b9e74a1 after CI PASS on its head (`ci:watch`); every Done-when box above was ticked with evidence, re-checked before merging.
