classDiagram
  direction TB
  namespace cat_harness__beans {
    class n_cat_harness_beans_beans["beans: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_beans_beans" fa_uml_kind_beans
  cssClass "n_cat_harness_beans_beans" fa_uml_undetermined
