classDiagram
  direction TB
  namespace cat_harness__blueprint {
    class n_cat_harness_blueprint_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_blueprint_code" fa_uml_kind_code
  cssClass "n_cat_harness_blueprint_code" fa_uml_undetermined
