classDiagram
  direction TB
  namespace cat_harness__bootstrap_tools_schemas {
    class n_cat_harness_bootstrap_tools_schemas_schemas["schemas: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_bootstrap_tools_schemas_schemas" fa_uml_kind_schemas
  cssClass "n_cat_harness_bootstrap_tools_schemas_schemas" fa_uml_undetermined
