classDiagram
  direction TB
  namespace cat_harness__cat_harness_validators {
    class cat_harness_cat_harness_validators_folio_validator_v1_folio_validator_v1["folio-validator/v1"] {
      <<json: ValidatorNodeSchema>>
      $schema [1] 'folio-validator/v1'
      id [1] string
      validates [1] object
      schema [1] string
      pages [0..1] string
      rationale [0..1] string
    }
  }
  cssClass "cat_harness_cat_harness_validators_folio_validator_v1_folio_validator_v1" fa_uml_kind_validators
