classDiagram
  direction TB
  namespace cat_harness__cat_harness_tests {
    class n_cat_harness_cat_harness_tests_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_cat_harness_tests_code" fa_uml_kind_code
  cssClass "n_cat_harness_cat_harness_tests_code" fa_uml_undetermined
