classDiagram
  direction TB
  namespace cat_harness__deploy {
    class n_cat_harness_deploy_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_deploy_code" fa_uml_kind_code
  cssClass "n_cat_harness_deploy_code" fa_uml_undetermined
