classDiagram
  direction TB
  namespace cat_harness__detangle_schemas {
    class n_cat_harness_detangle_schemas_schemas["schemas: no node schema"] {
      <<could not determine>>
    }
    class n_cat_harness_detangle_schemas_cat_harness["cat-harness: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_detangle_schemas_schemas" fa_uml_kind_schemas
  cssClass "n_cat_harness_detangle_schemas_schemas" fa_uml_undetermined
  cssClass "n_cat_harness_detangle_schemas_cat_harness" fa_uml_kind_cat_harness
  cssClass "n_cat_harness_detangle_schemas_cat_harness" fa_uml_undetermined
