classDiagram
  direction TB
  namespace cat_harness__fsh_guts {
    class n_cat_harness_fsh_guts_fsh_guts["fsh-guts: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_fsh_guts_fsh_guts" fa_uml_kind_fsh_guts
  cssClass "n_cat_harness_fsh_guts_fsh_guts" fa_uml_undetermined
