classDiagram
  direction TB
  namespace cat_harness__glossary {
    class n_cat_harness_glossary_glossary["glossary: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_glossary_glossary" fa_uml_kind_glossary
  cssClass "n_cat_harness_glossary_glossary" fa_uml_undetermined
