classDiagram
  direction TB
  namespace cat_harness__guides {
    class n_cat_harness_guides_doc_group["doc-group: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_guides_doc_group" fa_uml_kind_doc_group
  cssClass "n_cat_harness_guides_doc_group" fa_uml_undetermined
