classDiagram
  direction TB
  namespace cat_harness__index_processes {
    class n_cat_harness_index_processes_auto_docs["auto-docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_index_processes_auto_docs" fa_uml_kind_auto_docs
  cssClass "n_cat_harness_index_processes_auto_docs" fa_uml_undetermined
