classDiagram
  direction TB
  namespace cat_harness__issue_marks {
    class n_cat_harness_issue_marks_issue_marks["issue-marks: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_issue_marks_issue_marks" fa_uml_kind_issue_marks
  cssClass "n_cat_harness_issue_marks_issue_marks" fa_uml_undetermined
