classDiagram
  direction TB
  namespace cat_harness__methodologies {
    class n_cat_harness_methodologies_methodology["methodology: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_methodologies_methodology" fa_uml_kind_methodology
  cssClass "n_cat_harness_methodologies_methodology" fa_uml_undetermined
