classDiagram
  direction TB
  namespace cat_harness__root_docs {
    class n_cat_harness_root_docs_docs["docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_root_docs_docs" fa_uml_kind_docs
  cssClass "n_cat_harness_root_docs_docs" fa_uml_undetermined
