classDiagram
  direction TB
  namespace cat_harness__site {
    class n_cat_harness_site_basic_cdn_site["basic-cdn-site: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_site_basic_cdn_site" fa_uml_kind_basic_cdn_site
  cssClass "n_cat_harness_site_basic_cdn_site" fa_uml_undetermined
