classDiagram
  direction TB
  namespace cat_harness__swimlane_glossary {
    class n_cat_harness_swimlane_glossary_swimlane_glossary_glossary_ledger_1_0_0["swimlane-glossary glossary-ledger/1.0.0: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_swimlane_glossary_swimlane_glossary_glossary_ledger_1_0_0" fa_uml_kind_swimlane_glossary_glossary_ledger_1_0_0
  cssClass "n_cat_harness_swimlane_glossary_swimlane_glossary_glossary_ledger_1_0_0" fa_uml_undetermined
