classDiagram
  direction TB
  namespace cat_harness__swimlane_glossary {
    class cat_harness_swimlane_glossary_glossary_ledger_v1_glossary_ledger_v1["glossary-ledger/v1"] {
      <<json: LedgerSchema>>
      $schema [1] 'glossary-ledger/v1'
      instance [1] string
      concepts [1] map~object~
    }
  }
  cssClass "cat_harness_swimlane_glossary_glossary_ledger_v1_glossary_ledger_v1" fa_uml_kind_swimlane_glossary
