classDiagram
  direction TB
  namespace cat_harness__todos {
    class cat_harness_todos_folio_board_v1_folio_board_v1["folio-board/v1"] {
      <<json: BoardSchema>>
      $schema [1] 'folio-board/v1'
      id [1] string
      title [1] string
      filter [0..1] object
    }
  }
  cssClass "cat_harness_todos_folio_board_v1_folio_board_v1" fa_uml_kind_todos
