classDiagram
  direction TB
  namespace cat_harness__tools {
    class cat_harness_tools_Maintain["Maintain"] {
      <<json: ToolDefinitionSchema>>
      source [1] string
      artefact [1] string
      format [0..1] string
    }
    class cat_harness_tools_ToolDefinition["ToolDefinition"] {
      <<json: ToolDefinitionSchema>>
      id [1] string
      title [1] string
      description [1] string
      install [1] object
      invoke [1] object
      io [1] object
      satisfies [1..*] string[]
      alternativeTo [0..*] string[]
      selection [0..1] object
      requires [0..1] object
      maintains [0..*] Maintain[]
    }
  }
  cat_harness_tools_ToolDefinition *-- "0..*" cat_harness_tools_Maintain : maintains
  cssClass "cat_harness_tools_Maintain" fa_uml_kind_tools
  cssClass "cat_harness_tools_ToolDefinition" fa_uml_kind_tools
