classDiagram
  direction TB
  namespace cat_harness__ui {
    class n_cat_harness_ui_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_ui_code" fa_uml_kind_code
  cssClass "n_cat_harness_ui_code" fa_uml_undetermined
