classDiagram
  direction TB
  namespace cat_harness__uml {
    class n_cat_harness_uml_uml["uml: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_uml_uml" fa_uml_kind_uml
  cssClass "n_cat_harness_uml_uml" fa_uml_undetermined
