---
# folio-assistant-kye5
title: 'TWO README GENERATORS claim bootstrap-tools/README.md: folio-assistant''s readme:sync:all strips the generated-by notices bootstrap-tools'' own writes'
status: completed
type: bug
priority: normal
created_at: 2026-10-01T09:30:25Z
updated_at: 2026-10-07T08:07:00Z
parent: folio-assistant-iirv
---

Found 2026-10-01 (PR #1769). At the bootstrap-tools pin c5e5e25, bun run readme:sync:all:check is red: folio-assistant's cat-harness/content/pipeline/readme-sections.ts rewrites the kg:roles row (adds glossary links) in a SUBMODULE this repo cannot commit to. At bootstrap-tools main (9c00c53) its own scripts/readme-sections.ts adds 'generated by bootstrap-tools' notices, which folio-assistant's generator then REMOVES. Either way the check is red, and a fix pushed upstream from here would regress bootstrap-tools.

The question is ownership, not content: D3 (owner 2026-10-01) says each instance hosts the generated outputs about itself, so a submodule's README is generated by that submodule's tools and folio-assistant should CHECK it only through bootstrap-tools' generator, or not at all.

## Done when
- [x] readme:sync:all skips (or delegates for) READMEs inside a submodule instance
- [x] readme:sync:all:check green at the current bootstrap-tools pin
- [x] the bootstrap-tools branch claude/fervent-brahmagupta-rbwhzm (commit 2ec5eab, pushed, no PR, would regress it) deleted with the owner's ok


## 2026-10-01 — fixed in PR #1769
readme-sections --all now skips an instance whose root is a git submodule (its .git is a file) and SAYS so per README; bootstrap keeps its explicit readme:sync:bootstrap:check (green). isSubmoduleRoot is tested (file / directory / absent / this checkout's bootstrap-tools). readme:sync:all:check green. Remaining: delete bootstrap-tools branch claude/fervent-brahmagupta-rbwhzm (2ec5eab) with the owner's ok.


## Evidence: Closed 2026-10-07
- Items 1–2 landed in PR #1769 (commit `8cfb5e1b21`, 2026-10-01): `readme-sections --all` skips submodule instances, `readme:sync:all:check` passes cleanly.
- Item 3 completed 2026-10-07: The branch `claude/fervent-brahmagupta-rbwhzm` on `litlfred/bootstrap-tools` was deleted via GitHub API (`DELETE /repos/litlfred/bootstrap-tools/git/refs/heads/claude/fervent-brahmagupta-rbwhzm`) following owner confirmation. Verified HTTP 404 response on query. All criteria satisfied.
