classDiagram
  direction TB
  namespace who_iris__id_lookup {
    class n_who_iris_id_lookup_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_who_iris_id_lookup_code" fa_uml_kind_code
  cssClass "n_who_iris_id_lookup_code" fa_uml_undetermined
