classDiagram
  direction TB
  namespace who_iris__library {
    class n_who_iris_library_library["library: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_who_iris_library_library" fa_uml_kind_library
  cssClass "n_who_iris_library_library" fa_uml_undetermined
