"""Shared configuration constants for the QOU pipeline.

All repository paths, chapter metadata, LaTeX-to-Lean mappings, and
GitHub metadata used by multiple scripts are defined here.
"""

import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
CHAPTERS_DIR = REPO_ROOT / "chapters"
LEAN_DIR = REPO_ROOT / "content/quantum-observable-universe/lean"
# Authoritative type definitions (TypeScript + Zod).
# Runtime validation of JSON manifests is done via Zod in the TS pipeline
# (schemas/constraints.ts), not via Python JSON Schema.
TYPES_PATH = REPO_ROOT / "folio-assistant" / "schemas" / "formalization-types.ts"
CONSTRAINTS_PATH = REPO_ROOT / "folio-assistant" / "schemas" / "constraints.ts"
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
DEFAULT_MANIFEST = REPO_ROOT / "proof-objects.json"

# ---------------------------------------------------------------------------
# GitHub / publishing
# ---------------------------------------------------------------------------

GITHUB_REPO = "litlfred/qou"
GH_PAGES_BASE = "https://litlfred.github.io/qou"
DEFAULT_PDF_URL = f"{GH_PAGES_BASE}/quantum-observable-universe.pdf"

# ---------------------------------------------------------------------------
# Chapter metadata
# ---------------------------------------------------------------------------

# Chapter file order (matches main.tex \input order).
# These are generated by the content pipeline from content objects.
CHAPTER_FILES = [
    "introduction.tex",
    "quantum-observable-universe.tex",
    "brings-surface.tex",
    "lifting-of-quantum-torsion.tex",
    "path-integrals-and-braiding.tex",
    "descartes-universe.tex",
    "experimental-evidence.tex",
    "interpretations.tex",
    "glossary.tex",
]

# Map chapter number to Lean file (relative to lean/).
# Chapter numbers match main.tex \input order (0 = introduction, unnumbered).
CHAPTER_LEAN_FILES = {
    2: "QOU/QuantumObservableUniverse.lean",
    3: "QOU/BringsSurface.lean",
    4: "QOU/Torsion.lean",
    5: "QOU/PathIntegrals.lean",
    6: "QOU/DescartesUniverse.lean",
}

# Chapter titles for display (e.g. in dependency graph).
# Keyed by 1-based position in CHAPTER_FILES.
CHAPTER_TITLES = {
    1: "Introduction",
    2: "Ch.1 Quantum Observable Universe",
    3: "Ch.2 Bring's Surface",
    4: "Ch.3 Lifting of Quantum Torsion",
    5: "Ch.4 Path Integrals and Braiding",
    6: "Ch.5 The Descartes Universe",
    7: "Ch.6 Experimental Evidence",
    8: "Ch.7 Interpretations",
}

# ---------------------------------------------------------------------------
# LaTeX environment ↔ proof-object type mapping
# ---------------------------------------------------------------------------

# Map from LaTeX environment name to object_type in the schema.
ENV_TYPES = {
    "theorem": "theorem",
    "lemma": "lemma",
    "proposition": "proposition",
    "corollary": "corollary",
    "definition": "definition",
    "example": "example",
    "remark": "remark",
    "conjecture": "conjecture",
}

# Map object_type to Lean keyword.
LEAN_KEYWORDS = {
    "theorem": "theorem",
    "lemma": "lemma",
    "proposition": "theorem",  # Lean doesn't have proposition keyword
    "corollary": "theorem",
    "definition": "def",
    "conjecture": "theorem",  # conjectures become theorems with sorry
}

# Short prefixes for display labels.
TYPE_PREFIX = {
    "definition": "Def",
    "theorem": "Thm",
    "lemma": "Lem",
    "proposition": "Prop",
    "corollary": "Cor",
    "conjecture": "Conj",
    "example": "Ex",
    "remark": "Rem",
}

# ---------------------------------------------------------------------------
# LaTeX regex patterns
# ---------------------------------------------------------------------------

# Matches \begin{theorem}, \begin{lemma}[title], etc.
BEGIN_RE = re.compile(
    r"\\begin\{(" + "|".join(ENV_TYPES.keys()) + r")\}(?:\[([^\]]*)\])?"
)
LABEL_RE = re.compile(r"\\label\{([^}]+)\}")
LEAN_RE = re.compile(r"\\lean\{([^}]+)\}")
USES_RE = re.compile(r"\\uses\{([^}]+)\}")
LEANOK_RE = re.compile(r"\\leanok\b")

# Maximum lines to scan within a LaTeX environment body.
MAX_ENV_SCAN_LINES = 50

# Keys to preserve when merging Lean linkage data from existing records.
LEAN_MERGE_KEYS = ("url", "file", "sorry_free", "mathlib_links")

# ---------------------------------------------------------------------------
# Review / agent configuration
# ---------------------------------------------------------------------------

VALID_VERDICTS = {"APPROVE", "REQUEST_CHANGES", "NEEDS_DISCUSSION"}
REQUIRED_REVIEW_SECTIONS = ["Summary", "Issues Found", "Suggestions", "Verdict"]

# ---------------------------------------------------------------------------
# Ontologist / Formalizer paths
# ---------------------------------------------------------------------------

DEFAULT_GLOSSARY = REPO_ROOT / "glossary.json"
DEFAULT_MAPPING = REPO_ROOT / "mapping.json"
GLOSSARY_LEAN = LEAN_DIR / "QOU" / "Glossary.lean"

# Tactic mapping: narrative phrases → Lean tactics (used by formalizer).
NARRATIVE_TACTIC_MAP = {
    "by calculation": ("ring", ["field_simp", "polyrith"]),
    "clearly follows from": ("aesop", ["linarith", "omega"]),
    "by the universal property": ("exact Limits.IsLimit.lift", ["exact Limits.IsLimit.hom_ext"]),
    "diagram commutes": ("aesop_cat", ["slice_lhs 1 2 => { simp [Category.assoc] }"]),
    "naturality": ("aesop_cat", ["slice_lhs 1 2 => { rw [NatTrans.naturality] }"]),
    "by contradiction": ("by_contra", ["exfalso"]),
    "by definition": ("rfl", ["unfold", "simp only"]),
}
