/**
 * Conjectural-propagation sweep (CLAUDE.md §3b enforcement).
 *
 * For every `conj:` block in the paper, walk forward (BFS) through
 * the `uses[]` reverse graph and report which provable kinds
 * (theorem / proposition / lemma / corollary) live in each cone.
 *
 * Usage (from repo root):
 *   bun run content/pipeline/conjectural-propagation-sweep.ts [output-path]
 *
 * Default output: `docs/audits/2026-05-01-conjectural-propagation-sweep.md`
 */
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "fs";
import { join, basename, dirname, relative } from "path";

type Block = { kind: string; label: string; uses: string[]; file: string };
const blocks = new Map<string, Block>();

function walk(dir: string) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    const s = statSync(p);
    if (s.isDirectory()) { walk(p); continue; }
    if (!p.endsWith(".ts")) continue;
    if (basename(p).startsWith("index")) continue;
    const src = readFileSync(p, "utf8");
    const m = src.match(/^(?:export default\s+)?(definition|theorem|lemma|proposition|corollary|conjecture|remark|example|prose|equation|diagram|simulator|proof)\s*\(\s*\{/m);
    if (!m) continue;
    const kind = m[1];
    const labelM = src.match(/label\s*:\s*["']([^"']+)["']/);
    if (!labelM) continue;
    const label = labelM[1];
    const usesBlock = src.match(/uses\s*:\s*\[([^\]]*)\]/s);
    const uses: string[] = [];
    if (usesBlock) for (const u of usesBlock[1].matchAll(/["']([^"']+)["']/g)) uses.push(u[1]);
    blocks.set(label, { kind, label, uses, file: relative(process.cwd(), p) });
  }
}

walk("content/quantum-observable-universe");

const conjectureLabels = new Set<string>();
for (const b of blocks.values()) if (b.kind === "conjecture") conjectureLabels.add(b.label);

const reverseDeps = new Map<string, Set<string>>();
for (const b of blocks.values()) {
  for (const u of b.uses) {
    if (!reverseDeps.has(u)) reverseDeps.set(u, new Set());
    reverseDeps.get(u)!.add(b.label);
  }
}

const provable = new Set(["theorem", "proposition", "lemma", "corollary"]);

// For each conjecture, BFS forward (reverseDeps) collecting downstream provable blocks.
// (BFS via shift() — visit-order does not affect the final set, but keeps the
// traversal layered for any future use that depends on dependency-chain order.)
const reportLines: string[] = [];
reportLines.push("# Conjectural-propagation sweep — per-conjecture cones");
reportLines.push("");
reportLines.push("Generated by `pipeline/conjectural-propagation-sweep.ts` (Tier 3 / P3.1).");
reportLines.push("");
reportLines.push("Per CLAUDE.md §3b, every **provable** block (theorem/proposition/lemma/");
reportLines.push("corollary) whose transitive `uses[]` cone reaches a `conj:` label must");
reportLines.push("be demoted to `conjecture`. This file lists the cones grouped by the");
reportLines.push("upstream conjecture.");
reportLines.push("");
reportLines.push("**Note (CLAUDE.md §3b clarification):** definitions that transitively");
reportLines.push("touch a conjecture are *not* automatic violations — only provable");
reportLines.push("kinds. This report restricts to provable kinds.");
reportLines.push("");

// Aggregate
type Hit = { label: string; kind: string; file: string };
const conjToProvable = new Map<string, Hit[]>();

for (const c of conjectureLabels) {
  const visited = new Set<string>();
  const queue: string[] = [c];
  while (queue.length) {
    const cur = queue.shift()!;
    const deps = reverseDeps.get(cur);
    if (!deps) continue;
    for (const d of deps) {
      if (visited.has(d)) continue;
      visited.add(d);
      queue.push(d);
    }
  }
  const hits: Hit[] = [];
  for (const lab of visited) {
    const b = blocks.get(lab);
    if (b && provable.has(b.kind)) hits.push({ label: lab, kind: b.kind, file: b.file });
  }
  hits.sort((a,b)=>a.label.localeCompare(b.label));
  conjToProvable.set(c, hits);
}

// Summary
const conjsByCone = [...conjToProvable.entries()].sort((a,b)=>b[1].length - a[1].length);

reportLines.push("## Summary");
reportLines.push("");
reportLines.push("| Conjecture | Provable cone size | File |");
reportLines.push("|------------|-------------------:|------|");
for (const [c, hits] of conjsByCone) {
  const cb = blocks.get(c);
  reportLines.push(`| \`${c}\` | ${hits.length} | \`${cb?.file ?? '?'}\` |`);
}
reportLines.push("");
const total = [...conjToProvable.values()].reduce((s,h)=>s+h.length,0);
const uniqueAffected = new Set<string>();
for (const hits of conjToProvable.values()) for (const h of hits) uniqueAffected.add(h.label);
reportLines.push(`**Total provable blocks affected (unique):** ${uniqueAffected.size}.`);
reportLines.push(`**Total (with multiplicity):** ${total}.`);
reportLines.push("");

// Per-conjecture sections
reportLines.push("## Per-conjecture cones");
reportLines.push("");
for (const [c, hits] of conjsByCone) {
  if (hits.length === 0) continue;
  const cb = blocks.get(c);
  reportLines.push(`### \`${c}\` — ${hits.length} downstream provable block${hits.length===1?"":"s"}`);
  reportLines.push("");
  if (cb) reportLines.push(`Source: [\`${cb.file}\`](../../${cb.file})`);
  reportLines.push("");
  reportLines.push(`| Kind | Label | File |`);
  reportLines.push(`|------|-------|------|`);
  for (const h of hits) {
    reportLines.push(`| ${h.kind} | \`${h.label}\` | \`${h.file}\` |`);
  }
  reportLines.push("");
}

// Conjectures with empty cones
const empty = conjsByCone.filter(([,h])=>h.length===0).map(([c])=>c);
if (empty.length) {
  reportLines.push("## Conjectures with no downstream provable blocks");
  reportLines.push("");
  for (const c of empty) reportLines.push(`- \`${c}\``);
  reportLines.push("");
}

const outputPath = process.argv[2] ?? "docs/audits/2026-05-01-conjectural-propagation-sweep.md";
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, reportLines.join("\n"));
console.log(`Wrote ${outputPath}`);
console.log(`Conjectures: ${conjectureLabels.size}`);
console.log(`Unique provable blocks in any cone: ${uniqueAffected.size}`);
