#!/usr/bin/env bun
/**
 * Script-reviewer checkers for the non-voice integration-watcher
 * axes:
 *
 *   - proof-*        (5 criteria, 3 script + 2 mixed/agent)
 *   - canonical-*    (3 criteria, 2 script + 1 agent)
 *   - compute-*      (4 criteria, all script)
 *   - detangler-*    (4 criteria, all script)
 *   - bib-*          (4 criteria, all script)
 *
 * Each checker returns the same `{ result, hits }` shape as the
 * voice checkers in `qa-checkers-voice.ts`, so they wire into the
 * existing `AUTOMATED_CHECKERS` dispatcher unchanged.
 *
 * Many checkers delegate to existing repo scripts (`bib-qa.ts`,
 * `validate-references.ts`, `compute_audit_scan.py`, etc.) by
 * reading the cached JSON artefacts those scripts produce, rather
 * than re-running them per block. This keeps `qa-sweep` fast
 * (sub-second per block) while preserving the canonical sources.
 *
 * @module content/pipeline/qa-checkers-extended
 */

import { existsSync, readFileSync } from "fs";
import { resolve, dirname, join, relative } from "path";
import { fileURLToPath } from "url";
import { Q_USAGE_AUTOMATED_CHECKERS } from "./qa-checkers-q-usage";
import { hashFile } from "./qa-utils";

const __filename = fileURLToPath(import.meta.url);
// The pipeline normally lives vendored inside the content repo
// (`<repo>/content/pipeline/`), so REPO_ROOT is two levels up. When the
// pipeline runs as a *sibling* checkout (the miga layout: content repo and
// folio-assistant side by side, wired by a symlink), that heuristic points
// at the folio-assistant clone instead of the content repo — the compile-
// diagnostics / witness / computations paths then resolve to the wrong tree.
// Honour an explicit `QA_REPO_ROOT` override for that case (defaults to the
// legacy behaviour, so vendored / CI runs are unchanged).
const REPO_ROOT = process.env.QA_REPO_ROOT
  ? resolve(process.env.QA_REPO_ROOT)
  : resolve(dirname(__filename), "..", "..");
const CONTENT_DIR = resolve(dirname(__filename), "..");
const COMPUTATIONS_DIR = join(REPO_ROOT, "folio-assistant", "computations");
const BIB_QA_IMAGES_DIR = join(CONTENT_DIR, "bib-qa-images");
const BIB_QA_REPORT = join(CONTENT_DIR, "bib-qa.json");

export interface CheckerHit {
  file: string;
  line: number;
  text: string;
}

export interface CheckerResult {
  /**
   * Outcome. `warn` is preserved end-to-end (matches block-qa/v1's
   * `QaCriterionEntry.result` union) so a soft finding lands in the
   * sidecar without being silently coerced to `pass`.
   */
  result: "pass" | "fail" | "warn" | "n/a";
  hits: CheckerHit[];
  /**
   * Optional human-readable context threaded into the sidecar entry's
   * `notes` field. Used by cache-backed checkers (e.g.
   * `proof-lean-compiles`) to record WHY a result is `n/a` — for
   * instance "cached diagnostics are stale relative to current .lean".
   */
  notes?: string;
  /**
   * Optional structured numeric/heuristic measures persisted into the
   * sidecar entry's `metrics` field (see `QaCriterionEntry.metrics`).
   * Used by the detangler axis to record per-block graph measures
   * (degree, dependency-cone size, edge span, graph energy, topic
   * coherence) alongside the pass/fail verdict.
   */
  metrics?: Record<string, number | string>;
}

// ── Lazy-loaded bib-qa report (cached across calls per process) ─

let bibQaReportCache: Record<string, unknown> | null = null;
function loadBibQaReport(): Record<string, unknown> | null {
  if (bibQaReportCache !== null) return bibQaReportCache;
  if (!existsSync(BIB_QA_REPORT)) {
    bibQaReportCache = {};
    return bibQaReportCache;
  }
  try {
    bibQaReportCache = JSON.parse(readFileSync(BIB_QA_REPORT, "utf-8"));
  } catch {
    bibQaReportCache = {};
  }
  return bibQaReportCache;
}

// Extract `\cite{key1, key2}` + `-- Ref: [key]` from .md / .lean.
function extractCitations(text: string): Set<string> {
  const keys = new Set<string>();
  // \cite{a,b} / \citep{a} / \citet{a}
  for (const m of text.matchAll(
    /\\cite[a-zA-Z]*(?:\[[^\]]*\])?\{([^}]+)\}/g,
  )) {
    for (const k of m[1].split(",")) {
      const trimmed = k.trim();
      if (trimmed) keys.add(trimmed);
    }
  }
  // -- Ref: [key]
  for (const m of text.matchAll(/--\s*Ref:\s*\[([^\]]+)\]/g)) {
    keys.add(m[1].trim());
  }
  return keys;
}

function readMaybe(path: string | undefined): string {
  if (!path || !existsSync(path)) return "";
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return "";
  }
}

// ─── Bibliography axis ──────────────────────────────────────────

// Lazily-built set of known reference ids, sourced first from
// `references.ts` (always available, committed source) and second from
// `bib-qa.json` (gitignored — generated by `pipeline/bib-qa.ts`; only
// present after a local/CI bib-qa run).
let bibIdSetCache: Set<string> | null = null;
function loadBibIdSet(): Set<string> {
  if (bibIdSetCache !== null) return bibIdSetCache;
  const set = new Set<string>();
  // Primary source: references.ts. Parse out every `id: "<key>"`.
  // This is robust to bib-qa.json absence (the file is gitignored).
  try {
    const refsPath = join(CONTENT_DIR, "schema", "references.ts");
    if (existsSync(refsPath)) {
      const src = readFileSync(refsPath, "utf-8");
      const idRe = /\bid:\s*"([^"]+)"/g;
      for (const m of src.matchAll(idRe)) set.add(m[1]);
    }
  } catch {
    /* fall through to bib-qa.json */
  }
  // Secondary: bib-qa.json (entries is a LIST of {id, …} records).
  const report = loadBibQaReport();
  const entriesRaw = report?.entries;
  if (Array.isArray(entriesRaw)) {
    for (const e of entriesRaw) {
      if (e && typeof e === "object" && "id" in e) {
        const id = (e as { id?: unknown }).id;
        if (typeof id === "string") set.add(id);
      }
    }
  } else if (entriesRaw && typeof entriesRaw === "object") {
    for (const k of Object.keys(entriesRaw as Record<string, unknown>)) {
      set.add(k);
    }
  }
  // `manuscript` is the canonical placeholder for unpublished references
  // (per CLAUDE.md §1) — always accept even if absent from references.ts.
  set.add("manuscript");
  bibIdSetCache = set;
  return set;
}

export function checkBibCiteResolves(
  mdPath: string | undefined,
  leanPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  const lean = readMaybe(leanPath);
  const keys = new Set<string>([
    ...extractCitations(md),
    ...extractCitations(lean),
  ]);
  if (keys.size === 0) return { result: "pass", hits: [] };

  const entrySet = loadBibIdSet();

  const hits: CheckerHit[] = [];
  for (const key of keys) {
    // Skip cross-paper qualified references (`paper-dir:label`) — they
    // are validated at the folio level, not by the per-paper bib check.
    if (/^[a-z0-9_-]+:/.test(key)) continue;
    if (!entrySet.has(key)) {
      hits.push({
        file: mdPath ?? leanPath ?? "(unknown)",
        line: 1,
        text: `\\cite{${key}} or -- Ref: [${key}] does not resolve in references.ts`,
      });
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

function checkBibRefTag(
  mdPath: string | undefined,
  leanPath: string | undefined,
  tagKey: string,
  describe: string,
): CheckerResult {
  const md = readMaybe(mdPath);
  const lean = readMaybe(leanPath);
  const keys = new Set<string>([
    ...extractCitations(md),
    ...extractCitations(lean),
  ]);
  if (keys.size === 0) return { result: "pass", hits: [] };

  const report = loadBibQaReport();
  const entries = (report?.entries ?? {}) as Record<
    string,
    { tags?: Array<{ key: string; status: string }> }
  >;
  const hits: CheckerHit[] = [];
  for (const key of keys) {
    const entry = entries[key];
    if (!entry) continue; // resolution failure is a different criterion
    const tag = entry.tags?.find((t) => t.key === tagKey);
    if (!tag || tag.status !== "pass") {
      hits.push({
        file: mdPath ?? leanPath ?? "(unknown)",
        line: 1,
        text: `cite [${key}] fails bib-qa tag '${tagKey}' (${describe})`,
      });
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

export function checkBibCitedRefHasUrl(
  mdPath: string | undefined,
  leanPath: string | undefined,
): CheckerResult {
  return checkBibRefTag(mdPath, leanPath, "has_url", "no URL or DOI");
}

export function checkBibCitedRefMetadataOk(
  mdPath: string | undefined,
  leanPath: string | undefined,
): CheckerResult {
  return checkBibRefTag(
    mdPath,
    leanPath,
    "metadata_ok",
    "missing title/author/year",
  );
}

export function checkBibCitedRefHasScreenshot(
  mdPath: string | undefined,
  leanPath: string | undefined,
): CheckerResult {
  return checkBibRefTag(
    mdPath,
    leanPath,
    "has_screenshot",
    "no screenshot under content/bib-qa-images/",
  );
}

// ─── Compute axis ───────────────────────────────────────────────

function readTs(path: string | undefined): string {
  return readMaybe(path);
}

function getComputationField(tsSrc: string): {
  witness?: string;
  witnesses?: string[];
  probe?: string;
} {
  // Light extraction — looks for `computation: { witness: "..." }`,
  // `computation: { witness: [...] }`, and `probe: "..."` patterns at
  // any nesting depth.
  //
  // Comments are stripped first so a `witness:` token inside a `//`
  // or `/* */` comment is not picked up as a real declaration.
  //
  // Both forms are normalised into a `witnesses: string[]` so consumers
  // can validate the FULL declared dependency set (`checkComputeWitnessExists`
  // iterates and checks every path on disk). The legacy `witness?: string`
  // slot returns the first element for back-compat with consumers that
  // only need to know that SOMETHING is declared
  // (e.g. `canonical-witness-pinned`).
  const cleanSrc = tsSrc.replace(/\/\*[\s\S]*?\*\/|\/\/.*/g, "");
  const result: {
    witness?: string;
    witnesses?: string[];
    probe?: string;
  } = {};
  const witnessRe = /witness:\s*(?:\[([^\]]*)\]|["']([^"']+)["'])/;
  const witnessMatch = cleanSrc.match(witnessRe);
  if (witnessMatch) {
    if (witnessMatch[2]) {
      // String form: witness: "path"
      result.witnesses = [witnessMatch[2]];
    } else {
      // Array form: witness: ["a", "b", ...] — extract every quoted item.
      const arrayBody = witnessMatch[1] ?? "";
      const items = [...arrayBody.matchAll(/["']([^"']+)["']/g)].map(
        (m) => m[1],
      );
      if (items.length > 0) result.witnesses = items;
    }
    if (result.witnesses && result.witnesses.length > 0) {
      result.witness = result.witnesses[0];
    }
  }
  const probeMatch = cleanSrc.match(/probe:\s*["']([^"']+)["']/);
  if (probeMatch) result.probe = probeMatch[1];
  return result;
}

// Lazily-loaded I1 no-probe audit (the source of truth for which
// blocks have probe wiring). Generated by
// `folio-assistant/computations/audits/i1_no_probe_audit.py`.
const I1_NO_PROBE_AUDIT = join(
  REPO_ROOT,
  "folio-assistant",
  "computations",
  "i1-no-probe-audit.witness.json",
);
let i1AuditCache: Map<string, string> | null = null;
function loadI1Audit(): Map<string, string> {
  if (i1AuditCache !== null) return i1AuditCache;
  const m = new Map<string, string>();
  if (!existsSync(I1_NO_PROBE_AUDIT)) {
    i1AuditCache = m;
    return m;
  }
  try {
    const d = JSON.parse(readFileSync(I1_NO_PROBE_AUDIT, "utf-8"));
    const rows = (d?.data as { rows?: unknown })?.rows;
    if (Array.isArray(rows)) {
      for (const r of rows) {
        const path = (r as { path?: unknown }).path;
        const result = (r as { result?: unknown }).result;
        if (typeof path === "string" && typeof result === "string") {
          m.set(path, result);
          // Also key by .ts stem for path-shape robustness.
          const stem = path.replace(/^content\//, "");
          m.set(stem, result);
        }
      }
    }
  } catch {
    /* leave map empty */
  }
  i1AuditCache = m;
  return m;
}

export function checkComputePropHasProbe(
  tsPath: string | undefined,
  leanPath?: string | undefined,
): CheckerResult {
  const ts = readTs(tsPath);
  if (!ts) return { result: "n/a", hits: [] };
  // Blocks with sorry-free Lean proofs are formally verified —
  // a computational probe is redundant for structural/algebraic
  // results. Only blocks making numerical predictions (those with
  // :val[] directives or computation: fields) still need probes.
  if (leanPath && existsSync(resolve(REPO_ROOT, leanPath))) {
    const lean = readFileSync(resolve(REPO_ROOT, leanPath), "utf-8");
    // Strip Lean comments before checking for sorry:
    //   /-! ... -/ and /- ... -/ (block/doc comments)
    //   -- ...  (line comments)
    // "sorry" in a docstring ("currently a sorry placeholder") or
    // bibliographic citation ("-- Ref: ... sorry") is not a proof gap.
    const leanCode = lean
      .replace(/\/\-[\!]?[\s\S]*?\-\//g, "")
      .split("\n").map((l) => l.split("--")[0]).join("\n");
    if (!leanCode.includes("sorry")) {
      return { result: "pass", hits: [] };
    }
  }
  // **First-class direct evidence**: if the block's own `.ts` declares
  // a `computation:` block (with `script` and/or `witness`) or a
  // legacy `probe:` field, that IS the probe declaration. The
  // i1-no-probe audit reports `i1_no_probe` when no *upstream* witness
  // has `contentBlock` matching this block's label — but the block's
  // own self-declared computation pointer is the more authoritative
  // signal and shouldn't be overridden by the upstream-side audit.
  const { probe, witnesses } = getComputationField(ts);
  if (probe || (witnesses && witnesses.length > 0)) {
    return { result: "pass", hits: [] };
  }
  // No direct evidence in .ts — consult the i1-no-probe audit, which
  // looks for any witness in the corpus whose `contentBlock` field
  // matches this block's label.
  if (tsPath) {
    const audit = loadI1Audit();
    const tsRel = relative(REPO_ROOT, tsPath);
    const result =
      audit.get(tsRel) ??
      audit.get(tsRel.replace(/^content\//, "")) ??
      audit.get(tsPath);
    if (result === "wired" || result === "conditional_class" || result === "i1_lean_with_sorry") {
      return { result: "pass", hits: [] };
    }
    if (result === "i1_no_probe") {
      return {
        result: "fail",
        hits: [
          {
            file: tsPath,
            line: 1,
            text:
              "no probe witness for this prop — every prop:/theorem: " +
              "needs an I1 probe witness per CLAUDE.md compute-integration §B " +
              "(audit: i1-no-probe-audit.witness.json)",
          },
        ],
      };
    }
  }
  return {
    result: "fail",
    hits: [
      {
        file: tsPath ?? "(unknown)",
        line: 1,
        text:
          "no `probe:` field or `computation:` block declared — every prop:/theorem: " +
          "needs an I1 probe witness per CLAUDE.md compute-integration §B",
      },
    ],
  };
}

// Lazily-loaded I2 probe-only audit (lists witnesses with no
// production consumer). Generated by
// `folio-assistant/computations/audits/i2_probe_only_audit.py`.
const I2_PROBE_ONLY_AUDIT = join(
  REPO_ROOT,
  "folio-assistant",
  "computations",
  "i2-probe-only-audit.witness.json",
);
let i2AuditByWitnessCache: Map<string, { result: string; consumers: string[] }> | null =
  null;
function loadI2AuditByWitness(): Map<
  string,
  { result: string; consumers: string[] }
> {
  if (i2AuditByWitnessCache !== null) return i2AuditByWitnessCache;
  const m = new Map<string, { result: string; consumers: string[] }>();
  if (!existsSync(I2_PROBE_ONLY_AUDIT)) {
    i2AuditByWitnessCache = m;
    return m;
  }
  try {
    const d = JSON.parse(readFileSync(I2_PROBE_ONLY_AUDIT, "utf-8"));
    const rows = (d?.data as { rows?: unknown })?.rows;
    if (Array.isArray(rows)) {
      for (const r of rows) {
        const witness = (r as { witness?: unknown }).witness;
        const result = (r as { result?: unknown }).result;
        const consumers = (r as { production_consumers?: unknown })
          .production_consumers;
        if (typeof witness === "string" && typeof result === "string") {
          const c = Array.isArray(consumers)
            ? consumers.filter((s): s is string => typeof s === "string")
            : [];
          m.set(witness, { result, consumers: c });
        }
      }
    }
  } catch {
    /* leave map empty */
  }
  i2AuditByWitnessCache = m;
  return m;
}

export function checkComputePropHasConsumer(
  tsPath: string | undefined,
  leanPath?: string | undefined,
): CheckerResult {
  const ts = readTs(tsPath);
  if (!ts) return { result: "n/a", hits: [] };
  // Same exemption as compute-prop-has-probe: sorry-free Lean
  // proofs are formally verified — no compute consumer needed.
  if (leanPath && existsSync(resolve(REPO_ROOT, leanPath))) {
    const lean = readFileSync(resolve(REPO_ROOT, leanPath), "utf-8");
    const leanCode2 = lean
      .replace(/\/\-[\!]?[\s\S]*?\-\//g, "")
      .split("\n").map((l) => l.split("--")[0]).join("\n");
    if (!leanCode2.includes("sorry")) {
      return { result: "pass", hits: [] };
    }
  }
  // Primary: the block has a `consumers:` field with at least one entry.
  const consumersMatch = ts.match(/consumers:\s*\[([^\]]*)\]/);
  if (consumersMatch && consumersMatch[1].trim() !== "") {
    return { result: "pass", hits: [] };
  }
  // Secondary: any `computation:` declaration (script and/or witness)
  // counts as wiring. A self-declared probe IS evidence that the prop
  // is computationally backed; the I2 audit may not yet record
  // production_consumers for new or shared witnesses. The .ts is the
  // authoritative source for the block's own wiring intent.
  const { witnesses, probe } = getComputationField(ts);
  if (probe || (witnesses && witnesses.length > 0)) {
    return { result: "pass", hits: [] };
  }
  // Tertiary: I2 audit confirms production consumers for the block's
  // witness (kept as a fallback for blocks that declare via different
  // shapes my regex doesn't catch).
  if (witnesses && witnesses.length > 0) {
    const audit = loadI2AuditByWitness();
    for (const w of witnesses) {
      const entry = audit.get(w);
      if (entry && entry.result === "wired_production") {
        return { result: "pass", hits: [] };
      }
      if (entry && entry.consumers.length > 0) {
        return { result: "pass", hits: [] };
      }
    }
  }
  return {
    result: "fail",
    hits: [
      {
        file: tsPath ?? "(unknown)",
        line: 1,
        text:
          "no `consumers:` field and no `computation:` declaration — " +
          "the prop is NOT-WIRED per CLAUDE.md compute-integration §B " +
          "(I2-I13)",
      },
    ],
  };
}

export function checkComputeWitnessExists(
  tsPath: string | undefined,
): CheckerResult {
  const ts = readTs(tsPath);
  if (!ts) return { result: "n/a", hits: [] };
  const { witnesses } = getComputationField(ts);
  if (!witnesses || witnesses.length === 0) {
    return { result: "pass", hits: [] };
  }
  // Iterate the full declared dependency set; surface every missing /
  // empty witness so a multi-witness block doesn't hide a stale entry
  // behind the first valid one.
  const hits: CheckerHit[] = [];
  for (const witness of witnesses) {
    const absPath = witness.startsWith("/")
      ? witness
      : resolve(REPO_ROOT, witness);
    if (!existsSync(absPath)) {
      hits.push({
        file: tsPath ?? "(unknown)",
        line: 1,
        text: `declared witness '${witness}' does not exist on disk`,
      });
      continue;
    }
    try {
      const content = readFileSync(absPath, "utf-8");
      if (content.trim().length === 0) {
        hits.push({
          file: tsPath ?? "(unknown)",
          line: 1,
          text: `declared witness '${witness}' exists but is empty`,
        });
      }
    } catch {
      /* fall through to pass */
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

const LP_DUAL_HINT_RE =
  /lp-dual|operator-selection-lp|shadow-price|primal-dual|lp-duality/i;
const LP_DUAL_REQUIRED_FIELDS = [
  "y0_star",
  "y_star",
  "primal_obj",
  "dual_obj",
  "duality_gap",
];
const LP_DUAL_ACTIVE_ALIASES = [
  "active_set",
  "active_constraints",
  "active_channels",
];

export function checkComputeLpDualPresent(
  tsPath: string | undefined,
): CheckerResult {
  const ts = readTs(tsPath);
  if (!ts) return { result: "n/a", hits: [] };
  const { witness } = getComputationField(ts);
  if (!witness) return { result: "pass", hits: [] };
  // Filter: only blocks whose ts mentions LP/SDP/operator-selection
  // OUTSIDE the `uses: [...]` array. References inside `uses:` are
  // downstream dependencies (the block consumes an LP result) — they
  // do not imply the block's OWN witness must carry LP dual fields.
  // Strip uses: array + cites: array + interprets: field — these are
  // downstream references, not evidence the block computes LP duals.
  const tsStripped = ts
    .replace(/\buses\s*:\s*\[[\s\S]*?\]/g, "")
    .replace(/\bcites\s*:\s*\[[\s\S]*?\]/g, "")
    .replace(/\binterprets\s*:\s*"[^"]*"/g, "");
  if (!LP_DUAL_HINT_RE.test(tsStripped)) {
    return { result: "pass", hits: [] };
  }
  // Require the LP hint to appear in the computation SCRIPT or
  // WITNESS filename — not just in tags/title. Tags describe the
  // block's theoretical context; the script/witness filename
  // indicates what the computation actually produces.
  // Require LP evidence in compute artifacts (script/witness name)
  // OR in the block label. Tags alone are too loose (a block can
  // be ABOUT LP duality without its own script computing LP duals).
  const scriptName = (ts.match(/script:\s*"([^"]+)"/)?.[1] ?? "").toLowerCase();
  const witnessName = (witness ?? "").toLowerCase();
  const label = (ts.match(/label:\s*"([^"]+)"/)?.[1] ?? "").toLowerCase();
  const LP_COMPUTE_RE = /\blp[-_]|[-_]lp\b|sdp[-_]|[-_]sdp\b|operator[-_]selection|shadow[-_]price/;
  const computeOrLabel = `${scriptName} ${witnessName} ${label}`;
  if (!LP_COMPUTE_RE.test(computeOrLabel)) {
    return { result: "pass", hits: [] };
  }
  const absPath = witness.startsWith("/")
    ? witness
    : resolve(REPO_ROOT, witness);
  if (!existsSync(absPath)) return { result: "pass", hits: [] };
  let body: Record<string, unknown> = {};
  try {
    body = JSON.parse(readFileSync(absPath, "utf-8"));
  } catch {
    return { result: "pass", hits: [] };
  }
  // LP fields may live at the top level OR nested anywhere reachable
  // by a shallow walk (the conventional layout for WitnessBuilder
  // outputs from `solve_operator_selection_lp` /
  // `solve_psd_operator_selection_sdp` is `data.<field>`, but some
  // producers wrap the solver result one level deeper at
  // `data.sdp_full.<field>` / `data.lp_full.<field>` /
  // `data.solver_result.<field>`).
  //
  // Walk up to 3 levels deep. The required fields (`y0_star`,
  // `y_star`, `primal_obj`, `dual_obj`, `duality_gap`) are
  // highly specific to the LP-dual convention, so false positives
  // from arbitrary keys are unlikely.
  const containsField = (
    obj: unknown,
    field: string,
    depth = 0,
  ): boolean => {
    if (depth > 3 || obj === null || typeof obj !== "object") return false;
    const rec = obj as Record<string, unknown>;
    if (field in rec) return true;
    for (const v of Object.values(rec)) {
      if (containsField(v, field, depth + 1)) return true;
    }
    return false;
  };
  const hasField = (f: string) => containsField(body, f);
  const hasActive = LP_DUAL_ACTIVE_ALIASES.some((a) => containsField(body, a));
  const missing: string[] = [];
  for (const f of LP_DUAL_REQUIRED_FIELDS) {
    if (!hasField(f)) missing.push(f);
  }
  if (!hasActive) {
    missing.push(`active_set (or alias: ${LP_DUAL_ACTIVE_ALIASES.join("/")})`);
  }
  if (missing.length === 0) return { result: "pass", hits: [] };
  return {
    result: "fail",
    hits: [
      {
        file: tsPath ?? "(unknown)",
        line: 1,
        text: `LP/SDP witness '${witness}' missing dual field(s): ${missing.join(", ")}`,
      },
    ],
  };
}

// ─── Canonical axis ─────────────────────────────────────────────

const CALIBRATION_RE = /\b(calibration|anchor)\s*:\s*(?:".*?"|\d+)/g;

export function checkCanonicalCalibrationCount(
  mdPath: string | undefined,
  tsPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  const ts = readMaybe(tsPath);
  const combined = md + "\n" + ts;
  // De-duplicate: the same calibration anchor is routinely declared in
  // BOTH the .md narrative and the .ts manifest, so a raw global-regex
  // count double-counts it and can push a legitimate 3-calibration
  // block over the threshold into a false fail. Count distinct anchor
  // declarations only.
  const matches = [...new Set(combined.match(CALIBRATION_RE) ?? [])];
  if (matches.length <= 3) return { result: "pass", hits: [] };
  return {
    result: "fail",
    hits: [
      {
        file: mdPath ?? tsPath ?? "(unknown)",
        line: 1,
        text:
          `block declares ${matches.length} calibration anchors — exceeds the ` +
          `three-calibration discipline (CODATA m_e + α + G_Planck only)`,
      },
    ],
  };
}

const VAL_DIRECTIVE_RE = /:val\[([^\]]+)\]\{([^}]+)\}/g;

// Negative-result / falsified-probe signal patterns. A block whose
// primary content is one of these is audit material, not paper material
// (CLAUDE.md authoring discipline added 2026-05-31 in
// docs/audits/2026-05-31-ck-exploratory-probes-removed.md). The .md
// signals fire on *opening* prose: "## Status: ... falsified",
// "Hypothesis falsified", "## Status: open R&D — no known", etc.
//
// Note on `scaffolding`: handled separately below — only flagged when
// paired with a `open-rd-item-*` tag (WIP marker). A standalone
// `scaffolding` tag means *axiomatic scaffolding* (categorical /
// structural buildup, e.g. braid-group-n-strand as the axiomatic
// scaffold generalising B_2/B_3) and is legitimate paper content. See
// docs/audits/2026-06-03-canonical-axis-current-fails-triage.md
// Pattern A.1 for the cases that motivated the distinction.
const NEG_RESULT_TAGS = new Set([
  "negative-result",
  "falsified",
  "superseded",
]);
// .md status markers — accept ASCII hyphen, en-dash, and em-dash for
// the dash separator after "Status:" / "Errata banner" prefixes.
const _DASH = "[-\\u2013\\u2014]";
const NEG_RESULT_MD_SIGNALS: RegExp[] = [
  new RegExp(`^##\\s+Status\\s*:[^\\n]*\\bfalsified\\b`, "im"),
  new RegExp(`^##\\s+Status\\s*:[^\\n]*\\bopen\\s+R&D\\s*${_DASH}\\s*no\\s+known`, "im"),
  new RegExp(`^##\\s+Status\\s*:[^\\n]*\\bsuperseded\\b`, "im"),
  /\*\*Hypothesis\s+falsified\.?\*\*/i,
  new RegExp(`^>\\s*\\*\\*Errata\\s+banner\\s*${_DASH}[^\\n]*\\bsuperseded\\b`, "im"),
];

export function checkCanonicalNoNegativeResultInPaper(
  mdPath: string | undefined,
  tsPath: string | undefined,
): CheckerResult {
  const ts = readMaybe(tsPath);
  if (!ts) return { result: "pass", hits: [] };

  // Open conjectures are exempt: kind=conjecture blocks legitimately
  // document open / partially-falsified directions. Accept either
  // single- or double-quoted .ts string literals.
  const kindMatch = ts.match(/kind:\s*["']([a-z]+)["']/);
  if (kindMatch?.[1] === "conjecture") return { result: "pass", hits: [] };

  const hits: CheckerHit[] = [];

  // .ts tag signal — accept either quoting style.
  const tagsBlock = ts.match(/tags:\s*\[([\s\S]*?)\]/);
  if (tagsBlock) {
    const tags = Array.from(tagsBlock[1].matchAll(/["']([^"']+)["']/g),
      (m) => m[1]);
    const offenders = tags.filter((t) => NEG_RESULT_TAGS.has(t));
    if (offenders.length > 0) {
      hits.push({
        file: tsPath ?? "(unknown)",
        line: 1,
        text:
          `paper block carries negative-result tag(s) ${JSON.stringify(offenders)} ` +
          `— move primary content to docs/audits/ and keep only canonical ` +
          `material in the paper (CLAUDE.md authoring discipline; see ` +
          `docs/audits/2026-05-31-ck-exploratory-probes-removed.md).`,
      });
    }
    // Special case: `scaffolding` paired with `open-rd-item-*` is the
    // WIP-scaffolding pattern (legit-scaffolding-tag alone is allowed
    // for axiomatic/structural buildup blocks). Flag the pair.
    const hasScaffolding = tags.includes("scaffolding");
    const openRdItem = tags.find((t) => /^open-rd-item-\d+$/.test(t));
    if (hasScaffolding && openRdItem) {
      hits.push({
        file: tsPath ?? "(unknown)",
        line: 1,
        text:
          `paper block carries WIP-scaffolding tag pair ["scaffolding", ` +
          `"${openRdItem}"] — move primary content to docs/audits/ and ` +
          `keep only canonical material in the paper. (Standalone ` +
          `"scaffolding" tag is allowed for axiomatic/structural ` +
          `buildup; pairing with an "open-rd-item-*" tag signals WIP ` +
          `R&D content. See ` +
          `docs/audits/2026-06-03-canonical-axis-current-fails-triage.md ` +
          `Pattern A.1.)`,
      });
    }
  }

  // .md prose signal
  const md = readMaybe(mdPath);
  if (md) {
    for (const re of NEG_RESULT_MD_SIGNALS) {
      const m = md.match(re);
      if (m) {
        const lineNo = md.slice(0, m.index ?? 0).split("\n").length;
        hits.push({
          file: mdPath ?? "(unknown)",
          line: lineNo,
          text:
            `paper block opens with a negative-result status marker — ` +
            `move to docs/audits/ (matched: ${JSON.stringify(m[0].slice(0, 80))}).`,
        });
        break;  // one hit per block is enough
      }
    }
  }

  return hits.length === 0
    ? { result: "pass", hits: [] }
    : { result: "fail", hits };
}

export function checkCanonicalWitnessPinned(
  mdPath: string | undefined,
  tsPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  if (!md) return { result: "pass", hits: [] };
  const ts = readMaybe(tsPath);
  const tsWitness = ts ? getComputationField(ts).witness : undefined;
  const hits: CheckerHit[] = [];
  let lineNo = 0;
  for (const line of md.split("\n")) {
    lineNo++;
    if (!line.includes(":val[")) continue;
    const re = new RegExp(VAL_DIRECTIVE_RE.source, "g");
    for (const m of line.matchAll(re)) {
      const attrs = m[2];
      const witnessMatch = attrs.match(/witness=["']?([^"' }]+)/);
      if (!witnessMatch) {
        if (!tsWitness) {
          hits.push({
            file: mdPath ?? "(unknown)",
            line: lineNo,
            text:
              `:val[${m[1]}] has no \`witness=\` attribute and the block ` +
              `has no \`computation:\` field`,
          });
        }
        continue;
      }
      const w = witnessMatch[1];
      const absPath = w.startsWith("/") ? w : resolve(REPO_ROOT, w);
      if (!existsSync(absPath)) {
        hits.push({
          file: mdPath ?? "(unknown)",
          line: lineNo,
          text: `:val witness '${w}' does not exist on disk`,
        });
      }
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

// ─── Canonical axis (new criteria) ──────────────────────────────

const NUMEROLOGY_PHRASES = [
  /\bmiraculous(?:ly)?\b/i,
  /\bsurprising(?:ly)?\s+agree(?:ment|s)?\b/i,
  /\bnumerical\s+coincidence\b/i,
  /\bremarkably\s+close\b/i,
  /\bhappens\s+to\s+equal\b/i,
  /\bempirically\s+match(?:es)?\b/i,
  /\bstrik(?:ing|ingly)\s+close\b/i,
  /\baccidental(?:ly)?\s+match/i,
];

export function checkCanonicalNoNumerology(
  mdPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  if (!md) return { result: "pass", hits: [] };
  const hits: CheckerHit[] = [];
  let lineNo = 0;
  for (const line of md.split("\n")) {
    lineNo++;
    for (const re of NUMEROLOGY_PHRASES) {
      const m = line.match(re);
      if (m) {
        hits.push({
          file: mdPath ?? "(unknown)",
          line: lineNo,
          text: `numerology signal phrase: "${m[0]}"`,
        });
        break;
      }
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

const DEPRECATED_MODULES = [
  "mass_endomorphism",
  "LAMBDA_PROTON_DOC",
  "LAMBDA_NEUTRON_DOC",
  "LAMBDA_PROTON_FITTED",
  "LAMBDA_NEUTRON_FITTED",
];

export function checkCanonicalScriptNotDeprecated(
  tsPath: string | undefined,
): CheckerResult {
  const ts = readMaybe(tsPath);
  if (!ts) return { result: "pass", hits: [] };
  const { probe } = getComputationField(ts);
  const witness = getComputationField(ts).witness;
  const scriptMatch = ts.match(/script:\s*["']([^"']+)["']/);
  if (!scriptMatch) return { result: "pass", hits: [] };
  const scriptRelPath = scriptMatch[1];
  const scriptAbsPath = resolve(REPO_ROOT, scriptRelPath);
  if (!existsSync(scriptAbsPath)) return { result: "pass", hits: [] };
  const scriptSrc = readFileSync(scriptAbsPath, "utf-8");
  const hits: CheckerHit[] = [];
  // Check for script-level deprecation markers (first 10 lines or
  // module docstring). Ignore DEPRECATED inside function-level
  // docstrings deeper in the file (e.g. hecke_core.py has
  // [DEPRECATED] on individual internal functions, not the module).
  const firstLines = scriptSrc.split("\n").slice(0, 10).join("\n");
  const moduleDocstring = scriptSrc.match(/^("""[\s\S]*?"""|'''[\s\S]*?''')/m)?.[0] ?? "";
  const headerZone = firstLines + "\n" + moduleDocstring;
  if (/\bSUPERSEDED\b/i.test(headerZone) || /\bDEPRECATED\b/i.test(headerZone)) {
    hits.push({
      file: scriptRelPath,
      line: 1,
      text: "computation script contains SUPERSEDED/DEPRECATED marker",
    });
  }
  for (const mod of DEPRECATED_MODULES) {
    // Only match actual imports, not comment mentions.
    // Python: `from mass_endomorphism import ...` or `import mass_endomorphism`
    const importRe = new RegExp(
      `^\\s*(?:from\\s+${mod}\\s+import|import\\s+${mod})`, "m",
    );
    if (importRe.test(scriptSrc)) {
      hits.push({
        file: scriptRelPath,
        line: 1,
        text: `computation script imports deprecated module: ${mod}`,
      });
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

const BINDING_TAGS = new Set([
  "binding", "binding-energy", "binding-block", "interface-knot",
  "borromean", "borromean-tower", "bar-symmetric", "li2q",
]);
const MASS_ANCHOR_TAGS = new Set([
  "mass-anchor", "mass-derivation", "proton-mass", "neutron-mass",
  "mass-formula", "hadron-mass", "nuclear-mass",
]);

export function checkCanonicalDilogarithmContext(
  mdPath: string | undefined,
  tsPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  const ts = readMaybe(tsPath);
  if (!md || !ts) return { result: "pass", hits: [] };

  const tagsMatch = ts.match(/tags:\s*\[([\s\S]*?)\]/);
  const tags = tagsMatch
    ? tagsMatch[1].match(/"([^"]+)"/g)?.map((t) => t.replace(/"/g, "")) ?? []
    : [];

  const isBinding = tags.some((t) => BINDING_TAGS.has(t));
  const isMassAnchor = tags.some((t) => MASS_ANCHOR_TAGS.has(t));
  if (!isBinding && !isMassAnchor) return { result: "pass", hits: [] };

  // Exempt blocks that discuss BOTH contexts (disambiguation,
  // calibration discipline, cross-context derivation chain).
  const EXEMPT_TAGS = new Set([
    "disambiguation", "quantum-dilogarithm", "phi_q",
    "calibration", "audit", "derivation-chain",
    "legacy-phi-q-tower", "brane-tower", "mass-derivation",
    "first-principles", "li2q",
  ]);
  if (tags.some((t) => EXEMPT_TAGS.has(t))) return { result: "pass", hits: [] };
  // Blocks tagged with both binding AND mass contexts are cross-context
  if (isBinding && isMassAnchor) return { result: "pass", hits: [] };

  const hits: CheckerHit[] = [];
  let lineNo = 0;
  for (const line of md.split("\n")) {
    lineNo++;
    if (isBinding && /\\?Phi_q|faddeev_dilogarithm|\\Phi_q/i.test(line)) {
      hits.push({
        file: mdPath ?? "(unknown)",
        line: lineNo,
        text: "Φ_q (Faddeev) in binding-context block — bar-symmetry violation (use Li_2^q)",
      });
    }
    if (isMassAnchor && /Li_2\^q|rogers_dilogarithm|\\mathrm\{Li\}_2\^q/i.test(line)) {
      hits.push({
        file: mdPath ?? "(unknown)",
        line: lineNo,
        text: "Li_2^q (Rogers) in mass-anchor block — context violation (use Φ_q)",
      });
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

const HARDCODED_OBSERVABLE_RE =
  /[^≈≃~∼\\](?:=\s*)\$?\s*(\d{2,}(?:\.\d+)?)\s*(?:\\[,;]?\s*)?\\?(?:text|mathrm)\{(?:MeV|keV|eV)\}/g;

export function checkCanonicalNoHardcodedObservable(
  mdPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  if (!md) return { result: "pass", hits: [] };
  // Skip bulk data tables (appendix mass calculations, element tables)
  if (mdPath && /amc-|appendix-atomic-mass/.test(mdPath))
    return { result: "pass", hits: [] };
  const hits: CheckerHit[] = [];
  let inTable = false;
  let lineNo = 0;
  for (const line of md.split("\n")) {
    lineNo++;
    // Track markdown table context — data tables use = legitimately
    if (/^\|/.test(line.trim())) inTable = true;
    else if (line.trim() === "") inTable = false;
    if (inTable) continue;
    if (/\\approx|\\simeq|≈|≃|O\(10\^/.test(line)) continue;
    // Skip intermediate arithmetic (chain of = in derivations)
    if ((line.match(/=/g) || []).length >= 2) continue;
    const re = new RegExp(HARDCODED_OBSERVABLE_RE.source, "g");
    for (const m of line.matchAll(re)) {
      hits.push({
        file: mdPath ?? "(unknown)",
        line: lineNo,
        text: `hardcoded observable "${m[0].trim()}" without ≈ — use $\\approx$ per §7ab`,
      });
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

const CAL4_PATTERNS = [
  /\bCAL-4\b/,
  /4th\s+calibration/i,
  /demoted\s+prop\s*→?\s*conj/i,
  /fourth.calibration/i,
];

export function checkCanonicalCal4Acknowledged(
  mdPath: string | undefined,
  tsPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  const ts = readMaybe(tsPath);
  // Strip markdown blockquotes (lines starting with >) — these are
  // historical/demotion notes that describe PAST violations, not
  // current ones. Also strip TS comments.
  const mdClean = (md ?? "").split("\n")
    .filter((l) => !l.trimStart().startsWith(">"))
    .join("\n");
  const tsClean = (ts ?? "").replace(/\/\*[\s\S]*?\*\/|\/\/.*/g, "");
  const combined = mdClean + "\n" + tsClean;
  const hasCal4 = CAL4_PATTERNS.some((re) => re.test(combined));
  if (!hasCal4) return { result: "pass", hits: [] };

  // Exclude blocks that DEFINE the calibration discipline — they
  // mention "4th calibration" prescriptively, not as a violation.
  const label = (ts ?? "").match(/label:\s*["']([^"']+)["']/)?.[1] ?? "";
  const DEFINITIONAL_LABELS = new Set([
    "prop:three-calibration-discipline",
    "prop:three-calibration-inputs",
  ]);
  if (DEFINITIONAL_LABELS.has(label)) return { result: "pass", hits: [] };

  // Exclude blocks where the CAL-4 mention is in a prescriptive
  // context ("would require", "must be flagged", "violation that").
  const prescriptive =
    /would\s+require\s+a\s+4th\s+calibration/i.test(combined) ||
    /4th\s+calibration.*must\s+be\s+flagged/i.test(combined) ||
    /violation\s+that/i.test(combined);
  if (prescriptive && !(/\bCAL-4\s+anchor\b/i.test(combined)))
    return { result: "pass", hits: [] };

  const kindMatch = (ts ?? "").match(
    /export\s+default\s+(conjecture|theorem|proposition|lemma|corollary)\(/,
  );
  const kind = kindMatch?.[1];
  if (kind === "conjecture") return { result: "pass", hits: [] };

  const hasBanner =
    /CAL-4\s+caveat/i.test(md ?? "") ||
    /q-source\s+open/i.test(md ?? "") ||
    /acknowledged.*CAL-4/i.test(md ?? "");
  if (hasBanner) return { result: "pass", hits: [] };

  return {
    result: "fail",
    hits: [
      {
        file: tsPath ?? mdPath ?? "(unknown)",
        line: 1,
        text:
          `block has CAL-4 caveat but is kind=${kind ?? "unknown"} without ` +
          `acknowledgment banner — demote to conjecture or add CAL-4 banner`,
      },
    ],
  };
}

// Precision-ladder / convergent-coefficient context. The checker
// below only fires inside blocks that discuss a truncation-order
// coefficient ladder (Q_β c_k, α_EM Habiro factor, etc.), where the
// canonical framing (docs/audits/2026-05-31-qbeta-ck-truncation-order-
// canonical-framing.md, Rule 4) requires TIERED reporting.
const LADDER_CONTEXT_TAGS = new Set([
  "precision-ladder", "1ppb-roadmap", "habiro", "truncation-order",
]);
// Ladder-coefficient token: matches c_k, c_2, c_3, c_{10}, d_k, d_3, …
// (single or multi-digit, braced or bare, c- or d-family).
const CK = String.raw`[cd]_?\{?[k0-9]+\}?`;
const LADDER_CONTEXT_RE = new RegExp(
  String.raw`\bprecision\s+ladder\b|\btruncation\s+order\b|\b${CK}\b|` +
    String.raw`\bHabiro\s+element\b`,
  "i",
);

// Binary "negative result" framing — the flip-flop signature. A
// near-match coefficient reported as flatly dropped / un-wired / "just
// a fit" instead of tiered. See the four-session wire/un-wire log in
// the canonical framing doc.
const NEGATIVE_RESULT_PHRASES = [
  /\bun-?wire[ds]?\b/i,
  new RegExp(String.raw`\bdrop(?:ping|ped)?\s+(?:the\s+)?${CK}`, "i"),
  /\b(?:just|merely|only|nothing\s+but)\s+a\s+fit\b/i,
  new RegExp(
    String.raw`\b${CK}.{0,30}\b(?:is|are)\s+(?:just|merely|only)\s+numerolog`,
    "i",
  ),
  /\bfails?\s+to\s+(?:beat|derive|hold)\b/i,
  /\bshould\s+be\s+(?:dropped|reverted|un-?wired)\b/i,
  /\bnegative\s+result\b/i,
];

// Tiered-framing vocabulary that discharges a negative-result hit:
// the block is reporting proved / near-match / fitted tiers rather
// than a binary verdict, OR cites the canonical framing doc.
const TIERED_FRAMING_RE =
  /\bnear[- ]match(?:es)?\b|\btier\b|\btiered\b|truncation-order-canonical-framing/i;

/**
 * canonical-ck-tiered-not-binary — locks Q_β c_k truncation-order
 * Rule 4 into CI: a precision-ladder block that frames a coefficient
 * as a binary "negative result" (dropped / un-wired / just-a-fit) MUST
 * also carry the tiered framing (proved / near-match / fitted) or cite
 * the canonical framing doc. Prevents the four-session wire/un-wire
 * flip-flop from re-entering the paper as flat negative-result prose.
 *
 * Complement to #1574's `canonical-no-negative-result-in-paper`, which
 * catches falsified/superseded *probe-block* leakage via .ts tags and
 * .md Status banners. This checker catches the *prose-framing* failure
 * mode (binary wire/un-wire language in ladder context) that the
 * tag/banner checker does not see.
 */
export function checkCanonicalCkTieredNotBinary(
  mdPath: string | undefined,
  tsPath: string | undefined,
): CheckerResult {
  const md = readMaybe(mdPath);
  if (!md) return { result: "pass", hits: [] };
  const ts = readMaybe(tsPath);

  const tagsMatch = (ts ?? "").match(/tags:\s*\[([\s\S]*?)\]/);
  const tags = tagsMatch
    ? tagsMatch[1].match(/["']([^"']+)["']/g)?.map((t) =>
        t.replace(/["']/g, "")) ?? []
    : [];

  const inContext =
    tags.some((t) => LADDER_CONTEXT_TAGS.has(t)) || LADDER_CONTEXT_RE.test(md);
  if (!inContext) return { result: "pass", hits: [] };

  // Discipline satisfied if the block reports tiers or cites the doc.
  if (TIERED_FRAMING_RE.test(md)) return { result: "pass", hits: [] };

  // Strip blockquotes — historical "wired and un-wired N times" notes
  // describe past flip-flops, not the block's current claim.
  const scan = md
    .split(/\r?\n/)
    .map((l, i) => [i + 1, l] as const)
    .filter(([, l]) => !l.trimStart().startsWith(">"));

  const hits: CheckerHit[] = [];
  for (const [lineNo, line] of scan) {
    for (const re of NEGATIVE_RESULT_PHRASES) {
      const m = line.match(re);
      if (m) {
        hits.push({
          file: mdPath ?? "(unknown)",
          line: lineNo,
          text:
            `binary negative-result framing "${m[0].trim()}" in a ` +
            `precision-ladder block without tiered (proved/near-match/` +
            `fitted) framing — report TIERED per the c_k truncation-order ` +
            `canonical framing (Rule 4), do not re-open the wire/un-wire flip-flop`,
        });
        break;
      }
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

// ─── Detangler axis ─────────────────────────────────────────────

// Resolve a block slug (filename without .ts) under a chapter dir to
// its kind, handling both declaration forms (`kind: "x"` and the
// `export default <builder>(` builder call). Returns "" if unresolved.
function blockKindForSlug(chapterDir: string, slug: string): string {
  const p = join(chapterDir, `${slug}.ts`);
  if (!existsSync(p)) return "";
  const src = readFileSync(p, "utf-8");
  const m =
    src.match(/kind:\s*"([^"]+)"/) ||
    src.match(/export\s+default\s+(\w+)\s*\(/);
  return m ? m[1] : "";
}

export function checkDetanglerSectionBand(
  tsPath: string | undefined,
): CheckerResult {
  const ts = readMaybe(tsPath);
  if (!ts || !tsPath) return { result: "n/a", hits: [] };
  const chapterDir = dirname(tsPath);
  // Only applies to chapter manifests (which list sections). Capture
  // the section TITLE too, so intro/overview sections can be skipped
  // (detangler H4 excludes them from the sparse-section check).
  const sectionRe =
    /\{\s*title:\s*["']([^"']*)["']\s*,\s*blocks:\s*\[([^\]]*)\]/g;
  const sections: Array<{ title: string; nonProse: number }> = [];
  for (const m of ts.matchAll(sectionRe)) {
    const slugs = m[2]
      .split(",")
      .map((s) => s.trim().replace(/^["']|["']$/g, ""))
      .filter(Boolean);
    // Count NON-PROSE blocks only (detangler H4/H5 measure "content
    // blocks", not narrative prose/section-intro text). Resolving each
    // slug's kind avoids the old bug of counting every ref — including
    // prose — which inflated dense counts and masked sparse ones.
    let nonProse = 0;
    for (const slug of slugs) {
      const kind = blockKindForSlug(chapterDir, slug);
      // Unresolved slugs (kind "") count as content (conservative — do
      // not silently drop a block we failed to read).
      if (kind !== "prose") nonProse++;
    }
    sections.push({ title: m[1], nonProse });
  }
  if (sections.length === 0) return { result: "n/a", hits: [] };
  const isIntro = (t: string) =>
    /\b(introduction|overview|preliminaries|motivation)\b/i.test(t);
  const hits: CheckerHit[] = [];
  sections.forEach((s, i) => {
    // Sparse check excludes intro/overview sections (H4); dense check
    // applies to all.
    const sparse = s.nonProse < 3 && !isIntro(s.title);
    const dense = s.nonProse > 18;
    if (sparse || dense) {
      hits.push({
        file: tsPath,
        line: 1,
        text: `section ${i + 1} "${s.title}": ${s.nonProse} non-prose blocks (out of band 3..18)`,
      });
    }
  });
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

// `detangler-no-forward-ref`, `detangler-no-xchapter-fwd`, and
// `detangler-archimedean-wall` need access to the chapter ordering
// of the paper. They share a heavier preamble — left as TODO in
// this commit, with explicit `n/a` returns so the sweep doesn't
// flag them as missing. A follow-up commit will wire them.

export function checkDetanglerNoForwardRef(
  tsPath: string | undefined,
): CheckerResult {
  if (!tsPath || !existsSync(tsPath)) return { result: "n/a", hits: [] };
  loadChapterGraph();
  if (!_graphLoaded || !_blockPos || !_usesGraph || !_labelToChapter)
    return { result: "n/a", hits: [] };

  const content = readFileSync(tsPath, "utf-8");
  const labelMatch = content.match(/label:\s*"([^"]+)"/);
  if (!labelMatch) return { result: "pass", hits: [] };
  const label = labelMatch[1];
  const myPos = _blockPos.get(label);
  if (myPos === undefined) return { result: "pass", hits: [] }; // not listed
  const myChapter = _labelToChapter.get(label);

  const hits: CheckerHit[] = [];
  for (const u of _usesGraph.get(label) ?? []) {
    // Only SAME-chapter forward refs here; cross-chapter is the
    // separate `detangler-no-xchapter-fwd` criterion.
    if (_labelToChapter.get(u) !== myChapter) continue;
    const uPos = _blockPos.get(u);
    if (uPos !== undefined && uPos > myPos) {
      hits.push({
        file: tsPath,
        line: 0,
        text: `forward ref: uses ${u} (manifest pos ${withinChapter(uPos)}) which appears after this block (pos ${withinChapter(myPos)}) in the chapter`,
      });
    }
  }
  return hits.length
    ? { result: "fail", hits }
    : { result: "pass", hits: [] };
}

export function checkDetanglerNoXChapterFwd(
  _tsPath: string | undefined,
): CheckerResult {
  // TODO: same as above but at paper.ts level — verify cross-chapter
  // `uses:` refs point at an earlier chapter in `paper.ts`'s
  // ordering. n/a until wired.
  return { result: "n/a", hits: [] };
}

export function checkDetanglerArchimedeanWall(
  _tsPath: string | undefined,
  _leanPath: string | undefined,
): CheckerResult {
  // TODO: parse the chapter directory + classify Lean files as
  // archimedean / generic-R / mixed; verify the chapter's expected
  // wall side per the chapter-ts metadata. n/a until wired.
  return { result: "n/a", hits: [] };
}

// ─── detangler-block-tanglement ─────────────────────────────────
// Per-block forward-ref score: counts uses[] targets in later
// chapters + blocks in earlier chapters that reference this block.

let _chapterOrder: Map<string, number> | null = null;
let _labelToChapter: Map<string, string> | null = null;
let _usesGraph: Map<string, string[]> | null = null;
// Reverse adjacency: block label -> labels whose uses[] reference it.
// Drives the per-block in-degree metric (how foundational a block is)
// without a per-call full scan.
let _reverseUses: Map<string, string[]> | null = null;
// Memoized transitive dependency-cone sizes (label -> count), filled
// lazily by `dependencyConeSize` and reset on each graph (re)build so
// the per-block cone metric is O(1) amortised across a full sweep
// rather than re-walking the graph once per block.
let _coneSizeCache: Map<string, number> | null = null;
// Memoized longest `uses[]` dependency chain depth (label -> count of
// edges on the longest acyclic path out of the block). Back-edges
// (cycles) are skipped so depth stays well-defined on the rare cyclic
// block. A deep chain ⇒ the block sits atop a tall argument tower —
// the proof-depth proxy. Reset on each graph build.
let _depthCache: Map<string, number> | null = null;
// PageRank centrality over the `uses[]` graph (label -> score in
// [0,1], summing to ~1). Computed once per graph build by power
// iteration. High score ⇒ a foundational block many others lean on
// (a weighted refinement of raw in-degree). Reset on each build.
let _pagerank: Map<string, number> | null = null;
// Precomputed once per load: block label -> an example uses[] cycle
// path through it (only present for labels that sit on a cycle), so
// the per-block cycle check is an O(1) lookup, not a per-call DFS.
let _inCyclePath: Map<string, string[]> | null = null;
// block label -> global manifest position (chapterIndex*1e6 + index
// within the chapter's ordered sections[].blocks[]). Drives the
// same-chapter forward-ref check.
let _blockPos: Map<string, number> | null = null;
// block label -> global section id (chapterIndex*STRIDE + section index
// within the chapter's ordered sections[]). Two blocks share a section
// iff their ids match. Drives the within-section graph-energy measure:
// a forward edge ACROSS sections reflects the chapter's intentional
// face ordering (Algebraic→Geometric→…), not a reorderable local
// tangle, so graph-energy only counts WITHIN-section forward edges.
let _blockSection: Map<string, number> | null = null;
// Set true only after a *successful* graph build. Checkers gate on
// this (not on map nullability) so a missing paper manifest yields
// `n/a` rather than a false "everything passes".
let _graphLoaded = false;

// Block-position encoding: `chapterIndex * CHAPTER_POS_STRIDE + index`
// within the chapter's ordered blocks. Shared by the encoder
// (loadChapterGraph) and the decoder (`withinChapter`, used to recover
// the within-chapter index for evidence messages). Assumes fewer than
// CHAPTER_POS_STRIDE blocks per chapter.
const CHAPTER_POS_STRIDE = 1_000_000;
const withinChapter = (pos: number): number => pos % CHAPTER_POS_STRIDE;

function loadChapterGraph(): void {
  if (_graphLoaded) return;

  // Build into locals; publish to the module-level caches only on a
  // fully successful load.
  const chapterOrder = new Map<string, number>();
  const labelToChapter = new Map<string, string>();
  const usesGraph = new Map<string, string[]>();

  const paperTs = join(CONTENT_DIR, "quantum-observable-universe", "quantum-observable-universe.ts");
  if (!existsSync(paperTs)) return; // not loaded — _graphLoaded stays false
  const src = readFileSync(paperTs, "utf-8");
  const dirs = [...src.matchAll(/dir:\s*"([^"]+)"/g)].map(m => m[1]);
  dirs.forEach((d, i) => chapterOrder.set(d, i));

  // Build label→chapter + uses[] adjacency + slug→label by scanning
  // all block .ts. (slug = filename without .ts; the chapter manifests
  // order blocks by slug, while uses[] reference labels.)
  const base = join(CONTENT_DIR, "quantum-observable-universe");
  const slugToLabel = new Map<string, string>();
  for (const dir of dirs) {
    const chDir = join(base, dir);
    if (!existsSync(chDir)) continue;
    try {
      const files = require("fs").readdirSync(chDir);
      for (const f of files) {
        if (!f.endsWith(".ts") || f === `${dir}.ts`) continue;
        const content = readFileSync(join(chDir, f), "utf-8");
        const m = content.match(/label:\s*"([^"]+)"/);
        if (m) {
          labelToChapter.set(m[1], dir);
          slugToLabel.set(f.slice(0, -3), m[1]);
          // Record the block's `uses:[...]` dependency edges (only the
          // uses array — NOT cites/interprets/own-label) for cycle
          // detection.
          const usesM = content.match(/uses\s*:\s*\[([\s\S]*?)\]/);
          // De-duplicate: a block listing the same `uses:` label twice
          // must not inflate out-degree / in-degree / cone size — count
          // unique dependency edges only.
          const useLabels = usesM
            ? [...new Set([...usesM[1].matchAll(/"([^"]+)"/g)].map((x) => x[1]))]
            : [];
          usesGraph.set(m[1], useLabels);
        }
      }
    } catch {}
  }

  // Build label→position from each chapter manifest's ordered
  // `sections[].blocks[]` slug lists.
  const blockPos = new Map<string, number>();
  const blockSection = new Map<string, number>();
  dirs.forEach((dir, ci) => {
    const manifestPath = join(base, dir, `${dir}.ts`);
    if (!existsSync(manifestPath)) return;
    const mc = readFileSync(manifestPath, "utf-8");
    let within = 0;
    let sectionIdx = 0;
    for (const bm of mc.matchAll(/blocks\s*:\s*\[([\s\S]*?)\]/g)) {
      for (const sm of bm[1].matchAll(/"([^"]+)"/g)) {
        const lbl = slugToLabel.get(sm[1]);
        if (lbl && !blockPos.has(lbl)) {
          blockPos.set(lbl, ci * CHAPTER_POS_STRIDE + within);
          blockSection.set(lbl, ci * CHAPTER_POS_STRIDE + sectionIdx);
        }
        within++;
      }
      sectionIdx++;
    }
  });

  // Build the reverse adjacency (label -> users) once so per-block
  // in-degree is an O(1) lookup rather than a full corpus scan.
  const reverseUses = new Map<string, string[]>();
  for (const [user, deps] of usesGraph) {
    for (const dep of deps) {
      const arr = reverseUses.get(dep);
      if (arr) arr.push(user);
      else reverseUses.set(dep, [user]);
    }
  }

  // Precompute uses[]-cycle membership ONCE: for each label on a
  // dependency cycle, store an example back-to-self path. Per-block
  // checks then become an O(1) lookup.
  const inCyclePath = new Map<string, string[]>();
  for (const start of usesGraph.keys()) {
    const visited = new Set<string>([start]);
    const path: string[] = [start];
    const dfs = (node: string): string[] | null => {
      for (const next of usesGraph.get(node) ?? []) {
        if (next === start) return [...path, start];
        if (!visited.has(next)) {
          visited.add(next);
          path.push(next);
          const found = dfs(next);
          if (found) return found;
          path.pop();
        }
      }
      return null;
    };
    const cyc = dfs(start);
    if (cyc) inCyclePath.set(start, cyc);
  }

  // PageRank over the uses[] graph by power iteration. Nodes = all
  // labels appearing as a block or as a dependency target. An edge
  // b -> d (block depends on d) contributes rank mass to d, so a
  // heavily-depended-on foundational block accrues a high score.
  const nodes = new Set<string>([...usesGraph.keys()]);
  for (const deps of usesGraph.values()) for (const d of deps) nodes.add(d);
  const N = nodes.size;
  const pagerank = new Map<string, number>();
  if (N > 0) {
    const damping = 0.85;
    const base = (1 - damping) / N;
    for (const n of nodes) pagerank.set(n, 1 / N);
    for (let iter = 0; iter < 40; iter++) {
      const next = new Map<string, number>();
      for (const n of nodes) next.set(n, base);
      let dangling = 0;
      for (const n of nodes) {
        const outs = usesGraph.get(n) ?? [];
        if (outs.length === 0) dangling += pagerank.get(n)! / N;
        else {
          const share = (damping * pagerank.get(n)!) / outs.length;
          for (const d of outs) next.set(d, (next.get(d) ?? base) + share);
        }
      }
      // Redistribute dangling-node mass uniformly (standard PageRank).
      if (dangling > 0)
        for (const n of nodes)
          next.set(n, next.get(n)! + damping * dangling);
      for (const [k, v] of next) pagerank.set(k, v);
    }
  }

  _chapterOrder = chapterOrder;
  _labelToChapter = labelToChapter;
  _usesGraph = usesGraph;
  _reverseUses = reverseUses;
  _coneSizeCache = new Map();
  _depthCache = new Map();
  _pagerank = pagerank;
  _inCyclePath = inCyclePath;
  _blockPos = blockPos;
  _blockSection = blockSection;
  _graphLoaded = true;
}

// Longest acyclic `uses[]` dependency chain out of a block (edge
// count). Recursive memoized DFS with an on-stack guard so a rare
// dependency cycle does not loop forever (back-edges contribute 0).
// Recursion depth is bounded by the longest dependency chain (tens of
// levels on this corpus), so it is stack-safe. Memoized in
// `_depthCache`, so amortised O(1) per block across a sweep.
function dependencyDepth(start: string): number {
  if (!_usesGraph) return 0;
  const cached = _depthCache?.get(start);
  if (cached !== undefined) return cached;
  const onStack = new Set<string>();
  const compute = (node: string): number => {
    const memo = _depthCache?.get(node);
    if (memo !== undefined) return memo;
    if (onStack.has(node)) return 0; // back-edge: don't extend depth
    onStack.add(node);
    let best = 0;
    for (const dep of _usesGraph!.get(node) ?? []) {
      const d = 1 + compute(dep);
      if (d > best) best = d;
    }
    onStack.delete(node);
    _depthCache?.set(node, best);
    return best;
  };
  return compute(start);
}

// Transitive `uses[]` dependency-cone size from a starting label:
// the count of distinct blocks reachable by following uses[] edges
// (excluding the start itself). A large cone means "much breaks if
// this block changes" — the downstream-impact proxy used by the
// dependency-graph section of CLAUDE.md.
function dependencyConeSize(start: string): number {
  if (!_usesGraph) return 0;
  const cached = _coneSizeCache?.get(start);
  if (cached !== undefined) return cached;
  const seen = new Set<string>();
  const stack = [...(_usesGraph.get(start) ?? [])];
  while (stack.length) {
    const node = stack.pop()!;
    if (node === start || seen.has(node)) continue;
    seen.add(node);
    for (const next of _usesGraph.get(node) ?? []) {
      if (next !== start && !seen.has(next)) stack.push(next);
    }
  }
  _coneSizeCache?.set(start, seen.size);
  return seen.size;
}

export function checkDetanglerBlockTanglement(
  tsPath: string | undefined,
): CheckerResult & { metrics?: Record<string, number | string> } {
  if (!tsPath || !existsSync(tsPath)) return { result: "pass", hits: [] };

  loadChapterGraph();
  if (!_chapterOrder || !_labelToChapter) return { result: "n/a", hits: [] };

  const content = readFileSync(tsPath, "utf-8");
  const labelMatch = content.match(/label:\s*"([^"]+)"/);
  if (!labelMatch) return { result: "pass", hits: [] };
  const label = labelMatch[1];

  // Determine this block's chapter
  const relPath = relative(join(CONTENT_DIR, "quantum-observable-universe"), tsPath);
  // Platform-aware split: `relative()` yields `\` on Windows.
  const thisChapter = relPath.split(/[\\/]/)[0];
  const thisIdx = _chapterOrder.get(thisChapter) ?? 999;

  // Count forward refs emitted: LOGICAL dependencies (`uses[]`) whose
  // target lives in a later chapter. Use the parsed `_usesGraph`
  // adjacency, NOT a raw label scan of the whole .ts — the latter also
  // matches `examples:` / `cites:` / `interprets:` pointers, which are
  // illustrative/back-references, not logical forward dependencies, and
  // over-count the tangle (e.g. a prop listing later-chapter example
  // remarks is not a dependency tangle). Consistent with the
  // graph-energy and no-forward-ref checkers, which key off `uses[]`.
  const uses = _usesGraph?.get(label) ?? [];
  let fwdEmitted = 0;
  const hits: CheckerHit[] = [];
  for (const u of uses) {
    const tgtCh = _labelToChapter.get(u);
    if (tgtCh && (_chapterOrder.get(tgtCh) ?? 0) > thisIdx) {
      fwdEmitted++;
      hits.push({ file: tsPath, line: 0, text: `emits fwd-ref to ${tgtCh}: ${u}` });
    }
  }

  // Receive-side: blocks in EARLIER chapters that reference this label
  // (now an O(1) reverse-index lookup, not a deferred full scan).
  let fwdReceived = 0;
  for (const user of _reverseUses?.get(label) ?? []) {
    const userCh = _labelToChapter.get(user);
    if (userCh && (_chapterOrder.get(userCh) ?? 999) < thisIdx) fwdReceived++;
  }

  // ── Structural graph metrics (canonical uses[] adjacency) ──────
  // out-degree = direct dependency fan-out; in-degree = how many
  // blocks build on this one (fan-in / "foundational-ness");
  // cone-size = transitive downstream-impact blast radius;
  // edge-span = the manifest-position distance of this block's
  // same-chapter dependency edges (max + mean), the magnitude that
  // bare forward-ref counts miss.
  const outDegree = (_usesGraph?.get(label) ?? []).length;
  const inDegree = (_reverseUses?.get(label) ?? []).length;
  const coneSize = dependencyConeSize(label);
  // depth = longest dependency chain (proof-depth proxy); pagerank =
  // weighted centrality (refines in-degree by who depends on you).
  const depth = dependencyDepth(label);
  const pagerank =
    Math.round((_pagerank?.get(label) ?? 0) * 1e6) / 1e6;

  const myPos = _blockPos?.get(label);
  const spans: number[] = [];
  if (myPos !== undefined) {
    for (const u of _usesGraph?.get(label) ?? []) {
      if (_labelToChapter.get(u) !== thisChapter) continue; // same-chapter only
      const uPos = _blockPos?.get(u);
      if (uPos !== undefined) spans.push(Math.abs(myPos - uPos));
    }
  }
  const edgeSpanMax = spans.length ? Math.max(...spans) : 0;
  const edgeSpanMean = spans.length
    ? Math.round((spans.reduce((a, b) => a + b, 0) / spans.length) * 100) / 100
    : 0;

  const score = fwdEmitted; // emit-side cross-chapter forward refs
  const result = score >= 4 ? "fail" : score >= 1 ? "warn" : "pass";

  return {
    result,
    hits: hits.slice(0, 10),
    metrics: {
      fwd_emitted: fwdEmitted,
      fwd_received: fwdReceived,
      tanglement_score: score,
      out_degree: outDegree,
      in_degree: inDegree,
      cone_size: coneSize,
      depth: depth,
      pagerank: pagerank,
      edge_span_max: edgeSpanMax,
      edge_span_mean: edgeSpanMean,
      worst_target: hits[0]?.text ?? "",
    },
  };
}

// ─── detangler-graph-energy ─────────────────────────────────────
// Per-block contribution to the chapter's graph energy
//   E(b) = Σ_{d ∈ uses(b), pos(d) > pos(b)} (pos(d) − pos(b))
// summed over SAME-chapter dependency edges that point *forward* in
// the manifest order (i.e. backward edges in the dependency DAG — the
// reader must skip ahead). Where `detangler-no-forward-ref` is a
// binary count, energy weights each forward edge by how far it
// reaches: one definition used 30 blocks later is a worse tangle than
// one used 2 blocks later. Mirrors the `chapter-complexity-review`
// graph-energy metric, projected onto a single block.
export function checkDetanglerGraphEnergy(
  tsPath: string | undefined,
): CheckerResult & { metrics?: Record<string, number | string> } {
  if (!tsPath || !existsSync(tsPath)) return { result: "pass", hits: [] };
  loadChapterGraph();
  if (!_graphLoaded || !_blockPos || !_usesGraph || !_labelToChapter)
    return { result: "n/a", hits: [] };

  const content = readFileSync(tsPath, "utf-8");
  const labelMatch = content.match(/label:\s*"([^"]+)"/);
  if (!labelMatch) return { result: "pass", hits: [] };
  const label = labelMatch[1];
  const myPos = _blockPos.get(label);
  if (myPos === undefined) return { result: "pass", hits: [] };
  const mySection = _blockSection?.get(label);

  let energy = 0;
  let fwdEdges = 0;
  let worstSpan = 0;
  const hits: CheckerHit[] = [];
  for (const u of _usesGraph.get(label) ?? []) {
    // Count only WITHIN-section forward edges. A forward edge that
    // crosses a section boundary reflects the chapter's intentional
    // face ordering (e.g. a Geometric-face block citing an Archimedean-
    // face result) — not a tangle a within-section reorder can fix, so
    // it would be a false "reorder me" signal. Same-section forward
    // edges ARE locally reorderable and are the actionable tangle.
    if (mySection === undefined || _blockSection?.get(u) !== mySection)
      continue;
    const uPos = _blockPos.get(u);
    if (uPos !== undefined && uPos > myPos) {
      const span = uPos - myPos;
      energy += span;
      fwdEdges++;
      if (span > worstSpan) worstSpan = span;
      hits.push({
        file: tsPath,
        line: 0,
        text: `within-section forward edge to ${u} spans ${span} manifest positions`,
      });
    }
  }

  // 0 → pass; any forward edge → warn; deep tangle (≥ 100, i.e. far
  // above the corpus median non-zero energy of ~18) → fail. The metrics
  // payload records the exact energy regardless, so the verdict gates
  // only the pathological cases while the measure is always available.
  const result = energy === 0 ? "pass" : energy >= 100 ? "fail" : "warn";
  return {
    result,
    hits: hits.slice(0, 10),
    metrics: {
      graph_energy: energy,
      fwd_edge_count: fwdEdges,
      worst_span: worstSpan,
    },
  };
}

// ─── detangler-topic-coherence ──────────────────────────────────
// Keyword-based topic-fit heuristic, ported from
// `content/pipeline/block-density-audit.py` (multi-topic check R-?).
// A block whose prose scores more chapter-keyword hits for some OTHER
// chapter than for its own home chapter is a candidate for relocation
// or splitting. Soft (warn) — keyword overlap is noisy — but the
// metrics payload records the scores so a reviewer can adjudicate.
const DETANGLER_CHAPTER_KEYWORDS: Record<string, string[]> = {
  introduction: ["overview", "outline", "motivation"],
  "quantum-universes": [
    "quantum universe", "fibre functor", "Tannaka", "monoidal",
    "dagger", "Frobenius",
  ],
  "quantum-observable-universes": [
    "observable", "QOU", "theta", "state bundle", "jet bundle",
    "q-codifferential",
  ],
  "lifting-and-descent": [
    "lifting", "descent", "torsion", "jet", "prolongation",
    "brane tower",
  ],
  "braids-and-knots": [
    "braid", "knot", "Hecke", "Markov trace", "skein", "crossing",
    "Jones polynomial", "SU(2)", "SO(3)", "vertex operator",
    "transfer matrix", "trefoil",
  ],
  "models-of-qous": [
    "Calabi-Yau", "ALE", "instanton", "Reeb", "Riemannian", "Webster",
    "inner product",
  ],
  "descartes-universe": [
    "Bring", "Descartes", "color tube", "coral", "shell", "hadron",
    "proton", "neutron", "quark", "beta decay", "nucleus", "nuclear",
    "half-life", "periodic table", "torus knot T_{",
  ],
  "algebraic-substrate": [
    "substrate", "Collatz", "algebraic", "classical limit",
    "Hasse-Weil", "Birch", "rigid dualizing",
  ],
  "fluid-dynamics": [
    "fluid", "Navier--Stokes", "vortex", "turbulence", "Reynolds",
    "helicity", "Madelung",
  ],
  "information-theory": [
    "information", "entropy", "Planck", "speed of light",
    "gravitational constant", "Bekenstein", "horizon", "CMB",
    "big bang", "aeon",
  ],
  observations: [
    "CODATA", "PDG", "experiment", "measurement", "prediction",
    "crystal", "photonic Hall", "fine structure", "lepton",
    "proton radius",
  ],
  "organic-chemistry": [
    "benzene", "covalent", "carbon", "organic", "molecular",
    "ring closure",
  ],
  glossary: ["glossary"],
};

// Topic-coherence is only meaningful signal for LOAD-BEARING logical
// blocks: a `definition`/`proposition`/`theorem`/`lemma`/`corollary`
// whose prose is mostly about another chapter's topic is a genuine
// misplacement. Interpretive/narrative kinds (`remark`, `example`,
// `prose`, `proof`, `diagram`, `simulator`, `conjecture`) reference
// upstream concepts by nature, so flagging them is noise — they are
// excluded (n/a). Empirically, restricting to these kinds + requiring
// a clear margin cut a 153-warn dragnet (61 remarks, 79 in the
// cross-cutting observations chapter) down to genuine signal.
const TOPIC_COHERENCE_KINDS = new Set([
  "definition",
  "proposition",
  "theorem",
  "lemma",
  "corollary",
]);

export function checkDetanglerTopicCoherence(
  mdPath: string | undefined,
): CheckerResult & { metrics?: Record<string, number | string> } {
  if (!mdPath || !existsSync(mdPath)) return { result: "n/a", hits: [] };
  // Read the block kind from the .ts sibling; only audit load-bearing
  // logical kinds (see TOPIC_COHERENCE_KINDS rationale above). Blocks
  // declare their kind in one of two forms — an explicit `kind: "x"`
  // field OR a builder call `export default <kind>({ ... })` (the
  // builder name IS the kind). Detect both, matching the convention in
  // block-density-audit.py.
  const tsPath = mdPath.replace(/\.md$/, ".ts");
  if (existsSync(tsPath)) {
    const tsSrc = readFileSync(tsPath, "utf-8");
    const kindM =
      tsSrc.match(/kind:\s*"([^"]+)"/) ||
      tsSrc.match(/export\s+default\s+(\w+)\s*\(/);
    if (kindM && !TOPIC_COHERENCE_KINDS.has(kindM[1]))
      return { result: "n/a", hits: [] };
  }
  const content = readFileSync(mdPath, "utf-8");
  const nonBlank = content.split("\n").filter((l) => l.trim().length > 0);
  // Match the Python gate: only audit substantive blocks (> 20 lines);
  // short blocks rarely accumulate enough keyword signal to judge.
  if (nonBlank.length <= 20) return { result: "n/a", hits: [] };

  const homeChapter = relative(
    join(CONTENT_DIR, "quantum-observable-universe"),
    mdPath,
  ).split(/[\\/]/)[0]; // platform-aware (relative() yields `\` on Windows)
  // If we have no keyword profile for the home chapter we cannot judge
  // coherence — its home score is structurally 0, so ANY other-chapter
  // hit would spuriously "win". Report n/a rather than a false warn.
  // (The ported keyword map predates some current chapters, e.g.
  // particle-interactions; absence ⇒ undecidable, not a mismatch.)
  if (!(homeChapter in DETANGLER_CHAPTER_KEYWORDS))
    return { result: "n/a", hits: [] };
  const lower = content.toLowerCase();

  const scores: Record<string, number> = {};
  for (const [ch, kws] of Object.entries(DETANGLER_CHAPTER_KEYWORDS)) {
    let hits = 0;
    for (const kw of kws) if (lower.includes(kw.toLowerCase())) hits++;
    if (hits > 0) scores[ch] = hits;
  }
  const homeScore = scores[homeChapter] ?? 0;

  let topOther = "";
  let topOtherScore = 0;
  for (const [ch, s] of Object.entries(scores)) {
    if (ch !== homeChapter && s > topOtherScore) {
      topOther = ch;
      topOtherScore = s;
    }
  }

  // Require a CLEAR margin (≥ 3 more hits than home), not a bare tie-
  // break: "4 vs 3" is within keyword-overlap noise, "6 vs 1" is a real
  // misplacement. `top_other_score >= home_score + 3` filters borderline
  // cases the bare `>` rule let through.
  const mismatch =
    topOtherScore >= 3 && topOtherScore >= homeScore + 3;
  const hits: CheckerHit[] = mismatch
    ? [
        {
          file: mdPath,
          line: 0,
          text: `${topOtherScore} keyword hits for '${topOther}' but only ${homeScore} for home chapter '${homeChapter}'`,
        },
      ]
    : [];
  return {
    result: mismatch ? "warn" : "pass",
    hits,
    metrics: {
      home_chapter: homeChapter,
      home_score: homeScore,
      top_other_chapter: topOther || "(none)",
      top_other_score: topOtherScore,
    },
  };
}

// Dependency-cycle detector: a `uses[]` cycle through this block.
// Unlike `detangler-no-forward-ref` (a position check that a reorder
// can satisfy), a cycle is reorder-invariant — no ordering removes the
// forward edge — so it signals a genuine structural tangle (two blocks
// each `uses:` the other, or a longer loop) that needs an edge removed
// or the blocks merged. Walks the cached `uses[]` adjacency graph from
// this block's label; fails if the label is reachable from itself.
export function checkDetanglerNoDependencyCycle(
  tsPath: string | undefined,
): CheckerResult {
  if (!tsPath || !existsSync(tsPath)) return { result: "pass", hits: [] };
  loadChapterGraph();
  if (!_graphLoaded || !_inCyclePath) return { result: "n/a", hits: [] };

  const content = readFileSync(tsPath, "utf-8");
  const labelMatch = content.match(/label:\s*"([^"]+)"/);
  if (!labelMatch) return { result: "pass", hits: [] };

  const cyclePath = _inCyclePath.get(labelMatch[1]);
  if (cyclePath) {
    return {
      result: "fail",
      hits: [
        {
          file: tsPath,
          line: 0,
          text: `uses[] dependency cycle: ${cyclePath.join(" -> ")}`,
        },
      ],
    };
  }
  return { result: "pass", hits: [] };
}

// ─── Proof axis ─────────────────────────────────────────────────

// Lookback rule: a `-- Ref:` covers a `sorry` if it appears
//   (a) on the same line as the sorry, OR
//   (b) anywhere between the sorry and the start of the enclosing
//       top-level declaration (instance, def, theorem, …), OR
//   (c) within the 5 lines immediately preceding that decl-opening
//       (where authors typically place per-declaration citations).
// This matches actual authoring practice — one `-- Ref:` above an
// `instance ... where` covers every sorry-bodied field within it,
// rather than requiring each field to repeat the citation.
const BARE_SORRY_REF_PREDECL_LINES = 5;
const DECL_BOUNDARY_RE =
  /^(?:noncomputable\s+|@\[[^\]]*\]\s+)*(?:def|instance|theorem|lemma|proposition|example|abbrev|structure|class|inductive|opaque)\b/;
const REF_LINE_RE = /--\s*Ref:\s*\[/;

function bareSorryHasRefInScope(
  origLines: string[],
  sorryLineIdx: number,
): boolean {
  if (REF_LINE_RE.test(origLines[sorryLineIdx] ?? "")) return true;
  let declStart = -1;
  for (let j = sorryLineIdx - 1; j >= 0; j--) {
    if (REF_LINE_RE.test(origLines[j])) return true;
    if (DECL_BOUNDARY_RE.test(origLines[j])) {
      declStart = j;
      break;
    }
  }
  if (declStart < 0) return false;
  const stop = Math.max(0, declStart - BARE_SORRY_REF_PREDECL_LINES);
  for (let j = declStart - 1; j >= stop; j--) {
    if (REF_LINE_RE.test(origLines[j])) return true;
  }
  return false;
}

export function checkProofNoBareSorries(
  leanPath: string | undefined,
): CheckerResult {
  const src = readMaybe(leanPath);
  if (!src) return { result: "n/a", hits: [] };
  // Mask comment regions before scanning, preserving line numbers:
  //   /-! ... -/  Lean module docstring
  //   /-  ... -/  block comment
  //   --  ...     line comment (rest of line)
  // Without this, the word "sorry" in narrative prose inside a
  // docstring is flagged as a missing-citation bare `sorry`.
  // For the `-- Ref:` lookback we still need the original lines.
  const blankNonNewline = (m: string) => m.replace(/[^\n]/g, " ");
  const masked = src
    .replace(/\/-![\s\S]*?-\//g, blankNonNewline)
    .replace(/\/-[\s\S]*?-\//g, blankNonNewline)
    .replace(/--[^\n]*/g, blankNonNewline);
  const lines = masked.split("\n");
  const origLines = src.split("\n");
  const hits: CheckerHit[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (!/\bsorry\b/.test(lines[i])) continue;
    if (bareSorryHasRefInScope(origLines, i)) continue;
    hits.push({
      file: leanPath ?? "(unknown)",
      line: i + 1,
      text:
        `bare \`sorry\` at line ${i + 1} — no \`-- Ref: [key]\` citation ` +
        `on the same line, within the enclosing declaration, or in the ` +
        `${BARE_SORRY_REF_PREDECL_LINES} lines preceding its opening`,
    });
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

const HOLDS_PROP_RE = /\bholds\s*:\s*Prop\b/;
const INSTANCE_HYP_RE = /\[\s*\w+\s+\w+\s*\]/;

export function checkProofSubstantive(
  leanPath: string | undefined,
): CheckerResult {
  const src = readMaybe(leanPath);
  if (!src) return { result: "n/a", hits: [] };
  // A block-level signature using `holds : Prop` without ANY class
  // hypothesis is the flag. Heuristic — script catches the common
  // cases; lean-substantive-pass agent handles the rest.
  if (!HOLDS_PROP_RE.test(src)) return { result: "pass", hits: [] };
  if (INSTANCE_HYP_RE.test(src)) return { result: "pass", hits: [] };
  const lineIdx = src
    .split("\n")
    .findIndex((l) => HOLDS_PROP_RE.test(l));
  return {
    result: "fail",
    hits: [
      {
        file: leanPath ?? "(unknown)",
        line: (lineIdx >= 0 ? lineIdx : 0) + 1,
        text:
          `\`holds : Prop\` placeholder used WITHOUT a class hypothesis ` +
          `[Instance ...] — per CLAUDE.md §3b-cond, the downstream consumer ` +
          `must take the conjecture as a typeclass`,
      },
    ],
  };
}

// `proof-no-axiom-growth` and `proof-build-green` both read CI
// artefacts that are produced by `lean_ci.yml` (`axiom-report.txt`
// + `proof-objects.json`). Local sweeps return n/a; the CI sweep
// reads the artefacts and writes pass/fail entries.

export function checkProofNoAxiomGrowth(
  _leanPath: string | undefined,
): CheckerResult {
  return { result: "n/a", hits: [] };
}

export function checkProofBuildGreen(
  _leanPath: string | undefined,
): CheckerResult {
  return { result: "n/a", hits: [] };
}

// `proof-lean-compiles` reads a cached diagnostics JSON produced by
// the lean-lsp MCP server (`lean_diagnostic_messages`). The cache is
// at `docs/audits/lean-compile-diagnostics.json`, populated by agent
// invocation of the lean-lsp tools or by `lean-compile-audit.ts`.
// Shape: { files: { "<repo-relative-path>": { errors: [...] } } }

const LEAN_COMPILE_DIAGNOSTICS = join(
  REPO_ROOT,
  "docs/audits/lean-compile-diagnostics.json",
);

interface LeanDiagnostic {
  line: number;
  severity: string;
  message: string;
}

interface LeanCompileDiagnosticFile {
  errors: LeanDiagnostic[];
  /**
   * 12-char SHA-256 prefix of the `.lean` file at the moment the
   * diagnostics were collected (same convention as the sidecar
   * `source_hashes.lean`, via `qa-utils.hashFile`). Absent on
   * legacy `v1` caches — treated as "unverifiable / stale".
   */
  lean_sha?: string;
  checked_at?: string;
}

interface LeanCompileDiagnostics {
  files: Record<string, LeanCompileDiagnosticFile>;
  generated_at?: string;
}

let leanCompileCache: LeanCompileDiagnostics | null = null;
function loadLeanCompileDiagnostics(): LeanCompileDiagnostics | null {
  if (leanCompileCache !== null) return leanCompileCache;
  if (!existsSync(LEAN_COMPILE_DIAGNOSTICS)) {
    leanCompileCache = { files: {} };
    return leanCompileCache;
  }
  try {
    leanCompileCache = JSON.parse(
      readFileSync(LEAN_COMPILE_DIAGNOSTICS, "utf-8"),
    );
  } catch {
    leanCompileCache = { files: {} };
  }
  return leanCompileCache;
}

export function checkProofLeanCompiles(
  leanPath: string | undefined,
): CheckerResult {
  if (!leanPath) return { result: "n/a", hits: [] };
  const diag = loadLeanCompileDiagnostics();
  if (!diag || Object.keys(diag.files).length === 0) {
    return { result: "n/a", hits: [] };
  }
  const relPath = relative(REPO_ROOT, resolve(leanPath));
  const entry = diag.files[relPath];
  if (!entry) {
    return { result: "n/a", hits: [] };
  }

  // Staleness gate. The cached diagnostics are only trustworthy if the
  // `.lean` source has not changed since they were collected. Compare
  // the cached `lean_sha` (12-char SHA-256 prefix) against the live
  // file's hash — using the same `qa-utils.hashFile` helper the sidecar
  // `source_hashes` use. A missing `lean_sha` (legacy v1 cache) or a
  // mismatch means the entry is stale: return `n/a` rather than a
  // confident `fail`, so an outdated/broken cache never masquerades as
  // a live backlog. Regenerate via `lean-compile-audit.ts` to refresh.
  if (!entry.lean_sha) {
    return {
      result: "n/a",
      hits: [],
      notes:
        "stale: cached lean diagnostics have no lean_sha (legacy v1 cache); " +
        "re-run content/pipeline/lean-compile-audit.ts to refresh",
    };
  }
  // Only hash the live file once we know there is a cached SHA to
  // compare against (skips file I/O on legacy-v1 / no-sha entries).
  const currentSha = hashFile(leanPath);
  if (entry.lean_sha !== currentSha) {
    return {
      result: "n/a",
      hits: [],
      notes:
        `stale: cached lean_sha ${entry.lean_sha} != current ${currentSha ?? "missing"}; ` +
        "re-run content/pipeline/lean-compile-audit.ts to refresh",
    };
  }

  const errors = entry.errors.filter((e) => e.severity === "error");
  if (errors.length === 0) return { result: "pass", hits: [] };
  return {
    result: "fail",
    hits: errors.slice(0, 10).map((e) => ({
      file: leanPath,
      line: e.line,
      text: e.message.slice(0, 200),
    })),
  };
}

// ─── Cached-witness-driven proof criteria ──────────────────────
//
// These three checkers read the JSON artefacts produced by the
// standalone audit scripts (`conjectural-propagation-audit.ts`,
// `trivial-skeleton-audit.ts`, `conditional-class-banner-audit.ts`).
// The artefacts are committed under `docs/audits/`; CI regenerates
// them when their inputs change. Reading the cache is sub-millisecond
// per block, vs. re-running the full graph audit which takes ~5s.

const CONJ_PROP_WITNESS = join(
  REPO_ROOT,
  "docs/audits/2026-05-01-p3-1-conjectural-propagation.witness.json",
);
const TRIVIAL_SKELETON_WITNESS = join(
  REPO_ROOT,
  "docs/audits/2026-05-08-trivial-skeleton-audit.json",
);
const COND_CLASS_BANNER_WITNESS = join(
  REPO_ROOT,
  "docs/audits/2026-05-09-conditional-class-banner.witness.json",
);

let conjPropCache: Record<string, unknown> | null = null;
function loadConjPropAudit(): Record<string, unknown> | null {
  if (conjPropCache !== null) return conjPropCache;
  if (!existsSync(CONJ_PROP_WITNESS)) {
    conjPropCache = {};
    return conjPropCache;
  }
  try {
    conjPropCache = JSON.parse(readFileSync(CONJ_PROP_WITNESS, "utf-8"));
  } catch {
    conjPropCache = {};
  }
  return conjPropCache;
}

type TrivialSkeletonHit = { line: number; pattern: string; snippet: string };

let trivialSkeletonCache: {
  flagged: Record<string, TrivialSkeletonHit[]>;
} | null = null;
function loadTrivialSkeletonAudit() {
  if (trivialSkeletonCache !== null) return trivialSkeletonCache;
  if (!existsSync(TRIVIAL_SKELETON_WITNESS)) {
    trivialSkeletonCache = { flagged: {} };
    return trivialSkeletonCache;
  }
  try {
    const d = JSON.parse(readFileSync(TRIVIAL_SKELETON_WITNESS, "utf-8"));
    trivialSkeletonCache = { flagged: d.flagged ?? {} };
  } catch {
    trivialSkeletonCache = { flagged: {} };
  }
  return trivialSkeletonCache;
}

let condClassCache: Record<string, unknown> | null = null;
function loadCondClassAudit(): Record<string, unknown> | null {
  if (condClassCache !== null) return condClassCache;
  if (!existsSync(COND_CLASS_BANNER_WITNESS)) {
    condClassCache = {};
    return condClassCache;
  }
  try {
    condClassCache = JSON.parse(readFileSync(COND_CLASS_BANNER_WITNESS, "utf-8"));
  } catch {
    condClassCache = {};
  }
  return condClassCache;
}

export function checkProofNoConjPropagationViolation(
  tsPath: string | undefined,
): CheckerResult {
  if (!tsPath) return { result: "n/a", hits: [] };
  const audit = loadConjPropAudit();
  const violators = (audit?.violators ?? []) as Array<{
    file?: string;
    label?: string;
  }>;
  if (violators.length === 0) return { result: "pass", hits: [] };
  // tsPath is absolute; cached `file` values are relative — normalize.
  const tsRel = relative(REPO_ROOT, tsPath);
  const hit = violators.find(
    (v) => v.file === tsRel || tsPath.endsWith(v.file ?? "//"),
  );
  if (!hit) return { result: "pass", hits: [] };
  return {
    result: "fail",
    hits: [
      {
        file: tsRel,
        line: 1,
        text:
          `block '${hit.label ?? "?"}' is a provable kind whose uses[] cone ` +
          `touches a conj: label — demote to 'conjecture' or apply §3b-cond ` +
          `(class-axiomatise the conjecture + [Instance] hypothesis + ` +
          `narrative banner)`,
      },
    ],
  };
}

export function checkProofNoTrivialSkeleton(
  leanPath: string | undefined,
): CheckerResult {
  if (!leanPath) return { result: "n/a", hits: [] };
  const audit = loadTrivialSkeletonAudit();
  // The audit script keys flagged files relative to the paper-content
  // root (e.g. `braids-and-knots/braid-link-types.lean` or
  // `lean/QOU/BraidKnot/PerNucleusMassDerivation.lean`). We may
  // encounter the absolute path, the repo-root-relative path, or
  // the content-root-relative path — try them all.
  const leanAbs = leanPath;
  const leanRel = relative(REPO_ROOT, leanPath);
  const leanShort = leanRel.replace(/^content\//, "");
  const leanChapter = leanShort.replace(/^[^/]+\//, ""); // drop paper dir
  const flagged =
    audit.flagged[leanRel] ??
    audit.flagged[leanShort] ??
    audit.flagged[leanChapter] ??
    audit.flagged[leanAbs];
  if (!flagged || flagged.length === 0) return { result: "pass", hits: [] };
  const stripLeanComments = (text: string): string => {
    let out = "";
    let i = 0;
    let blockDepth = 0;
    while (i < text.length) {
      const c = text[i];
      const n = text[i + 1] ?? "";
      if (blockDepth > 0) {
        if (c === "/" && n === "-") {
          blockDepth += 1;
          i += 2;
          continue;
        }
        if (c === "-" && n === "/") {
          blockDepth -= 1;
          i += 2;
          continue;
        }
        if (c === "\n") out += "\n";
        i += 1;
        continue;
      }
      if (c === "/" && n === "-") {
        blockDepth = 1;
        i += 2;
        continue;
      }
      if (c === "-" && n === "-") {
        i += 2;
        while (i < text.length && text[i] !== "\n") i += 1;
        continue;
      }
      out += c;
      i += 1;
    }
    return out;
  };
  const source = stripLeanComments(readFileSync(leanPath, "utf-8")).split(/\r?\n/);
  const normalize = (s: string) => s.replace(/\s+/g, " ").trim();
  // Guard against stale audit rows: only fail when the captured snippet
  // still appears at (or very near) the recorded location.
  const stillFlagged = flagged
    .map((f) => {
      const target = normalize(f.snippet ?? "");
      if (!target) return null;
      const center = Math.max(0, f.line - 1);
      const from = Math.max(0, center - 10);
      const to = Math.min(source.length - 1, center + 10);
      const span = Math.max(1, (f.snippet.match(/\r?\n/g) ?? []).length + 1);
      for (let i = from; i <= to; i++) {
        const candidate = normalize(source.slice(i, i + span).join("\n"));
        if (candidate === target) {
          return { ...f, line: i + 1 };
        }
      }
      return null;
    })
    .filter((x): x is TrivialSkeletonHit => x !== null);
  if (stillFlagged.length === 0) return { result: "pass", hits: [] };
  return {
    result: "fail",
    hits: stillFlagged.slice(0, 3).map((f) => ({
      file: leanRel,
      line: f.line,
      text:
        `trivial-skeleton pattern '${f.pattern}' at line ${f.line}: ` +
        `${f.snippet.slice(0, 80)}`,
    })),
  };
}

export function checkProofConditionalClassBanner(
  mdPath: string | undefined,
  leanPath: string | undefined,
): CheckerResult {
  if (!mdPath && !leanPath) return { result: "n/a", hits: [] };
  const audit = loadCondClassAudit();
  const findings = (audit?.findings ?? []) as Array<{
    file?: string;
    label?: string;
    missing_lean_class_hypothesis?: boolean;
    missing_md_conditional_banner?: boolean;
  }>;
  if (findings.length === 0) return { result: "pass", hits: [] };
  // Match by either md or lean path.
  const mdRel = mdPath ? relative(REPO_ROOT, mdPath) : "";
  const leanRel = leanPath ? relative(REPO_ROOT, leanPath) : "";
  const hit = findings.find(
    (f) =>
      f.file === mdRel ||
      f.file === leanRel ||
      (f.file && (mdRel.endsWith(f.file) || leanRel.endsWith(f.file))),
  );
  if (!hit) return { result: "pass", hits: [] };
  if (
    !hit.missing_lean_class_hypothesis &&
    !hit.missing_md_conditional_banner
  ) {
    return { result: "pass", hits: [] };
  }
  const missing: string[] = [];
  if (hit.missing_lean_class_hypothesis) missing.push("Lean [Inst : C] hypothesis");
  if (hit.missing_md_conditional_banner)
    missing.push("narrative `**Theorem (conditional on …).**` banner");
  return {
    result: "fail",
    hits: [
      {
        file: mdRel || leanRel,
        line: 1,
        text:
          `block '${hit.label ?? "?"}' is conditional-on-class but missing: ` +
          missing.join(" + "),
      },
    ],
  };
}

// ─── Voice: content-block titles must be scholarly ─────────────
//
// Extract the `title:` field from the .ts manifest and flag
// non-scholarly forms: questions, first-person, second-person,
// imperatives, and casual aside markers.

const TITLE_FIELD_RE = /\btitle:\s*(?:"([^"]+)"|'([^']+)')/;

const NON_SCHOLARLY_TITLE_PATTERNS: Array<{
  re: RegExp;
  what: string;
}> = [
  { re: /\?$/, what: "ends in '?' — title is a question" },
  {
    re: /^(?:Why|How(?:\s+does|\s+do|\s+can|\s+is|\s+are|\s+to)|What(?:\s+is|\s+are|\s+does|\s+do|\s+if)|When|Where|Should|Could|Would|Do(?:es)?|Is|Are|Can)\b/i,
    what: "starts with a question word",
  },
  {
    // Note: apostrophe REQUIRED for contractions ("I'll", "we'll", "I'm") —
    // the bare-letter forms (`Ill`, `well`, `Im`) trigger false positives on
    // common math/text (e.g. "well-separated", "$\mathrm{Im}(q)$"). The
    // multi-word phrasings ("let us", "I will", "we are") stay literal.
    re: /\b(?:I['’]ll|we['’]ll|let['’]s|let\s+us|I['’]m|we['’]re|I\s+(?:will|am)|we\s+(?:will|are))\b/i,
    what: "first-person aside in the title",
  },
  {
    re: /\b(?:you['’]ll|you['’]re|your|you\s+(?:can|will|might|should|may))\b/i,
    what: "second-person address in the title",
  },
  {
    re: /^(?:Quick (?:note|aside|check|look)|TODO|FIXME|WIP|Note|Sidebar|Footnote|Punt|Stub|Placeholder)\b/i,
    what: "casual / status-leak marker in the title",
  },
  {
    re: /\bobviously|clearly|simply|trivially|easily|naturally\b/i,
    what: "editorializing adverb in the title",
  },
  {
    re: /\bhopefully|maybe|probably|perhaps|possibly\b/i,
    what: "hedge in the title — titles state, not speculate",
  },
];

export function checkVoiceTitleScholarly(
  tsPath: string | undefined,
): CheckerResult {
  if (!tsPath) return { result: "n/a", hits: [] };
  const text = readMaybe(tsPath);
  if (!text) return { result: "n/a", hits: [] };
  const m = text.match(TITLE_FIELD_RE);
  if (!m) return { result: "n/a", hits: [] };
  const title = m[1] ?? m[2] ?? "";
  if (!title) return { result: "n/a", hits: [] };
  const hits: CheckerHit[] = [];
  for (const { re, what } of NON_SCHOLARLY_TITLE_PATTERNS) {
    if (re.test(title)) {
      // Find the line containing the title field for accurate
      // reporting.
      const lineIdx = text
        .slice(0, m.index)
        .split("\n").length;
      hits.push({
        file: tsPath,
        line: lineIdx,
        text: `title "${title.slice(0, 100)}" — ${what}`,
      });
    }
  }
  return { result: hits.length > 0 ? "fail" : "pass", hits };
}

// ─── Voice: statement should not contain interpretation ────────
//
// A theorem/proposition/lemma/corollary STATEMENT is the bare claim.
// Interpretation, motivation, "physical meaning", or "why this
// matters" belongs in a separate `remark` block linked via
// `interprets:`. This checker is a candidate-flagger only — the
// actual judgement (is this prose interpretation, or a legitimate
// proof sketch?) is non-mechanical and the criterion is registered
// as `automated: false`. Script returns `n/a` to queue the block
// for agent review when the candidate heading pattern fires.

const INTERPRETATION_HEADING_RE =
  /^##+\s*(Interpretation|Discussion|Motivation|Why\s+(?:this\s+matters|we\s+care)|Significance|Physical(?:\s+meaning|\s+interpretation)?|Meaning|Commentary|Aside|Reading|Intuition)/im;

export function checkVoiceStatementNoInterpretation(
  mdPath: string | undefined,
): CheckerResult {
  if (!mdPath) return { result: "n/a", hits: [] };
  const text = readMaybe(mdPath);
  if (!text) return { result: "n/a", hits: [] };
  // Agent-only criterion. Script returns `n/a` ALWAYS so the sidecar
  // is marked needs-agent on every applicable block; an agent /
  // human reviewer entry supersedes. BUT — when the candidate
  // heading pattern fires, append a hint to the agent's queue via
  // the `hits[]` payload so the agent knows where to look.
  const m = text.match(INTERPRETATION_HEADING_RE);
  if (!m) return { result: "n/a", hits: [] };
  const idx = text.slice(0, m.index).split("\n").length;
  return {
    result: "n/a",
    hits: [
      {
        file: mdPath,
        line: idx,
        text:
          `candidate '${m[0].trim()}' heading at line ${idx} — agent should ` +
          `review whether the section's content is interpretation that ` +
          `belongs in a separate remark block`,
      },
    ],
  };
}

// ─── Dispatch map ───────────────────────────────────────────────

export const EXTENDED_AUTOMATED_CHECKERS: Record<
  string,
  (paths: { md?: string; ts?: string; lean?: string }) => CheckerResult
> = {
  // bibliography
  "bib-cite-resolves": (p) => checkBibCiteResolves(p.md, p.lean),
  "bib-cited-ref-has-url": (p) => checkBibCitedRefHasUrl(p.md, p.lean),
  "bib-cited-ref-metadata-ok": (p) =>
    checkBibCitedRefMetadataOk(p.md, p.lean),
  "bib-cited-ref-has-screenshot": (p) =>
    checkBibCitedRefHasScreenshot(p.md, p.lean),
  // compute
  "compute-prop-has-probe": (p) => checkComputePropHasProbe(p.ts, p.lean),
  "compute-prop-has-consumer": (p) => checkComputePropHasConsumer(p.ts, p.lean),
  "compute-witness-exists": (p) => checkComputeWitnessExists(p.ts),
  "compute-lp-dual-present": (p) => checkComputeLpDualPresent(p.ts),
  // canonical
  "canonical-calibration-count": (p) =>
    checkCanonicalCalibrationCount(p.md, p.ts),
  "canonical-no-numerology": (p) => checkCanonicalNoNumerology(p.md),
  "canonical-witness-pinned": (p) => checkCanonicalWitnessPinned(p.md, p.ts),
  "canonical-script-not-deprecated": (p) =>
    checkCanonicalScriptNotDeprecated(p.ts),
  "canonical-dilogarithm-context": (p) =>
    checkCanonicalDilogarithmContext(p.md, p.ts),
  "canonical-no-hardcoded-observable": (p) =>
    checkCanonicalNoHardcodedObservable(p.md),
  "canonical-cal4-acknowledged": (p) =>
    checkCanonicalCal4Acknowledged(p.md, p.ts),
  "canonical-ck-tiered-not-binary": (p) =>
    checkCanonicalCkTieredNotBinary(p.md, p.ts),
  "canonical-no-negative-result-in-paper": (p) =>
    checkCanonicalNoNegativeResultInPaper(p.md, p.ts),
  // detangler
  "detangler-section-band": (p) => checkDetanglerSectionBand(p.ts),
  "detangler-no-forward-ref": (p) => checkDetanglerNoForwardRef(p.ts),
  "detangler-no-xchapter-fwd": (p) => checkDetanglerNoXChapterFwd(p.ts),
  "detangler-archimedean-wall": (p) =>
    checkDetanglerArchimedeanWall(p.ts, p.lean),
  "detangler-block-tanglement": (p) => checkDetanglerBlockTanglement(p.ts),
  "detangler-graph-energy": (p) => checkDetanglerGraphEnergy(p.ts),
  "detangler-topic-coherence": (p) => checkDetanglerTopicCoherence(p.md),
  "detangler-no-dependency-cycle": (p) =>
    checkDetanglerNoDependencyCycle(p.ts),
  // proof
  "proof-no-bare-sorries": (p) => checkProofNoBareSorries(p.lean),
  "proof-substantive": (p) => checkProofSubstantive(p.lean),
  "proof-no-axiom-growth": (p) => checkProofNoAxiomGrowth(p.lean),
  "proof-build-green": (p) => checkProofBuildGreen(p.lean),
  // proof — cached-witness-driven (read the docs/audits/*.json
  // artefacts emitted by the standalone audit scripts)
  "proof-no-conj-propagation-violation": (p) =>
    checkProofNoConjPropagationViolation(p.ts),
  "proof-no-trivial-skeleton": (p) => checkProofNoTrivialSkeleton(p.lean),
  "proof-conditional-class-banner": (p) =>
    checkProofConditionalClassBanner(p.md, p.lean),
  "proof-lean-compiles": (p) => checkProofLeanCompiles(p.lean),
  // voice
  "voice-title-scholarly": (p) => checkVoiceTitleScholarly(p.ts),
  "voice-statement-no-interpretation": (p) =>
    checkVoiceStatementNoInterpretation(p.md),
  // q-usage — per-block regime detector + 6 mismatch criteria. The
  // checker functions live in qa-checkers-q-usage.ts and return a
  // CheckerResult-compatible shape. `warn` flows through end-to-end
  // (#1640-Copilot @ qa-checkers-extended.ts:1927 — earlier `warn`→`pass`
  // coercion silently dropped chapter-mismatch warnings).
  ...(() => {
    const m: Record<string, (paths: { md?: string; ts?: string; lean?: string }) => CheckerResult> = {};
    for (const [id, fn] of Object.entries(Q_USAGE_AUTOMATED_CHECKERS)) {
      m[id] = (p) => {
        const r = fn(p);
        return { result: r.result, hits: r.hits };
      };
    }
    return m;
  })(),
};
