classDiagram
  direction TB
  namespace bootstrap__glossary {
    class n_bootstrap_glossary_glossary["glossary: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_bootstrap_glossary_glossary" fa_uml_kind_glossary
  cssClass "n_bootstrap_glossary_glossary" fa_uml_undetermined
