classDiagram
  direction TB
  namespace bootstrap__schemas {
    class bootstrap_schemas_http___json_schema_org_draft_07_schema_["JSON Schema draft-07"] {
      <<ext: JSON Schema draft-07>>
    }
  }
  cssClass "bootstrap_schemas_http___json_schema_org_draft_07_schema_" fa_uml_kind_schemas
