classDiagram
  direction TB
  namespace bootstrap__swimlane_glossary {
    class bootstrap_swimlane_glossary_folio_glossary_ledger_v1["folio-glossary-ledger/v1"] {
      <<ts: Ledger>>
      $schema [1] string
      instance [1] string
      concepts [1] Record~string, LedgerEntry~
    }
  }
  cssClass "bootstrap_swimlane_glossary_folio_glossary_ledger_v1" fa_uml_kind_swimlane_glossary
