classDiagram
  direction TB
  namespace folio_assistant_sci__attestations {
    class folio_assistant_sci_attestations_QaAttestations["QaAttestations"] {
      <<json: QaAttestationsSchema>>
    }
  }
  cssClass "folio_assistant_sci_attestations_QaAttestations" fa_uml_kind_attestations
