classDiagram
  direction TB
  namespace folio_assistant_sci__folio_assistant_sci_qa_checkers {
    class folio_assistant_sci_folio_assistant_sci_qa_checkers_folio_qa_checker_v1_folio_qa_checker_v1["folio-qa-checker/v1"] {
      <<json: QaCheckerNodeSchema>>
      $schema [1] 'folio-qa-checker/v1'
      criterion [1] string
      check [1] string
      rationale [0..1] string
    }
  }
  cssClass "folio_assistant_sci_folio_assistant_sci_qa_checkers_folio_qa_checker_v1_folio_qa_checker_v1" fa_uml_kind_qa_checkers
