classDiagram
  direction TB
  namespace folio_assistant_sci__folio_assistant_sci_pipeline_plugins {
    class folio_assistant_sci_folio_assistant_sci_pipeline_plugins_folio_pipeline_plugin_v1_folio_pipeline_plugin_v1["folio-pipeline-plugin/v1"] {
      <<json: PipelinePluginNodeSchema>>
      $schema [1] 'folio-pipeline-plugin/v1'
      slot [1] string
      implementation [1] string
      rationale [0..1] string
    }
  }
  cssClass "folio_assistant_sci_folio_assistant_sci_pipeline_plugins_folio_pipeline_plugin_v1_folio_pipeline_plugin_v1" fa_uml_kind_pipeline_plugins
