---
# folio-assistant-4682
title: 'Agent memory target: Gemini CLI (not implemented — owner 2026-10-06)'
status: todo
type: task
created_at: 2026-10-06T18:35:15Z
updated_at: 2026-10-06T18:35:15Z
parent: folio-assistant-31ni
---

Owner 2026-10-06: bean up, DO NOT implement yet. Target format: .gemini/agents/<agent>.md (front matter + prompt body; @file imports allowed, depth 5). Generated by the shared memory assembler into a marked region, with a --check gate and a per-target budget that drops lowest-priority nodes and reports them. Research: see parent bean 31ni.
