---
# folio-assistant-uj55
title: Windows .bat wrappers for every .sh a user runs from the normal workflow
status: in-progress
type: feature
priority: normal
created_at: 2026-09-18T07:47:05Z
updated_at: 2026-09-18T07:50:21Z
parent: folio-assistant-5a3l
---

Branch `claude/windows-bat-wrappers-2026-09-18`, PR #231. 36 wrappers generated by `cat-harness/scripts/gen-bat-wrappers.sh` (moved from `scripts/` when main split into `cat-harness/`), `bun run bat:sync:check` in the code-quality gate, `.gitattributes` pins `.sh`→LF and `.bat`→CRLF.

The platform ships 49 `.sh` scripts and no Windows entry point for any of
them. `.mcp.json` names `scripts/sage-mcp.sh` and `scripts/google-drive-mcp.sh`
as MCP commands, the session-start hook runs `session-start-coord-sweep.sh`,
and the docs tell a new user to run `install-beans.sh`, `start-folio-assistant.sh`
and `git-hooks/install.sh` — none of which a `cmd.exe` user can invoke by name.

Route: one `.bat` beside each `.sh` a user runs by hand or wires into a
config, which locates Git Bash (`Git\bin\bash.exe`, never the WSL
`System32\bash.exe`) and forwards all arguments. Not native ports: the
scripts are bash and Git for Windows is already a prerequisite of `git`.

Excluded on purpose: Linux-host provisioning (`deploy/*`, `install-tex.sh`,
`setup-sage.sh`, `setup-singular.sh`, `setup-elan-symlinks.sh`,
`adapters/mcp-server/install.sh`), sourced libraries (`scripts/lib/*`), the
git-invoked hook (`git-hooks/auto-commit-feedback.sh`), CI-only helpers
(`.github/scripts/generate-diff.sh`, `latexmk-compile.sh`), and the
qou-specific leftovers (`docker-latex-build/build-pdf.sh`,
`smoke-test-libraries.sh`).
