classDiagram
  direction TB
  namespace cat_harness_tools__cat_harness_tools_schemas {
    class n_cat_harness_tools_cat_harness_tools_schemas_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_tools_cat_harness_tools_schemas_code" fa_uml_kind_code
  cssClass "n_cat_harness_tools_cat_harness_tools_schemas_code" fa_uml_undetermined
