---
# folio-assistant-6ztw
title: 'Node kinds: generic pages at /<locale>/<declaring>/<kind>/[<harness>/[<path>]] (#2195 PR 2)'
status: in-progress
type: feature
created_at: 2026-10-05T22:30:10Z
updated_at: 2026-10-05T22:30:10Z
parent: folio-assistant-zzmr
---

Issue #2195 PR 2. Generic dashboard per kind (subclasses included, filters by kind and harness, status tiles from enum fields), per-harness dashboard, per-node page; en only; generated by node-kind:pages, checked in CI. Next: PR 3 change-set override + pages-resolve QA; folio builds (smart-ra) run the generator.
