classDiagram
  direction TB
  namespace bootstrap_tools__bootstrap_tools_schemas {
    class bootstrap_tools_bootstrap_tools_schemas_http___json_schema_org_draft_07_schema_["JSON Schema draft-07"] {
      <<ext: JSON Schema draft-07>>
    }
    class bootstrap_tools_bootstrap_tools_schemas_https___json_schema_org_draft_2020_12_schema["JSON Schema 2020-12"] {
      <<ext: JSON Schema 2020-12>>
    }
    class bootstrap_tools_bootstrap_tools_schemas_folio_source_descriptor_v1_Identifier["Identifier"] {
      <<json: SourceDescriptorSchema>>
      name [1] string
      authoritative [1] boolean
      example [0..1] string
      note [0..1] string
    }
    class bootstrap_tools_bootstrap_tools_schemas_folio_source_descriptor_v1_folio_source_descriptor_v1["folio-source-descriptor/v1"] {
      <<json: SourceDescriptorSchema>>
      $schema [1] 'folio-source-descriptor/v1'
      id [1] string
      title [1] string
      system [0..1] string
      baseUrl [0..1] string~uri~
      nodeKind [1] string
      subsetStrategies [1..*] list~container | identifier | facet | range | closure~
      subsetIsSelfContained [1] boolean
      enumeration [1] object
      termsUrl [0..1] string~uri~
      character [1] object
    }
  }
  bootstrap_tools_bootstrap_tools_schemas_folio_source_descriptor_v1_folio_source_descriptor_v1 *-- "1..*" bootstrap_tools_bootstrap_tools_schemas_folio_source_descriptor_v1_Identifier : identifiers
  cssClass "bootstrap_tools_bootstrap_tools_schemas_http___json_schema_org_draft_07_schema_" fa_uml_kind_schemas
  cssClass "bootstrap_tools_bootstrap_tools_schemas_https___json_schema_org_draft_2020_12_schema" fa_uml_kind_schemas
  cssClass "bootstrap_tools_bootstrap_tools_schemas_folio_source_descriptor_v1_Identifier" fa_uml_kind_schemas
  cssClass "bootstrap_tools_bootstrap_tools_schemas_folio_source_descriptor_v1_folio_source_descriptor_v1" fa_uml_kind_schemas
