classDiagram
  direction TB
  namespace cat_openapi__cat_openapi_schemas {
    class n_cat_openapi_cat_openapi_schemas_schemas["schemas: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_openapi_cat_openapi_schemas_schemas" fa_uml_kind_schemas
  cssClass "n_cat_openapi_cat_openapi_schemas_schemas" fa_uml_undetermined
