classDiagram
  direction TB
  namespace fhir_harness__fhir_ig_scripts {
    class n_fhir_harness_fhir_ig_scripts_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_fhir_harness_fhir_ig_scripts_code" fa_uml_kind_code
  cssClass "n_fhir_harness_fhir_ig_scripts_code" fa_uml_undetermined
