classDiagram
  direction TB
  namespace fhir_harness__fhir_harness_validators {
    class fhir_harness_fhir_harness_validators_folio_validator_v1_folio_validator_v1["folio-validator/v1"] {
      <<json: ValidatorNodeSchema>>
      $schema [1] 'folio-validator/v1'
      id [1] string
      validates [1] object
      schema [1] string
      rationale [0..1] string
    }
  }
  cssClass "fhir_harness_fhir_harness_validators_folio_validator_v1_folio_validator_v1" fa_uml_kind_validators
