classDiagram
  direction TB
  namespace fhir_harness__qa {
    class n_fhir_harness_qa_qa["qa: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_fhir_harness_qa_qa" fa_uml_kind_qa
  cssClass "n_fhir_harness_qa_qa" fa_uml_undetermined
