---
# folio-assistant-xxh4
title: 'Agent memory target: GitHub Copilot (not implemented — owner 2026-10-06)'
status: todo
type: task
created_at: 2026-10-06T18:35:16Z
updated_at: 2026-10-06T18:35:16Z
parent: folio-assistant-31ni
---

Owner 2026-10-06: bean up, DO NOT implement yet. Target format: .github/agents/<agent>.agent.md (30,000-char body); repo-wide .github/copilot-instructions.md. Generated by the shared memory assembler into a marked region, with a --check gate and a per-target budget that drops lowest-priority nodes and reports them. Research: see parent bean 31ni.
