classDiagram
  direction LR
  namespace cat_harness_tools__cat_harness_tools_adapters {
    class n_cat_harness_tools_cat_harness_tools_adapters_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  namespace cat_harness_tools__cat_harness_tools_tests {
    class n_cat_harness_tools_cat_harness_tools_tests_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_tools_cat_harness_tools_adapters_code" fa_uml_kind_code
  cssClass "n_cat_harness_tools_cat_harness_tools_adapters_code" fa_uml_undetermined
  cssClass "n_cat_harness_tools_cat_harness_tools_tests_code" fa_uml_kind_code
  cssClass "n_cat_harness_tools_cat_harness_tools_tests_code" fa_uml_undetermined
