classDiagram
  direction TB
  namespace fhir_harness__fhir_ig_skills {
    class n_fhir_harness_fhir_ig_skills_skills["skills: no node schema"] {
      <<could not determine>>
    }
  }
  namespace fhir_harness__fhir_ig_tools {
    class fhir_harness_fhir_ig_tools_Maintain["Maintain"] {
      <<json: ToolDefinitionSchema>>
    }
    class fhir_harness_fhir_ig_tools_ToolDefinition["ToolDefinition"] {
      <<json: ToolDefinitionSchema>>
    }
  }
  cssClass "n_fhir_harness_fhir_ig_skills_skills" fa_uml_kind_skills
  cssClass "n_fhir_harness_fhir_ig_skills_skills" fa_uml_undetermined
  fhir_harness_fhir_ig_tools_ToolDefinition *-- "0..*" fhir_harness_fhir_ig_tools_Maintain : maintains
  cssClass "fhir_harness_fhir_ig_tools_Maintain" fa_uml_kind_tools
  cssClass "fhir_harness_fhir_ig_tools_ToolDefinition" fa_uml_kind_tools
