classDiagram
  direction TB
  namespace smart_trust__smart_trust_artifact_index {
    class n_smart_trust_smart_trust_artifact_index_fhir_artifact_index["fhir-artifact-index: no node schema"] {
      <<could not determine>>
    }
  }
  namespace smart_trust__smart_trust_docs {
    class n_smart_trust_smart_trust_docs_docs["docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_trust_smart_trust_artifact_index_fhir_artifact_index" fa_uml_kind_fhir_artifact_index
  cssClass "n_smart_trust_smart_trust_artifact_index_fhir_artifact_index" fa_uml_undetermined
  cssClass "n_smart_trust_smart_trust_docs_docs" fa_uml_kind_docs
  cssClass "n_smart_trust_smart_trust_docs_docs" fa_uml_undetermined
