classDiagram
  direction TB
  namespace who_iris__library {
    class n_who_iris_library_library["library: no node schema"] {
      <<could not determine>>
    }
  }
  namespace who_iris__who_iris_catalogue {
    class n_who_iris_who_iris_catalogue_catalogue["catalogue: no node schema"] {
      <<could not determine>>
    }
  }
  namespace who_iris__who_iris_uploads {
    class n_who_iris_who_iris_uploads_uploads["uploads: no node schema"] {
      <<could not determine>>
    }
  }
  namespace who_iris__who_iris_skills {
    class n_who_iris_who_iris_skills_skills["skills: no node schema"] {
      <<could not determine>>
    }
  }
  namespace who_iris__who_iris_themes {
    class n_who_iris_who_iris_themes_themes["themes: no node schema"] {
      <<could not determine>>
    }
  }
  namespace who_iris__who_iris_docs {
    class n_who_iris_who_iris_docs_docs["docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_who_iris_library_library" fa_uml_kind_library
  cssClass "n_who_iris_library_library" fa_uml_undetermined
  cssClass "n_who_iris_who_iris_catalogue_catalogue" fa_uml_kind_catalogue
  cssClass "n_who_iris_who_iris_catalogue_catalogue" fa_uml_undetermined
  cssClass "n_who_iris_who_iris_uploads_uploads" fa_uml_kind_uploads
  cssClass "n_who_iris_who_iris_uploads_uploads" fa_uml_undetermined
  cssClass "n_who_iris_who_iris_skills_skills" fa_uml_kind_skills
  cssClass "n_who_iris_who_iris_skills_skills" fa_uml_undetermined
  cssClass "n_who_iris_who_iris_themes_themes" fa_uml_kind_themes
  cssClass "n_who_iris_who_iris_themes_themes" fa_uml_undetermined
  cssClass "n_who_iris_who_iris_docs_docs" fa_uml_kind_docs
  cssClass "n_who_iris_who_iris_docs_docs" fa_uml_undetermined
