/**
 * @module bootstrap-tools/scripts/export-graph.test
 * @graphNode none — a test
 */
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { GraphExportSchema } from "../schemas/graph-export.ts";
import { COLLECTED_KINDS, exportGraph, parseXml } from "./export-graph.ts";

const BOOTSTRAP = join(import.meta.dir, "..", "..", "bootstrap");
const DOC = "https://example.org/site/bootstrap/bootstrap.jsonld";
const build = (provenance = false) => exportGraph(BOOTSTRAP, { docIri: DOC, provenance });
type Node = { "@id": string; "@type": string; [k: string]: unknown };
const nodes = () => build()["@graph"] as Node[];

describe("bootstrap's graph, from bootstrap's files, in standard terms", () => {
  test("parses against its schema, with and without provenance", () => {
    for (const d of [build(), build(true)]) {
      const r = GraphExportSchema.safeParse(d);
      expect(r.success ? [] : r.error.issues).toEqual([]);
    }
  });

  test("pure: two builds are byte-identical, and nothing absolute from this machine appears", () => {
    expect(JSON.stringify(build())).toBe(JSON.stringify(build()));
    expect(JSON.stringify(build())).not.toContain(BOOTSTRAP);
  });

  test("names nothing above bootstrap — no harness prefix, no harness property", () => {
    const text = JSON.stringify({ ...build(), "@id": "", "@graph": nodes().map((n) => ({ ...n, "@id": "" })) });
    expect(text).not.toContain("cat-harness");
    expect(text).not.toContain("folio-assistant");
  });

  test("every skill bootstrap holds is a node, at the id cat-harness links to", () => {
    const onDisk = readdirSync(join(BOOTSTRAP, "skills"))
      .filter((f) => f.endsWith(".md") && f !== "README.md")
      .map((f) => /^name:\s*(.+)$/m.exec(readFileSync(join(BOOTSTRAP, "skills", f), "utf-8"))?.[1]?.trim() ?? f.slice(0, -3))
      .sort();
    const inGraph = nodes().filter((n) => n["@type"] === "bootstrap:Skill").map((n) => n["@id"].split("#skill/")[1]).sort();
    expect(inGraph).toEqual(onDisk);
  });

  test("every link inside the graph lands on a node of it", () => {
    const ids = new Set([DOC, ...nodes().map((n) => n["@id"])]);
    const dangling: string[] = [];
    for (const n of nodes()) {
      for (const k of ["isPartOf", "sourceRef", "targetRef", "skill"]) {
        const v = n[k];
        if (typeof v === "string" && !ids.has(v)) dangling.push(`${n["@id"]} ${k} → ${v}`);
      }
      for (const v of (n["flowNodeRef"] as string[] | undefined) ?? []) if (!ids.has(v)) dangling.push(`${n["@id"]} flowNodeRef → ${v}`);
    }
    expect(dangling).toEqual([]);
  });

  test("a subgraph says what it holds with bootstrap's own graph-kind individuals", () => {
    const declared = new Set((JSON.parse(readFileSync(join(BOOTSTRAP, "bootstrap.json"), "utf-8")) as { directories: { graphKinds: string[] }[] }).directories.flatMap((d) => d.graphKinds));
    for (const n of nodes().filter((x) => x["@type"] === "bootstrap:Subgraph")) {
      for (const t of n["type"] as string[]) expect(declared.has(t.replace("bootstrap:graphKind/", ""))).toBe(true);
    }
  });

  test("provenance only when asked, and never on a node", () => {
    expect("generatedAtTime" in build()).toBe(false);
    const p = build(true);
    expect("generatedAtTime" in p).toBe(true);
    expect(JSON.stringify(p["@graph"])).not.toContain("generatedAtTime");
  });

  test("the document says it is generated, and by what", () => {
    expect(String(build()["comment"])).toContain("Generated by bootstrap-tools");
  });

  test("nothing the build could not read is dropped silently", () => {
    expect(build()["problems"]).toEqual([]);
  });

  test("a declared subgraph whose contents were not read is named, not left empty", () => {
    const g = build();
    const graph = g["@graph"] as { "@type": string; label: string; type: string[] }[];
    const unread = graph
      .filter((n) => n["@type"] === "bootstrap:Subgraph")
      .filter((n) => !n.type.some((k) => COLLECTED_KINDS.some((c) => k.endsWith(`/${c}`))))
      .map((n) => n.label)
      .sort();
    expect(unread.length).toBeGreaterThan(0);
    expect(g["omitted"]).toEqual(unread);
  });

  test("nodes are sorted by @id, by code unit", () => {
    const ids = (build()["@graph"] as { "@id": string }[]).map((n) => n["@id"]);
    expect(ids).toEqual([...ids].sort());
  });
});

describe("the XML reader is enough for authored BPMN", () => {
  test("elements, attributes, nesting, text and entities", () => {
    const x = parseXml('<?xml version="1.0"?><!-- c --><a:r x="1"><a:c y=\'2\'/><a:t>a &amp; b</a:t></a:r>');
    const r = x.children[0]!;
    expect(r.name).toBe("a:r");
    expect(r.attrs).toEqual({ x: "1" });
    expect(r.children.map((c) => c.name)).toEqual(["a:c", "a:t"]);
    expect(r.children[1]!.text).toBe("a & b");
  });
});
