/**
 * The note every file bootstrap-tools writes into bootstrap carries: that it
 * is generated, by what, and what to change instead.
 *
 * @module bootstrap-tools/scripts/generated-by
 *
 * Owner, 2026-09-30 (bean `xsqm`): generated content needs "a header note that
 * content is autogenerated and (unique exception) reference the
 * bootstrap-tools as what generated". bootstrap otherwise names nothing
 * outside itself; its tools repository is the one name it may carry, and only
 * as the answer to "what wrote this file?". One wording, here, so the check
 * that every generated file carries it (`generated-by.test.ts`) has one thing
 * to look for.
 */

/** The repository that writes bootstrap's generated files. */
export const TOOLS_REPOSITORY = "https://github.com/litlfred/bootstrap-tools";

/** The phrase every note begins with — what the check looks for. */
export const GENERATED_BY = "Generated by bootstrap-tools";

/** `Generated by bootstrap-tools (<script>) from <from> — do not edit; <instead>.` */
export function generatedNote(script: string, from: string, instead: string): string {
  return `${GENERATED_BY} (${script}) from ${from} — do not edit; ${instead}.`;
}
