---
# folio-assistant-v8n5
title: 'HARNESS THEMING: the who-iris board tile, navbar and stickies render on the IRIS theme, not only its pages'
status: in-progress
type: feature
priority: high
created_at: 2026-09-30T08:43:50Z
updated_at: 2026-09-30T11:02:57Z
parent: folio-assistant-yg29
---

Owner, 2026-09-30, answering the GOAL 3 goal review: keep GOAL 3 **open**, and theme the harness itself. The goal's words are *"showing who-iris w/ existing materialized assets with themed harness"*, and the owner reads "themed harness" as more than the pages.

## What is true today (measured 2026-09-30)
- The who-iris **pages** (`/who-iris/`, generated by `who-iris/scripts/gen-iris-pages.ts`) render on `--iris-*` custom properties from `who-iris/themes/themes.ts`. That file holds two WHO themes, `iris-web` and `who-wpro-publication`, measured from the captured IRIS stylesheet and the style guide, and resolved through the platform's `resolveTheme` with `instance: "who-iris"`.
- The **harness surfaces** do not use them. The board tile, the navbar entry and any sticky resolve a `theme` name against the platform's own themes (`cat-harness/schemas/theme.ts`; `harness-tiles.ts` via `resolveThemeBackdrop`). The who-iris harness entry in `docs/_data/harness.json` carries only `tone: 199` (a WHO-blue hue) and `genericAvatar: false`. `who-iris/who-iris.json` declares no `theme` on any sticky or tile.

## The shape of the fix, to be checked rather than assumed
An instance-declared theme has to be resolvable wherever a surface names a theme. That means resolving the who-iris themes through the same `resolveTheme` lookup the surfaces use, not copying the palette into the platform. `who-iris/themes/themes.ts` already says why it must not live in `cat-harness/schemas/`: a palette read off a WHO style guide is subject matter. The platform learns to *find* an instance's themes and never *holds* them.

## Done when
- [x] The who-iris board tile and navbar entry render on `iris-web` (or a theme the owner names), resolved from `who-iris/themes/`, with no WHO palette value in `cat-harness/`
- [x] A test fails if the surface falls back to the platform default for an instance that declares its own theme
- [x] `check:voices`, `iris:pages:check` and the SC 1.4.1 rule from `j66n` (state carried by word as well as colour) still hold
- [x] Checked on a rendered build, `preview:site` **plus** the `mount-instance-docs.ts` step (see `yg29` §"A correction worth keeping"), not inferred from generator output

_2026-09-30T11:02:54Z_ — Claimed by claude/magical-archimedes-4qkfxp-v8n5 — pushed to main so sibling sessions see it before this branch has a PR (bean 35nj).

## 2026-09-30: the platform half is built; the who-iris half waits on one question

**Built** (`cat-harness/schemas/theme-by-ref.ts`, with 9 tests). A theme reference now resolves against its **owner**. `{instance: "who-iris", themeId: "iris-web"}` finds who-iris's declared `themes` directory and reads its `themes.ts` export, `INSTANCE_THEMES`, by declaration, not by import, so the platform holds no WHO value. A reference with no `instance` means the citing instance's own, then the platform's, so every reference written before #1168 B8 resolves exactly as it did.

It is wired into the two consumers that take a reference, `harness-tiles.ts` and `gen-landing-data.ts`. For today's references their output is byte-identical.

**Held: which theme styles who-iris's harness surfaces.** The note board styles a card only from **`sticky`-kind** themes. `gen-themes-css.ts` states the rule: a `webpage` theme *"shares the geometry but not this stylesheet: its CSS is the site's, not the note board's."* who-iris's themes are `iris-web` (webpage) and `who-wpro-publication` (publication). The platform's own model therefore forbids a who-iris card from citing either.

The options, put to the owner:
- author a `sticky`-kind IRIS theme in `who-iris/themes/`, derived from `iris-web`'s measured palette; or
- let a `webpage` theme style harness surfaces, which changes the platform rule; or
- theme only the tile and navbar tone from `iris-web`'s accent. Its hue is about 198°, against the avatar's 199, so the tile's colour barely moves.

The owner earlier called theme mapping *"authoring (human/agentic) decision/judgement"* (for `xffc`/`d3yq`), which is why this is asked rather than decided here.

## 2026-09-30: built — owner's ruling (a) "Author iris-sticky", branch `claude/magical-archimedes-4qkfxp-v8n5-theme`

- **Theme.** `who-iris/themes/themes.ts` gains `iris-sticky` (kind `sticky`). It `inherits` `{who-iris, iris-web}`, so its palette — accent `#008dc9`, surface `#ffffff`, ink `#212529`, edge `#ced4da` — arrives through `resolveTheme`'s palette merge from the theme measured off the captured DSpace stylesheet; the declaration holds no colour literal. Geometry is read from the platform's default sticky theme (IRIS has no sticky surface; `iris-web`'s `1140px` is a page column). No backdrop. `themes.test.ts` asserts the resolved palette equals what `client-theme.css` in the capture zip says, and that the declaration carries no hex value.
- **CSS.** `gen-themes-css.ts` now also emits every INSTANCE-declared sticky theme, found by `instanceStickyThemes()` (new, in `schemas/theme-by-ref.ts`, same declaration-driven discovery as `themeByRef`). A collision with a platform id or across instances is refused (exit 1) rather than resolved by order, because a card writes the bare id. No instance name or colour in the generator (tested). Note: the GENERATED `cat-harness/docs/assets/css/themes.css` now carries the IRIS values — output, not source.
- **Sticky.** `who-iris/who-iris.json` contributes its own card (`id: who-iris`, order 40, `theme: {instance: who-iris, themeId: iris-sticky}`, `bodyFrom: description`, one link to `/who-iris/`); `cat-harness/folio/who-iris.json` written by `landing:sticky`.
- **Tile + navbar.** `hexHue()` in `schemas/theme.ts`; `harness-tiles.ts` takes `tone` from the accent's hue when the instance's own sticky resolves a theme the INSTANCE declares (not a platform theme), with `toneFrom: theme|avatar` in `harness.json`. who-iris: 199 → 198. Scoped to instance-owned themes on purpose: applied to every sticky it would re-hue five other harnesses (cat-harness 268→184, folio-assistant 236→127, core 212→88, bootstrap 96→23, smart-trust 0→211) — not asked for. The navbar entry takes the same tone (`gen-navbar-include.ts` passes `h.tone`; verified `hsl(198 45% 28%)` on the built page).
- **Tests that fail on a fallback.** `harness-tiles.test.ts` (who-iris tone == hue of its own theme's accent, `toneFrom: theme`), `gen-themes-css.test.ts` (committed CSS has a block with each instance theme's accent), `theme-refs.test.ts` now resolves by reference, owner first.
- **Rendered check.** `preview:site` (which runs `mount-instance-docs.ts`: 5 mounts, rail on 19 pages), served under `/folio-assistant/`, Chromium: the landing card carries `data-fa-sticky-theme="iris-sticky"` and computes `--fa-sticky-accent: #008dc9`; `#harness-who-iris` computes `--fa-tile-tone: 198`; the sidebar entry's mark is `hsl(198 45% 28%)`.
- **Seen on the build, not fixed here:** the board uses `--fa-sticky-accent` only for the medium-priority stripe, and a landing card has no priority, so the IRIS card renders as white / `#ced4da` edge / `#212529` ink — faithful to IRIS, but the blue does not show on the card itself. Making it show needs a board CSS change or a backdrop: the owner's call.


## OWNER RULING, 2026-09-30: a thin accent band on themed cards with no priority

Asked in session https://claude.ai/code/session_01SiFEMuTciyB681XP5WfcbB. The problem: the board paints a theme's accent colour only as a priority stripe, so the who-iris landing card, which has no priority, showed white with grey edges and no IRIS blue. **The owner chose the generic fix:** a thin accent band on ANY themed card without a priority, so every instance theme benefits. Not a who-iris special case. Implementation follows in its own PR.

## The band is built — 2026-09-30, branch `claude/magical-archimedes-4qkfxp-v8n5-band`

One rule in `docs-ui.css`: `.fa-sticky[data-fa-sticky-theme]:not([class*="fa-sticky-p-"])` gets a 3px `border-top` in `--fa-sticky-accent`, falling back to the edge colour. It keys on the theme ATTRIBUTE, so every instance theme gets it and no theme is named.

**Top edge, not left:** the left edge is the priority channel, and medium already paints the accent there. An accent left edge on a card with no priority would read as "medium".

Rendered in Chromium against the real `docs-ui.css` and `themes.css` (computed `border-top`):

| card | top border |
|---|---|
| `iris-sticky`, no priority (the who-iris landing card) | **3px rgb(0, 141, 201)**, the IRIS blue |
| `iris-sticky`, `fa-sticky-p-medium` | 1px edge: no band, and priority stays on the left |
| `iris-sticky`, `fa-sticky-p-critical` | 1px edge, red left stripe unchanged |
| `pale-sage`, no priority | 3px rgb(111, 140, 100), the sage accent |

**Not verified here:** the deployed who-iris landing page itself. The staging preview is the place to look.
