---
# folio-assistant-gm9g
title: 'render:bpmn:check on bootstrap/processes/*.svg — two generators, one artefact; FIXED by #1663, and my ''flap'' diagnosis retracted'
status: completed
type: bug
priority: high
created_at: 2026-09-30T18:57:39Z
updated_at: 2026-09-30T19:10:33Z
parent: folio-assistant-vke6
---

**A regression from `oqdr`'s fix**, which is `completed` and covered exactly
these three files from the opposite direction: *"rendered by nothing since the
split"*. They are now rendered by **two** generators that disagree.

## Measured

`End-to-end + accessibility (hard)` failed on PR #1664, at `render:bpmn:check`:

```
✗ bootstrap/processes/discussion.svg is stale
✗ bootstrap/processes/initialize-harness.svg is stale
✗ bootstrap/processes/log-message.svg is stale
```

**NOT MINE, and established rather than asserted:** zero `.bpmn`/`processes/`
files in that PR's diff, and a pristine `origin/main` worktree reports the
SAME three. Main is red on this.

## Regenerating "fixes" the check by DELETING the provenance banner

`bun run render:bpmn` produces a diff of **3 deletions, 0 insertions**:

```
-<!-- Generated by bootstrap-tools (scripts/render-bpmn.ts) from log-message.bpmn — do not edit; change log-message.bpmn. -->
```

That is the `sec-119` shape from #1637 one corpus over: a regeneration that
silently drops content is not a regeneration. Not committed.

## The actual defect: two generators, one artefact

| generator | writes the banner? | wired to |
|---|---|---|
| `bootstrap-tools/scripts/render-bpmn.ts:200` | **yes**, via `generatedNote(...)` | not the npm script |
| `cat-harness/scripts/render-bpmn.ts` | **no** | `render:bpmn`, `render:bpmn:check`, CI |

And the omission is DELIBERATE — `bootstrap-tools`' own comment says so:

> The note goes on THIS copy only — the one written into the content graph. A
> harness drawing its own site copy with `drawing()` is not bootstrap-tools
> writing into bootstrap, and must not say it is.

So `cat-harness`'s generator is correct to omit the banner **for its own site
copy**, and is judging a file it does not own. `oqdr` closed the "nobody renders
these" gap by widening the cat-harness scan to reach `bootstrap/`, which made
the owner ambiguous.

## Why this is NOT a one-line fix, and why I did not guess

Three readings, and they are not equivalent:

1. **bootstrap-tools owns `bootstrap/processes/*.svg`** → the cat-harness scan
   must EXCLUDE them, and something must run the bootstrap-tools renderer in CI.
   `oqdr`'s gap returns unless that second half lands.
2. **cat-harness owns them** → the banner is dropped from the committed files
   on purpose, and `generatedNote` at `render-bpmn.ts:200` is dead code for
   this path. A generated file then no longer says it is generated.
3. **Both write, to different destinations** → the content-graph copy keeps the
   banner and the site copy does not, which is what the comment describes, and
   the two must not share a path.

Getting it wrong either strips provenance from a generated artefact or leaves
two writers fighting over one file. That is an ownership ruling, not a repair,
and it belongs to whoever owns the split (`vke6`).

## Done when

- [ ] Which generator owns `bootstrap/processes/*.svg` is DECIDED and written
      down where both scripts' scan sets are computed.
- [ ] `render:bpmn:check` passes on `main` without any SVG losing its banner.
- [ ] `oqdr`'s gap stays closed — whatever renders them is RUN in CI, not
      merely able to be run.
- [ ] A test pins whichever way it goes, so the next widening of a scan set
      cannot silently re-create the overlap.

## NOT in this bean

Whether `generatedNote` should be used by more generators. This is about one
overlap, not about provenance banners in general.


## CORRECTION 2026-09-30 — the gate FLAPPED, and the title's "main is red" overclaims

The title and the account above present this as a deterministic failure. It is
not, and I do not have the mechanism. What is measured:

| head | `End-to-end` | note |
|---|---|---|
| `b937d71cb40` 18:52 | **red** at `render:bpmn:check`, naming exactly the three `bootstrap/processes/*.svg` | read from the CI log, not inferred |
| `7d28eb637da` 19:0x | **green**, whole job | same three files untouched between the two heads |

The only difference between those commits is a bean file and the
`beans/README.md` regenerated from it. Neither touches an `.svg`, a `.bpmn`, or
either generator. **So the gate flapped, and #1664 merged with every one of its
twelve checks green.**

Locally it fails CONSISTENTLY, and there the diff is banner-only — 3 deletions,
0 insertions, removing `<!-- Generated by bootstrap-tools ... do not edit -->`.
That part stands, and so does the two-generator overlap: `bootstrap-tools`
emits the banner at `render-bpmn.ts:200`, `cat-harness` deliberately does not,
and `cat-harness` is the one CI runs.

### What I checked and what I did NOT establish

Ruled out by reading the 18:52 log in full: that the CI failure named different
files than the local one. It named the same three.

**NOT established, and not to be read as established:**

- why it passed on the later head. A plausible story is available — that run
  installed fonts and downloaded a fresh Chromium seconds before the check, and
  bpmn-js lays out SVG text from font metrics — but the local diff is
  banner-only, which font metrics do not explain. Two incompatible stories, so
  neither is recorded as the cause.
- whether `main` is red on this NOW. The worktree reproduction was run in this
  container, which also fails consistently; that is evidence about this
  container, not about CI.

### This is the `1xhc` family, not only an ownership question

A gate whose verdict changes without its inputs changing is worse than one that
is simply wrong: it teaches readers to re-run rather than to look, and it made
me write a confident ownership story into a bean off one observation. The
ownership overlap is real and still worth settling — but **the flap has to be
characterised first**, or a fix will be judged by a gate that cannot tell
whether it worked.

### Done when — amended, flap first

- [ ] The flap is characterised: run `render:bpmn:check` on one unchanged
      commit repeatedly in CI and record the outcomes. A gate that flaps is
      not a gate.
- [ ] Whether the environment (fonts, Chromium version) changes the rendered
      SVG is MEASURED, not assumed — and if it does, the committed artefact
      cannot be compared byte-for-byte and the check needs a different
      comparison.
- [ ] Only then: which generator owns `bootstrap/processes/*.svg`.
- [ ] `oqdr`'s gap stays closed — whatever renders them is RUN in CI.


## RESOLVED 2026-09-30 — measured, and the "flap" is RETRACTED

The owner asked for the flap to be measured. It was not a flap. Three
experiments, cheapest first.

### B — the renderer is DETERMINISTIC locally

Two independent renders of all three SVGs, byte-compared: **identical**. So
local non-determinism is ruled out. (A first attempt at this was invalid — a
stale `.git/index.lock` blocked the restore so the second render never
happened, and `cmp` reported a missing file. Not read as a result.)

### C — the committed files are byte-identical to a fresh render

    discussion           IDENTICAL to committed
    initialize-harness   IDENTICAL to committed
    log-message          IDENTICAL to committed

And `render:bpmn:check` now exits **0**.

A first comparison here was also invalid: I stripped the banner from the
committed copy before comparing, on the assumption the render omitted it. The
render **includes** the banner, so the stripped comparison differed at line 2
for a reason I had created. Reading the two file headers side by side is what
caught it.

### A — why it was red at 18:52 and green at 19:00

    18:51:32  6c7acb528ac authored — "render-bpmn: delegate beside-source
              SVGs to bootstrap-tools' own writer"
    18:52:22  my b937d71cb40 CI ran render:bpmn:check   -> RED
    18:58:45  that fix MERGED TO MAIN as c431e64e611 (#1663)
    19:00:0x  my 7d28eb637da CI ran render:bpmn:check   -> GREEN

Neither of my heads CONTAINS `6c7acb528ac`. It did not have to: a
`pull_request` run tests the head **merged with main**, and main gained the fix
in the six minutes between my two runs. **The inputs changed. The gate did not
flap.**

### What each of my claims was worth

| claim | verdict |
|---|---|
| two generators, one artefact | **correct** — and #1663's fix is essentially reading 1: bootstrap-tools owns the beside-source SVGs, so the cat-harness writer delegates to it |
| `main` is red on this | **true at 18:52, false from 18:58:45** — stated without a time, which is what made it wrong |
| the gate flapped | **wrong, and retracted** — I reached for non-determinism rather than checking whether main had moved |
| a font/Chromium story explains the flip | **wrong** — recorded as unestablished at the time, which was the one thing I got right about it |

### The lesson, and it is the SAME mechanism that bit the other way

`code-quality-gates.yml`'s own `merge_group` comment says it: *a pull_request
run tests the PR merged with main AS IT WAS WHEN THE PR WAS PUSHED*. This
morning that made a green branch head produce a red merge commit (#1634, which
reddened `main`). This afternoon it made a red check go green with no change to
my branch.

**So a verdict that changes with no change to your branch is not evidence of
non-determinism — check whether the base moved FIRST.** That check is one
command and I did not run it before writing "flapped" into a bean.

## Closed on evidence rather than authorship

`render:bpmn:check` exits 0 on `main` at `75acd070efd` and the three SVGs are
byte-identical to a fresh render. The fix is `6c7acb528ac` in #1663, by another
session. Nothing here is left to do, so this closes rather than staying open as
a duplicate of work that landed.

`oqdr`'s gap stays closed by that fix's own design: the beside-source SVGs are
delegated to the writer that owns them rather than dropped.

## MERGE COLLISION 2026-09-30 — a sibling claimed this 3.5 hours after it was completed here

`origin/main` carried a claim this branch had to merge past, and it is preserved
verbatim rather than dropped:

> _2026-09-30T22:46:49Z_ — Claimed by claude/sharp-einstein-970n6g — pushed to main so sibling sessions see it before this branch has a PR (bean 35nj).

**The claim was made against main's stale copy of this bean.** On main the title
still read *"MAIN IS RED"* and the status still read `in-progress`, because the
completion above lives only on `claude/cool-fermi-htir5p` and that branch has
not merged. That is exactly `bean-coordination` §"A claim is branch-local": a
claim ANNOUNCES rather than reserves, and the corollary bites in both
directions — a completion that has not landed does not stop anyone either.

**Re-measured before resolving, rather than deferring or overruling on
authorship.** `bun run render:bpmn:check` on this branch exits **0**, and the
three `bootstrap/processes/*.svg` files this bean is about **do not appear in
its output at all** — the check no longer reaches them. #1663's fix held. Status
stays `completed` on that evidence, which is the rule
(`bean-coordination` §"Closing a bean whose work has already landed" —
**evidence, not authorship**).

**To `claude/sharp-einstein-970n6g`, if you are reading this:** the work is
done, and the measurement above is the whole of it — you do not need to
re-derive it. Leaving this `in-progress` to be polite would have sent you into
a dead end, which is the one thing bean status exists to prevent. If you have
found something the above misses, this bean is the place for it and the
retraction of my own "flap" diagnosis is already recorded here.

## Summary of Changes (2026-09-30, sharp-einstein) — appended
- Verified on `main` that `6c7acb5` settled ownership as ONE writer: `cat-harness/scripts/render-bpmn.ts` calls bootstrap-tools' own `besideSource()`. `render:bpmn:check` passes and `bootstrap/processes/*.svg` keep "Generated by bootstrap-tools"; the CI check runs the delegating renderer, so `oqdr`'s gap stays closed.
- PR #1717 adds `cat-harness/scripts/tests/render-bpmn-single-writer.test.ts`, the pin the last `## Done when` box asked for: the platform renderer imports `besideSource` and carries no `siblingLinks` copy, and every committed beside-source SVG keeps its provenance note.
