classDiagram
  direction TB
  namespace smart_immunizations__smart_immunizations_docs {
    class n_smart_immunizations_smart_immunizations_docs_docs["docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_immunizations_smart_immunizations_docs_docs" fa_uml_kind_docs
  cssClass "n_smart_immunizations_smart_immunizations_docs_docs" fa_uml_undetermined
