---
# folio-assistant-rbz3
title: 'Separation stage E rehearsal on litlfred/smart-trust: gates run with 23 platform files; directory name is the instance identity'
status: in-progress
type: task
priority: normal
created_at: 2026-10-02T07:57:50Z
updated_at: 2026-10-02T08:08:25Z
parent: folio-assistant-n3ni
---

Owner, 2026-10-02: *"use forks litlfred/smart-* as staging before we do it on WHO reps"*, then *"start smart-trust fork rehearsal"*.

Rehearsal branch `separation/stage-e-rehearsal` on litlfred/smart-trust, draft PR litlfred/smart-trust#3 (do not merge). It carries `smart-trust/` from folio-assistant `52a35ddf` unchanged, plus `REHEARSAL.md` and `PLATFORM-FILES.txt`.

## Measured
- **Pages:** `gen-ig-pages --instance smart-trust --check` **passes** in the fork: 2,158 pages byte-identical. It needs:
  - 23 platform files (11 cat-harness/schemas, 5 fhir-harness, 2 folio-assistant-core, 2 bootstrap-tools; bootstrap-tools is a separate repository);
  - the page templates;
  - smart-base's `smart-base.json` and `chrome.json`.

  A static import scan found only 20 of the 23. The other 3 load at run time, one of them a JSON code list read by URL.
- **Menu:** `ingest-ig-menu --source . --check` **passes** against the fork's own `sushi-config.yaml` (5 groups, 29 items). folio-assistant's CI cannot run this gate.
- **Rename:** with the directory renamed to `smart-base/`, as the plan's layout has it, **all 2,153 artefact pages change**. The URL prefix and the chrome lookup both key on the directory name.

## Done when
- [x] rehearsal branch pushed, with findings
- [x] the owner has decided between an instance id separate from the directory and keeping `<instance>/` as the data directory in each fork (**"2"**: the plan's `smart-base/` layout; the id comes from the declaration)
- [ ] the tools package's file list is generated by running the gates, not by a static scan
- [ ] Q4 (chrome with the harness) lands, so a fork builds its pages without smart-base's data

## Round 2 (2026-10-02): the owner chose "2", so data goes under `smart-base/` in every fork

Owner, verbatim: *"2"*, then *"do smart-base and smart-[trust]. also start moving their dir content over"*.

- **folio-assistant `853f9532`:**
  - `gen-ig-pages` takes the instance identity from the declaration's `name`, not from the directory.
  - `dakServed` and `ingest-ig-releases` find the declaration with `declarationPathIn`. They no longer compose `<directory>.json`.
  - Nothing changes in this repository: both page checks still pass.
- **litlfred/smart-trust#3, round 2 (`7ff6286`):**
  - Data moved `smart-trust/` → `smart-base/`, with the declaration still `smart-trust.json`.
  - `gen-ig-pages --instance smart-base --chrome-owner smart-trust --check` **passes**: 2,158 pages byte-identical.
  - `chrome.json` is copied in until Q4.
- **litlfred/smart-base#1, round 1 (`71106428`):**
  - `smart-base/` copied unchanged: 2,924 files, 51 MB.
  - The page check **passes**: 299 pages.
  - `menu.json` is ingested from the fork's own `sushi-config.yaml`: 4 groups.
- **Next:** move the smart-base harness definition to the repository root, per plan Q1(a). This waits on stage D (#1795).
