import type { TranslationNode } from "../../schemas/translation";

/**
 * Français (fr) translation of the knowledge-graph viewer's chrome.
 *
 * Generated by `bun run translate-kg-viewer --extract`. The source is the
 * string table in `scripts/kg-viewer-strings.ts`, not the page the generator emits —
 * see that module for why a generated artefact is never the translation
 * source.
 *
 * The graph's own content is NOT covered by this node: node names,
 * descriptions and property names come from the corpus and reach the page in
 * whatever language the corpus is written in.
 */
const node: TranslationNode = {
  label: "trans:fr/kg-viewer",
  locale: "fr",
  sourceFile: "scripts/kg-viewer-strings.ts",
  sourceHash: "a7ab6ebe9cf8",
  potFile: "translations/fr/kg-viewer.pot",
  poFile: "translations/fr/kg-viewer.po",
  status: {
    locale: "fr",
    official: false,
    generatedBy: "agent",
    generator: "folio-assistant translate-kg-viewer",
  },
  coverage: { translated: 38, total: 38, pct: 100 },
  title: "Français — knowledge-graph viewer interface",
  description:
    "Interface strings for the knowledge-graph viewer. Unofficial: produced " +
    "by an agent and not adjudicated by a person, which the page itself says " +
    "while this stays false.",
};
export default node;
