/**
 * The adjective is the requirement — bean `06e3` §4(b).
 *
 * @module scripts/tests/check-docs-populated
 *
 * The test that matters is the FALSIFIER: a page that is a title and a list
 * of links must come out `thin`. If it does not, the check is measuring file
 * size rather than documentation and is theatre.
 */
import { describe, expect, test } from "bun:test";
import { chmodSync, mkdirSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { assess, looksGenerated, proseWords } from "../check-docs-populated.ts";

// The planted directory is called `pages`, NOT `docs`, and that is the point
// twice over. `site-dir-single-answer` refuses a hardcoded site root in any
// source file and was right to fail the first draft of this file; and a
// harness's documentation directory is whatever its DECLARATION names, so a
// check that only worked for one called `docs` would be reading the name
// instead of the declaration.

const SENTENCE =
  "A process here is not a picture of a workflow drawn after the fact; the file is the source " +
  "of truth, the tools run it, and a diagram that disagreed with them would be a defect in the " +
  "diagram rather than in the tools. ";

/** Prose long enough to clear the threshold, without pretending to be a page. */
const LONG = SENTENCE.repeat(20);

describe("proseWords", () => {
  test("a line that is only a link contributes nothing", () => {
    // THE FALSIFIER, at the unit level. A page of links measures as a page of
    // links, or the whole check passes exactly what it exists to fail.
    const links = ["# Title", "", "- [One](one.html)", "- [Two](two.html)", "- [Three](three.html)"].join("\n");
    expect(proseWords(links, true)).toBeLessThan(5);
  });

  test("front matter, comments and code fences are not prose", () => {
    const md = ["---", "title: X", "nav_order: 3", "---", "", "<!-- a note -->", "", "```ts", "const x = 1;", "```", "", "Real words here."].join("\n");
    expect(proseWords(md, true)).toBe(3);
  });

  test("markup is stripped from html, and script and style with it", () => {
    const html = "<style>body{color:red}</style><script>var a=1;</script><p>Three real words</p>";
    expect(proseWords(html, false)).toBe(3);
  });
});

describe("looksGenerated — anchored, because both loose forms measured wrong", () => {
  test("prose ABOUT a generator is not a generated page", () => {
    // `docs/getting-started.md` says an SVG is generated by `render:bpmn`. A
    // substring search discards that authored page.
    expect(looksGenerated("the SVG is generated by `bun run render:bpmn`.")).toBe(false);
  });

  test("the viewers' own marker is recognised, on its own line", () => {
    expect(looksGenerated('var SCOPE = "beans";')).toBe(true);
    // ...and not when it is being quoted in prose about the marker.
    expect(looksGenerated('the pruner reads a var SCOPE = "x"; line from the page')).toBe(false);
  });

  test("the two whole phrases are recognised", () => {
    expect(looksGenerated("Generated by scripts/state-visualizer.ts. Do not hand-edit: ...")).toBe(true);
    expect(looksGenerated("Generated from `skills/folio-core/role-model.md` — do not edit here.")).toBe(true);
  });
});

describe("assess", () => {
  function harness(): string {
    return mkdtempSync(join(tmpdir(), "docs-pop-"));
  }

  test("a harness whose only page is a link list is THIN", () => {
    const repo = harness();
    mkdirSync(join(repo, "h", "pages"), { recursive: true });
    writeFileSync(
      join(repo, "h", "pages", "index.md"),
      ["---", "title: Home", "---", "# Home", "", "- [Processes](a/)", "- [Skills](b/)"].join("\n"),
    );
    const r = assess(repo, "h", ["h/pages"]);
    expect(r.verdict).toBe("thin");
    expect(r.detail).toContain("words of prose");
    rmSync(repo, { recursive: true });
  });

  test("a page that says something is POPULATED, and it is named as the evidence", () => {
    const repo = harness();
    mkdirSync(join(repo, "h", "pages"), { recursive: true });
    writeFileSync(join(repo, "h", "pages", "index.md"), `---\ntitle: Home\n---\n\n${LONG}`);
    const r = assess(repo, "h", ["h/pages"]);
    expect(r.verdict).toBe("populated");
    expect(r.best!.path).toBe("h/pages/index.md");
    rmSync(repo, { recursive: true });
  });

  test("a GENERATED page never carries a harness, however long it is", () => {
    // The false pass this check exists to stop: an index is not the
    // documentation, so a harness whose docs are all generated is thin.
    const repo = harness();
    mkdirSync(join(repo, "h", "pages"), { recursive: true });
    writeFileSync(join(repo, "h", "pages", "index.html"), `<p>${LONG}</p>\n<script>\nvar SCOPE = "h";\n</script>`);
    const r = assess(repo, "h", ["h/pages"]);
    expect(r.verdict).toBe("thin");
    expect(r.generated).toBe(1);
    expect(r.detail).toContain("an index is not the documentation");
    rmSync(repo, { recursive: true });
  });

  test("a declared directory that is not there is UNKNOWN, never thin", () => {
    // `dh4f`. Nobody can say whether the harness is documented, and saying
    // "thin" would be a conclusion nobody reached.
    const repo = harness();
    const r = assess(repo, "h", ["h/pages"]);
    expect(r.verdict).toBe("unknown");
    expect(r.detail).toContain("dh4f");
    rmSync(repo, { recursive: true });
  });

  test("an unreadable page is UNKNOWN, not a thin verdict", () => {
    const repo = harness();
    mkdirSync(join(repo, "h", "pages"), { recursive: true });
    writeFileSync(join(repo, "h", "pages", "index.md"), `---\ntitle: Home\n---\n\n${LONG}`);
    writeFileSync(join(repo, "h", "pages", "locked.md"), "x");
    chmodSync(join(repo, "h", "pages", "locked.md"), 0o000);
    const r = assess(repo, "h", ["h/pages"]);
    chmodSync(join(repo, "h", "pages", "locked.md"), 0o644);
    if (r.verdict === "populated") {
      // root, or a filesystem ignoring the mode. Say so rather than pass quietly.
      console.log("  n/a: the permission plant did not take (running as root?) — unknown path unexercised");
    } else {
      expect(r.verdict).toBe("unknown");
      expect(r.ambiguous).toBeGreaterThan(0);
    }
    rmSync(repo, { recursive: true });
  });

  test("dot-prefixed directories are not searched", () => {
    const repo = harness();
    mkdirSync(join(repo, "h", "pages", ".cache"), { recursive: true });
    writeFileSync(join(repo, "h", "pages", ".cache", "index.md"), `---\ntitle: X\n---\n\n${LONG}`);
    expect(assess(repo, "h", ["h/pages"]).verdict).toBe("thin");
    rmSync(repo, { recursive: true });
  });
});
