/**
 * The cross-reference audit, and in particular that its middle state fires.
 *
 * The first implementation scanned `AGENTS.md` line by line and reported zero
 * folio-attributed citations, because the one attribution in the live file
 * wraps across two lines. A three-state check whose middle state can never
 * fire is a two-state check with a longer description — so that case is the
 * first thing asserted here, on a fixture that wraps exactly as the real file
 * does.
 */
import { describe, expect, test } from "bun:test";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  SKILL_ROOTS,
  auditXrefs,
  folioAttributedSections,
  headingsOf,
  normalise,
} from "../check-agents-xref.js";
import { repoRootFor } from "../../schemas/cat-harness.js";

function repo(agentsMd: string, skills: Record<string, string>): string {
  // `root` IS the fixture's repository root, so `AGENTS.md` goes in it.
  //
  // A mechanical pass over `join(ROOT, "AGENTS.md")` call sites rewrote this
  // to `repoRootFor(root)` on 2026-09-19 — correct for the ~57 real call sites
  // it was drained for, wrong here, because a fixture's root has no enclosing
  // instance. It wrote `/tmp/AGENTS.md` while `auditXrefs` looked in the temp
  // directory, and three tests failed on a file the fixture had just written.
  //
  // The lesson is about the sweep rather than the line: `repoRootFor` means
  // "up from an INSTANCE root", and a variable named `root` is not always one.
  const root = mkdtempSync(join(tmpdir(), "xref-"));
  writeFileSync(join(root, "AGENTS.md"), agentsMd);
  for (const [rel, body] of Object.entries(skills)) {
    const p = join(root, "skills", rel);
    mkdirSync(join(p, ".."), { recursive: true });
    writeFileSync(p, body);
  }
  return root;
}

describe("heading and name matching", () => {
  test("headings are read at every level", () => {
    expect(headingsOf("# a\n## b\n#### d\ntext\n")).toEqual(["a", "b", "d"]);
  });

  test("a blockquoted heading is a heading", () => {
    // `> ## …` renders as a heading on GitHub and is as reachable as any
    // other, so a citation naming it is correct. This repo's own AGENTS.md
    // puts its two most-cited sections — the do-not-edit banner and Getting
    // skills — inside a blockquote, and both read as `unresolved`: the
    // verdict reserved for a section that is not there.
    expect(headingsOf("> ## quoted\n>### tight\n")).toEqual(["quoted", "tight"]);
    // Not at the cost of the ordinary case, and not swallowing prose that
    // merely starts with `#` mid-line.
    expect(headingsOf("# a\ntext # not a heading\n")).toEqual(["a"]);
  });

  test("this repo's own banner resolves, not just a fixture", () => {
    // The fixture above proves the regex; this proves the corpus. A fix
    // asserted only against a string of my own writing is a fix asserted
    // against nothing the gate actually reads.
    const agents = readFileSync(join(import.meta.dir, "../../../AGENTS.md"), "utf-8");
    const found = headingsOf(agents).map(normalise);
    expect(found).toContain(normalise("🛑 Do not edit this file to change how agents work"));
    expect(found).toContain(normalise("Getting skills"));
  });

  test("a cited name matches a heading that carries a gloss after it", () => {
    // Citations write the section's NAME; headings here nearly always append a
    // dash and an explanation. Exact matching would report almost everything
    // broken, which is a checker nobody runs twice.
    const md = "## Commit early, commit often, always PR (STRICT)\n";
    const found = auditXrefs(
      repo(md, { "s.md": 'See AGENTS.md §"Commit early, commit often".\n' }),
      SKILL_ROOTS,
    );
    expect(found.map((c) => c.verdict)).toEqual(["resolves"]);
  });

  test("normalise strips the formatting a citation and a heading disagree on", () => {
    expect(normalise('  `Foo` — “Bar”  ')).toBe("foo — bar");
  });
});

describe("the third state — a section this file hands to a folio", () => {
  // Verbatim shape of the live paragraph: the repository name ends one line and
  // the section reference begins the next.
  const WRAPPED = [
    "## Cross-references, so these do not drift",
    "",
    "`litlfred/qou`'s `AGENTS.md` carries the same first two rules for that folio —",
    '§"Branch + PR workflow" rule 0 (commit early / often / push) and rule 2.',
  ].join("\n");

  test("an attribution that WRAPS across lines is still found", () => {
    expect(folioAttributedSections(WRAPPED)).toContain("branch + pr workflow");
  });

  test("a citation of it is `folio`, not `unresolved`", () => {
    const found = auditXrefs(
      repo(WRAPPED, { "s.md": 'Operationalises AGENTS.md "Branch + PR workflow" rule 2.\n' }),
      SKILL_ROOTS,
    );
    expect(found.map((c) => c.verdict)).toEqual(["folio"]);
  });

  test("a section named in a paragraph with no folio in it is NOT attributed", () => {
    // Otherwise every `§` in the file would be waved through as somebody
    // else's, which is the silencing failure the audit exists to prevent.
    const md = '## Real\n\nSee §"Some Other Thing" for detail.\n';
    expect(folioAttributedSections(md).size).toBe(0);
  });
});

describe("unresolved", () => {
  test("a citation naming nothing here and nothing attributed is unresolved", () => {
    const found = auditXrefs(
      repo("## Real heading\n", { "s.md": 'Per AGENTS.md §"Critical-distance license".\n' }),
      SKILL_ROOTS,
    );
    expect(found).toEqual([
      { file: "skills/s.md", section: "Critical-distance license", verdict: "unresolved" },
    ]);
  });

  test("a bare mention of AGENTS.md naming no section is not a citation", () => {
    // The file is mentioned in 54 places and cited with a section in 20. Only
    // the latter can break when a section moves.
    const found = auditXrefs(
      repo("## Real\n", { "s.md": "AGENTS.md is the bootstrap pointer. Read it.\n" }),
      SKILL_ROOTS,
    );
    expect(found).toEqual([]);
  });

  test("a missing AGENTS.md throws rather than reporting a clean run", () => {
    // Could-not-check is never rendered as green; the CLI turns this into
    // exit 2, distinct from exit 1 for real findings.
    expect(() => auditXrefs(mkdtempSync(join(tmpdir(), "empty-")), SKILL_ROOTS)).toThrow();
  });
});

describe("the live corpus", () => {
  test("every one of this repo's citations gets a verdict, and none is unresolved", () => {
    // No floor on the COUNT — that was asserted as `> 10` and broke the moment
    // the backlog was cleared and the corpus fell to 8. Second instance of the
    // same mistake in one session; the note below is why there will not be a
    // third. What is asserted is the property CI actually gates on.
    // THE REPOSITORY root: `AGENTS.md` is a repository artefact, and
    // `"..", ".."` reaches this file's INSTANCE root since the move.
    // Note the contrast with `repo()` above, which passes a fixture root
    // PLAIN — three roots in one file, which is why a blunt sweep over
    // `join(x, "AGENTS.md")` got one of them wrong.
    const found = auditXrefs(repoRootFor(join(import.meta.dir, "..", "..")), SKILL_ROOTS);
    expect(found.filter((c) => !c.verdict)).toEqual([]);
    expect(found.filter((c) => c.verdict === "unresolved")).toEqual([]);
  });

  // WHAT THIS DELIBERATELY DOES NOT ASSERT, and why the first version was wrong.
  //
  // It required the live corpus to hold at least one `folio` and one `resolves`
  // citation, as a regression guard for the line-vs-paragraph scanning bug. It
  // failed within the hour — not because the detector broke, but because the
  // `1hsf` migration removed both: `todo-manager` stopped citing AGENTS.md for
  // its own rule, and `continual-progress` stopped naming a folio section.
  //
  // Both were improvements, and the test called them regressions. Pinning a
  // COVERAGE COUNT of the live corpus as a guard makes the corpus getting
  // better indistinguishable from the tool getting worse — the same mistake as
  // gating on `skill-in-role-or-process`, which this repo already declines to
  // make. The wrapping guard belongs on a fixture that pins the SHAPE, and it
  // is above: "an attribution that WRAPS across lines is still found".

});

describe("a citation may declare which AGENTS.md it means", () => {
  test("naming another repo makes it `folio` without this file attributing it", () => {
    // Declaration over inference. Before this, a correct citation of a folio's
    // section stayed `unresolved` unless the PLATFORM's prose happened to
    // mention it — so clearing the backlog would have meant restating a
    // folio's table of contents here.
    const found = auditXrefs(
      repo("## Real heading\n", {
        "s.md": 'Per `litlfred/qou` `AGENTS.md` §"CI billing failures", recognise it.\n',
      }),
      SKILL_ROOTS,
    );
    expect(found.map((c) => c.verdict)).toEqual(["folio"]);
  });

  test("naming THIS repo is still audited against this file's headings", () => {
    // Otherwise the escape hatch swallows the check: writing your own repo's
    // name would wave any citation through.
    const md = "# AGENTS.md — litlfred/folio-assistant\n\n## Real heading\n";
    const found = auditXrefs(
      repo(md, { "s.md": 'Per `litlfred/folio-assistant` `AGENTS.md` §"Nope".\n' }),
      SKILL_ROOTS,
    );
    expect(found.map((c) => c.verdict)).toEqual(["unresolved"]);
  });

  test("qualifying a citation moves it between states — it never leaves the census", () => {
    // The census bug, pinned. `AGENTS.md` followed by a closing backtick did
    // not match at all, so adding a qualifier made the citation VANISH and the
    // count fell from 8 to 1, reading as success.
    const md = "## Real heading\n";
    const bare = auditXrefs(repo(md, { "s.md": 'AGENTS.md §"Whatever".\n' }), SKILL_ROOTS);
    const qualified = auditXrefs(
      repo(md, { "s.md": 'Per `litlfred/qou` `AGENTS.md` §"Whatever".\n' }),
      SKILL_ROOTS,
    );
    expect(qualified.length).toBe(bare.length);
    expect(bare[0]!.verdict).toBe("unresolved");
    expect(qualified[0]!.verdict).toBe("folio");
  });
});
