/**
 * The merge guard, against the three PRs it exists because of.
 *
 * @module scripts/tests/merge-guard
 *
 * Bean `uoob` (merge gate (f), epic `nok9`). Each fixture under `fixtures/merge-guard/` is a real PR as it
 * stood at the instant the Merge Manager merged it — comments, timeline events
 * and workflow runs created before that instant, labels replayed from the
 * timeline — captured by `fetchSnapshot` itself and trimmed to what
 * `evaluate` reads. So every refusal below is one the guard would have made
 * on the day, not one constructed to pass.
 *
 * One test per refusal reason. Where a real case trips several checks, the
 * test names the check it is about and asserts that check's status; the
 * variants that isolate one reason (a signed marker, a re-timed question) say
 * what they changed from the real record and why.
 *
 * The tests here that read the aggregate repository's own root
 * (`feature-staging.yml`, `merge-main.yml`) live in
 * `cat-harness-tools/scripts/tests/merge-guard-workflows.test.ts` (bean
 * `ho66`): standing alone, cat-harness has no such root to read.
 */
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  CannotAsk,
  evaluate,
  fetchPull,
  getAll,
  isBotMerge,
  openQuestions,
  readyMarkers,
  sameRepoNext,
  signingSession,
  untickedItems,
  SELF_WORKFLOW_FILE,
  NOT_WAITED_FOR_WORKFLOW_FILES,
  DEPLOY_ONLY_STEP,
  type CheckId,
  type GuardOptions,
  type GuardRun,
  type GuardSnapshot,
} from "../merge-guard.js";
import type { TriggerScan } from "../../src/core/workflow-events.js";

const FIXTURES = join(import.meta.dir, "fixtures", "merge-guard");

/**
 * The owed set, fixed for the fixtures rather than read from today's
 * `.github/workflows/`, which will drift. Code-quality gates is the one
 * required unconditionally on `pull_request`; the guard's own workflow is
 * present so the test proves it is excluded.
 */
const SCAN: TriggerScan = {
  triggers: [
    { file: ".github/workflows/code-quality-gates.yml", name: "Code-quality gates", requirement: "required", filters: [] },
    { file: ".github/workflows/jsonld-gen-check.yml", name: "JSON-LD generated-file drift", requirement: "conditional", filters: ["paths"] },
    { file: ".github/workflows/feature-staging.yml", name: "Feature Staging (GitHub Pages)", requirement: "conditional", filters: ["paths"] },
    { file: SELF_WORKFLOW_FILE, name: "Merge guard", requirement: "conditional", filters: ["types"] },
  ],
  unreadable: [],
};

/** What today's `merge-main.yml` dispatches, fixed here for the reason {@link SCAN} is. */
const DISPATCHED = ["code-quality-gates.yml", "jsonld-gen-check.yml"] as const;

/**
 * A fresh, mutable copy of a real PR's snapshot.
 *
 * `mergeable: true` is supplied here, not in the fixture: the fixtures were
 * trimmed to what `evaluate` read before check 8 (bean `vihx`) existed, and
 * they are captures, so a field is not written into them after the fact. The
 * value is not invented either. All three PRs DID merge, and GitHub refuses
 * the merge PUT of a conflicting head (HTTP 405), so each one was mergeable
 * at the instant captured. Check 8's own tests set the field explicitly.
 */
function real(n: 1937 | 1957 | 1960): GuardSnapshot {
  const fx = JSON.parse(readFileSync(join(FIXTURES, `pr-${n}.json`), "utf8")) as { snapshot: Omit<GuardSnapshot, "scan"> };
  const s: GuardSnapshot = { ...structuredClone(fx.snapshot), scan: SCAN, mergeMainDispatches: [...DISPATCHED] };
  s.pr.mergeable ??= true;
  return s;
}

const status = (s: GuardSnapshot, id: CheckId, o: GuardOptions = {}) => evaluate(s, o).checks.find((c) => c.id === id)!;

const STEWARD = "session_01StewardStewardSteward";

/** A comment signed by `session`, `at` an instant, saying `text`. */
function signed(id: number, at: string, session: string, text: string) {
  return {
    id,
    created_at: at,
    user: { login: "litlfred" },
    html_url: `https://github.com/litlfred/folio-assistant/pull/0#issuecomment-${id}`,
    body: `${text}\n\n---\n_Generated by [Claude Code](https://claude.ai/code/${session})_`,
  };
}

/** Shift an ISO instant by `ms`. */
const shift = (iso: string, ms: number) => new Date(Date.parse(iso) + ms).toISOString().replace(/\.000Z$/, "Z");

describe("the three real cases are refused — exit 1, never 0", () => {
  for (const n of [1937, 1957, 1960] as const) {
    test(`#${n}`, () => {
      const v = evaluate(real(n));
      expect(v.verdict).toBe("refused");
      expect(v.exitCode).toBe(1);
    });
  }
});

describe("check 1 — base", () => {
  test("#1937: base was #1764's head branch after #1764 merged, not main", () => {
    const c = status(real(1937), "base");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("not `main`");
    expect(c.detail).toContain("#1764");
  });

  test("a base that is a merged PR's head is refused even if it were named main", () => {
    const s = real(1957);
    s.baseMergedAsHeadOf = [1];
    expect(status(s, "base").status).toBe("refuse");
  });

  test("could not ask about the base is unknown, not a pass", () => {
    const s = real(1957);
    s.baseMergedAsHeadOf = { unknown: "HTTP 502" };
    expect(status(s, "base").status).toBe("unknown");
  });
});

describe("check 2 — ready for review", () => {
  test("a draft is refused", () => {
    const s = real(1960);
    s.pr.draft = true;
    expect(status(s, "ready-for-review").status).toBe("refuse");
  });

  test("#1957: marked ready with nothing from its own session beside it — the steward did it", () => {
    const c = status(real(1957), "ready-for-review");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("cannot be attributed to the PR's own session");
  });

  test("#1957 with the steward's signed comment beside the event: refused as the MERGING session", () => {
    const s = real(1957);
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(1, shift(ev.created_at!, 60_000), STEWARD, "Marking ready and labelling."));
    const c = status(s, "ready-for-review", { mergingSession: STEWARD });
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("MERGING session");
  });

  test("marked ready beside the PR's OWN signed ready marker passes", () => {
    const s = real(1957);
    const own = signingSession(s.pr.body)!;
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(2, shift(ev.created_at!, 4_000), own, `ready: ${s.pr.head.sha.slice(0, 11)}`));
    expect(status(s, "ready-for-review", { mergingSession: STEWARD }).status).toBe("pass");
  });

  test("never a draft: nothing to attribute, passes", () => {
    expect(status(real(1960), "ready-for-review").status).toBe("pass");
  });
});

describe("check 3 — the ready marker", () => {
  test("#1960 and #1957: no `ready:` comment at all", () => {
    for (const n of [1960, 1957] as const) {
      const c = status(real(n), "ready-marker");
      expect(c.status).toBe("refuse");
      expect(c.detail).toBe("no `ready: <sha>` comment");
    }
  });

  test("#1937: its `ready: e75895610c4` is signed by no session", () => {
    const s = real(1937);
    expect(readyMarkers(s.comments).map((m) => [m.sha, m.session])).toEqual([["e75895610c4", undefined]]);
    const c = status(s, "ready-marker");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("signed by no session");
  });

  test("#1937 with the marker signed: still refused, the head is newer and the commits after it are not bot merges", () => {
    const s = real(1937);
    const own = signingSession(s.pr.body)!;
    const m = s.comments.find((c) => c.body.startsWith("ready: e75895610c4"))!;
    m.body += `\n\nhttps://claude.ai/code/${own}`;
    const c = status(s, "ready-marker");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("not merge-main bot merges");
    // The hand merge of #1764 and the two claim-bean commits; the bot's merge is not listed.
    expect(c.detail).toContain("1aaa669f99");
    expect(c.detail).toContain("c4036a79af");
    expect(c.detail).not.toContain("`ee4151d2cc` by");
  });

  test("a head newer than the marker ONLY by merge-main bot merges passes", () => {
    const s = real(1937);
    const own = signingSession(s.pr.body)!;
    s.comments.find((c) => c.body.startsWith("ready: e75895610c4"))!.body += `\n\nhttps://claude.ai/code/${own}`;
    const i = s.commits.findIndex((c) => c.sha.startsWith("e75895610c4"));
    // Keep the ready commit and the bot's merge; drop the three foreign commits between.
    s.commits = [...s.commits.slice(0, i + 1), s.commits.at(-1)!];
    expect(isBotMerge(s.commits.at(-1)!, [])).toBe(true);
    expect(status(s, "ready-marker").status).toBe("pass");
  });

  test("a marker signed by another session is not this PR's marker", () => {
    const s = real(1960);
    s.comments.push(signed(3, "2026-10-03T10:30:00Z", STEWARD, `ready: ${s.pr.head.sha}`));
    const c = status(s, "ready-marker");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain(STEWARD);
  });

  test("a quoted marker is not a marker", () => {
    expect(readyMarkers([signed(4, "2026-10-03T10:30:00Z", STEWARD, "> ready: abcdef1")])).toEqual([]);
  });
});

describe("check 4 — labels", () => {
  test("#1937: `needs-merge-human` was still on it", () => {
    const c = status(real(1937), "labels");
    expect(c.status).toBe("refuse");
    expect(c.detail).toBe("`needs-merge-human` is present");
  });

  test("#1960: no `ready-to-merge`", () => {
    const c = status(real(1960), "labels");
    expect(c.status).toBe("refuse");
    expect(c.detail).toBe("`ready-to-merge` is absent");
  });
});

describe("check 5 — the head's own pull_request CI", () => {
  test("#1937: its pull_request runs failed; the green dispatches are named and NOT counted", () => {
    const c = status(real(1937), "ci");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("Code-quality gates: failure");
    expect(c.detail).toContain("2 green `workflow_dispatch` run(s)");
  });

  test("an in-flight run is not green", () => {
    const s = real(1957);
    if (s.runs.state !== "has-run") throw new Error("fixture");
    s.runs.runs.find((r) => r.name === "Code-quality gates" && r.event === "pull_request")!.status = "in_progress";
    expect(status(s, "ci").status).toBe("refuse");
  });

  test("the guard's own run is never evidence, either way", () => {
    const s = real(1957);
    if (s.runs.state !== "has-run") throw new Error("fixture");
    const own: GuardRun = { id: 99_999_999_999, name: "Merge guard", event: "pull_request", status: "completed", conclusion: "failure", html_url: "" };
    s.runs.runs.push(own);
    expect(status(s, "ci").status).toBe("pass");
  });

  test("a later success supersedes an earlier failure of the same workflow", () => {
    const s = real(1937);
    if (s.runs.state !== "has-run") throw new Error("fixture");
    for (const r of [...(s.runs.runs as GuardRun[])]) {
      if (r.event === "pull_request") {
        const rerun: GuardRun = { ...r, id: (r.id ?? 0) + 1_000_000, conclusion: "success" };
        s.runs.runs.push(rerun);
      }
    }
    expect(status(s, "ci").status).toBe("pass");
  });

  test("could not read the runs is unknown — and unknown outranks every refusal: exit 2", () => {
    const s = real(1937);
    s.runs = { state: "cannot-ask", reason: "HTTP 502" };
    const v = evaluate(s);
    expect(v.checks.find((c) => c.id === "ci")!.status).toBe("unknown");
    expect(v.verdict).toBe("unknown");
    expect(v.exitCode).toBe(2);
  });
});

/**
 * A bot-merged head: merge-main pushed it with the bot token, so GitHub held
 * every `pull_request` run at `action_required` (bean `0qjq`), and merge-main
 * dispatched the two gating workflows on the branch. #1937's head IS such a
 * merge (`ee4151d2cc`, authored by the bot), so its record is the base; its
 * `pull_request` runs are re-cast as held, which is what they are today.
 */
describe("check 5 — a held run on a bot-merged head is judged by its dispatch", () => {
  const botHead = (dispatch: Record<string, Partial<GuardRun> | null> = {}) => {
    const s = real(1937);
    if (s.runs.state !== "has-run") throw new Error("fixture");
    for (const r of s.runs.runs) if (r.event === "pull_request") r.conclusion = "action_required";
    s.runs.runs = s.runs.runs.flatMap((r) => {
      if (r.event !== "workflow_dispatch") return [r];
      const patch = dispatch[r.name];
      return patch === null ? [] : [{ ...r, ...patch }];
    });
    return s;
  };

  test("every pull_request run held, green dispatches of both gating workflows — passes; staging is not judged", () => {
    const c = status(botHead(), "ci");
    expect(c.status).toBe("pass");
    expect(c.detail).toContain("judged by its green `workflow_dispatch` run: Code-quality gates, JSON-LD generated-file drift");
    expect(c.detail).toContain("not judged (preview-only, not dispatched by merge-main): Feature Staging (GitHub Pages)");
  });

  test("Feature Staging held and never dispatched does not refuse — it is not one merge-main dispatches", () => {
    const s = botHead();
    if (s.runs.state !== "has-run") throw new Error("fixture");
    expect(s.runs.runs.some((r) => r.name === "Feature Staging (GitHub Pages)" && r.event === "workflow_dispatch")).toBe(false);
    expect(status(s, "ci").status).toBe("pass");
  });

  test("a dispatch still in progress is not-ready", () => {
    const c = status(botHead({ "Code-quality gates": { status: "in_progress", conclusion: null } }), "ci");
    expect([c.status, c.kind]).toEqual(["refuse", "not-ready"]);
    expect(c.detail).toContain("Code-quality gates: action_required; its `workflow_dispatch` stand-in (run 37114602513) is in_progress");
  });

  test("a red dispatch is a defect", () => {
    const c = status(botHead({ "JSON-LD generated-file drift": { conclusion: "failure" } }), "ci");
    expect([c.status, c.kind]).toEqual(["refuse", "defect"]);
    expect(c.detail).toContain("is failure");
  });

  test("no dispatch yet for code-quality-gates is not-ready: merge-main still owes it", () => {
    const c = status(botHead({ "Code-quality gates": null }), "ci");
    expect([c.status, c.kind]).toEqual(["refuse", "not-ready"]);
    expect(c.detail).toContain("the `workflow_dispatch` merge-main owes for `code-quality-gates.yml` has not appeared");
  });

  test("merge-main.yml unparseable is unknown — never a pass", () => {
    const s = botHead({ "Code-quality gates": null });
    s.mergeMainDispatches = { unknown: "no `for wf in … ; do gh workflow run` line" };
    const v = evaluate(s);
    expect(v.checks.find((c) => c.id === "ci")!.status).toBe("unknown");
    expect(v.exitCode).toBe(2);
    // The held preview-only workflow needs the set too: unknown even with both gates dispatched.
    const t = botHead();
    t.mergeMainDispatches = { unknown: "unparseable" };
    expect(status(t, "ci").status).toBe("unknown");
  });

  test("a held run on a head that is NOT a bot merge gets no stand-in", () => {
    const s = botHead();
    // An ordinary commit: one parent, so neither its author nor a bot comment makes it a bot merge.
    s.commits.at(-1)!.parents = s.commits.at(-1)!.parents.slice(0, 1);
    const c = status(s, "ci");
    expect([c.status, c.kind]).toEqual(["refuse", "not-ready"]);
    expect(c.detail).toContain("not a merge-main bot merge");
  });

  test("an ordinary head whose pull_request runs executed is unchanged: a green dispatch never rescues a red run", () => {
    // #1937 as recorded: the bot-merged head's pull_request runs EXECUTED and failed.
    const c = status(real(1937), "ci");
    expect([c.status, c.kind]).toEqual(["refuse", "defect"]);
    expect(c.detail).toContain("Code-quality gates: failure");
    expect(c.detail).not.toContain("judged by its green");
    expect(status(real(1957), "ci").status).toBe("pass");
  });
});

describe("check 6 — the body's checklist", () => {
  test("#1960: `- [ ] CI green` was unticked", () => {
    const c = status(real(1960), "checklist");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("- [ ] CI green");
    expect(untickedItems(real(1960).pr.body)).toEqual(["- [ ] CI green"]);
  });

  test("an unticked box inside a code fence is a template, not an item", () => {
    expect(untickedItems("```\n- [ ] example\n```\n- [x] done")).toEqual([]);
  });
});

describe("check 7 — an open question after the ready marker", () => {
  /**
   * #1937's real question — "**Should I delete the `_external` copy?** Until
   * someone answers…" — was asked BEFORE its marker, so on the day it was
   * answered. Re-timed to after a signed marker it is exactly the case
   * check 7 is for, and it names nobody: it is caught because it asks for a
   * decision.
   */
  test("#1937's own question, re-timed after the marker, is caught", () => {
    const s = real(1937);
    const own = signingSession(s.pr.body)!;
    const marker = s.comments.find((c) => c.body.startsWith("ready: e75895610c4"))!;
    marker.body += `\n\nhttps://claude.ai/code/${own}`;
    const q = s.comments.find((c) => c.body.includes("Should I delete the `_external` copy?"))!;
    q.created_at = shift(marker.created_at, 60_000);
    const c = status(s, "open-question");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("Should I delete the `_external` copy?");
  });

  test("before the marker it is not open", () => {
    const s = real(1937);
    s.comments.find((c) => c.body.startsWith("ready: e75895610c4"))!.body += `\n\nhttps://claude.ai/code/${signingSession(s.pr.body)!}`;
    expect(status(s, "open-question").status).toBe("pass");
  });

  test("a question naming nobody and asking no decision is a documented miss", () => {
    expect(openQuestions([signed(5, "2026-10-03T12:00:00Z", STEWARD, "Is this the right file?")], "2026-10-03T11:00:00Z", "litlfred")).toEqual([]);
  });

  test("a `?` inside a URL is not a question", () => {
    const qs = openQuestions(
      [signed(6, "2026-10-03T12:00:00Z", STEWARD, "Owner: see https://example.org/x?y=1 for the run.")],
      "2026-10-03T11:00:00Z",
      "litlfred",
    );
    expect(qs).toEqual([]);
  });
});

describe("every check passes only when every fact is in hand", () => {
  test("#1957 as it SHOULD have been: own session marks ready and signs `ready:`, label on, CI green — exit 0", () => {
    const s = real(1957);
    const own = signingSession(s.pr.body)!;
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(7, shift(ev.created_at!, 4_000), own, `ready: ${s.pr.head.sha.slice(0, 11)}. Every check is green.`));
    const v = evaluate(s, { mergingSession: STEWARD });
    expect(v.checks.map((c) => [c.id, c.status])).toEqual([
      ["base", "pass"],
      ["ready-for-review", "pass"],
      ["ready-marker", "pass"],
      ["labels", "pass"],
      ["ci", "pass"],
      ["checklist", "pass"],
      ["open-question", "pass"],
      ["mergeable", "pass"],
    ]);
    expect(v.exitCode).toBe(0);
  });

  test("and the same PR is refused when the MERGING session is the one that signed the marker beside the event", () => {
    const s = real(1957);
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(8, shift(ev.created_at!, 4_000), STEWARD, `ready: ${s.pr.head.sha.slice(0, 11)}`));
    expect(evaluate(s, { mergingSession: STEWARD }).exitCode).toBe(1);
  });
});

/**
 * The status STATE: `pending` for a PR that is merely unfinished, `failure`
 * only for a defect. Coordinator, 2026-10-03: the status is posted on every
 * open PR, and red on every draft trains people to ignore red. Both states
 * still refuse (exit 1), so this changes what a reader sees, never what may
 * merge.
 */
describe("the commit-status state: pending for unfinished, failure for a defect", () => {
  test("#1960 was only unfinished — no marker, no label, an unticked box — so `pending`, exit 1", () => {
    const v = evaluate(real(1960));
    expect(v.checks.filter((c) => c.status === "refuse").map((c) => [c.id, c.kind])).toEqual([
      ["ready-marker", "not-ready"],
      ["labels", "not-ready"],
      ["checklist", "not-ready"],
    ]);
    expect([v.state, v.exitCode]).toEqual(["pending", 1]);
  });

  test("#1937 had defects — a dead base, needs-merge-human, red CI — so `failure`", () => {
    const v = evaluate(real(1937));
    const kinds = Object.fromEntries(v.checks.filter((c) => c.kind).map((c) => [c.id, c.kind]));
    expect(kinds.base).toBe("defect");
    expect(kinds.labels).toBe("defect");
    expect(kinds.ci).toBe("defect");
    expect(v.state).toBe("failure");
  });

  test("a draft alone is `pending`", () => {
    const s = real(1960);
    s.pr.draft = true;
    expect(status(s, "ready-for-review").kind).toBe("not-ready");
  });

  test("CI still running is `not-ready`; the same run failed is a `defect`; a run that never executed is `not-ready`", () => {
    const at = (conclusion: string | null, st: string) => {
      const s = real(1957);
      if (s.runs.state !== "has-run") throw new Error("fixture");
      const r = s.runs.runs.find((x) => x.name === "Code-quality gates" && x.event === "pull_request")!;
      r.status = st;
      r.conclusion = conclusion;
      return status(s, "ci").kind;
    };
    expect(at(null, "in_progress")).toBe("not-ready");
    expect(at("failure", "completed")).toBe("defect");
    expect(at("action_required", "completed")).toBe("not-ready");
  });

  test("a marker signed by ANOTHER session is a defect; an unsigned one is merely not ready", () => {
    expect(status(real(1937), "ready-marker").kind).toBe("not-ready");
    const s = real(1960);
    s.comments.push(signed(9, "2026-10-03T10:30:00Z", STEWARD, `ready: ${s.pr.head.sha}`));
    expect(status(s, "ready-marker").kind).toBe("defect");
  });

  test("the merging session beside the ready flip is a defect", () => {
    const s = real(1957);
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(10, shift(ev.created_at!, 60_000), STEWARD, "Marking ready."));
    expect(status(s, "ready-for-review", { mergingSession: STEWARD }).kind).toBe("defect");
  });

  test("pass is `success`, unknown is `error`", () => {
    const s = real(1957);
    const own = signingSession(s.pr.body)!;
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(11, shift(ev.created_at!, 4_000), own, `ready: ${s.pr.head.sha.slice(0, 11)}`));
    expect(evaluate(s).state).toBe("success");
    s.runs = { state: "cannot-ask", reason: "HTTP 502" };
    expect(evaluate(s).state).toBe("error");
  });
});

/**
 * Paging (issue #2137). GitHub's `Link: rel="next"` names the numeric
 * `/repositories/<id>/…` form, which the agent proxy refuses with a 403, so a
 * PR with more than 100 commits or timeline events was COULD NOT DETERMINE
 * from every agent session. The walk now follows the `repos/{owner}/{repo}/…`
 * form; a page that still cannot be read still throws {@link CannotAsk},
 * which `main` reports as COULD NOT DETERMINE (exit 2).
 */
describe("paging — page 2 is asked in the repos/{owner}/{repo} form", () => {
  const API = "https://api.github.com";
  const START = "repos/litlfred/folio-assistant/pulls/1955/commits?per_page=100";
  const NUMERIC_NEXT = `${API}/repositories/1189760173/pulls/1955/commits?per_page=100&page=2`;
  const NAMED_NEXT = `${API}/repos/litlfred/folio-assistant/pulls/1955/commits?per_page=100&page=2`;

  /** A fetch that serves `pages` by URL and records what it was asked; any other URL gets the proxy's 403. */
  function fakeFetch(pages: Record<string, { body: unknown; next?: string }>): { fetch: typeof fetch; asked: string[] } {
    const asked: string[] = [];
    const impl = async (input: string | URL | Request): Promise<Response> => {
      const url = String(input);
      asked.push(url);
      const page = pages[url];
      if (!page) {
        return new Response(
          JSON.stringify({ message: "Numeric-ID repository paths (repositories/{id}/...) are not supported through this proxy." }),
          { status: 403, headers: { "content-type": "application/json" } },
        );
      }
      const headers: Record<string, string> = { "content-type": "application/json" };
      if (page.next) headers.link = `<${page.next}>; rel="next", <${page.next}>; rel="last"`;
      return new Response(JSON.stringify(page.body), { status: 200, headers });
    };
    return { fetch: impl as unknown as typeof fetch, asked };
  }

  test("sameRepoNext rewrites the numeric form to the walk's own repos/{owner}/{repo} prefix", () => {
    expect(sameRepoNext(NUMERIC_NEXT, START)).toBe(NAMED_NEXT);
    expect(sameRepoNext(NUMERIC_NEXT, `${API}/${START}`)).toBe(NAMED_NEXT);
  });

  test("sameRepoNext leaves a next it cannot place unchanged", () => {
    expect(sameRepoNext(NAMED_NEXT, START)).toBe(NAMED_NEXT);
    expect(sameRepoNext(NUMERIC_NEXT, "user/repos?per_page=100")).toBe(NUMERIC_NEXT);
  });

  test("a two-page list is read whole, with page 2 asked by name and never by numeric id", async () => {
    const { fetch, asked } = fakeFetch({
      [`${API}/${START}`]: { body: [{ sha: "a" }, { sha: "b" }], next: NUMERIC_NEXT },
      [NAMED_NEXT]: { body: [{ sha: "c" }] },
    });
    const got = await getAll<{ sha: string }>(START, fetch);
    expect(got.map((c) => c.sha)).toEqual(["a", "b", "c"]);
    expect(asked).toEqual([`${API}/${START}`, NAMED_NEXT]);
    expect(asked.some((u) => u.includes("/repositories/"))).toBe(false);
  });

  test("a page 2 that cannot be read is CannotAsk (could-not-determine), never a short list", async () => {
    // page 2 deliberately absent: the fake answers it with the proxy's 403
    const { fetch } = fakeFetch({ [`${API}/${START}`]: { body: [{ sha: "a" }], next: NUMERIC_NEXT } });
    const err = await getAll(START, fetch).then(
      () => undefined,
      (e: unknown) => e,
    );
    expect(err).toBeInstanceOf(CannotAsk);
    expect((err as Error).message).toContain(`GET ${NAMED_NEXT}: HTTP 403`);
    expect((err as Error).message).toContain("not supported through this proxy");
  });
});

/**
 * Bean `gnnj`, owner ruling 2026-10-05: check 5 JUDGES Feature Staging once it
 * finishes but never WAITS for it. Its deploy is held by the #1956 rate limit —
 * measured up to 41 min that day — and every PR in the merge queue inherited it.
 */
describe("check 5 — Feature Staging is judged once finished, never waited for", () => {
  const STAGING = "Feature Staging (GitHub Pages)";
  /** #1937's head with every `pull_request` run green, then `patch` applied to staging's. */
  const green = (patch?: Partial<GuardRun> | null) => {
    const s = real(1937);
    if (s.runs.state !== "has-run") throw new Error("fixture");
    for (const r of s.runs.runs) if (r.event === "pull_request") r.conclusion = "success";
    s.runs.runs = s.runs.runs.flatMap((r) => {
      if (r.name !== STAGING || patch === undefined) return [r];
      return patch === null ? [] : [{ ...r, ...patch }];
    });
    return s;
  };

  test("the scan maps the exempt FILE to the run name check 5 sees", () => {
    expect(NOT_WAITED_FOR_WORKFLOW_FILES.has(".github/workflows/feature-staging.yml")).toBe(true);
    expect(SCAN.triggers.find((t) => NOT_WAITED_FOR_WORKFLOW_FILES.has(t.file))?.name).toBe(STAGING);
  });

  test("every run green: passes, as before", () => {
    expect(status(green(), "ci").status).toBe("pass");
  });

  test("staging still IN PROGRESS (waiting out the #1956 window): passes, and says it did not wait", () => {
    const c = status(green({ status: "in_progress", conclusion: null }), "ci");
    expect(c.status).toBe("pass");
    expect(c.detail).toContain(`not waited for (judged only once finished, bean \`gnnj\`): ${STAGING} (in_progress)`);
    expect(c.detail).toContain("2 `pull_request` workflow(s) on the head");
  });

  test("staging QUEUED: passes", () => {
    expect(status(green({ status: "queued", conclusion: null }), "ci").status).toBe("pass");
  });

  test("staging has no run on the head at all: passes", () => {
    expect(status(green(null), "ci").status).toBe("pass");
  });

  test("staging FINISHED red: still refused — the exemption is from waiting, never from judging", () => {
    const c = status(green({ status: "completed", conclusion: "failure" }), "ci");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain(`${STAGING}: failure`);
  });

  /** Staging finished red, with `steps` as the failed steps of its run (or `undefined` = not fetched). */
  const redWith = (steps: string[] | { unknown: string } | undefined) => {
    const s = green({ status: "completed", conclusion: "failure" });
    if (s.runs.state !== "has-run") throw new Error("fixture");
    const run = s.runs.runs.find((r) => r.name === STAGING && r.event === "pull_request") as GuardRun;
    if (steps !== undefined) s.failedSteps = { [run.id!]: steps };
    return s;
  };

  test("staging red ONLY in the deploy step (push window never opened): passes, and says so", () => {
    const c = status(redWith([DEPLOY_ONLY_STEP]), "ci");
    expect(c.status).toBe("pass");
    expect(c.detail).toContain(`${STAGING} (failure in the deploy step only)`);
  });

  test("staging red in a build step as well as the deploy: still refused", () => {
    const c = status(redWith(["Build the site", DEPLOY_ONLY_STEP]), "ci");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain(`${STAGING}: failure`);
  });

  test("staging red, failed steps could not be read: still refused", () => {
    expect(status(redWith({ unknown: "HTTP 403" }), "ci").status).toBe("refuse");
    expect(status(redWith(undefined), "ci").status).toBe("refuse");
    expect(status(redWith([]), "ci").status).toBe("refuse");
  });

  test("control: a gating workflow in progress is still waited for", () => {
    const s = green();
    if (s.runs.state !== "has-run") throw new Error("fixture");
    const gates = s.runs.runs.find((r) => r.name === "Code-quality gates" && r.event === "pull_request")!;
    gates.status = "in_progress";
    gates.conclusion = null;
    const c = status(s, "ci");
    expect(c.status).toBe("refuse");
    expect(c.detail).toContain("Code-quality gates: in_progress");
  });
});

/**
 * Check 8, bean `vihx`. Check 5 judges the head's `pull_request` runs, which
 * tested the head merged with main AS MAIN WAS when it was pushed. #1898 was
 * signed, green and labelled, passed checks 1-7, and conflicted with main by
 * the time it was merged; twice on 2026-10-05 GitHub refused a guard-passed
 * merge with HTTP 405 "merge conflicts". #1898 has merged since, and on a
 * merged PR the PR API's mergeability is stale, serving the pre-merge view
 * (bean `fx5r`); it now reads `null` / `unknown`. So its conflicting state is
 * rebuilt here as the PR API reports any conflicting OPEN head, the one
 * reading check 8 trusts — only `dirty`: `mergeable: false`, `mergeable_state: "dirty"`.
 */
describe("check 8 — the head still merges cleanly into main", () => {
  /** #1957 as it should have been (checks 1-7 pass), with the PR API's mergeability set. */
  const passingOtherwise = (mergeable: boolean | null | undefined, state?: string) => {
    const s = real(1957);
    const own = signingSession(s.pr.body)!;
    const ev = s.timeline.find((e) => e.event === "ready_for_review")!;
    s.comments.push(signed(12, shift(ev.created_at!, 4_000), own, `ready: ${s.pr.head.sha.slice(0, 11)}`));
    if (mergeable === undefined) delete s.pr.mergeable;
    else s.pr.mergeable = mergeable;
    // An OPEN PR's state is set directly: the post-merge staleness (bean `fx5r`) is check 1's case.
    if (state === undefined) delete s.pr.mergeable_state;
    else s.pr.mergeable_state = state;
    return s;
  };

  test("control: every check passes on the base case", () => {
    const v = evaluate(passingOtherwise(true, "clean"));
    expect(v.checks.filter((c) => c.status !== "pass")).toEqual([]);
    expect([v.verdict, v.state, v.exitCode]).toEqual(["pass", "success", 0]);
  });

  test("#1898's state — signed, green, labelled, but conflicting (`dirty`) — is refused, not-ready, with the remedy", () => {
    const s = passingOtherwise(false, "dirty");
    const c = status(s, "mergeable");
    expect(c.n).toBe(8);
    expect(c.status).toBe("refuse");
    expect(c.kind).toBe("not-ready");
    expect(c.detail).toContain("conflicts with `main`");
    expect(c.detail).toContain("Merge `main` into the head");
    const v = evaluate(s);
    expect([v.verdict, v.state, v.exitCode]).toEqual(["refused", "pending", 1]);
  });

  test("`mergeable: false` alone refuses; so does `dirty` alone", () => {
    expect(status(passingOtherwise(false), "mergeable").status).toBe("refuse");
    expect(status(passingOtherwise(true, "dirty"), "mergeable").status).toBe("refuse");
  });

  test("`mergeable: null` (not computed yet) is unknown, never a pass, and the verdict is `error`, exit 2", () => {
    const s = passingOtherwise(null, "unknown");
    const c = status(s, "mergeable");
    expect(c.status).toBe("unknown");
    expect(c.detail).toContain("has not computed");
    const v = evaluate(s);
    expect([v.verdict, v.state, v.exitCode]).toEqual(["unknown", "error", 2]);
  });

  test("a record with no `mergeable` field is unknown, not a pass", () => {
    const c = status(passingOtherwise(undefined), "mergeable");
    expect(c.status).toBe("unknown");
    expect(c.detail).toContain("no `mergeable` field");
  });

  test("`mergeable: true` passes, including `unstable`, `blocked` and `behind`: CI and review are not this check's", () => {
    for (const state of ["clean", "unstable", "blocked", "behind", undefined]) {
      const s = passingOtherwise(true, state);
      expect(status(s, "mergeable").status).toBe("pass");
      expect(evaluate(s).exitCode).toBe(0);
    }
  });

  test("a conflict beside a defect elsewhere still posts `failure`: the conflict adds, it does not mask", () => {
    const s = passingOtherwise(false, "dirty");
    s.pr.labels.push({ name: "needs-merge-human" });
    expect(evaluate(s).state).toBe("failure");
  });
});

describe("fetchPull — re-asks while GitHub has not computed `mergeable`", () => {
  const PR_URL = "https://api.github.com/repos/litlfred/folio-assistant/pulls/1898";
  // `unknown` is not computed yet (bean `h2s9`); a closed PR's view is stale (bean `fx5r`).
  type Answer = { mergeable?: boolean | null; mergeable_state?: string; state?: string };
  /** Serves `answers` in order (the last one repeats) for the PR URL, recording each wait. */
  const serve = (answers: Answer[]) => {
    let i = 0;
    const waits: number[] = [];
    const impl = (async (input: string | URL | Request) => {
      expect(String(input)).toBe(PR_URL);
      const body = { number: 1898, state: "open", ...answers[Math.min(i, answers.length - 1)] };
      i += 1;
      return new Response(JSON.stringify(body), { status: 200, headers: { "content-type": "application/json" } });
    }) as unknown as typeof fetch;
    return {
      impl,
      waits,
      asked: () => i,
      sleep: async (ms: number) => {
        waits.push(ms);
      },
    };
  };

  test("null then false: the second answer is the one returned", async () => {
    // `unknown` = not computed yet (bean `h2s9`); then a conflict, the reading trusted.
    const f = serve([{ mergeable: null, mergeable_state: "unknown" }, { mergeable: false, mergeable_state: "dirty" }]);
    const pr = await fetchPull("litlfred/folio-assistant", 1898, { fetchImpl: f.impl, sleep: f.sleep, waitsMs: [1, 2, 3] });
    expect([pr.mergeable, pr.mergeable_state]).toEqual([false, "dirty"]);
    expect(f.waits).toEqual([1]);
  });

  test("still null after every wait: returned as null, so check 8 says unknown", async () => {
    const f = serve([{ mergeable: null }]);
    const pr = await fetchPull("litlfred/folio-assistant", 1898, { fetchImpl: f.impl, sleep: f.sleep, waitsMs: [1, 2, 3] });
    expect(pr.mergeable).toBeNull();
    expect(f.waits).toEqual([1, 2, 3]);
    expect(f.asked()).toBe(4);
  });

  test("an answer on the first ask is not re-asked; nor is a closed PR", async () => {
    // `clean` on an open PR; on a merged one it would be stale (bean `fx5r`).
    const a = serve([{ mergeable: true, mergeable_state: "clean" }]);
    await fetchPull("litlfred/folio-assistant", 1898, { fetchImpl: a.impl, sleep: a.sleep, waitsMs: [1, 2] });
    expect(a.asked()).toBe(1);
    const b = serve([{ mergeable: null, state: "closed" }]);
    await fetchPull("litlfred/folio-assistant", 1898, { fetchImpl: b.impl, sleep: b.sleep, waitsMs: [1, 2] });
    expect(b.asked()).toBe(1);
  });
});
