/**
 * Committed docs pages carry no QA data — bean `4l4d`.
 *
 * With `test/results/` absent (the state after bean `5hox`), `gen-docs-pages
 * --check` read all 17 generated pages as stale, because each embedded
 * whether its subjects had a sidecar ("not swept" spans) and whether the
 * corpus had been fetched at all ("not available" spans). `docs:pages:check`
 * and `check:ci-invocations` went red on every checkout that had not run
 * `qa:fetch`.
 *
 * The fix moves every corpus-dependent fact into the per-page `qa-index.json`
 * and the `translation-qa-pages.json` list — JSON assets generated beside the
 * projections at site-build time and fetched by `docs-ui.js`. These tests pin
 * the three halves of that:
 *
 * 1. the placeholder is a function of STRUCTURE only (no corpus argument
 *    exists to vary it) — and the committed pages hold nothing else;
 * 2. the index says `corpus: "absent"` rather than an empty list when there
 *    was no corpus, so the browser reads "not available in this build";
 * 3. the authored-page list does the same.
 *
 * The byte-identity of the committed pages with and without a fetched corpus
 * is the gate itself: `docs:pages:check` in `code-quality-gates.yml`, which
 * runs on a checkout that holds whatever `test/results/` it holds.
 */
import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

import {
  qaBadgePlaceholder,
  qaIndexDoc,
  translationQaPagesDoc,
  TRANSLATION_QA_PAGES_FILE,
} from "../gen-docs-pages.ts";
import { QaIndexSchema, QaTranslationPagesSchema } from "../../schemas/site-indexes.ts";
import { siteDirFor } from "../../schemas/cat-harness.ts";

const ROOT = join(import.meta.dir, "..", "..");
const SITE = join(ROOT, siteDirFor(ROOT));

const COUNTS = { fail: 0, warn: 1, pass: 3, na: 0, unknown: 0 };

describe("the badge placeholder", () => {
  test("is a pending button carrying only URLs and names — no verdict, no swept-ness", () => {
    const b = qaBadgePlaceholder({ family: "block", key: "overview.block", noun: "block", slug: "demo" });
    expect(b).toContain(`class="fa-qa-badge fa-qa-pending fa-qa-fam-block"`);
    expect(b).toContain(`data-qa-index="{{ '/assets/qa/demo/qa-index.json' | relative_url }}"`);
    expect(b).toContain(`data-qa-src="{{ '/assets/qa/demo/overview.block.json' | relative_url }}"`);
    for (const corpusFact of ["fa-qa-unswept", "fa-qa-unavailable", "fa-qa-pass", "fa-qa-fail", "fa-qa-warn", "not swept", "not available"]) {
      expect(b).not.toContain(corpusFact);
    }
  });

  test("declares itself English, left-to-right — bean `giiw`", () => {
    // On an Arabic page the badge inherited `dir="rtl"`; `docs-ui.css`
    // reversed its direction, but a screen reader hears `lang`, not CSS.
    const b = qaBadgePlaceholder({ family: "translation", key: "page.translation", noun: "page", slug: "demo" });
    expect(b).toMatch(/^<button [^>]*\blang="en" dir="ltr"/);
  });

  test("every committed generated page carries placeholders only", () => {
    // The scan is over the CHECKOUT's pages, so it must find some: a filter
    // over nothing would pass.
    const pages: string[] = [];
    const walk = (d: string): void => {
      for (const e of readdirSync(d, { withFileTypes: true })) {
        const p = join(d, e.name);
        if (e.isDirectory()) {
          if (e.name.startsWith("_") || e.name.startsWith(".") || e.name === "assets" || e.name === "vendor") continue;
          walk(p);
        } else if (e.name.endsWith(".md")) {
          const t = readFileSync(p, "utf-8");
          // Source pages only. A TRANSLATED page (`translation_source:`) is a
          // translation of a generated page, authored through the translation
          // tools and not rewritten by this generator, so it is not what
          // `docs:pages:check` gates.
          if (t.includes("Generated by scripts/gen-docs-pages.ts") && t.includes("fa-qa-badge") && !/^translation_source:/m.test(t)) {
            pages.push(p);
          }
        }
      }
    };
    walk(SITE);
    expect(pages.length).toBeGreaterThan(0);
    const offenders: string[] = [];
    for (const p of pages) {
      const t = readFileSync(p, "utf-8");
      for (const m of t.matchAll(/<(span|button)\b[^>]*class="fa-qa-badge ([^"]*)"/g)) {
        if (m[1] !== "button" || !m[2]!.startsWith("fa-qa-pending ")) offenders.push(`${p}: <${m[1]} class="fa-qa-badge ${m[2]}">`);
      }
    }
    expect(offenders).toEqual([]);
  });
});

describe("the per-page verdict index", () => {
  test("with the corpus: rows, and `unswept` as its own sorted list", () => {
    const doc = JSON.parse(qaIndexDoc("demo", true, { "a.block": { state: "warn", counts: COUNTS } }, ["z.block", "b.translation", "z.block"]));
    expect(doc.corpus).toBe("present");
    expect(doc.badges["a.block"].state).toBe("warn");
    expect(doc.unswept).toEqual(["b.translation", "z.block"]);
    expect(QaIndexSchema.safeParse(doc).success).toBe(true);
  });

  test("without it: `absent`, and no rows — never an empty answer that reads as 'nothing swept'", () => {
    const doc = JSON.parse(qaIndexDoc("demo", false, { "a.block": { state: "pass", counts: COUNTS } }, ["b.block"]));
    expect(doc.corpus).toBe("absent");
    expect(doc.badges).toEqual({});
    expect(doc.unswept).toEqual([]);
    expect(QaIndexSchema.safeParse(doc).success).toBe(true);
  });

  test("the schema refuses an absent-corpus index that claims rows", () => {
    const bad = { $schema: "folio-qa-index/v1", page: "demo", corpus: "absent", badges: { "a.block": { state: "pass", counts: COUNTS } }, unswept: [] };
    expect(QaIndexSchema.safeParse(bad).success).toBe(false);
  });
});

describe("the authored-page translation list", () => {
  test("is published under the witness tree, not as a Jekyll data file", () => {
    expect(TRANSLATION_QA_PAGES_FILE).toBe("translation-qa-pages.json");
    expect(TRANSLATION_QA_PAGES_FILE.startsWith("_")).toBe(false);
  });

  test("says `absent` rather than `[]` when there was no corpus", () => {
    const present = JSON.parse(translationQaPagesDoc(true, ["skills", "index"]));
    expect(present).toEqual({ $schema: "folio-qa-translation-pages/v1", corpus: "present", pages: ["index", "skills"] });
    const absent = JSON.parse(translationQaPagesDoc(false, ["index"]));
    expect(absent.corpus).toBe("absent");
    expect(absent.pages).toEqual([]);
    expect(QaTranslationPagesSchema.safeParse(present).success).toBe(true);
    expect(QaTranslationPagesSchema.safeParse(absent).success).toBe(true);
  });

  test("`head_custom.html` no longer reads it from `_data`", () => {
    const head = readFileSync(join(SITE, "_includes", "head_custom.html"), "utf-8");
    expect(head).not.toContain("site.data.translation-qa-pages");
    expect(head).toContain(`/assets/qa/${TRANSLATION_QA_PAGES_FILE}`);
  });
});
