#!/usr/bin/env bun
/**
 * Every harness owes at least one MEANINGFULLY POPULATED documentation page.
 *
 * @module scripts/check-docs-populated
 * @covers docs, doc-group — the docs graph's named groups (bean `xka5`) are
 *   folders of docs pages, and `pagesOfExt` walks every folder of the site, so
 *   their pages are read here exactly as the top-level ones are.
 *
 * Usage: `bun run check:docs-populated [--json] [--strict]`
 * Exit:  0 every harness has one · 1 one is thin · 2 could not determine
 *        With `--strict`, a harness whose pages name none of its declared
 *        processes, roles and tasks is also exit 1.
 *
 * ## The adjective is the requirement
 *
 * Owner, bean `06e3` §4(b): *"QA every harness needs at least one meaningfully
 * popualated doc page that outlines what the harness does."* A page that
 * exists and says nothing passes a file-exists check and fails the reader —
 * the `xom7` shape, where a broken thing and a working one look identical from
 * in here. So this measures CONTENT, and `could not determine` is its own
 * answer rather than a pass.
 *
 * ## Authored or generated, and it is READ off the file
 *
 * A generated index clearing the bar would be the exact false pass this check
 * exists to stop: the bean's own §2 says an index is not the documentation.
 * So a page is counted only when nothing in its bytes says it was generated —
 * the same ownership-is-read-not-assumed rule the orphan pruners follow.
 *
 * **The markers are ANCHORED, and both loose alternatives were measured
 * wrong.** A substring search for "generated by" marks
 * `docs/getting-started.md` generated, because it says in prose that an SVG is
 * generated by `render:bpmn` — an authored page discarded for describing a
 * generator. And searching only for that phrase misses
 * `docs/publication-workflow.md`, which `gen-docs-pages.ts` writes and which
 * carries no marker at all.
 *
 * ## That second case is a FINDING, not a rounding error
 *
 * `gen-docs-pages.ts` writes pages that are byte-indistinguishable from
 * authored ones. Nothing downstream can tell them apart, so this check cannot
 * either: those pages are counted as `ambiguous` and reported per harness
 * rather than being quietly credited or quietly dropped. Crediting them would
 * let a harness pass on documentation nobody wrote; dropping them would fail a
 * harness for pages it does have. Naming the ambiguity is the only honest
 * third option, and the fix belongs in that generator — a marker in what it
 * writes — rather than in a list here.
 *
 * ## The threshold, and its basis
 *
 * `MIN_PROSE_WORDS` is the length at which a page can do what §4(a) asks —
 * say what a process is FOR, when you would be in it, and what it is not —
 * for even a couple of things. Below it a page is a title and a list of links,
 * which is the index again. The number is stated with that basis rather than
 * tuned to the corpus: measured here, the pages that clear it are the ones a
 * reader would call documentation, and the ones that do not are viewer shells
 * and link lists.
 *
 * Prose EXCLUDES front matter, comments, code fences, markup, and lines that
 * are nothing but a link or a bullet — otherwise a page of links measures as
 * prose, which is the failure mode being tested for.
 *
 * ## SUBJECT — the other half of §4(b), and why length alone was not enough
 *
 * The owner asked two things in one sentence: *"does the page reference the
 * harness's **processes, roles and tasks**, and does it say something about
 * them that the index does not?"* Length and authorship answer the second.
 * Nothing answered the first, and measured on `main` 2026-10-03 the gate was
 * green on these pages:
 *
 * | harness | the page it passed on | words |
 * |---|---|---|
 * | `smart-trust` | `docs/category/`**`Other.md`** | 14158 |
 * | `cat-harness` | `docs/proposals/placement-audit-2026-10-01.md` | 17605 |
 * | `folio-assistant` | `docs/README.md` | 299 |
 *
 * A page called `Other.md` clearing a bar whose words are *"outlines what the
 * harness does"* is the `xom7` shape one level up: teeth about how LONG a page
 * is, none about what it is FOR, so a harness with no landing page is
 * indistinguishable from one with a good one. Bean `akjg`.
 *
 * So a second dimension: does an authored page NAME a declared process, a
 * declared role and a declared task of that harness.
 *
 * **Resolved from the DECLARATIONS, never from a list here.** A list would be
 * a second answer to "what processes does this harness have", free to disagree
 * with the declaration the moment either moves — the failure this repository
 * has paid for repeatedly. `processes` and `scenarios` graph typologies are read off
 * the instance's own declaration, exactly as the `docs` kind already is.
 *
 * **Three states on this half too.** A harness that declares no processes, no
 * roles and no tasks cannot be judged on whether its pages mention them, so it
 * is `unknown` — never a pass. A sweep blind on one dimension has not cleared
 * it.
 *
 * ## It REPORTS; `--strict` grades
 *
 * The subject verdict is printed every run and is fatal only under `--strict`.
 * That is deliberate and has an owner. Measured 2026-10-03: **1 populated, 5
 * unknown, 0 thin** — and the shape of that result is the point. Four of the
 * six harnesses declare no `processes` and no `scenarios` directory at all, and
 * `smart-base` declares processes but no roles, so for five of six the question
 * §4(b) asks **cannot be put**. That is a fact about the declarations rather
 * than about the pages, and gating on it would fail a harness for a graph it
 * never claimed to have.
 *
 * Same split as `audit:coverage:require-all` / `audit:coverage:strict`, for the
 * same reason: the two lock different things and a reader should see which
 * broke. `--strict` is what `06e3` §4(a) turns on when the landing pages exist.
 *
 * Printing it every run is what stops the deferral going quiet the way `xom7`
 * did for two months.
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { basename, join, relative } from "node:path";

import { instanceRootsIn, readDeclaration, repoRootFor } from "../../cat-harness/schemas/cat-harness.ts";
import { readRoleGraph } from "../../cat-harness/schemas/role-graph.ts";
// The HARNESS, not this layer: these scripts moved up in 70lx B2b and read cat-harness.
import { HARNESS_ROOT } from "./lib/roots.ts";

/**
 * Words of prose a page needs to count.
 *
 * Basis, not a tuned number: §4(a) asks a landing page to say what a process
 * is for, when you would be in it, and what it is not. Two or three of those,
 * plus a sentence saying what the harness does, is a few hundred words. Below
 * that the page is a title and a link list.
 */
const MIN_PROSE_WORDS = 250;

/**
 * A page that says, in its own bytes, that a generator wrote it.
 *
 * Anchored: `var SCOPE` on its own line is the viewers' marker, and the other
 * two are whole phrases rather than the word "generated", which appears in
 * authored prose about generators.
 */
const GENERATED_MARKERS = [
  /^var SCOPE = "[^"]*";$/m,
  /Do not hand-edit/,
  /— do not edit here\./,
] as const;

export function looksGenerated(text: string): boolean {
  return GENERATED_MARKERS.some((re) => re.test(text));
}

/**
 * Words that are prose — not markup, not front matter, not a link list.
 *
 * A line whose only content is a link or a bullet contributes nothing: a page
 * of links is the index, and counting it as prose would pass exactly the page
 * this check exists to fail.
 */
export function proseWords(text: string, isMarkdown: boolean): number {
  let t = text;
  if (isMarkdown) {
    t = t.replace(/^---\n[\s\S]*?\n---\n/, "");
    t = t.replace(/```[\s\S]*?```/g, "");
  } else {
    t = t.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi, "");
  }
  t = t.replace(/<!--[\s\S]*?-->/g, "");
  if (!isMarkdown) t = t.replace(/<[^>]+>/g, " ");

  const kept: string[] = [];
  for (const line of t.split("\n")) {
    const s = line.trim();
    if (!s) continue;
    // Strip markdown links, then punctuation and list markers. What is left is
    // the line's own words; under three characters, there were none.
    const bare = s.replace(/\[[^\]]*\]\([^)]*\)/g, "").replace(/[-*|>#`_\s]/g, "");
    if (bare.length < 3) continue;
    kept.push(s);
  }
  return kept.join(" ").split(/\s+/).filter(Boolean).length;
}

/**
 * The BPMN element kinds that are a task in a lane — the same list
 * `gen-auto-docs.ts`'s `index/tasks` type uses, and namespace-tolerant for the
 * same reason: a process authored with the `bpmn:` prefix is the same process.
 */
const TASK_RE =
  /<(?:bpmn:)?(?:task|userTask|serviceTask|manualTask|scriptTask|callActivity)\b[^>]*\sname="([^"]*)"[^>]*>/g;
const PROCESS_NAME_RE = /<(?:bpmn:)?process\b[^>]*\sname="([^"]*)"/g;

/** What a harness declares, by name — the things §4(b) asks its pages to reference. */
export interface Subjects {
  processes: string[];
  roles: string[];
  tasks: string[];
  /**
   * Graphs that exist and could not be read, one line each.
   *
   * Separate from an empty list, because "declares no roles" and "its role
   * graph does not parse" are different facts and only one of them is about the
   * harness's documentation.
   */
  unreadable: string[];
}

/**
 * The processes, roles and tasks an instance DECLARES.
 *
 * Read off that instance's own declaration — `processes` and `scenarios` graph
 * kinds — exactly as `harnessesWithDocs` reads the `docs` kind. Never a list in
 * this file: a list would be a second answer to "what processes does this
 * harness have", free to disagree with the declaration the moment either moves.
 *
 * A process contributes its `name` attribute, falling back to the file's
 * basename, because a diagram authored without a `name` is still a process the
 * page could reference. Roles contribute both `id` and `title`: the id is what
 * a lane binds and the title is what a reader would write.
 */
export function subjectsOf(instanceRoot: string): Subjects {
  const decl = readDeclaration(instanceRoot);
  const processes = new Set<string>();
  const tasks = new Set<string>();
  const roles = new Set<string>();
  const unreadable: string[] = [];
  if (!decl) return { processes: [], roles: [], tasks: [], unreadable: ["(no declaration)"] };

  for (const d of decl.directories ?? []) {
    const kinds = (d.graphTypologies ?? []) as readonly string[];
    const abs = join(instanceRoot, d.path);
    if (kinds.includes("processes")) {
      for (const f of pagesOfExt(abs, ".bpmn")) {
        let xml: string;
        try {
          xml = readFileSync(f, "utf-8");
        } catch {
          continue;
        }
        const named = [...xml.matchAll(PROCESS_NAME_RE)].map((m) => m[1]?.trim()).filter((n): n is string => !!n);
        if (named.length > 0) for (const n of named) processes.add(n);
        else processes.add(basename(f, ".bpmn"));
        for (const m of xml.matchAll(TASK_RE)) {
          const n = m[1]?.trim();
          if (n) tasks.add(n);
        }
      }
    }
    if (kinds.includes("scenarios")) {
      let g;
      try {
        g = readRoleGraph(abs);
      } catch (e) {
        // A role graph that does not PARSE is not a harness with no roles, and
        // collapsing the two would make the verdict's reason a lie: the detail
        // would say "declares no roles" about a file that declares plenty and
        // is broken. The verdict is `unknown` either way — never a pass — but
        // which fact it is gets reported.
        unreadable.push(`${relative(instanceRoot, abs)}: ${e instanceof Error ? e.message.split("\n")[0] : String(e)}`);
        g = undefined;
      }
      // `abs` is the scenarios directory ITSELF — `readRoleGraph`'s own
      // docblock says callers that pass a declared graph root pass it that
      // way, and joining `roles/` on would look one level too deep.
      for (const r of g?.roles ?? []) {
        if (r.id) roles.add(r.id);
        if (r.title) roles.add(r.title);
      }
    }
  }
  return {
    processes: [...processes].sort(),
    roles: [...roles].sort(),
    tasks: [...tasks].sort(),
    unreadable,
  };
}

/** Files of one extension beneath `dir`, skipping dot-prefixed segments. */
function pagesOfExt(dir: string, ext: string, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir).sort()) {
    if (e.startsWith(".")) continue;
    const p = join(dir, e);
    let st;
    try {
      st = statSync(p);
    } catch {
      continue;
    }
    if (st.isDirectory()) pagesOfExt(p, ext, out);
    else if (e.endsWith(ext)) out.push(p);
  }
  return out;
}

export type Verdict = "populated" | "thin" | "unknown";

/**
 * Whether any authored page NAMES this harness's declared processes, roles and
 * tasks — §4(b)'s first half. Reported always, fatal only under `--strict`.
 */
export interface SubjectVerdict {
  verdict: Verdict;
  /** How many of each the harness declares — 0 everywhere is what makes it `unknown`. */
  declared: { processes: number; roles: number; tasks: number };
  /** One example found of each, for a reader who wants to check the claim. */
  found: { process?: string; role?: string; task?: string };
  /** The page that named the most of them, where any did. */
  page?: string;
  detail: string;
}

export interface HarnessDocs {
  instance: string;
  /** Repo-relative declared docs directories. */
  dirs: string[];
  verdict: Verdict;
  /** The best authored page, where there is one. */
  best?: { path: string; words: number };
  authored: number;
  generated: number;
  /** Pages nothing can classify — see the module note. */
  ambiguous: number;
  detail: string;
  subject: SubjectVerdict;
}

/** Pages under a docs directory: markdown and html, skipping dot-prefixed segments. */
function pagesIn(dir: string, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir).sort()) {
    if (e.startsWith(".")) continue;
    const p = join(dir, e);
    let st;
    try {
      st = statSync(p);
    } catch {
      continue;
    }
    if (st.isDirectory()) pagesIn(p, out);
    else if (e.endsWith(".md") || e.endsWith(".html")) out.push(p);
  }
  return out;
}

/**
 * Pages written by `gen-docs-pages.ts`, which marks nothing it writes.
 *
 * Read from the generator's own output rather than listed: it prints the
 * pages it wrote, but this check must not run it. So the one thing that is
 * knowable without running it — that those pages live directly in a docs root
 * and carry Jekyll front matter with `nav_order` — is NOT used as a proxy,
 * because an authored page has exactly that shape too. This is the ambiguity
 * the module note names, and it is reported rather than guessed.
 */
export function classify(path: string, text: string): "authored" | "generated" {
  return looksGenerated(text) ? "generated" : "authored";
}

/**
 * Does any authored page name a declared process, a declared role and a
 * declared task?
 *
 * **All three, not any one.** §4(b) names them together, and the distinction is
 * what separates a landing page from a page about one thing: a proposal names
 * processes, a role model names roles, and only a page outlining what the
 * harness DOES names all three.
 *
 * A name is matched case-insensitively as a whole phrase. Names under four
 * characters are DROPPED rather than matched: a role id like `BA` matches
 * inside ordinary prose, and a check that counts that has found nothing while
 * reporting a pass.
 *
 * ## ONE page must satisfy BOTH halves
 *
 * `pages` is the authored pages that ALREADY clear {@link MIN_PROSE_WORDS}, not
 * every authored page, and that is the whole point. The owner asked for *"at
 * least one meaningfully populated doc page"* — one page doing the job. Letting
 * the length half pass on page A and the subject half on page B would mean a
 * harness clears a bar no single page of its own meets, which is the vacuous
 * pass in its subtlest form: both columns green, no such page.
 *
 * Measured while building this (bean `akjg`): the first draft asked every
 * authored page, and `cat-harness` passed on `docs/ar/architecture.md` — an
 * ARABIC TRANSLATION — while the length half was passing on a placement-audit
 * proposal. Two different pages, neither a landing page, one ✓.
 */
export function assessSubject(subjects: Subjects, pages: Array<{ path: string; text: string }>): SubjectVerdict {
  const declared = {
    processes: subjects.processes.length,
    roles: subjects.roles.length,
    tasks: subjects.tasks.length,
  };
  const usable = (xs: string[]): string[] => xs.filter((x) => x.length >= 4);
  const [ps, rs, ts] = [usable(subjects.processes), usable(subjects.roles), usable(subjects.tasks)];

  if (ps.length === 0 || rs.length === 0 || ts.length === 0) {
    const missing = [ps.length === 0 && "processes", rs.length === 0 && "roles", ts.length === 0 && "tasks"]
      .filter(Boolean)
      .join(", ");
    return {
      verdict: "unknown",
      declared,
      found: {},
      detail:
        subjects.unreadable.length > 0
          ? `could not read ${subjects.unreadable.length} declared graph(s), so its ${missing} are unknown rather than absent: ` +
            subjects.unreadable.join("; ")
          : `declares no ${missing} with a name long enough to match, so whether its pages reference them ` +
            `is not a question this check can answer — reported rather than passed`,
    };
  }

  const hits = (lower: string, names: string[]): string[] => names.filter((n) => lower.includes(n.toLowerCase()));

  /**
   * One process, one role and one task that are THREE DISTINCT NAMES.
   *
   * Measured while building this (bean `akjg`): without the distinctness rule,
   * `cat-harness/docs/methodologies/index.md` scored 3 on the single word
   * **"Adjudication"** — which is the name of a process *and* of a task. Three
   * dimensions satisfied by one token is not a page that references processes,
   * roles and tasks; it is a page that says one word. The same crack as the
   * two-different-pages one, one level smaller.
   *
   * Returned as a triple plus a `complete` flag rather than a boolean, so the
   * report can name what it found and a reader can check the claim.
   *
   * `complete` is the ONLY thing the verdict reads. An earlier draft also
   * derived the verdict from `new Set([...]).size === 3`, which is the same
   * rule computed twice — and a mutation that removed the distinctness
   * condition from the search left every test green, because the set was still
   * enforcing it. Two mechanisms for one rule means one of them is dead, and a
   * dead mechanism cannot be tested. One answer, here.
   */
  const distinctTriple = (
    text: string,
  ): { process?: string; role?: string; task?: string; complete: boolean } => {
    const lower = text.toLowerCase();
    const [mp, mr, mt] = [hits(lower, ps), hits(lower, rs), hits(lower, ts)];
    for (const process of mp) {
      for (const role of mr) {
        if (role === process) continue;
        const task = mt.find((t) => t !== process && t !== role);
        if (task !== undefined) return { process, role, task, complete: true };
      }
    }
    // No distinct triple: report whichever dimensions matched at all, so the
    // `thin` detail says how close the page came.
    return { process: mp[0], role: mr[0], task: mt[0], complete: false };
  };

  // Ranked by (score, then length), and NOT short-circuited on the first full
  // hit. The first draft broke on the first page scoring 3 and reported
  // `cat-harness/docs/concepts/ar/architecture.md` — the ARABIC TRANSLATION of a page
  // whose English original scores the same. It won on `readdirSync().sort()`
  // order, because `ar/` precedes `architecture/`. A verdict decided by
  // alphabetical order is a verdict about the filesystem, so every eligible
  // page is scored and the strongest one is named.
  let bestPage:
    | { path: string; process?: string; role?: string; task?: string; score: number; words: number; complete: boolean }
    | undefined;
  for (const { path, text } of pages) {
    const { process, role, task, complete } = distinctTriple(text);
    // Ranking only. The VERDICT is `complete`; this counts distinct names so a
    // page that came closer is the one reported as the closest.
    const score = complete ? 3 : new Set([process, role, task].filter(Boolean)).size;
    const words = proseWords(text, path.endsWith(".md"));
    if (!bestPage || score > bestPage.score || (score === bestPage.score && words > bestPage.words)) {
      bestPage = { path, process, role, task, score, words, complete };
    }
  }

  if (bestPage?.complete === true) {
    return {
      verdict: "populated",
      declared,
      found: { process: bestPage.process, role: bestPage.role, task: bestPage.task },
      page: bestPage.path,
      detail: `${bestPage.path} names a declared process, role and task (${bestPage.words} words)`,
    };
  }
  // The "how close" message is built from the DISTINCT names, not from the
  // fallback triple. The fallback reports whatever each dimension matched so a
  // reader can see it, and on a collision the same string appears twice — so
  // counting those entries would say "a process and a role and a task" about a
  // page that named two things. Caught by this module's own test.
  const distinctNames = bestPage ? [...new Set([bestPage.process, bestPage.role, bestPage.task].filter(Boolean))] : [];
  const closest = bestPage
    ? ` — the closest, ${bestPage.path}, names ${distinctNames.length} of the three as distinct names` +
      (distinctNames.length > 0 ? ` (${distinctNames.join(", ")})` : "")
    : "";
  return {
    verdict: "thin",
    declared,
    found: { process: bestPage?.process, role: bestPage?.role, task: bestPage?.task },
    page: bestPage?.path,
    detail:
      `no authored page names all three of ${declared.processes} process(es), ${declared.roles} role(s) and ` +
      `${declared.tasks} task(s) it declares` +
      closest +
      (pages.length === 0 ? ` (no authored page clears ${MIN_PROSE_WORDS} words, so none was eligible)` : ""),
  };
}

export function assess(repoRoot: string, instance: string, dirs: string[], instanceRoot?: string): HarnessDocs {
  const abs = dirs.map((d) => join(repoRoot, d));
  const subjects: Subjects = instanceRoot
    ? subjectsOf(instanceRoot)
    : { processes: [], roles: [], tasks: [], unreadable: [] };
  const missing = abs.filter((d) => !existsSync(d));
  if (missing.length === dirs.length) {
    return {
      instance,
      dirs,
      verdict: "unknown",
      authored: 0,
      generated: 0,
      ambiguous: 0,
      detail: `declares ${dirs.join(", ")} and none of them exists — declared-but-absent is \`dh4f\`, and nobody can say whether this harness is documented`,
      // No page was read, so the subject half is equally undetermined. Passing
      // it here would be the vacuous pass twice over.
      subject: assessSubject(subjects, []),
    };
  }

  /**
   * Authored pages that clear the prose bar — read once, asked twice.
   *
   * Only these reach the subject pass: ONE page must satisfy both halves, or a
   * harness clears a bar no single page of its own meets.
   */
  const authoredPages: Array<{ path: string; text: string }> = [];
  let authored = 0;
  let generated = 0;
  let unreadable = 0;
  let best: { path: string; words: number } | undefined;

  for (const dir of abs) {
    for (const p of pagesIn(dir)) {
      let text: string;
      try {
        text = readFileSync(p, "utf-8");
      } catch {
        unreadable++;
        continue;
      }
      if (classify(p, text) === "generated") {
        generated++;
        continue;
      }
      authored++;
      const words = proseWords(text, p.endsWith(".md"));
      if (words >= MIN_PROSE_WORDS) authoredPages.push({ path: relative(repoRoot, p), text });
      if (!best || words > best.words) best = { path: relative(repoRoot, p), words };
    }
  }

  const subject = assessSubject(subjects, authoredPages);

  if (unreadable > 0) {
    return {
      instance,
      dirs,
      verdict: "unknown",
      best,
      authored,
      generated,
      ambiguous: unreadable,
      detail: `${unreadable} page(s) could not be read, so a thin verdict here would be a conclusion nobody reached`,
      subject,
    };
  }
  if (!best) {
    return {
      instance,
      dirs,
      verdict: "thin",
      authored,
      generated,
      ambiguous: 0,
      detail: `${generated} generated page(s) and nothing authored — an index is not the documentation (bean \`06e3\` §2)`,
      subject,
    };
  }
  if (best.words < MIN_PROSE_WORDS) {
    return {
      instance,
      dirs,
      verdict: "thin",
      best,
      authored,
      generated,
      ambiguous: 0,
      detail: `the fullest authored page is ${best.path} at ${best.words} words of prose, under ${MIN_PROSE_WORDS}`,
      subject,
    };
  }
  return {
    instance,
    dirs,
    verdict: "populated",
    best,
    authored,
    generated,
    ambiguous: 0,
    detail: `${best.path} — ${best.words} words of prose`,
    subject,
  };
}

/** Every instance that declares a `docs` graph, with the directories it names. */
export function harnessesWithDocs(repoRoot: string): { instance: string; root: string; dirs: string[] }[] {
  const out: { instance: string; root: string; dirs: string[] }[] = [];
  for (const inst of instanceRootsIn(repoRoot)) {
    const decl = readDeclaration(inst);
    if (!decl) continue;
    const dirs = (decl.directories ?? [])
      .filter((d) => (d.graphTypologies ?? []).includes("docs"))
      .map((d) => relative(repoRoot, join(inst, d.path)).split("\\").join("/"));
    // `root` is carried rather than re-derived from `instance`: the name is a
    // declared identifier and nothing resolves a path from it, so a consumer
    // that mapped name → directory would be guessing.
    if (dirs.length > 0) out.push({ instance: decl.name ?? inst, root: inst, dirs: [...new Set(dirs)].sort() });
  }
  return out;
}

if (import.meta.main) {
  // FROM THIS MODULE'S OWN LOCATION, never the CWD. The first draft used
  // `repoRootFor(process.cwd())`, which resolved to the repository's PARENT
  // when run from anywhere but the root: `instanceRootsIn` then found one
  // instance, no `docs` graph, and the check printed a clean pass over a
  // sweep that had looked at nothing. That is the CWD-vs-instance-root defect
  // bean `a6kl` swept every gate for, committed by the gate written after it.
  const repoRoot = repoRootFor(HARNESS_ROOT);
  const asJson = process.argv.includes("--json");
  const strict = process.argv.includes("--strict");
  const rows = harnessesWithDocs(repoRoot).map((h) => assess(repoRoot, h.instance, h.dirs, h.root));

  if (asJson) {
    console.log(JSON.stringify({ minProseWords: MIN_PROSE_WORDS, strict, harnesses: rows }, null, 2));
  } else {
    console.log(`\nDocumentation, per harness that declares a \`docs\` graph`);
    console.log(
      `  A page counts when it is AUTHORED — nothing in its bytes says a generator wrote it —\n` +
        `  and carries at least ${MIN_PROSE_WORDS} words of prose, which excludes front matter,\n` +
        `  markup, code and lines that are only a link.\n`,
    );
    for (const r of rows) {
      const mark = r.verdict === "populated" ? "✓" : r.verdict === "thin" ? "✗" : "?";
      console.log(`  ${mark} ${r.instance.padEnd(18)} ${r.detail}`);
      console.log(
        `      ${r.authored} authored, ${r.generated} generated` +
          (r.ambiguous > 0 ? `, ${r.ambiguous} unreadable` : "") +
          `  ·  ${r.dirs.join(", ")}`,
      );
      const sm = r.subject.verdict === "populated" ? "✓" : r.subject.verdict === "thin" ? "✗" : "?";
      console.log(`      ${sm} subject: ${r.subject.detail}`);
    }
    const sU = rows.filter((r) => r.subject.verdict === "unknown").length;
    const sT = rows.filter((r) => r.subject.verdict === "thin").length;
    console.log(
      `\n  SUBJECT is §4(b)'s other half — does ONE page name a declared process, role AND task,` +
        `\n  as three distinct names. Reported always; fatal only with --strict.` +
        `\n  ${sU} of ${rows.length} are \`unknown\` and ${sT} \`thin\`: most harnesses declare no processes or` +
        `\n  scenarios of their own, so the question cannot be ASKED of them — which is a fact about` +
        `\n  the declarations, not about the pages. Bean \`akjg\`.`,
    );
  }

  // A SWEEP THAT FOUND NOTHING HAS NOT CLEARED ANYTHING. Every harness here
  // declares its own docs graph, so an empty list means the declarations could
  // not be read — and the first draft rendered that as "✓ every harness has
  // one", which is the vacuous pass this whole check exists to make
  // impossible. Caught by its own output on the first run.
  if (rows.length === 0) {
    console.error(
      `\nNo harness declares a \`docs\` graph, which is not a pass: this repository has` +
        ` at least one, so the declarations were not read. Nothing was checked.`,
    );
    process.exit(2);
  }

  const unknown = rows.filter((r) => r.verdict === "unknown");
  const thin = rows.filter((r) => r.verdict === "thin");
  if (unknown.length > 0) {
    console.error(`\n${unknown.length} harness(es) COULD NOT BE DETERMINED. That is not a pass.`);
    process.exit(2);
  }
  if (thin.length > 0) {
    console.error(`\n${thin.length} harness(es) have no meaningfully populated documentation page.`);
    process.exit(1);
  }

  // The subject half, graded in the SAME ORDER as the length half: unknown
  // outranks thin, because a sweep blind on one dimension has not cleared the
  // others. Under --strict only; without it the finding is printed above and
  // the run is green, which is the audit:coverage split and is deliberate.
  const sUnknown = rows.filter((r) => r.subject.verdict === "unknown");
  const sThin = rows.filter((r) => r.subject.verdict === "thin");
  if (strict && sUnknown.length > 0) {
    console.error(
      `\n${sUnknown.length} harness(es) could not be judged on SUBJECT: ` +
        sUnknown.map((r) => r.instance).join(", ") +
        `. That is not a pass.`,
    );
    process.exit(2);
  }
  if (strict && sThin.length > 0) {
    console.error(
      `\n${sThin.length} harness(es) have no page naming a declared process, role and task: ` +
        sThin.map((r) => r.instance).join(", ") +
        `.\nThat is 06e3 §4(a) — the landing pages — not a defect in this check.`,
    );
    process.exit(1);
  }
  if (!asJson) {
    console.log(`\n✓ every harness declaring \`docs\` has one`);
    if (strict) console.log(`✓ and every one names a declared process, role and task`);
    else if (sThin.length + sUnknown.length > 0) {
      console.log(
        `· SUBJECT not cleared for ${sThin.length + sUnknown.length} of ${rows.length}: ` +
          `${sUnknown.length} undetermined, ${sThin.length} thin — reported, not gated. \`--strict\` grades it.`,
      );
    }
  }
}
