classDiagram
  direction TB
  namespace folio_assistant__archive {
    class n_folio_assistant_archive_bean_defs["bean-defs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_archive_bean_defs" fa_uml_kind_bean_defs
  cssClass "n_folio_assistant_archive_bean_defs" fa_uml_undetermined
