classDiagram
  direction TB
  namespace folio_assistant__interaction {
    class folio_assistant_interaction_folio_interaction_v1_folio_interaction_v1["folio-interaction/v1"] {
      <<json: InteractionNodeSchema>>
      $schema [1] 'folio-interaction/v1'
      $comment [0..1] string
      users [1] map~object~
      default [0..1] object
    }
  }
  cssClass "folio_assistant_interaction_folio_interaction_v1_folio_interaction_v1" fa_uml_kind_interaction
