classDiagram
  direction TB
  namespace folio_assistant__issue_marks {
    class folio_assistant_issue_marks_folio_issue_mark_v1_folio_issue_mark_v1["folio-issue-mark/v1"] {
      <<json: IssueMarkSchema>>
      $schema [1] 'folio-issue-mark/v1'
      issue [1] string
      lastCommentId [1] number
      lastUpdatedAt [0..1] string
      checkedAt [1] string
      note [0..1] string
    }
  }
  cssClass "folio_assistant_issue_marks_folio_issue_mark_v1_folio_issue_mark_v1" fa_uml_kind_issue_marks
