classDiagram
  direction TB
  namespace folio_assistant__positions {
    class folio_assistant_positions_BoardPositions["BoardPositions"] {
      <<json: BoardPositionsSchema>>
      $schema [1] 'folio-board-positions/v1'
      boards [1] map~map~object~~
    }
  }
  cssClass "folio_assistant_positions_BoardPositions" fa_uml_kind_board_positions
