classDiagram
  direction TB
  namespace folio_assistant__queue {
    class n_folio_assistant_queue_merge_queue["merge-queue: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_queue_merge_queue" fa_uml_kind_merge_queue
  cssClass "n_folio_assistant_queue_merge_queue" fa_uml_undetermined
