classDiagram
  direction TB
  namespace folio_assistant__root_tools {
    class n_folio_assistant_root_tools_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_root_tools_code" fa_uml_kind_code
  cssClass "n_folio_assistant_root_tools_code" fa_uml_undetermined
