classDiagram
  direction TB
  namespace folio_assistant__uploads {
    class n_folio_assistant_uploads_uploads["uploads: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_uploads_uploads" fa_uml_kind_uploads
  cssClass "n_folio_assistant_uploads_uploads" fa_uml_undetermined
