/**
 * JSON-LD projection of the content block model.
 *
 * Blocks are authored as TypeScript manifests and stay that way — the
 * builders in `builders.ts` are where author-time type checking lives, and
 * `content/pipeline/block-module.ts` treats a manifest that throws on import
 * as a *finding*. This module does not replace any of that. It defines the
 * **published** form: a `.jsonld` sibling next to each `.ts`, generated by
 * `content/pipeline/gen-block-jsonld.ts`, so that
 *
 * 1. an external consumer can reference a block without a TypeScript
 *    toolchain, and
 * 2. authored blocks and *ingested* documents (`library/**`) carry the same
 *    `@context`, the same `@type` vocabulary and the same edge terms — so one
 *    graph loader serves both populations instead of two.
 *
 * ## Why labels are not emitted as IRIs
 *
 * This is the hazard the whole module exists to route around, so it is worth
 * stating plainly.
 *
 * A folio label looks exactly like a JSON-LD compact IRI: `def:foo` has the
 * shape `prefix:reference`. It is not one. The `def:` part names a **block
 * kind**, not a namespace, and JSON-LD splits a compact IRI on its **first**
 * colon. Emitting labels directly as IRI values therefore goes wrong in two
 * different ways:
 *
 * - `def:quantum-universe` would need a `def` prefix in the context, which
 *   would place the block in a per-*kind* namespace. The same block referenced
 *   cross-paper as `some-paper:def:quantum-universe` would then expand under a
 *   per-*paper* namespace instead. **Two IRIs for one block** — every graph
 *   join silently under-counts, with no error anywhere.
 * - `unital-groebner-bases:thm:bar` splits into prefix
 *   `unital-groebner-bases` and suffix `thm:bar`. With no such prefix defined,
 *   JSON-LD falls back to treating the whole string as an absolute IRI — and
 *   `unital-groebner-bases:thm:bar` *is* syntactically valid, with
 *   `unital-groebner-bases` as its scheme. The result is a well-formed IRI
 *   that means nothing and joins with nothing.
 *
 * So `@id` is **minted** by {@link resolveLabel}, which resolves all three
 * authored reference forms to one canonical relative IRI, and the label is
 * additionally preserved verbatim in `folio:label` for grep and round-tripping.
 * Nothing in `content/**` has to change.
 *
 * ## Why `@id` is relative
 *
 * Emitted IRIs are relative (`papers/<paper>/blocks/def-foo`) and `@base`
 * lives in the published context. That keeps generator output identical
 * regardless of where a folio is deployed — which matters because the
 * generated siblings are committed and gated on drift: a base-URL change must
 * not rewrite thousands of files.
 *
 * @module schemas/jsonld
 */

import { BLOCK_KINDS, type BlockKind } from "./block-kinds";

// ── Namespaces ───────────────────────────────────────────────────

/** Folio's own terms — the relations no published vocabulary models. */
export const FOLIO_NS = "https://litlfred.github.io/folio-assistant/ns#";
/** SPAR Document Components Ontology — structural document parts. */
export const DOCO_NS = "http://purl.org/spar/doco/";
/** SPAR Discourse Elements Ontology — rhetorical roles. */
export const DEO_NS = "http://purl.org/spar/deo/";
/** SPAR Citation Typing Ontology. */
export const CITO_NS = "http://purl.org/spar/cito/";
/** W3C Web Annotation — the anchoring layer for ingested candidates. */
export const OA_NS = "http://www.w3.org/ns/oa#";
/** W3C PROV-O — derivation chains from source PDF to block. */
export const PROV_NS = "http://www.w3.org/ns/prov#";
export const SKOS_NS = "http://www.w3.org/2004/02/skos/core#";
export const DCTERMS_NS = "http://purl.org/dc/terms/";
/** HL7 FHIR — the health-policy semantics of the ingest side. */
export const FHIR_NS = "http://hl7.org/fhir/";

/** Where the published `@context` lives. Emitted files reference this URL. */
export const CONTENT_CONTEXT_URL =
  "https://litlfred.github.io/folio-assistant/ns/content/v1.jsonld";

/**
 * Base every minted `@id` is relative to. Declared in the context rather
 * than baked into emitted files — see the module docstring.
 */
export const FOLIO_BASE = "https://litlfred.github.io/folio/";

// ── Block kind → RDF types ───────────────────────────────────────

/**
 * `folio:` type for each block kind. These are folio's own classes because
 * no published vocabulary distinguishes a theorem from a lemma from a
 * conjecture in the way this project's editorial machinery needs.
 */
export const BLOCK_KIND_TO_FOLIO_TYPE: Record<BlockKind, string> = {
  definition: "folio:Definition",
  theorem: "folio:Theorem",
  lemma: "folio:Lemma",
  proposition: "folio:Proposition",
  corollary: "folio:Corollary",
  algorithm: "folio:Algorithm",
  conjecture: "folio:Conjecture",
  example: "folio:Example",
  remark: "folio:Remark",
  proof: "folio:Proof",
  simulator: "folio:Simulator",
  prose: "folio:Prose",
  equation: "folio:Equation",
  diagram: "folio:Diagram",
  table: "folio:Table",
};

/**
 * DoCO co-type, where one is *unambiguously* right.
 *
 * Deliberately partial. A `doco:` co-type is what lets an ingested WHO
 * section and an authored block answer the same query, so it earns its place
 * — but only where the mapping is a fact rather than a stretch. A theorem is
 * a section-like component in DoCO's terms and gets `doco:Section`; a
 * `simulator` block has no DoCO counterpart at all and gets none. Guessing
 * here would put wrong triples in a published graph, which is worse than
 * leaving a kind untyped.
 */
export const BLOCK_KIND_TO_DOCO_TYPE: Partial<Record<BlockKind, string>> = {
  equation: "doco:Formula",
  diagram: "doco:Figure",
  table: "doco:Table",
  prose: "doco:Section",
  definition: "doco:Section",
  theorem: "doco:Section",
  lemma: "doco:Section",
  proposition: "doco:Section",
  corollary: "doco:Section",
  algorithm: "doco:Section",
  conjecture: "doco:Section",
  example: "doco:Section",
  remark: "doco:Section",
  proof: "doco:Section",
};

/** Every `@type` for a block, most specific first. */
export function typesForKind(kind: string): string[] {
  const folio = BLOCK_KIND_TO_FOLIO_TYPE[kind as BlockKind];
  const doco = BLOCK_KIND_TO_DOCO_TYPE[kind as BlockKind];
  const out: string[] = [];
  if (folio) out.push(folio);
  if (doco) out.push(doco);
  return out;
}

// ── Label ↔ IRI segment ──────────────────────────────────────────

/**
 * Label prefixes recognised as *kind* markers, without their colon.
 *
 * Mirrors `KNOWN_LABEL_PREFIXES` in `constraints.ts`, which is the
 * authoritative list; kept here without the trailing colon because every use
 * below is a segment comparison. {@link assertPrefixesInSync} is the guard
 * against the two drifting, and the test suite calls it.
 */
export const KIND_PREFIXES = [
  "def", "thm", "lem", "prop", "cor", "rem", "ex", "conj",
  "prf", "sim", "eq", "fig", "tbl",
  "sec", "chap", "app", "bib",
] as const;

const KIND_PREFIX_SET: ReadonlySet<string> = new Set(KIND_PREFIXES);

/**
 * Throws if `KIND_PREFIXES` has drifted from `constraints.ts`.
 *
 * Takes the constraints list as an argument rather than importing it, so
 * this module stays free of the Zod dependency chain (it is imported by the
 * generator and by tooling that has no reason to pull in schema validation).
 */
export function assertPrefixesInSync(knownLabelPrefixes: readonly string[]): void {
  const theirs = new Set(knownLabelPrefixes.map((p) => p.replace(/:$/, "")));
  const missing = [...theirs].filter((p) => !KIND_PREFIX_SET.has(p));
  const extra = KIND_PREFIXES.filter((p) => !theirs.has(p));
  if (missing.length || extra.length) {
    throw new Error(
      `KIND_PREFIXES is out of sync with KNOWN_LABEL_PREFIXES: ` +
        `missing [${missing.join(", ")}], extra [${extra.join(", ")}]`,
    );
  }
}

/**
 * A parsed reference. `kind: "unresolvable"` is a first-class outcome, not an
 * error path: it is exactly the input that would otherwise become a
 * well-formed but meaningless IRI, and callers must be able to see it.
 */
export type ParsedReference =
  | { form: "absolute"; iri: string }
  | { form: "same-paper"; prefix: string; slug: string }
  | { form: "cross-paper"; namespace: string[]; prefix: string; slug: string }
  | { form: "unresolvable"; raw: string; reason: string };

/**
 * Parse one `uses[]` / `foreshadows[]` / `proofs[]` entry.
 *
 * The grammar, per `schemas/types.ts` and `constraints.ts:citesProvable`,
 * admits an arbitrary namespace path before the kind prefix:
 *
 * ```
 *   def:quantum-universe                          same paper
 *   unital-groebner-bases:cor:pbw                 cross-paper
 *   some-ns:unital-groebner-bases:cor:pbw         nested namespace
 *   https://folio.example.org/papers/foo#def:bar  cross-folio
 * ```
 *
 * The kind prefix is the pivot: everything before it is namespace, everything
 * from it onward is the local label. A slug may itself contain colons
 * (`def:foo:bar`), which is why the *first* kind prefix wins rather than the
 * last colon losing.
 */
export function parseReference(ref: string): ParsedReference {
  if (/^https?:\/\//i.test(ref)) return { form: "absolute", iri: ref };
  if (!ref.includes(":")) {
    return {
      form: "unresolvable",
      raw: ref,
      reason: "no ':' — a label must carry a kind prefix (e.g. \"def:foo\")",
    };
  }

  const parts = ref.split(":");
  const pivot = parts.findIndex((p) => KIND_PREFIX_SET.has(p));
  if (pivot < 0) {
    return {
      form: "unresolvable",
      raw: ref,
      reason:
        `no known kind prefix (${KIND_PREFIXES.slice(0, 4).join("/")}/…) — ` +
        `cannot tell namespace from label`,
    };
  }

  const prefix = parts[pivot]!;
  const slug = parts.slice(pivot + 1).join(":");
  if (!slug) {
    return { form: "unresolvable", raw: ref, reason: "empty slug after kind prefix" };
  }

  if (pivot === 0) return { form: "same-paper", prefix, slug };
  return { form: "cross-paper", namespace: parts.slice(0, pivot), prefix, slug };
}

/**
 * `def:quantum-universe` → `def-quantum-universe`.
 *
 * The colon is replaced rather than kept. RFC 3986 would permit it in a
 * non-first path segment, but a colon there trips relative-reference
 * resolution in enough consumers to be not worth defending. Reversible: no
 * kind prefix contains a hyphen, so the first hyphen is the boundary.
 */
export function labelToSegment(prefix: string, slug: string): string {
  return `${prefix}-${slug}`;
}

/** Inverse of {@link labelToSegment}. Returns undefined for a foreign segment. */
export function segmentToLabel(segment: string): string | undefined {
  const dash = segment.indexOf("-");
  if (dash < 0) return undefined;
  const prefix = segment.slice(0, dash);
  if (!KIND_PREFIX_SET.has(prefix)) return undefined;
  return `${prefix}:${segment.slice(dash + 1)}`;
}

/**
 * Resolve an authored reference to the canonical relative IRI for its block.
 *
 * `paper` is the directory name of the paper the reference was written in —
 * it supplies the namespace for the same-paper form, which is why the caller
 * must pass it rather than this being a pure string function.
 *
 * Returns `undefined` for an unresolvable reference. Callers should report
 * those rather than drop them: an unresolvable entry is a content defect
 * (a typo, or a label whose prefix was never registered), and silently
 * omitting the edge is how a graph loses edges without anyone noticing.
 */
export function resolveLabel(ref: string, paper: string): string | undefined {
  const parsed = parseReference(ref);
  switch (parsed.form) {
    case "absolute":
      return parsed.iri;
    case "same-paper":
      return `papers/${paper}/blocks/${labelToSegment(parsed.prefix, parsed.slug)}`;
    case "cross-paper":
      return (
        `papers/${parsed.namespace.join("/")}/blocks/` +
        labelToSegment(parsed.prefix, parsed.slug)
      );
    case "unresolvable":
      return undefined;
  }
}

/** The IRI for a bibliography key (`cites[]` entries are not labels). */
export function resolveReferenceKey(key: string): string {
  return `references/${key}`;
}

// ── The published @context ───────────────────────────────────────

/**
 * The `@context` served at {@link CONTENT_CONTEXT_URL} and referenced by every
 * emitted `.jsonld` — authored siblings and ingested nodes alike. Written as
 * a value here so `ns/content/v1.jsonld` is generated rather than hand-kept.
 */
export const CONTENT_CONTEXT = {
  "@version": 1.1,
  "@base": FOLIO_BASE,
  folio: FOLIO_NS,
  doco: DOCO_NS,
  deo: DEO_NS,
  cito: CITO_NS,
  oa: OA_NS,
  prov: PROV_NS,
  skos: SKOS_NS,
  dcterms: DCTERMS_NS,
  fhir: FHIR_NS,

  // Identity. `label` is the authored string, kept verbatim alongside the
  // minted `@id` so a grep hit in .jsonld matches a grep hit in .ts.
  label: "folio:label",
  title: "dcterms:title",
  kind: "folio:kind",

  // Editorial relations — folio's own, because no vocabulary models the
  // reader-facing prerequisite relation these encode.
  uses: { "@id": "folio:uses", "@type": "@id", "@container": "@set" },
  interprets: { "@id": "folio:interprets", "@type": "@id" },
  foreshadows: { "@id": "folio:foreshadows", "@type": "@id", "@container": "@set" },
  proofs: { "@id": "folio:proofs", "@type": "@id", "@container": "@set" },
  examples: { "@id": "folio:examples", "@type": "@id", "@container": "@set" },

  cites: { "@id": "cito:cites", "@type": "@id", "@container": "@set" },
  tags: { "@id": "folio:tag", "@container": "@set" },
  defines: { "@id": "folio:defines", "@container": "@set" },

  // Formal side. `leanRef` stays a literal: a Lean declaration is not a web
  // resource, and minting an IRI for one would imply a dereference that does
  // not exist.
  leanRef: "folio:leanRef",
  sorryFree: "folio:sorryFree",

  // Companions, as links rather than inlined content. Inlining prose would
  // duplicate the corpus and make every prose edit a two-file diff.
  text: { "@id": "folio:text", "@type": "@id" },
  leanSource: { "@id": "folio:leanSource", "@type": "@id" },

  meta: { "@id": "folio:meta", "@type": "@json" },

  // Ingest side. Declared in the shared context precisely so that an
  // ingested node and an authored block are the same kind of thing.
  //
  // `contains` maps to `dcterms:hasPart` rather than DoCO's own containment
  // property. DoCO does not define one: it imports `po:contains` from the
  // Pattern Ontology, which is documented as a sub-property of
  // `dcterms:hasPart`. The Pattern Ontology namespace could not be verified
  // from this sandbox (`sparontologies.github.io` is egress-blocked), and a
  // published context is the wrong place to guess an IRI — so this uses the
  // verified super-property. Generalising is sound; inventing is not.
  // Narrow it to `po:contains` once the namespace can be checked.
  contains: { "@id": "dcterms:hasPart", "@type": "@id", "@container": "@set" },
  refs: { "@id": "folio:refs", "@type": "@id", "@container": "@set" },
  derivedFrom: { "@id": "prov:wasDerivedFrom", "@type": "@id" },
  sourceDocument: { "@id": "folio:sourceDocument", "@type": "@id" },
  provenance: "folio:provenance",
  pageStart: "folio:pageStart",
  pageEnd: "folio:pageEnd",
  strength: "folio:strength",
  // No `certainty` term yet. It must bind to FHIR's GRADE value set
  // (`QualityOfEvidenceRating` on HL7 Terminology), and the exact predicate
  // wants checking against a real IG rather than guessed — it lands with the
  // ingest writer, which is the first thing that will emit one.
} as const;

/** Kinds with no DoCO counterpart — surfaced by the generator's summary. */
export const KINDS_WITHOUT_DOCO_TYPE = BLOCK_KINDS.filter(
  (k) => !BLOCK_KIND_TO_DOCO_TYPE[k],
);
