/**
 * Translation status, metadata, and node schemas for localized content.
 *
 * ## The translations/ directory
 *
 * The top-level `translations/` directory contains **only** `.pot` templates,
 * `.po` translated files, and their `.ts` manifests (TranslationNode).
 * Rendered output (`.md`), QA sidecars (`.qa.json`), and status metadata
 * are properties of the TranslationNode manifest, not loose files.
 *
 * ```
 * translations/
 *   fr/
 *     index.ts            ← TranslationNode manifest (KG node)
 *     index.pot           ← POT template (extractable strings)
 *     index.po            ← PO translated strings
 *     agent-onboarding.ts
 *     agent-onboarding.pot
 *     agent-onboarding.po
 *     glossary.ts         ← shared glossary PO (no POT — hand-authored)
 *     glossary.po
 * ```
 *
 * Each `.ts` file is a `TranslationNode` that references its `.po` and
 * `.pot` siblings. This makes every translation file a **node in the
 * knowledge graph** — addressable by label, discoverable by the pipeline,
 * and validatable by the same content-object infrastructure that manages
 * content blocks.
 *
 * ## PO source resolution (fallback behavior)
 *
 * When a content block does NOT declare `poSources[]` (the common case),
 * the pipeline resolves PO files by convention:
 *
 * 1. **Block-level:** `translations/<locale>/<block-stem>.po`
 * 2. **Chapter-level:** `translations/<locale>/<chapter-slug>.po`
 * 3. **Folio-level:** `translations/<locale>/global.po`
 * 4. **Dependency walk:** `harness.config.json` dependencies, depth-first
 *
 * When `poSources[]` IS declared on BlockBase, only the listed files are
 * consulted (no fallback). Later entries override earlier for the same msgid.
 *
 * ## Official vs unofficial
 *
 * An **official** translation has received human adjudication / sign-off.
 * An **unofficial** translation is agentic — generated by an LLM or
 * machine translation tool, possibly from an existing `.po` file. The
 * distinction is not quality (an unofficial translation may be excellent);
 * it is **accountability** — official means a named human has reviewed and
 * approved the translation for this source version.
 *
 * ## Staleness
 *
 * An official translation whose source content has changed since sign-off
 * is **stale**. The `sourceHash` field is the SHA-256 of the source `.md`
 * at sign-off time. The pipeline computes the current hash and compares;
 * a mismatch sets `stale: true`. The translation remains visible with a
 * warning — it is not hidden, because a stale official translation is
 * still more trustworthy than no translation.
 *
 * ## Sign-off levels
 *
 * A human can sign off at any level of the content hierarchy (block,
 * section, chapter, folio). The `level` field records this. A lower-level
 * sign-off overrides a higher-level one for that specific node.
 *
 * @module schemas/translation
 * @graphNode schema
 */

import { z } from "zod";

// ── BCP 47 locale tag ────────────────────────────────────────────

/**
 * The six UN official languages, as BCP 47 primary language subtags.
 *
 * These are the default `supportedLocales` in `harness.config.json`. A folio
 * may add or remove locales; this list is the platform default, not a
 * constraint.
 */
export const UN_LOCALES = ["ar", "zh", "en", "fr", "ru", "es"] as const;
export type UnLocale = (typeof UN_LOCALES)[number];

/**
 * Human-readable native names for the UN languages, for the viewer's
 * language switcher dropdown.
 */
export const LOCALE_NAMES: Record<UnLocale, string> = {
  ar: "العربية",
  zh: "中文",
  en: "English",
  fr: "Français",
  ru: "Русский",
  es: "Español",
};

/**
 * Whether the locale's primary script direction is right-to-left.
 * The viewer reads this to set `dir="rtl"` on the content container.
 */
export const LOCALE_RTL: Partial<Record<string, boolean>> = {
  ar: true,
  he: true,
  fa: true,
  ur: true,
};

// ── Translation status schema ────────────────────────────────────

/** The hierarchy level at which a sign-off was recorded. */
export const SIGNOFF_LEVELS = ["block", "section", "chapter", "folio"] as const;
export type SignoffLevel = (typeof SIGNOFF_LEVELS)[number];

/**
 * The shape of `translations/<locale>/status.json`.
 *
 * Every field is optional except `locale`, because a status file with no
 * locale is ambiguous — the directory name carries the locale, but the file
 * must be self-describing for tools that read it outside the tree.
 */
export interface TranslationStatus {
  /** BCP 47 locale tag (must match the enclosing directory name). */
  locale: string;

  /** Whether a human has signed off on this translation. */
  official: boolean;

  /**
   * Whether the source content has changed since the last sign-off.
   * Only meaningful when `official` is true.
   */
  stale?: boolean;

  // ── Official fields (present when official: true) ──────────────

  /** Who signed off. A human identifier (GitHub username, email, etc.). */
  signedOffBy?: string;

  /** ISO 8601 timestamp of the sign-off. */
  signedOffAt?: string;

  /**
   * SHA-256 hash of the source `.md` content at sign-off time.
   * Used for staleness detection: if the current source hash differs,
   * the translation is stale.
   */
  sourceHash?: string;

  /** The hierarchy level at which the sign-off was recorded. */
  level?: SignoffLevel;

  // ── Unofficial fields (present when official: false) ───────────

  /** What generated the translation. */
  generatedBy?: "agent" | "machine" | "human-draft" | string;

  /** ISO 8601 timestamp of generation. */
  generatedAt?: string;

  /** The tool or model used (e.g. "DeepL", "GPT-4o", "google-translate"). */
  generator?: string;

  /**
   * Whether the translation has been flagged for review.
   * Typically set by round-trip QA when semantic drift is detected.
   */
  flaggedForReview?: boolean;

  /** Reason for flagging, if any. */
  flagReason?: string;
}

/** Zod schema for `TranslationStatus`. */
export const TranslationStatusSchema = z.object({
  locale: z.string().min(2),
  official: z.boolean(),
  stale: z.boolean().optional(),

  signedOffBy: z.string().min(1).optional(),
  signedOffAt: z.string().datetime({ offset: true }).optional(),
  sourceHash: z.string().min(1).optional(),
  level: z.enum(SIGNOFF_LEVELS).optional(),

  generatedBy: z.string().min(1).optional(),
  generatedAt: z.string().datetime({ offset: true }).optional(),
  generator: z.string().min(1).optional(),

  flaggedForReview: z.boolean().optional(),
  flagReason: z.string().min(1).optional(),
});

// ── TranslationNode — .ts manifest for PO/POT files ─────────────

/**
 * A **TranslationNode** is a `.ts` manifest that wraps a `.po`/`.pot` pair
 * as a first-class node in the knowledge graph.
 *
 * ## Why .ts manifests?
 *
 * Raw `.po` and `.pot` files are opaque to the content-object model —
 * the pipeline can list them from the filesystem, but they are not nodes
 * that can be:
 *
 * - **addressed by label** (`"trans:fr/index"`)
 * - **referenced in `uses[]` or `poSources[]`**
 * - **validated** by the same Zod-based schema infrastructure
 * - **queried** as edges in the knowledge graph
 *
 * The `.ts` manifest makes them all of those things. It is a thin wrapper
 * — the translation content stays in the `.po` file, but the node carries
 * the metadata that makes it a first-class citizen.
 *
 * ## File layout
 *
 * ```
 * translations/fr/index.ts      ← this manifest
 * translations/fr/index.pot     ← POT template (optional — omit for glossaries)
 * translations/fr/index.po      ← PO translated strings
 * ```
 *
 * ## Example manifest
 *
 * ```ts
 * import type { TranslationNode } from "../../schemas/translation";
 *
 * const node: TranslationNode = {
 *   label: "trans:fr/index",
 *   locale: "fr",
 *   sourceFile: "docs/index.md",
 *   potFile: "translations/fr/index.pot",
 *   poFile: "translations/fr/index.po",
 *   status: { locale: "fr", official: false, generatedBy: "agent" },
 *   coverage: { translated: 37, total: 37, pct: 100 },
 * };
 * export default node;
 * ```
 */
export interface TranslationNode {
  /**
   * Label following the `trans:<locale>/<stem>` convention.
   *
   * This is the KG-addressable identifier. Content blocks reference it
   * in `poSources[]`, and the dependency graph can walk edges to it.
   */
  label: string;

  /** BCP 47 locale tag of the target language. */
  locale: string;

  /**
   * Path (relative to folio root) of the **source** file this PO
   * translates. For content blocks, this is the `.md` sibling.
   */
  sourceFile: string;

  /**
   * SHA-256 hash (12-char prefix) of the source file at extraction time.
   * Used for staleness detection — if the current source hash differs,
   * the POT is stale and needs re-extraction.
   */
  sourceHash?: string;

  /**
   * Path to the `.pot` template file (relative to folio root).
   * Optional — omit for hand-authored glossary PO files that have no
   * extractable source.
   */
  potFile?: string;

  /**
   * Path to the `.po` translated file (relative to folio root).
   * This is the file that carries the actual translations.
   */
  poFile: string;

  /**
   * One or more additional PO files this translation depends on.
   * Useful for shared glossaries or terminology POs that provide
   * base translations overridden by the primary `poFile`.
   *
   * Loaded in order; the primary `poFile` is loaded last and
   * overrides any duplicates.
   */
  poIncludes?: string[];

  /** Translation status (official/unofficial, staleness, etc.). */
  status: TranslationStatus;

  /** Translation coverage metrics. */
  coverage?: {
    /** Number of msgid entries with a non-empty msgstr. */
    translated: number;
    /** Total msgid entries in the POT. */
    total: number;
    /** Coverage percentage (0–100). */
    pct: number;
  };

  /**
   * There is deliberately no `roundTripQA` here any more.
   *
   * It held `{ pass, warn, fail, total, method }` for the whole node, written
   * by `simulate-translation.ts` — whose `BACK_TRANSLATIONS` map had **6
   * entries against 36 msgids**. Every string with no back-translation scored
   * a similarity of 0 and was recorded as drift, so `fail: 21` on the French
   * landing page counted strings that were never back-translated at all.
   * Absence was being published as a measurement.
   *
   * Semantic verification now lives per block, in
   * `<stem>.<locale>.translation-qa.json` (`translation-qa/v1`), where a
   * verdict carries the witness that reached it — a script, an agent or a
   * person, with a timestamp and the hashes it was measured against. A
   * node-level summary field with no producer is an invitation to fill it
   * with a plausible number again.
   *
   * @see content/pipeline/translation-block-qa.ts
   * @see content/pipeline/translation-roundtrip.ts
   */

  /** Optional title for display in the viewer / docs. */
  title?: string;

  /** Optional description of what this PO file covers. */
  description?: string;
}

/** Zod schema for `TranslationNode`. */
export const TranslationNodeSchema = z.object({
  label: z.string().regex(/^trans:[a-z]{2,}\//, {
    message: 'label must follow "trans:<locale>/<stem>" convention',
  }),
  locale: z.string().min(2),
  sourceFile: z.string().min(1),
  sourceHash: z.string().min(1).optional(),
  potFile: z.string().endsWith(".pot").optional(),
  poFile: z.string().endsWith(".po"),
  poIncludes: z.array(z.string().endsWith(".po")).optional(),
  status: TranslationStatusSchema,
  coverage: z
    .object({
      translated: z.number().int().min(0),
      total: z.number().int().min(0),
      pct: z.number().min(0).max(100),
    })
    .optional(),
  title: z.string().optional(),
  description: z.string().optional(),
});

// ── Translation config (harness.config.json section) ───────────────

/** The `translation` section of `harness.config.json`. */
export interface TranslationConfig {
  /** BCP 47 tag for the source language. Default: "en". */
  defaultLocale: string;

  /** Locales the folio supports. Default: the six UN languages. */
  supportedLocales: string[];

  /** Subdirectory name within content nodes. Default: "translations". */
  translationDir: string;

  /**
   * Whether to generate one POT per block, per chapter, or one for the
   * whole folio.
   */
  potGranularity: "block" | "chapter" | "folio";

  /**
   * If true, only official translations are shown in the viewer.
   * Default: false (unofficial translations are shown with a badge).
   */
  officialRequired: boolean;
}

/** Zod schema for `TranslationConfig`. */
export const TranslationConfigSchema = z.object({
  defaultLocale: z.string().min(2).default("en"),
  supportedLocales: z.array(z.string().min(2)).default([...UN_LOCALES]),
  translationDir: z.string().min(1).default("translations"),
  potGranularity: z.enum(["block", "chapter", "folio"]).default("block"),
  officialRequired: z.boolean().default(false),
});

// ── Kind heading translations ────────────────────────────────────

/**
 * Translatable kind headings for the six UN languages.
 *
 * These replace the hardcoded `KIND_HEADING` map in `render-markdown.ts`.
 * The viewer and the render pipeline both read this map to produce
 * locale-appropriate block headers.
 *
 * Entries cover all paper block kinds. DAK kinds use their own heading
 * convention (the kind name itself, title-cased).
 */
export const KIND_HEADINGS: Record<string, Record<string, string>> = {
  en: {
    definition: "Definition",
    theorem: "Theorem",
    lemma: "Lemma",
    proposition: "Proposition",
    corollary: "Corollary",
    algorithm: "Algorithm",
    conjecture: "Conjecture",
    example: "Example",
    remark: "Remark",
    proof: "Proof",
    simulator: "Simulator",
    equation: "Equation",
    diagram: "Figure",
    table: "Table",
    prose: "",
  },
  fr: {
    definition: "Définition",
    theorem: "Théorème",
    lemma: "Lemme",
    proposition: "Proposition",
    corollary: "Corollaire",
    algorithm: "Algorithme",
    conjecture: "Conjecture",
    example: "Exemple",
    remark: "Remarque",
    proof: "Preuve",
    simulator: "Simulateur",
    equation: "Équation",
    diagram: "Figure",
    table: "Tableau",
    prose: "",
  },
  es: {
    definition: "Definición",
    theorem: "Teorema",
    lemma: "Lema",
    proposition: "Proposición",
    corollary: "Corolario",
    algorithm: "Algoritmo",
    conjecture: "Conjetura",
    example: "Ejemplo",
    remark: "Observación",
    proof: "Demostración",
    simulator: "Simulador",
    equation: "Ecuación",
    diagram: "Figura",
    table: "Tabla",
    prose: "",
  },
  ar: {
    definition: "تعريف",
    theorem: "مبرهنة",
    lemma: "تمهيدية",
    proposition: "قضية",
    corollary: "نتيجة طبيعية",
    algorithm: "خوارزمية",
    conjecture: "حدسية",
    example: "مثال",
    remark: "ملاحظة",
    proof: "برهان",
    simulator: "محاكي",
    equation: "معادلة",
    diagram: "شكل",
    table: "جدول",
    prose: "",
  },
  zh: {
    definition: "定义",
    theorem: "定理",
    lemma: "引理",
    proposition: "命题",
    corollary: "推论",
    algorithm: "算法",
    conjecture: "猜想",
    example: "例",
    remark: "注",
    proof: "证明",
    simulator: "模拟器",
    equation: "方程",
    diagram: "图",
    table: "表",
    prose: "",
  },
  ru: {
    definition: "Определение",
    theorem: "Теорема",
    lemma: "Лемма",
    proposition: "Предложение",
    corollary: "Следствие",
    algorithm: "Алгоритм",
    conjecture: "Гипотеза",
    example: "Пример",
    remark: "Замечание",
    proof: "Доказательство",
    simulator: "Симулятор",
    equation: "Уравнение",
    diagram: "Рисунок",
    table: "Таблица",
    prose: "",
  },
};

/**
 * Look up the translated heading for a block kind in a given locale.
 * Falls back to English, then to the kind name title-cased.
 */
export function kindHeading(kind: string, locale: string): string {
  const lang = locale.split("-")[0]; // "zh-Hans" → "zh"
  return (
    KIND_HEADINGS[lang]?.[kind] ??
    KIND_HEADINGS["en"]?.[kind] ??
    kind.charAt(0).toUpperCase() + kind.slice(1)
  );
}
