/**
 * Translation status and metadata for localized content nodes.
 *
 * Each translated content node (block, section, chapter) carries a
 * `status.json` in its `translations/<locale>/` directory. This module
 * defines the shape of that file and the Zod schema that validates it.
 *
 * ## Official vs unofficial
 *
 * An **official** translation has received human adjudication / sign-off.
 * An **unofficial** translation is agentic — generated by an LLM or
 * machine translation tool, possibly from an existing `.po` file. The
 * distinction is not quality (an unofficial translation may be excellent);
 * it is **accountability** — official means a named human has reviewed and
 * approved the translation for this source version.
 *
 * ## Staleness
 *
 * An official translation whose source content has changed since sign-off
 * is **stale**. The `sourceHash` field is the SHA-256 of the source `.md`
 * at sign-off time. The pipeline computes the current hash and compares;
 * a mismatch sets `stale: true`. The translation remains visible with a
 * warning — it is not hidden, because a stale official translation is
 * still more trustworthy than no translation.
 *
 * ## Sign-off levels
 *
 * A human can sign off at any level of the content hierarchy (block,
 * section, chapter, folio). The `level` field records this. A lower-level
 * sign-off overrides a higher-level one for that specific node.
 *
 * @module schemas/translation
 */

import { z } from "zod";

// ── BCP 47 locale tag ────────────────────────────────────────────

/**
 * The six UN official languages, as BCP 47 primary language subtags.
 *
 * These are the default `supportedLocales` in `folio.config.json`. A folio
 * may add or remove locales; this list is the platform default, not a
 * constraint.
 */
export const UN_LOCALES = ["ar", "zh", "en", "fr", "ru", "es"] as const;
export type UnLocale = (typeof UN_LOCALES)[number];

/**
 * Human-readable native names for the UN languages, for the viewer's
 * language switcher dropdown.
 */
export const LOCALE_NAMES: Record<UnLocale, string> = {
  ar: "العربية",
  zh: "中文",
  en: "English",
  fr: "Français",
  ru: "Русский",
  es: "Español",
};

/**
 * Whether the locale's primary script direction is right-to-left.
 * The viewer reads this to set `dir="rtl"` on the content container.
 */
export const LOCALE_RTL: Partial<Record<string, boolean>> = {
  ar: true,
  he: true,
  fa: true,
  ur: true,
};

// ── Translation status schema ────────────────────────────────────

/** The hierarchy level at which a sign-off was recorded. */
export const SIGNOFF_LEVELS = ["block", "section", "chapter", "folio"] as const;
export type SignoffLevel = (typeof SIGNOFF_LEVELS)[number];

/**
 * The shape of `translations/<locale>/status.json`.
 *
 * Every field is optional except `locale`, because a status file with no
 * locale is ambiguous — the directory name carries the locale, but the file
 * must be self-describing for tools that read it outside the tree.
 */
export interface TranslationStatus {
  /** BCP 47 locale tag (must match the enclosing directory name). */
  locale: string;

  /** Whether a human has signed off on this translation. */
  official: boolean;

  /**
   * Whether the source content has changed since the last sign-off.
   * Only meaningful when `official` is true.
   */
  stale?: boolean;

  // ── Official fields (present when official: true) ──────────────

  /** Who signed off. A human identifier (GitHub username, email, etc.). */
  signedOffBy?: string;

  /** ISO 8601 timestamp of the sign-off. */
  signedOffAt?: string;

  /**
   * SHA-256 hash of the source `.md` content at sign-off time.
   * Used for staleness detection: if the current source hash differs,
   * the translation is stale.
   */
  sourceHash?: string;

  /** The hierarchy level at which the sign-off was recorded. */
  level?: SignoffLevel;

  // ── Unofficial fields (present when official: false) ───────────

  /** What generated the translation. */
  generatedBy?: "agent" | "machine" | "human-draft" | string;

  /** ISO 8601 timestamp of generation. */
  generatedAt?: string;

  /** The tool or model used (e.g. "DeepL", "GPT-4o", "google-translate"). */
  generator?: string;

  /**
   * Whether the translation has been flagged for review.
   * Typically set by round-trip QA when semantic drift is detected.
   */
  flaggedForReview?: boolean;

  /** Reason for flagging, if any. */
  flagReason?: string;
}

/** Zod schema for `TranslationStatus`. */
export const TranslationStatusSchema = z.object({
  locale: z.string().min(2),
  official: z.boolean(),
  stale: z.boolean().optional(),

  signedOffBy: z.string().min(1).optional(),
  signedOffAt: z.string().datetime({ offset: true }).optional(),
  sourceHash: z.string().min(1).optional(),
  level: z.enum(SIGNOFF_LEVELS).optional(),

  generatedBy: z.string().min(1).optional(),
  generatedAt: z.string().datetime({ offset: true }).optional(),
  generator: z.string().min(1).optional(),

  flaggedForReview: z.boolean().optional(),
  flagReason: z.string().min(1).optional(),
});

// ── Translation config (folio.config.json section) ───────────────

/** The `translation` section of `folio.config.json`. */
export interface TranslationConfig {
  /** BCP 47 tag for the source language. Default: "en". */
  defaultLocale: string;

  /** Locales the folio supports. Default: the six UN languages. */
  supportedLocales: string[];

  /** Subdirectory name within content nodes. Default: "translations". */
  translationDir: string;

  /**
   * Whether to generate one POT per block, per chapter, or one for the
   * whole folio.
   */
  potGranularity: "block" | "chapter" | "folio";

  /**
   * If true, only official translations are shown in the viewer.
   * Default: false (unofficial translations are shown with a badge).
   */
  officialRequired: boolean;
}

/** Zod schema for `TranslationConfig`. */
export const TranslationConfigSchema = z.object({
  defaultLocale: z.string().min(2).default("en"),
  supportedLocales: z.array(z.string().min(2)).default([...UN_LOCALES]),
  translationDir: z.string().min(1).default("translations"),
  potGranularity: z.enum(["block", "chapter", "folio"]).default("block"),
  officialRequired: z.boolean().default(false),
});

// ── Kind heading translations ────────────────────────────────────

/**
 * Translatable kind headings for the six UN languages.
 *
 * These replace the hardcoded `KIND_HEADING` map in `render-markdown.ts`.
 * The viewer and the render pipeline both read this map to produce
 * locale-appropriate block headers.
 *
 * Entries cover all paper block kinds. DAK kinds use their own heading
 * convention (the kind name itself, title-cased).
 */
export const KIND_HEADINGS: Record<string, Record<string, string>> = {
  en: {
    definition: "Definition",
    theorem: "Theorem",
    lemma: "Lemma",
    proposition: "Proposition",
    corollary: "Corollary",
    algorithm: "Algorithm",
    conjecture: "Conjecture",
    example: "Example",
    remark: "Remark",
    proof: "Proof",
    simulator: "Simulator",
    equation: "Equation",
    diagram: "Figure",
    table: "Table",
    prose: "",
  },
  fr: {
    definition: "Définition",
    theorem: "Théorème",
    lemma: "Lemme",
    proposition: "Proposition",
    corollary: "Corollaire",
    algorithm: "Algorithme",
    conjecture: "Conjecture",
    example: "Exemple",
    remark: "Remarque",
    proof: "Preuve",
    simulator: "Simulateur",
    equation: "Équation",
    diagram: "Figure",
    table: "Tableau",
    prose: "",
  },
  es: {
    definition: "Definición",
    theorem: "Teorema",
    lemma: "Lema",
    proposition: "Proposición",
    corollary: "Corolario",
    algorithm: "Algoritmo",
    conjecture: "Conjetura",
    example: "Ejemplo",
    remark: "Observación",
    proof: "Demostración",
    simulator: "Simulador",
    equation: "Ecuación",
    diagram: "Figura",
    table: "Tabla",
    prose: "",
  },
  ar: {
    definition: "تعريف",
    theorem: "مبرهنة",
    lemma: "تمهيدية",
    proposition: "قضية",
    corollary: "نتيجة طبيعية",
    algorithm: "خوارزمية",
    conjecture: "حدسية",
    example: "مثال",
    remark: "ملاحظة",
    proof: "برهان",
    simulator: "محاكي",
    equation: "معادلة",
    diagram: "شكل",
    table: "جدول",
    prose: "",
  },
  zh: {
    definition: "定义",
    theorem: "定理",
    lemma: "引理",
    proposition: "命题",
    corollary: "推论",
    algorithm: "算法",
    conjecture: "猜想",
    example: "例",
    remark: "注",
    proof: "证明",
    simulator: "模拟器",
    equation: "方程",
    diagram: "图",
    table: "表",
    prose: "",
  },
  ru: {
    definition: "Определение",
    theorem: "Теорема",
    lemma: "Лемма",
    proposition: "Предложение",
    corollary: "Следствие",
    algorithm: "Алгоритм",
    conjecture: "Гипотеза",
    example: "Пример",
    remark: "Замечание",
    proof: "Доказательство",
    simulator: "Симулятор",
    equation: "Уравнение",
    diagram: "Рисунок",
    table: "Таблица",
    prose: "",
  },
};

/**
 * Look up the translated heading for a block kind in a given locale.
 * Falls back to English, then to the kind name title-cased.
 */
export function kindHeading(kind: string, locale: string): string {
  const lang = locale.split("-")[0]; // "zh-Hans" → "zh"
  return (
    KIND_HEADINGS[lang]?.[kind] ??
    KIND_HEADINGS["en"]?.[kind] ??
    kind.charAt(0).toUpperCase() + kind.slice(1)
  );
}
