#!/usr/bin/env python3
"""
generate_weblate_yaml.py — Generate weblate.yaml from sushi-config.yaml and
discovered .pot components.

Reads translation configuration from sushi-config.yaml#translations (languages,
plural forms, services) and dynamically discovers .pot files to produce a
complete weblate.yaml that stays in sync with the repo.  This eliminates
manual maintenance of weblate.yaml.

Usage:
    python generate_weblate_yaml.py [--repo-root .] [--output weblate.yaml]

Author: WHO SMART Guidelines Team
"""

import argparse
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
from urllib.parse import urlparse

# Add parent directory to path for sibling imports
sys.path.insert(0, str(Path(__file__).resolve().parent))

from translation_config import (
    DakConfig,
    DakConfigError,
    LanguageEntry,
    TranslationComponent,
    discover_components,
    get_languages,
    load_dak_config,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# YAML serialisation helpers (hand-rolled to avoid PyYAML dependency)
# ---------------------------------------------------------------------------

def _yaml_scalar(value: Any) -> str:
    """Format a scalar value for YAML output."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    s = str(value)
    # Quote if the string contains special YAML characters
    if any(ch in s for ch in (":", "{", "}", "[", "]", ",", "&", "*", "#",
                               "?", "|", "-", "<", ">", "=", "!", "%", "@",
                               "\n")):
        escaped = s.replace('"', '\\"')
        return f'"{escaped}"'
    if not s or s in ("true", "false", "null", "yes", "no"):
        return f'"{s}"'
    return s


def _indent(level: int) -> str:
    return "  " * level


# ---------------------------------------------------------------------------
# Component-specific check_flags
# ---------------------------------------------------------------------------

# Components whose .pot files contain PlantUML source get extra check_flags
# to protect reserved keywords from translation.
_PLANTUML_CHECK_FLAGS = (
    "placeholders:^@startuml|^@enduml|participant|control|entity"
    "|actor|boundary|database|collections|queue|skinparam"
)


def _check_flags_for_component(comp: TranslationComponent) -> Optional[str]:
    """Return Weblate check_flags string if the component needs one."""
    # If the component sits under images-source (PlantUML diagrams) add
    # PlantUML keyword placeholders.
    rel = str(comp.translations_dir)
    if "images-source" in rel:
        return _PLANTUML_CHECK_FLAGS
    return None


# ---------------------------------------------------------------------------
# YAML generation
# ---------------------------------------------------------------------------

def _derive_repo_url(config: DakConfig) -> str:
    """Derive the GitHub repo URL from dak.json fields."""
    preview = config.raw.get("previewUrl", "")
    # previewUrl is usually https://WorldHealthOrganization.github.io/smart-base
    if not preview:
        return ""
    parsed = urlparse(preview)
    # urlparse lowercases hostname; use netloc to preserve original case
    netloc = parsed.netloc or ""
    hostname_lower = parsed.hostname or ""
    # Only accept *.github.io hostnames (not arbitrary URLs containing "github.io")
    if not hostname_lower.endswith(".github.io"):
        return ""
    # netloc preserves case: "WorldHealthOrganization.github.io"
    org = netloc.split(".")[0] if "." in netloc else ""
    path_parts = [p for p in parsed.path.split("/") if p]
    if org and path_parts:
        repo = path_parts[0]
        return f"https://github.com/{org}/{repo}"
    return ""


def _derive_publication_url(config: DakConfig) -> str:
    """Derive the publication URL from dak.json fields."""
    return config.raw.get("publicationUrl", "")


def generate_weblate_yaml(
    config: DakConfig,
    components: List[TranslationComponent],
    repo_root: Path,
) -> str:
    """
    Generate the complete weblate.yaml content as a string.

    All values are derived from dak.json and the discovered .pot components.
    """
    lines: List[str] = []
    repo_url = _derive_repo_url(config)
    pub_url = _derive_publication_url(config)
    languages = get_languages(config)

    # Header comment
    lines.append("# weblate.yaml — Weblate configuration for "
                 f"{config.title or config.name}")
    lines.append("#")
    lines.append("# AUTO-GENERATED by generate_weblate_yaml.py from sushi-config.yaml.")
    lines.append("# Do not edit manually — re-run the generator instead:")
    lines.append("#   python input/scripts/generate_weblate_yaml.py")
    lines.append("#")
    lines.append(f"# Source: sushi-config.yaml ({config.id} v{config.version})")
    lines.append("")

    # Project section
    lines.append("project:")
    lines.append(f"  name: {_yaml_scalar(config.title or config.name)}")
    if repo_url:
        lines.append(f"  url: {repo_url}")
    if pub_url:
        lines.append(f"  web: {pub_url}")
    lines.append("")

    # Components section
    lines.append("components:")
    for comp in components:
        rel_dir = str(comp.translations_dir.relative_to(repo_root))
        rel_pot = str(comp.pot_path.relative_to(repo_root))
        lines.append("")
        lines.append(f"  - name: {_yaml_scalar(comp.slug)}")
        lines.append(f"    slug: {comp.slug}")
        if repo_url:
            lines.append(f"    repo: {repo_url}")
            lines.append(f"    push: {repo_url}")
        lines.append("    branch: main")
        lines.append(f"    filemask: {rel_dir}/*.po")
        lines.append(f"    template: {rel_pot}")
        lines.append(f"    new_base: {rel_pot}")
        lines.append("    file_format: po")
        lines.append("    vcs: git")
        if pub_url:
            lines.append(f"    screenshot_url: {pub_url}")
        lines.append("    push_on_commit: false")
        lines.append("    commit_pending_age: 24")
        check_flags = _check_flags_for_component(comp)
        if check_flags:
            lines.append(f"    check_flags: {_yaml_scalar(check_flags)}")

    lines.append("")

    # Workflow section
    lines.append("# Quality control workflow")
    lines.append("workflow:")
    lines.append("  approval_required: true")
    lines.append("  suggestion_voting: true")
    lines.append("  machine_translation:")
    lines.append("    - service: libretranslate")
    lines.append("")

    # Languages section
    lines.append("# Languages from sushi-config.yaml#translations.languages")
    lines.append("languages:")
    for lang in languages:
        lines.append(f"  - code: {lang.code}")
        lines.append(f"    name: {_yaml_scalar(lang.name)}")
        lines.append(f"    direction: {lang.direction}")
        if lang.plural:
            lines.append(f"    plural: {_yaml_scalar(lang.plural)}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )

    parser = argparse.ArgumentParser(
        prog="generate_weblate_yaml.py",
        description="Generate weblate.yaml from sushi-config.yaml + discovered .pot files",
    )
    parser.add_argument(
        "--repo-root", default=".",
        help="Path to repository root (default: current directory)",
    )
    parser.add_argument(
        "--output", default=None,
        help="Output file path (default: <repo-root>/weblate.yaml)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print to stdout instead of writing file",
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()

    # Load config (translations from sushi-config.yaml, identity from dak.json)
    try:
        config = load_dak_config(repo_root)
    except DakConfigError as exc:
        logger.error("Configuration error: %s", exc)
        return 1

    if not config.translations:
        logger.error("No translations block in sushi-config.yaml or dak.json — nothing to generate")
        return 1

    # Check that Weblate is enabled
    weblate_svc = config.translations.services.get("weblate")
    if not weblate_svc or not weblate_svc.enabled:
        logger.warning("Weblate is not enabled — generating anyway")

    # Discover components
    components = discover_components(repo_root)
    if not components:
        logger.warning("No .pot files found — weblate.yaml will have no components")

    logger.info("Discovered %d component(s):", len(components))
    for comp in components:
        logger.info("  %s → %s", comp.slug, comp.pot_path.relative_to(repo_root))

    # Generate YAML
    yaml_content = generate_weblate_yaml(config, components, repo_root)

    if args.dry_run:
        print(yaml_content)
    else:
        output_path = Path(args.output) if args.output else repo_root / "weblate.yaml"
        output_path.write_text(yaml_content, encoding="utf-8")
        logger.info("Wrote %s", output_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
