/**
 * bootstrap's schemas, drawn — the page a person reads instead of raw JSON.
 *
 * @module scripts/bootstrap-schema-page
 *
 * `bootstrap/README.md` defines every term by linking it to
 * `schemas/graph.schema.json#/$defs/<Term>`, and on GitHub that link opens a
 * JSON document. Correct for a program, unkind to a person (owner,
 * 2026-09-29: *"references like A Knowledge Graph … are not nice for human
 * users. can you make a textual/visual repn like ascii UML of the various
 * schemas? preserve existing [src link]"*).
 *
 * So this renders `bootstrap/schemas/README.md` FROM the published schema
 * documents: one ASCII class box per JSON object, the conditional rules in
 * words, and one heading per defined term with a `[src]` link back to its
 * `$defs` entry. It is generated by `gen-bootstrap-schemas.ts` in the same
 * run as the documents it draws, so `bootstrap:schemas:check` fails the
 * moment the two differ — a hand-drawn diagram would be a second answer free
 * to disagree with the first.
 *
 * ## Why ASCII and not a diagram language
 *
 * A Bootstrapping Agent reads files with a text editor and nothing else. An
 * ASCII box reads the same in an editor, in a terminal and on GitHub; a
 * Mermaid block renders on GitHub and is source code everywhere else.
 *
 * ## Why this module has no side effects
 *
 * `gen-bootstrap-schemas.ts` writes its targets at module scope, so a test
 * that imported it would write into `bootstrap/` — the `ymsu` shape, where a
 * test writes what a later gate reads. The rendering lives here so the test
 * can import it and write nothing.
 *
 * ## It refuses what it cannot draw
 *
 * A schema construct this does not understand — a new conditional shape, an
 * object with no properties — throws rather than being left out. A page that
 * silently omits a rule reads as a complete description of a schema it is not.
 */

/** A JSON Schema node, as the generator emits it. Only what is drawn is typed. */
interface SchemaNode {
  type?: string | string[];
  title?: string;
  description?: string;
  properties?: Record<string, SchemaNode>;
  required?: string[];
  items?: SchemaNode;
  /** A keyed map's value shape, e.g. the ledger's `concepts`. */
  additionalProperties?: SchemaNode | boolean;
  minItems?: number;
  enum?: unknown[];
  const?: unknown;
  anyOf?: SchemaNode[];
  oneOf?: SchemaNode[];
  allOf?: unknown[];
  $defs?: Record<string, { title?: string; description?: string }>;
}

/** One published document, and how the page should present it. */
export interface PageDocument {
  /** File name beside the page, e.g. `graph.schema.json`. */
  file: string;
  /** The parsed document the generator wrote. */
  schema: SchemaNode;
  /** The file the document describes, shown under its heading. */
  describes?: string;
  /**
   * Box names for nested objects, keyed by field name. A field with no entry
   * is named after itself, as a singular noun: `models` becomes `Model`.
   */
  boxNames?: Readonly<Record<string, string>>;
}

/** `KnowledgeGraph` → `Knowledge Graph`. */
export function spaced(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, "$1 $2");
}

/** The anchor GitHub gives a heading: lower case, spaces to hyphens, punctuation dropped. */
export function anchor(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .trim()
    .replace(/ /g, "-");
}

/** `knownRepositories` → `Known Repository`; `askedOf` → `Asked Of`. */
function boxNameFor(field: string, isList: boolean, names: Readonly<Record<string, string>>): string {
  const given = names[field];
  if (given) return given;
  let s = field.replace(/([a-z])([A-Z])/g, "$1 $2");
  s = s[0]!.toUpperCase() + s.slice(1);
  if (isList) s = s.replace(/ies$/, "y").replace(/(?<!s)s$/, "");
  return s;
}

/** A map from any key to one shape: an object with no named fields, only `additionalProperties`. */
const mapValue = (n: SchemaNode | undefined): SchemaNode | undefined =>
  n && n.properties === undefined && typeof n.additionalProperties === "object" ? n.additionalProperties : undefined;

const isObject = (n: SchemaNode | undefined): boolean =>
  !!n && mapValue(n) === undefined && (n.type === "object" || n.properties !== undefined);

function literal(v: unknown): string {
  return typeof v === "string" ? `"${v}"` : JSON.stringify(v);
}

/** The type column of one field. */
function typeOf(n: SchemaNode, childName: string | undefined): string {
  if (n.const !== undefined) return `= ${literal(n.const)}`;
  if (n.enum) return n.enum.map(literal).join(" | ");
  const alts = n.anyOf ?? n.oneOf;
  if (alts) return alts.map((a) => typeOf(a, undefined)).join(" | ");
  if (n.type === "array") {
    const items = n.items ?? {};
    return isObject(items) ? `${childName} list` : `list of ${typeOf(items, undefined)}`;
  }
  const value = mapValue(n);
  if (value) return isObject(value) ? `map of key to ${childName}` : `map of key to ${typeOf(value, undefined)}`;
  if (isObject(n)) return childName ?? "object";
  return Array.isArray(n.type) ? n.type.join(" | ") : (n.type ?? "any");
}

/** `[1]`, `[0..1]`, `[1..*]` or `[0..*]`. */
function multiplicity(n: SchemaNode, required: boolean): string {
  if (n.type === "array") return required && (n.minItems ?? 0) >= 1 ? "[1..*]" : "[0..*]";
  if (mapValue(n)) return required ? "[1]" : "[0..1]";
  return required ? "[1]" : "[0..1]";
}

interface Box {
  name: string;
  lines: string[];
  children: { field: string; many: boolean; box: Box }[];
}

/** One object's box, and the boxes of the objects it holds. */
function buildBox(name: string, node: SchemaNode, names: Readonly<Record<string, string>>): Box {
  const props = Object.entries(node.properties ?? {});
  if (props.length === 0) {
    throw new Error(`bootstrap-schema-page: "${name}" is an object with no properties; there is nothing to draw.`);
  }
  const required = new Set(node.required ?? []);
  const children: Box["children"] = [];
  const rows: [string, string, string][] = [];
  for (const [field, n] of props) {
    const many = n.type === "array" || mapValue(n) !== undefined;
    const inner = n.type === "array" ? n.items : (mapValue(n) ?? n);
    const child = isObject(inner) ? boxNameFor(field, many, names) : undefined;
    if (child) children.push({ field, many, box: buildBox(child, inner!, names) });
    rows.push([`${required.has(field) ? "*" : " "} ${field}`, typeOf(n, child), multiplicity(n, required.has(field))]);
  }
  const w0 = Math.max(...rows.map((r) => r[0].length));
  const w2 = Math.max(...rows.map((r) => r[2].length));
  const lines = rows.map(([f, t, m]) => `${f.padEnd(w0)}  ${m.padEnd(w2)}  ${t}`);
  return { name, lines, children };
}

/** A box drawn with `+`, `-` and `|`. */
function drawBox(box: Box): string[] {
  const width = Math.max(box.name.length, ...box.lines.map((l) => l.length)) + 2;
  const rule = `+${"-".repeat(width)}+`;
  const row = (s: string) => `| ${s.padEnd(width - 1)}|`;
  return [rule, row(box.name), rule, ...box.lines.map(row), rule];
}

/**
 * A box, then each object it holds hanging below it on a connector labelled
 * with the field that holds it.
 */
function drawTree(box: Box): string[] {
  const out = drawBox(box);
  box.children.forEach(({ field, many, box: child }, i) => {
    // A list's items and a map's values both hang as "each item": one box per entry.
    const last = i === box.children.length - 1;
    const label = `  +-- ${field} ${many ? "(each item)" : ""}`.trimEnd() + " --> ";
    const sub = drawTree(child);
    out.push("  |");
    out.push(label + sub[0]);
    const pad = (last ? "   " : "  |").padEnd(label.length);
    for (const l of sub.slice(1)) out.push(pad + l);
  });
  return out;
}

/** `If \`status\` is "superseded"` — the condition half of one rule. */
function condition(ifNode: unknown): string {
  const props = (ifNode as SchemaNode)?.properties;
  const entries = Object.entries(props ?? {});
  if (entries.length !== 1 || entries[0]![1].const === undefined) {
    throw new Error(`bootstrap-schema-page: cannot state this condition in words: ${JSON.stringify(ifNode)}`);
  }
  const [field, n] = entries[0]!;
  return `if \`${field}\` is ${literal(n.const)}`;
}

const listed = (fields: string[]) =>
  fields.length === 1
    ? `\`${fields[0]}\``
    : `${fields.slice(0, -1).map((f) => `\`${f}\``).join(", ")} and \`${fields.at(-1)}\``;

/** The consequence half: fields that must be present, or must be absent. */
function consequence(thenNode: unknown): string {
  const t = thenNode as { required?: string[]; not?: { required?: string[]; anyOf?: { required?: string[] }[] } };
  if (t.required?.length) return `${listed(t.required)} must be present`;
  if (t.not?.required?.length) return `${listed(t.not.required)} must be absent`;
  const any = t.not?.anyOf?.map((a) => a.required ?? []);
  if (any?.every((r) => r.length === 1)) return `${listed(any.map((r) => r[0]!))} must be absent`;
  throw new Error(`bootstrap-schema-page: cannot state this consequence in words: ${JSON.stringify(thenNode)}`);
}

/** Every rule in an `allOf`, as sentences. Nested item rules are scoped to their list. */
export function rules(allOf: readonly unknown[], scope = ""): string[] {
  const out: string[] = [];
  for (const r of allOf) {
    const rule = r as { if?: unknown; then?: unknown; properties?: Record<string, { items?: { allOf?: unknown[] } }> };
    if (rule.if !== undefined && rule.then !== undefined) {
      const sentence = `${condition(rule.if)}, ${consequence(rule.then)}.`;
      out.push(scope ? `In each item of \`${scope}\`: ${sentence}` : sentence[0]!.toUpperCase() + sentence.slice(1));
      continue;
    }
    const nested = Object.entries(rule.properties ?? {});
    if (nested.length === 1 && nested[0]![1].items?.allOf) {
      out.push(...rules(nested[0]![1].items.allOf, nested[0]![0]));
      continue;
    }
    throw new Error(`bootstrap-schema-page: cannot state this rule in words: ${JSON.stringify(r)}`);
  }
  return out;
}

/** Every box name in a tree, the root first. */
function boxNames(box: Box): string[] {
  return [box.name, ...box.children.flatMap((c) => boxNames(c.box))];
}

/** One document's section: heading, what it is, the drawing, its rules. */
function section(doc: PageDocument, root: Box): string[] {
  const s = doc.schema;
  const out = [`### ${root.name}`, ""];
  out.push(`[src](${doc.file})${doc.describes ? ` · describes \`${doc.describes}\`` : ""}`, "");
  if (s.description) out.push(s.description, "");
  out.push("```text", ...drawTree(root), "```", "");
  if (s.allOf?.length) {
    out.push("Rules the drawing cannot show:", "");
    for (const r of rules(s.allOf)) out.push(`- ${r}`);
    out.push("");
  }
  return out;
}

/**
 * The whole page.
 *
 * `termsFrom` names the document whose `$defs` hold the defined terms. Each
 * term gets a heading, so `bootstrap/README.md` can link to it, and a `[src]`
 * link to its `$defs` entry, which is the link the README used to carry.
 */
export function renderSchemaPage(docs: readonly PageDocument[], termsFrom: string): string {
  const termDoc = docs.find((d) => d.file === termsFrom);
  if (!termDoc?.schema.$defs) {
    throw new Error(`bootstrap-schema-page: ${termsFrom} has no $defs, so there are no terms to list.`);
  }
  const out = [
    "## Schemas, drawn",
    "",
    "<!-- Generated from the schemas in this directory. Change a schema, not this page. -->",
    "",
    "Every JSON file bootstrap defines has a schema in this directory. This page",
    "draws each one, so you can read it without reading JSON Schema.",
    "",
    "How to read a drawing:",
    "",
    "- Each box is one kind of JSON object. Its first line is its name.",
    "- `*` marks a field that must be present.",
    "- `[1]` means exactly one, `[0..1]` means optional, `[1..*]` means a list",
    "  with at least one item, and `[0..*]` means a list that may be empty.",
    "- A field that holds another object points to that object's box, below it.",
    "- `[src]` opens the schema itself.",
    "",
    "### Terms",
    "",
    "Each defined term, in the words of",
    `[\`${termsFrom}\`](${termsFrom}). A term whose shape is drawn below links to`,
    "its drawing; the rest are defined in words only.",
    "",
  ];
  const roots = docs.map((d) => buildBox(d.schema.title ?? d.file, d.schema, d.boxNames ?? {}));
  // Which section draws a box named for a term. The declaration's root box is
  // titled "Knowledge Graph declaration", so a term matches a box that is its
  // own name or its name followed by more words.
  const drawnIn = (term: string): string | undefined => {
    const t = spaced(term);
    const i = roots.findIndex((r) => boxNames(r).some((b) => b === t || b.startsWith(`${t} `)));
    return i === -1 ? undefined : roots[i]!.name;
  };
  for (const [name, def] of Object.entries(termDoc.schema.$defs)) {
    const at = drawnIn(name);
    const drawn = at ? ` Drawn in [${at}](#${anchor(at)}).` : "";
    out.push(`#### ${spaced(name)}`, "", `${def.description ?? ""}${drawn} [src](${termsFrom}#/$defs/${name})`, "");
  }
  docs.forEach((doc, i) => out.push(...section(doc, roots[i]!)));
  return `${out.join("\n").trimEnd()}\n`;
}
