#!/usr/bin/env bun
/**
 * Audit every citation a skill makes to a section of an `AGENTS.md`.
 *
 * @module scripts/check-agents-xref
 * @covers skills, docs
 *
 * ## Why this has to exist before anything is migrated
 *
 * Bean `1hsf` moves substantive rules out of `AGENTS.md` into the skills that
 * govern them. Moving a section silently breaks every skill that cited it, and
 * measured on `main` 2026-09-19 — **before** a single line was moved — 18 of
 * the 20 section-naming citations already failed to resolve against this
 * repository's `AGENTS.md`. Nothing reported that, so nobody could tell an
 * inherited break from one the migration had just caused. A migration run
 * without this check is a migration whose damage is indistinguishable from the
 * damage already there.
 *
 * ## The third state, and why collapsing it would be wrong
 *
 * **There are two `AGENTS.md` files and a citation does not say which it
 * means.** The platform carries one; every folio built on it carries its own,
 * and skills are *synced into* a folio, where the same sentence resolves
 * against a different file. This repository's own `AGENTS.md` says so
 * explicitly — *"`litlfred/qou`'s `AGENTS.md` carries the same first two rules
 * for that folio — §'Branch + PR workflow'"* — and `continual-progress.md`
 * cites exactly that section.
 *
 * So a citation is one of three things, never two:
 *
 * | verdict | meaning |
 * |---|---|
 * | `resolves` | names a heading in this repository's `AGENTS.md` |
 * | `folio` | names a section this file itself attributes to a folio's `AGENTS.md` |
 * | `unresolved` | names neither — either deleted here, or a folio section nothing records |
 *
 * `unresolved` is **not** "dead". A platform-only checkout cannot read a
 * folio's `AGENTS.md`, so it cannot prove absence — it can only report that
 * nothing here accounts for the reference. Rendering that as a dead link would
 * produce a wall of false findings in exactly the checkout this usually runs in.
 *
 * ## How the backlog reached zero, and what it cost to find out
 *
 * 16 of the 20 original citations sat `unresolved`. Guessing which were the
 * folio's would have been a claim about a repository this checkout cannot see,
 * so `litlfred/qou` was cloned and **checked**. Of the seven that survived
 * repointing, five named real sections of its 6,036-line `AGENTS.md` — four
 * headings and one bullet — and **two, `be frugal` and `Executing actions with
 * care`, were in neither repository** and became plain rules with no citation.
 *
 * The lesson is in `OWNED_CITATION`: a citing file must be able to declare
 * which `AGENTS.md` it means. Before that, a correct citation could only leave
 * `unresolved` if the PLATFORM's prose happened to mention it, which would have
 * meant restating a folio's contents here to clear a backlog.
 *
 * Exit codes: 0 clean · 1 unresolved citations found · 2 could not check.
 */
import { readFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { instanceRootFor, repoRootFor } from "../schemas/cat-harness.js";

export type Verdict = "resolves" | "folio" | "unresolved";

export interface Citation {
  file: string;
  section: string;
  verdict: Verdict;
}

/**
 * Headings of an `AGENTS.md`, at any level.
 *
 * **A blockquoted heading is a heading.** `> ## …` renders as one on GitHub
 * and is as reachable as any other, so a citation naming it is correct. This
 * matched `^#` only, and the two sections this file quotes to itself — the
 * banner (`🛑 Do not edit this file to change how agents work`) and `Getting
 * skills` — were therefore invisible: a correct citation was reported
 * `unresolved`, which is the verdict reserved for a section that is not
 * there. Found by `where-a-proposal-goes.md` citing the banner, 2026-09-19.
 */
export function headingsOf(markdown: string): string[] {
  return [...markdown.matchAll(/^>?\s*#{1,4}\s+(.+?)\s*$/gm)].map((m) => m[1]);
}

/**
 * Compare a cited name with a heading loosely enough to survive formatting.
 *
 * A citation writes the section's *name*; the heading often carries a dash and
 * a gloss after it (`## Commit early, commit often, always PR (STRICT)` cited
 * as "always PR"). Matching exact strings would report almost everything as
 * broken, which is a checker nobody runs twice.
 */
export function normalise(s: string): string {
  return s
    .toLowerCase()
    .replace(/[`*_"'‘’“”]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function matches(cited: string, headings: string[]): boolean {
  const want = normalise(cited);
  if (!want) return false;
  return headings.map(normalise).some((h) => h === want || h.includes(want) || want.includes(h));
}

/**
 * Sections this file itself hands to a folio's `AGENTS.md`.
 *
 * Derived from the text rather than listed by hand: a sentence naming a folio
 * repository and a quoted `§` section in the same breath is this file saying
 * "that section lives over there". Hardcoding the list would rot the moment
 * the cross-reference paragraph is edited — which this very migration will do.
 *
 * **Scanned per PARAGRAPH, not per line, and that is not a detail.** The first
 * version scanned lines and found zero, because the one attribution in this
 * file wraps: `litlfred/qou`'s ... ends a line and `§"Branch + PR workflow"`
 * begins the next. A three-state check whose middle state can never fire is a
 * two-state check with a longer description.
 */
export function folioAttributedSections(agentsMd: string): Set<string> {
  const out = new Set<string>();
  for (const para of agentsMd.split(/\n\s*\n/)) {
    if (!/litlfred\/\w+|the folio's|a folio's|that folio/i.test(para)) continue;
    for (const m of para.matchAll(/§\s*["“]?([^"”\n,;]{4,60}?)["”]?(?=\s*(?:rule|,|;|and|\.|$))/gim)) {
      out.add(normalise(m[1]));
    }
  }
  return out;
}

/** Every `.md` under the given roots. */
function markdownUnder(root: string): string[] {
  if (!existsSync(root)) return [];
  const out: string[] = [];
  for (const e of readdirSync(root)) {
    const p = join(root, e);
    if (statSync(p).isDirectory()) out.push(...markdownUnder(p));
    else if (e.endsWith(".md")) out.push(p);
  }
  return out;
}

/**
 * A citation names a section: `AGENTS.md §"X"`, `AGENTS.md "X"`, `AGENTS.md's §X`.
 *
 * **The optional closing backtick is load-bearing.** Without it, writing the
 * qualified form `` `litlfred/qou` `AGENTS.md` §"X" `` made the citation
 * DISAPPEAR from the audit rather than be classified — the census fell from 8
 * to 1 and read as success. A checker that stops seeing a reference because
 * somebody improved its wording is not measuring what it claims to: qualifying
 * a citation must move it between states, never out of the count.
 */
const CITATION = /AGENTS\.md`?(?:'s)?\s*(?:§\s*)?["“]([^"”\n]{4,90})["”]/g;

/**
 * A citation that names its own repository — `` `litlfred/qou`'s `AGENTS.md`
 * §"X" ``.
 *
 * **Declaration over inference, which is this repository's own rule.** The
 * first version could only reach `folio` when THIS file attributed a section to
 * a folio — so a correct citation stayed `unresolved` until the platform's own
 * prose happened to mention it, and clearing the backlog would have meant
 * restating a folio's table of contents inside the platform. **A citing file
 * saying which file it means is the contract; the platform guessing on its
 * behalf is not.**
 *
 * Qualifying a citation is a claim about another repository, so it is checked
 * there rather than assumed here. Verified against a real checkout of
 * `litlfred/qou` (6,036-line `AGENTS.md`, 2026-09-19): `Critical-distance
 * license`, `CI billing failures`, `QA is agent-owned; CI is a backup` and
 * `Before declaring "open"` are headings in it, and `Combine related work into
 * one branch / one PR` is a bullet in its branch-and-PR section. Two other
 * long-standing citations — `be frugal` and `Executing actions with care` —
 * are in **neither** repository, and were rewritten as plain rules rather than
 * qualified.
 */
const OWNED_CITATION =
  /([\w.-]+\/[\w.-]+)`?(?:'s)?\s*`?AGENTS\.md`?(?:'s)?\s*(?:§\s*)?["“]([^"”\n]{4,90})["”]/g;

/**
 * @param repoRoot      where `AGENTS.md` is — the REPOSITORY's.
 * @param skillRoots    directories to scan, relative to `skillsRoot`.
 * @param skillsRoot    what `skillRoots` are relative to. Defaults to
 *   `repoRoot`, which is what it meant while the two were one directory.
 *
 * Two roots because the move (bean `wggr`) split the question in half:
 * `AGENTS.md` stayed at the top of the checkout and `skills/` went into the
 * instance. With one parameter the live run scanned `<repo>/skills`, found no
 * files, and printed a census of **0** — where it had been 8 — as a clean run.
 * The fixtures in `check-agents-xref.test.ts` still pass one root, because a
 * fixture repository has no instance in it.
 */
export function auditXrefs(
  repoRoot: string,
  skillRoots: string[],
  skillsRoot: string = repoRoot,
): Citation[] {
  const agentsPath = join(repoRoot, "AGENTS.md");
  if (!existsSync(agentsPath)) throw new Error(`no AGENTS.md at ${agentsPath}`);
  // Could-not-check, not "no citations". A census of zero over a tree that is
  // not there is indistinguishable from a corpus with nothing to say, and the
  // caller turns this into exit 2 rather than a green sweep.
  if (!skillRoots.some((r) => existsSync(join(skillsRoot, r)))) {
    throw new Error(
      `none of the skill roots exist under ${skillsRoot}: ${skillRoots.join(", ")}`,
    );
  }
  const agentsMd = readFileSync(agentsPath, "utf8");
  const headings = headingsOf(agentsMd);
  const folio = folioAttributedSections(agentsMd);
  // `owner/name` of this instance, so a citation naming THIS repo is still
  // audited against its own headings rather than waved through as somebody
  // else's.
  const instanceName = agentsMd.match(/^#\s+AGENTS\.md\s+[—-]\s+(\S+)/m)?.[1] ?? "";

  const out: Citation[] = [];
  for (const root of skillRoots) {
    for (const f of markdownUnder(join(skillsRoot, root))) {
      const text = readFileSync(f, "utf8");
      // A citation naming another repository declares its own destination, so
      // it is never reported against this file's headings.
      const owned = new Set(
        [...text.matchAll(OWNED_CITATION)]
          .filter((m) => m[1] !== instanceName)
          .map((m) => normalise(m[2])),
      );
      for (const m of text.matchAll(CITATION)) {
        const section = m[1];
        const verdict: Verdict = matches(section, headings)
          ? "resolves"
          : owned.has(normalise(section)) || folio.has(normalise(section))
            ? "folio"
            : "unresolved";
        out.push({ file: relative(repoRoot, f), section, verdict });
      }
    }
  }
  return out;
}

/**
 * The roots holding hand-authored skills.
 *
 * `docs/reference/skill-instructions/` is deliberately absent: it is GENERATED
 * from `skills/`, so every finding there is a duplicate of one already
 * reported against its source, and fixing it directly would be overwritten by
 * the next `gen-skill-docs` run.
 */
// declared-path-literal: these are relative roots applied to an ARBITRARY
// repository root — `auditXrefs(root, SKILL_ROOTS)` is called against fixture
// repositories throughout `check-agents-xref.test.ts`, which have no
// `harness.json` at all. Reading THIS instance's declaration would answer a
// question about a different tree, which is worse than a literal: it would be
// confidently wrong rather than obviously fixed. `.claude/skills` is not a
// declared `cat-harness` directory in any instance, so no declaration reaches
// it either.
export const SKILL_ROOTS = ["skills", "src/skills", ".claude/skills"];

if (import.meta.main) {
  const strict = process.argv.includes("--strict");
  let cites: Citation[];
  try {
    // `AGENTS.md` is the repository's; the skills are the instance's.
    const instance = instanceRootFor(import.meta.dir);
    cites = auditXrefs(repoRootFor(instance), SKILL_ROOTS, instance);
  } catch (e) {
    console.error(`could not check: ${(e as Error).message}`);
    process.exit(2);
  }

  const by = (v: Verdict): Citation[] => cites.filter((c) => c.verdict === v);
  const unresolved = by("unresolved");

  console.log(`AGENTS.md section citations: ${cites.length}`);
  console.log(`  resolves here : ${by("resolves").length}`);
  console.log(`  folio's file  : ${by("folio").length}   (attributed to a folio by AGENTS.md itself)`);
  console.log(`  unresolved    : ${unresolved.length}`);

  if (by("folio").length) {
    console.log("\nNaming a folio's AGENTS.md — correct, but ambiguous to a reader:");
    for (const c of by("folio")) console.log(`  · ${c.file}  §"${c.section}"`);
  }

  if (unresolved.length) {
    console.log("\nUnresolved — no heading here, and this file does not attribute them to a folio.");
    console.log("NOT proof of a dead reference: a folio's AGENTS.md cannot be read from a");
    console.log("platform-only checkout. Qualify the citation, or repoint it at the skill.");
    for (const c of unresolved) console.log(`  ✗ ${c.file}  §"${c.section}"`);
  }

  if (unresolved.length && strict) process.exit(1);
  process.exit(0);
}
