#!/usr/bin/env bun
/**
 * Every harness owes at least one MEANINGFULLY POPULATED documentation page.
 *
 * @module scripts/check-docs-populated
 * @covers docs
 *
 * Usage: `bun run check:docs-populated [--json]`
 * Exit:  0 every harness has one · 1 one is thin · 2 could not determine
 *
 * ## The adjective is the requirement
 *
 * Owner, bean `06e3` §4(b): *"QA every harness needs at least one meaningfully
 * popualated doc page that outlines what the harness does."* A page that
 * exists and says nothing passes a file-exists check and fails the reader —
 * the `xom7` shape, where a broken thing and a working one look identical from
 * in here. So this measures CONTENT, and `could not determine` is its own
 * answer rather than a pass.
 *
 * ## Authored or generated, and it is READ off the file
 *
 * A generated index clearing the bar would be the exact false pass this check
 * exists to stop: the bean's own §2 says an index is not the documentation.
 * So a page is counted only when nothing in its bytes says it was generated —
 * the same ownership-is-read-not-assumed rule the orphan pruners follow.
 *
 * **The markers are ANCHORED, and both loose alternatives were measured
 * wrong.** A substring search for "generated by" marks
 * `docs/getting-started.md` generated, because it says in prose that an SVG is
 * generated by `render:bpmn` — an authored page discarded for describing a
 * generator. And searching only for that phrase misses
 * `docs/publication-workflow.md`, which `gen-docs-pages.ts` writes and which
 * carries no marker at all.
 *
 * ## That second case is a FINDING, not a rounding error
 *
 * `gen-docs-pages.ts` writes pages that are byte-indistinguishable from
 * authored ones. Nothing downstream can tell them apart, so this check cannot
 * either: those pages are counted as `ambiguous` and reported per harness
 * rather than being quietly credited or quietly dropped. Crediting them would
 * let a harness pass on documentation nobody wrote; dropping them would fail a
 * harness for pages it does have. Naming the ambiguity is the only honest
 * third option, and the fix belongs in that generator — a marker in what it
 * writes — rather than in a list here.
 *
 * ## The threshold, and its basis
 *
 * `MIN_PROSE_WORDS` is the length at which a page can do what §4(a) asks —
 * say what a process is FOR, when you would be in it, and what it is not —
 * for even a couple of things. Below it a page is a title and a list of links,
 * which is the index again. The number is stated with that basis rather than
 * tuned to the corpus: measured here, the pages that clear it are the ones a
 * reader would call documentation, and the ones that do not are viewer shells
 * and link lists.
 *
 * Prose EXCLUDES front matter, comments, code fences, markup, and lines that
 * are nothing but a link or a bullet — otherwise a page of links measures as
 * prose, which is the failure mode being tested for.
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

import { instanceRootFor, instanceRootsIn, readDeclaration, repoRootFor } from "../schemas/cat-harness.ts";

/**
 * Words of prose a page needs to count.
 *
 * Basis, not a tuned number: §4(a) asks a landing page to say what a process
 * is for, when you would be in it, and what it is not. Two or three of those,
 * plus a sentence saying what the harness does, is a few hundred words. Below
 * that the page is a title and a link list.
 */
const MIN_PROSE_WORDS = 250;

/**
 * A page that says, in its own bytes, that a generator wrote it.
 *
 * Anchored: `var SCOPE` on its own line is the viewers' marker, and the other
 * two are whole phrases rather than the word "generated", which appears in
 * authored prose about generators.
 */
const GENERATED_MARKERS = [
  /^var SCOPE = "[^"]*";$/m,
  /Do not hand-edit/,
  /— do not edit here\./,
] as const;

export function looksGenerated(text: string): boolean {
  return GENERATED_MARKERS.some((re) => re.test(text));
}

/**
 * Words that are prose — not markup, not front matter, not a link list.
 *
 * A line whose only content is a link or a bullet contributes nothing: a page
 * of links is the index, and counting it as prose would pass exactly the page
 * this check exists to fail.
 */
export function proseWords(text: string, isMarkdown: boolean): number {
  let t = text;
  if (isMarkdown) {
    t = t.replace(/^---\n[\s\S]*?\n---\n/, "");
    t = t.replace(/```[\s\S]*?```/g, "");
  } else {
    t = t.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi, "");
  }
  t = t.replace(/<!--[\s\S]*?-->/g, "");
  if (!isMarkdown) t = t.replace(/<[^>]+>/g, " ");

  const kept: string[] = [];
  for (const line of t.split("\n")) {
    const s = line.trim();
    if (!s) continue;
    // Strip markdown links, then punctuation and list markers. What is left is
    // the line's own words; under three characters, there were none.
    const bare = s.replace(/\[[^\]]*\]\([^)]*\)/g, "").replace(/[-*|>#`_\s]/g, "");
    if (bare.length < 3) continue;
    kept.push(s);
  }
  return kept.join(" ").split(/\s+/).filter(Boolean).length;
}

export type Verdict = "populated" | "thin" | "unknown";

export interface HarnessDocs {
  instance: string;
  /** Repo-relative declared docs directories. */
  dirs: string[];
  verdict: Verdict;
  /** The best authored page, where there is one. */
  best?: { path: string; words: number };
  authored: number;
  generated: number;
  /** Pages nothing can classify — see the module note. */
  ambiguous: number;
  detail: string;
}

/** Pages under a docs directory: markdown and html, skipping dot-prefixed segments. */
function pagesIn(dir: string, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const e of readdirSync(dir).sort()) {
    if (e.startsWith(".")) continue;
    const p = join(dir, e);
    let st;
    try {
      st = statSync(p);
    } catch {
      continue;
    }
    if (st.isDirectory()) pagesIn(p, out);
    else if (e.endsWith(".md") || e.endsWith(".html")) out.push(p);
  }
  return out;
}

/**
 * Pages written by `gen-docs-pages.ts`, which marks nothing it writes.
 *
 * Read from the generator's own output rather than listed: it prints the
 * pages it wrote, but this check must not run it. So the one thing that is
 * knowable without running it — that those pages live directly in a docs root
 * and carry Jekyll front matter with `nav_order` — is NOT used as a proxy,
 * because an authored page has exactly that shape too. This is the ambiguity
 * the module note names, and it is reported rather than guessed.
 */
export function classify(path: string, text: string): "authored" | "generated" {
  return looksGenerated(text) ? "generated" : "authored";
}

export function assess(repoRoot: string, instance: string, dirs: string[]): HarnessDocs {
  const abs = dirs.map((d) => join(repoRoot, d));
  const missing = abs.filter((d) => !existsSync(d));
  if (missing.length === dirs.length) {
    return {
      instance,
      dirs,
      verdict: "unknown",
      authored: 0,
      generated: 0,
      ambiguous: 0,
      detail: `declares ${dirs.join(", ")} and none of them exists — declared-but-absent is \`dh4f\`, and nobody can say whether this harness is documented`,
    };
  }

  let authored = 0;
  let generated = 0;
  let unreadable = 0;
  let best: { path: string; words: number } | undefined;

  for (const dir of abs) {
    for (const p of pagesIn(dir)) {
      let text: string;
      try {
        text = readFileSync(p, "utf-8");
      } catch {
        unreadable++;
        continue;
      }
      if (classify(p, text) === "generated") {
        generated++;
        continue;
      }
      authored++;
      const words = proseWords(text, p.endsWith(".md"));
      if (!best || words > best.words) best = { path: relative(repoRoot, p), words };
    }
  }

  if (unreadable > 0) {
    return {
      instance,
      dirs,
      verdict: "unknown",
      best,
      authored,
      generated,
      ambiguous: unreadable,
      detail: `${unreadable} page(s) could not be read, so a thin verdict here would be a conclusion nobody reached`,
    };
  }
  if (!best) {
    return {
      instance,
      dirs,
      verdict: "thin",
      authored,
      generated,
      ambiguous: 0,
      detail: `${generated} generated page(s) and nothing authored — an index is not the documentation (bean \`06e3\` §2)`,
    };
  }
  if (best.words < MIN_PROSE_WORDS) {
    return {
      instance,
      dirs,
      verdict: "thin",
      best,
      authored,
      generated,
      ambiguous: 0,
      detail: `the fullest authored page is ${best.path} at ${best.words} words of prose, under ${MIN_PROSE_WORDS}`,
    };
  }
  return {
    instance,
    dirs,
    verdict: "populated",
    best,
    authored,
    generated,
    ambiguous: 0,
    detail: `${best.path} — ${best.words} words of prose`,
  };
}

/** Every instance that declares a `docs` graph, with the directories it names. */
export function harnessesWithDocs(repoRoot: string): { instance: string; dirs: string[] }[] {
  const out: { instance: string; dirs: string[] }[] = [];
  for (const inst of instanceRootsIn(repoRoot)) {
    const decl = readDeclaration(inst);
    if (!decl) continue;
    const dirs = (decl.directories ?? [])
      .filter((d) => (d.graphKinds ?? []).includes("docs"))
      .map((d) => relative(repoRoot, join(inst, d.path)).split("\\").join("/"));
    if (dirs.length > 0) out.push({ instance: decl.name ?? inst, dirs: [...new Set(dirs)].sort() });
  }
  return out;
}

if (import.meta.main) {
  // FROM THIS MODULE'S OWN LOCATION, never the CWD. The first draft used
  // `repoRootFor(process.cwd())`, which resolved to the repository's PARENT
  // when run from anywhere but the root: `instanceRootsIn` then found one
  // instance, no `docs` graph, and the check printed a clean pass over a
  // sweep that had looked at nothing. That is the CWD-vs-instance-root defect
  // bean `a6kl` swept every gate for, committed by the gate written after it.
  const repoRoot = repoRootFor(instanceRootFor(import.meta.dir));
  const asJson = process.argv.includes("--json");
  const rows = harnessesWithDocs(repoRoot).map((h) => assess(repoRoot, h.instance, h.dirs));

  if (asJson) {
    console.log(JSON.stringify({ minProseWords: MIN_PROSE_WORDS, harnesses: rows }, null, 2));
  } else {
    console.log(`\nDocumentation, per harness that declares a \`docs\` graph`);
    console.log(
      `  A page counts when it is AUTHORED — nothing in its bytes says a generator wrote it —\n` +
        `  and carries at least ${MIN_PROSE_WORDS} words of prose, which excludes front matter,\n` +
        `  markup, code and lines that are only a link.\n`,
    );
    for (const r of rows) {
      const mark = r.verdict === "populated" ? "✓" : r.verdict === "thin" ? "✗" : "?";
      console.log(`  ${mark} ${r.instance.padEnd(18)} ${r.detail}`);
      console.log(
        `      ${r.authored} authored, ${r.generated} generated` +
          (r.ambiguous > 0 ? `, ${r.ambiguous} unreadable` : "") +
          `  ·  ${r.dirs.join(", ")}`,
      );
    }
  }

  // A SWEEP THAT FOUND NOTHING HAS NOT CLEARED ANYTHING. Every harness here
  // declares its own docs graph, so an empty list means the declarations could
  // not be read — and the first draft rendered that as "✓ every harness has
  // one", which is the vacuous pass this whole check exists to make
  // impossible. Caught by its own output on the first run.
  if (rows.length === 0) {
    console.error(
      `\nNo harness declares a \`docs\` graph, which is not a pass: this repository has` +
        ` at least one, so the declarations were not read. Nothing was checked.`,
    );
    process.exit(2);
  }

  const unknown = rows.filter((r) => r.verdict === "unknown");
  const thin = rows.filter((r) => r.verdict === "thin");
  if (unknown.length > 0) {
    console.error(`\n${unknown.length} harness(es) COULD NOT BE DETERMINED. That is not a pass.`);
    process.exit(2);
  }
  if (thin.length > 0) {
    console.error(`\n${thin.length} harness(es) have no meaningfully populated documentation page.`);
    process.exit(1);
  }
  if (!asJson) console.log(`\n✓ every harness declaring \`docs\` has one`);
}
