#!/usr/bin/env bun
/**
 * Generate `bootstrap`'s JSON Schema from `bootstrap-tools`' Zod.
 *
 * @module scripts/gen-bootstrap-schemas
 * @graphNode none — a generator over the bootstrap schemas, not a schema itself
 *
 * ## Why the source and the output are in different instances
 *
 * `bootstrap/README.md` promises an Initiator **no harness, no server, no
 * tools and no work plan**, and that what it reads is "a file you read, not
 * something you run". That directory holds `.md`, `.json` and `.bpmn` and no
 * executable code. So the Zod lives in `bootstrap-tools/` and the JSON
 * lands in `bootstrap/`, which knows nothing of how it got there — owner,
 * 2026-09-20: *"bootstrap should not know zod at all (it is just generated by
 * it in main and ghpages rendering pipeline)"*.
 *
 * ## The `$id`s are a contract, so they are stated rather than derived
 *
 * They are already published, and the filenames are cited from
 * `discussion.bpmn`, `cat-harness/tools/index.ts`, the generated skill docs
 * and `.pot` catalogues in five languages. Deriving them from a base URL
 * would make a relocation silently repoint a consumer's `$ref`.
 *
 * ## What this has to put back, and why it is not optional
 *
 * The converter drops `.refine()` entirely — measured: no `allOf`, no
 * `if`/`then`, no message. The output document's two conditionals would
 * therefore vanish, and the published schema would start ACCEPTING what it
 * currently REJECTS. That is a contract weakened invisibly, which is the
 * failure this repository works hardest against, so the conditionals are
 * re-applied from `JSON_SCHEMA_CONDITIONALS` and
 * `bootstrap-tools/schemas/discussion.test.ts` proves it with documents
 * that must fail.
 *
 * Usage:
 *   bun run bootstrap-tools:schemas          # write
 *   bun run bootstrap-tools:schemas:check    # fail if stale
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import { z } from "zod";

import { instanceRootsIn, readDeclaration } from "../schemas/cat-harness.ts";


import {
  DiscussionInputSchema,
  DiscussionOutputObjectSchema,
  JSON_SCHEMA_CONDITIONALS,
} from "../../bootstrap-tools/schemas/discussion.ts";
import { BOOTSTRAP_TERMS, KnowledgeGraphDeclarationSchema } from "../../bootstrap-tools/schemas/graph.ts";

const ROOT = join(import.meta.dir, "..", "..");
const check = process.argv.includes("--check");

/**
 * Where `bootstrap` actually is, resolved from its own declaration.
 *
 * The INSTANCE is the part that can move — it is discovered by declared name
 * rather than assumed to sit at `bootstrap/`, so a relocation moves the
 * output with it. What is not resolved is the `skills/<file>` tail, and that
 * is deliberate: those filenames are half of a published `$id` and are cited
 * from `discussion.bpmn`, `cat-harness/tools/index.ts`, the generated skill
 * docs and `.pot` catalogues in five languages. A filename that followed a
 * directory rename would silently repoint every one of them.
 *
 * `skills/` cannot be resolved as a graph here in any case: `bootstrap`
 * declares three directories under the one `cat-harness` graph, so the
 * singular question has no answer — the `wggr` guard, correctly.
 */
function bootstrapRoot(): string {
  for (const root of instanceRootsIn(ROOT)) {
    try {
      if (readDeclaration(root)?.name === "bootstrap") return root;
    } catch {
      // An unreadable sibling declaration is not this generator's to report.
      continue;
    }
  }
  throw new Error(
    "no instance declares itself `bootstrap` — cannot place the generated schemas. " +
      "That is a missing or renamed declaration, not a missing directory.",
  );
}

const BOOTSTRAP = bootstrapRoot();

/** Where each document is published, and the `$id` it is published at. */
const TARGETS = [
  {
    // declared-path-literal: the convention fallback, at the call site. The
    // documents moved from `skills/` to the declared `schemas/` on
    // 2026-09-21; the `$id` below did NOT move with them, and must not —
    // it is half of a published contract cited from five languages'
    // catalogues, and ids are stable across a relocation while paths are not.
    file: "schemas/discussion.input.schema.json",
    id: "https://litlfred.github.io/folio-assistant/bootstrap/skills/discussion/input.schema.json",
    title: "Discussion Input",
    description:
      "The occasion for asking: what the agent already knows, and which unknown is still open. Deliberately small — an Initiator has read one README and can look nothing up, so an input it cannot populate is an input that stops the process.",
    schema: DiscussionInputSchema,
    conditionals: [] as readonly unknown[],
    terms: {} as Readonly<Record<string, string>>,
  },
  {
    // declared-path-literal: as above — path moved, `$id` deliberately not.
    file: "schemas/discussion.output.schema.json",
    id: "https://litlfred.github.io/folio-assistant/bootstrap/skills/discussion/output.schema.json",
    title: "Discussion Output",
    description:
      "What the exchange determined: which harness, which repositories, on whose word, and by what means. This document existing and conforming is what finishes the task — not that a conversation took place.",
    schema: DiscussionOutputObjectSchema,
    conditionals: JSON_SCHEMA_CONDITIONALS as readonly unknown[],
    terms: {} as Readonly<Record<string, string>>,
  },
  {
    // bootstrap's own terms, and the shape of a `<name>.json` declaration
    // (owner, 2026-09-23: "bootstrap = self definitional … all terms have a
    // schema"). `bootstrap/README.md` links each term's first use here.
    file: "schemas/graph.schema.json",
    id: "https://litlfred.github.io/folio-assistant/bootstrap/schemas/graph.schema.json",
    title: "Knowledge Graph declaration",
    description:
      BOOTSTRAP_TERMS.KnowledgeGraph +
      " This schema is the shape of that declaration, and its `$defs` define every term bootstrap uses.",
    schema: KnowledgeGraphDeclarationSchema,
    conditionals: [] as readonly unknown[],
    terms: BOOTSTRAP_TERMS as Readonly<Record<string, string>>,
  },
] as const;

/**
 * Remove every `additionalProperties` the exporter added, at any depth.
 *
 * Recursive rather than top-level-only, because the nested objects — a
 * repository reference, a participant, an exchange entry — each get one too,
 * and the documents this replaces carried none anywhere.
 */
export function stripAdditionalProperties(node: unknown): void {
  if (Array.isArray(node)) {
    for (const v of node) stripAdditionalProperties(v);
    return;
  }
  if (!node || typeof node !== "object") return;
  const o = node as Record<string, unknown>;
  delete o.additionalProperties;
  for (const v of Object.values(o)) stripAdditionalProperties(v);
}

/** One document, rendered. */
export function render(t: (typeof TARGETS)[number]): string {
  // `$refStrategy: "none"` inlines every shared definition, which is correct
  // for a document a consumer dereferences by `$id`: it gets something
  // self-contained. The cost — a referenced type is not a named thing in the
  // output — is the same one `harness-schema-export` accepts, and it is why
  // the schema GRAPH is read from the `.ts` rather than from this.
  const body = z.toJSONSchema(t.schema, { io: "input", reused: "inline" }) as Record<
    string,
    unknown
  >;

  // The converter emits its own `$schema`; the draft is stated below so the
  // published document does not change dialect when the library does.
  delete body.$schema;

  // STRICTNESS IS KEPT, DELIBERATELY — bean `z634`, decided 2026-09-21.
  //
  // `z.object()` is strict, so the converter emits `additionalProperties:
  // false` on every object. The port that introduced this file STRIPPED it,
  // and that was right THEN: the hand-written documents it replaced carried
  // none at any depth, and porting a shape is not the moment to change what
  // validates.
  //
  // The bean pre-registered the test that settles it — *"does anything
  // actually produce these documents today? If nothing does, the
  // compatibility risk is zero and this is free."* Measured 2026-09-21, and
  // all three answers agree:
  //
  //   producers of a discussion document, anywhere in the repo   NONE
  //   `skills/discussion.md` on whether extra keys are permitted SILENT
  //   age of the published `$id`                                 1 day
  //
  // So nothing can break, and what strictness buys is exactly the failure
  // these documents are most exposed to: they are written by AGENTS, and an
  // agent that types `assumtion` for `assumption` gets SILENCE today. Under
  // `additionalProperties: false` the key is rejected, and the `assumed`
  // conditional then fires and names the missing field.
  //
  // `stripAdditionalProperties` is kept, exported and tested rather than
  // deleted: it is the one-line reversal if a consumer ever appears, and a
  // deleted function is a decision that cannot be undone by reading this
  // comment.

  const doc: Record<string, unknown> = {
    $schema: "http://json-schema.org/draft-07/schema#",
    $id: t.id,
    title: t.title,
    description: t.description,
    ...body,
  };

  // THE PART ZOD CANNOT CARRY. Appended after the shape so it reads in the
  // published file the way it reads in the schema: the object, then the rules
  // that relate its fields.
  if (t.conditionals.length) doc.allOf = t.conditionals;

  // The glossary, as schema: one `$defs` entry per term, each a definition a
  // README links to. A term with no structure of its own (Role, Skill) is a
  // definition only, which JSON Schema expresses as a title and a description.
  const terms = Object.entries(t.terms);
  if (terms.length) {
    doc.$defs = Object.fromEntries(terms.map(([name, definition]) => [name, { title: name, description: definition }]));
  }

  return `${JSON.stringify(doc, null, 2)}\n`;
}

let stale = 0;
let wrote = 0;

for (const t of TARGETS) {
  const path = join(BOOTSTRAP, t.file);
  const next = render(t);
  const prev = existsSync(path) ? readFileSync(path, "utf8") : null;

  if (prev === next) {
    console.log(`  = ${relative(ROOT, path)}`);
    continue;
  }
  if (check) {
    // A red here means somebody changed the Zod and did not regenerate — a
    // real omission every time, which is the standard this repository holds a
    // staleness gate to.
    console.error(`  ✗ ${relative(ROOT, path)} is stale`);
    stale++;
    continue;
  }
  writeFileSync(path, next);
  console.log(`  ✓ ${relative(ROOT, path)}`);
  wrote++;
}

if (check && stale) {
  console.error(`\n${stale} bootstrap schema(s) stale — run \`bun run bootstrap-tools:schemas\`.`);
  process.exit(1);
}
console.log(
  check
    ? "\nbootstrap schemas are up to date"
    : `\n${wrote} written, ${TARGETS.length - wrote} unchanged`,
);
