#!/usr/bin/env bun
/**
 * Generate `themes.css` from the theme nodes.
 *
 * @module scripts/gen-themes-css
 * @covers themes
 *
 * **The knowledge graph is the source; the stylesheet is a rendering of it.**
 * That is the whole of the owner's *"named css assets in KG rather than
 * hardcoded colors"* — hand-authoring the CSS beside the nodes would give two
 * places to change a colour and no check that they agree, which is the same
 * shape as the 106 hardcoded literals this replaces.
 *
 * `--check` fails when the committed file is stale, so an edited node that was
 * never regenerated fails the build rather than quietly never reaching a
 * reader. Same contract as the skill-docs mirror.
 *
 * Exit codes: 0 written or up to date · 1 stale under `--check`.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";

import { instanceRootFor, siteDirFor } from "../schemas/cat-harness.js";
import { themeCssVars } from "../schemas/theme.js";
import { DEFAULT_THEME_ID, THEMES } from "../schemas/themes.js";

/**
 * Where the stylesheet goes, for the instance rooted at `root`.
 *
 * **Derived, never written down.** The site root is `siteDirFor`'s answer and
 * nobody else's — a literal here would be one more place to fix when the tree
 * moves, and the last such move broke seven links in `AGENTS.md` alone before
 * anyone noticed. `site-dir-single-answer.test.ts` enforces it, and it caught
 * this file on its first run.
 */
export function themesCssPath(root: string): string {
  return join(siteDirFor(root), "assets", "css", "themes.css");
}

export function renderThemesCss(): string {
  const head = `/* GENERATED by scripts/gen-themes-css.ts from schemas/themes.ts — do not hand-edit.
 *
 * Every value here is a NAMED ROLE (--fa-sticky-surface, -ink, -edge, -accent),
 * never a colour name, so a rule reads as what it does and a theme swap touches
 * this file only. Run \`bun run themes:css\` after editing a theme node;
 * \`themes:css:check\` fails the build when this is stale.
 *
 * A theme sets the priority stripe's HUE and never its width: the stripe is a
 * width as well as a colour because colour alone carrying a signal fails
 * WCAG SC 1.4.1, and no theme has a field with which to remove the other
 * channel.
 */\n`;

  // STICKY themes only, and the narrowing is the point rather than a cast.
  //
  // This emits `[data-fa-sticky-theme=...]` with `--fa-sticky-*` properties, so
  // it was always about one surface; it just had no way to say so while every
  // theme had the same geometry. A `publication` theme's layouts are `a4 | a5 |
  // a5Landscape` with trim sizes and margins, and there is no sticky note to
  // give them to — `tsc` refuses `g.laptop` on the union, which is the schema
  // doing the job `data-modelling` step 7 gave it.
  //
  // A `webpage` theme shares the geometry but not this stylesheet: its CSS is
  // the site's, not the note board's. Adding it here would emit sticky
  // properties for a surface that has no stickies.
  const blocks = THEMES.filter((t) => t.kind === "sticky").map((t) => {
    const g = t.layouts;
    return [
      `/* ${t.name}${t.description ? ` — ${t.description}` : ""} */`,
      `[data-fa-sticky-theme="${t.id}"] {`,
      `  ${themeCssVars(t)}`,
      `  --fa-sticky-min-width: ${g.laptop.minWidth};`,
      `  --fa-sticky-padding: ${g.laptop.padding};`,
      `  --fa-sticky-font-scale: ${g.laptop.fontScale};`,
      `}`,
      ``,
      `/* ${t.name} — mobile layout. A phone sticky is not a laptop one scaled down. */`,
      `@media (max-width: 40rem) {`,
      `  [data-fa-sticky-theme="${t.id}"] {`,
      `    --fa-sticky-min-width: ${g.mobile.minWidth};`,
      `    --fa-sticky-padding: ${g.mobile.padding};`,
      `    --fa-sticky-font-scale: ${g.mobile.fontScale};`,
      `  }`,
      `}`,
      ``,
      `/* ${t.name} — card layout, for a dense board. */`,
      `[data-fa-sticky-theme="${t.id}"][data-fa-sticky-layout="card"] {`,
      `  --fa-sticky-min-width: ${g.card.minWidth};`,
      `  --fa-sticky-padding: ${g.card.padding};`,
      `  --fa-sticky-font-scale: ${g.card.fontScale};`,
      `}`,
    ].join("\n");
  });

  const fallback = [
    `/* The default, applied when nothing has selected a theme. A board with no`,
    ` * theme attribute must still render: an unthemed sticky is a state, not an`,
    ` * error, and leaving it unstyled would make "no selection yet" look broken. */`,
    `.fa-sticky-board:not([data-fa-sticky-theme]) {`,
    `  ${themeCssVars(THEMES.find((t) => t.id === DEFAULT_THEME_ID)!)}`,
    `  --fa-sticky-min-width: 17rem;`,
    `  --fa-sticky-padding: 0.7em 0.8em;`,
    `  --fa-sticky-font-scale: 1;`,
    `}`,
  ].join("\n");

  return `${head}\n${blocks.join("\n\n")}\n\n${fallback}\n`;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  // THE INSTANCE this script belongs to — the one it lives in — not whatever
  // directory the gate was invoked from. Those were the same until the move
  // (bean `wggr`), after which `siteDirFor(cwd)` threw on a `harness.json`
  // that is one directory down.
  const root = instanceRootFor(import.meta.dir);
  const rel = themesCssPath(root);
  const path = join(root, rel);
  const next = renderThemesCss();
  const current = existsSync(path) ? readFileSync(path, "utf8") : undefined;

  if (check) {
    if (current === next) {
      console.log(`themes.css is up to date (${THEMES.length} themes)`);
      process.exit(0);
    }
    console.error(`themes.css is stale — run \`bun run themes:css\` and commit`);
    process.exit(1);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  console.log(`wrote ${rel} (${THEMES.length} themes, default ${DEFAULT_THEME_ID})`);
}
