#!/usr/bin/env bash
# gen-bat-wrappers.sh — write a Windows .bat entry point beside every .sh a
# user runs by hand or wires into a config (hooks, .mcp.json, docs).
#
# Each .bat locates Git Bash (Git\bin\bash.exe — never the WSL launcher in
# System32) and runs the sibling .sh with the same arguments. They are
# wrappers, not ports: the scripts stay bash, and Git for Windows is already
# a prerequisite of `git` on that platform.
#
# Usage:
#   cat-harness/scripts/gen-bat-wrappers.sh          # (re)write every wrapper
#   cat-harness/scripts/gen-bat-wrappers.sh --check  # exit 1 if any wrapper is missing or stale
#
# To add a script: append it to WRAPPED below and re-run. Deliberately NOT
# wrapped — a .bat would only relocate the failure:
#   deploy/*.sh, install-tex.sh, setup-sage.sh, setup-singular.sh,
#   setup-elan-symlinks.sh, adapters/mcp-server/install.sh   (Linux host: apt/sudo/symlinks)
#   scripts/lib/*.sh                                         (sourced, not run)
#   scripts/git-hooks/auto-commit-feedback.sh                (git runs it via sh)
#   .github/scripts/generate-diff.sh, latexmk-compile.sh     (CI only)
#   docker-latex-build/build-pdf.sh, smoke-test-libraries.sh (qou-specific leftovers)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

WRAPPED=(
  .claude/skills/hooks/session-start.sh
  cat-harness/scripts/audit-library-coherence.sh
  cat-harness/scripts/check-branch-todos.sh
  cat-harness/scripts/check-no-lean-artifacts.sh
  cat-harness/scripts/check-todos.sh
  cat-harness/scripts/check-upstream.sh
  cat-harness/scripts/delivery-summary.sh
  cat-harness/scripts/feature-build.sh
  cat-harness/scripts/folio-port.sh
  cat-harness/scripts/git-hooks/install.sh
  cat-harness/scripts/google-drive-mcp.sh
  cat-harness/scripts/greeting-task-selection.sh
  cat-harness/scripts/install-beans.sh
  cat-harness/scripts/install-lean-atlas.sh
  cat-harness/scripts/lake-cache-fetch.sh
  cat-harness/scripts/lake-cache.sh
  cat-harness/scripts/lean-build-all.sh
  cat-harness/scripts/lean-build-bg.sh
  cat-harness/scripts/lean-build-timed.sh
  cat-harness/scripts/lean-cache-dump.sh
  cat-harness/scripts/lean-closure-orchestrator.sh
  cat-harness/scripts/lean-compile-audit.sh
  cat-harness/scripts/open-folio-assistant.sh
  cat-harness/scripts/render-on-change.sh
  cat-harness/scripts/render-pre-commit.sh
  cat-harness/scripts/reseed-lean-cache.sh
  cat-harness/scripts/sage-mcp.sh
  cat-harness/scripts/session-start-coord-sweep.sh
  cat-harness/scripts/session-status.sh
  cat-harness/scripts/setup-lean-toolchain.sh
  cat-harness/scripts/start-folio-assistant.sh
  cat-harness/scripts/start-viewer.sh
  cat-harness/scripts/tests/run-tests.sh
  cat-harness/scripts/upload-bib-papers.sh
  cat-harness/scripts/upload-to-uploads.sh
  cat-harness/scripts/watch-main-prompt.sh
)

render() {
  local sh="$1"
  # CRLF on purpose: cmd.exe parses LF-only batch files, but mis-handles some
  # labels and multi-line blocks; CRLF is the safe encoding for .bat.
  printf '%s\r\n' \
    '@echo off' \
    'setlocal' \
    "rem Windows entry point for $sh -- generated by cat-harness/scripts/gen-bat-wrappers.sh; do not hand-edit." \
    'rem Runs the sibling .sh under Git Bash with the same arguments. Git for Windows is required.' \
    'set "SCRIPT=%~dpn0.sh"' \
    'set "BASH="' \
    'for %%B in ("%ProgramFiles%\Git\bin\bash.exe" "%ProgramFiles(x86)%\Git\bin\bash.exe" "%LocalAppData%\Programs\Git\bin\bash.exe") do if not defined BASH if exist %%B set "BASH=%%~B"' \
    "if not defined BASH for /f \"delims=\" %%G in ('where git.exe 2^>nul') do if not defined BASH if exist \"%%~dpG..\bin\bash.exe\" set \"BASH=%%~dpG..\bin\bash.exe\"" \
    'if not defined BASH (' \
    '  echo [%~nx0] Git Bash not found. Install Git for Windows from https://git-scm.com/download/win 1>&2' \
    '  exit /b 2' \
    ')' \
    'if not exist "%SCRIPT%" (' \
    '  echo [%~nx0] missing sibling script: %SCRIPT% 1>&2' \
    '  exit /b 2' \
    ')' \
    '"%BASH%" "%SCRIPT%" %*' \
    'exit /b %ERRORLEVEL%'
}

check="${1:-}"
stale=0
for sh in "${WRAPPED[@]}"; do
  [ -f "$sh" ] || { echo "ERROR: $sh does not exist — remove it from WRAPPED" >&2; exit 2; }
  bat="${sh%.sh}.bat"
  if [ "$check" = "--check" ]; then
    if [ ! -f "$bat" ] || ! cmp -s <(render "$sh") "$bat"; then
      echo "STALE: $bat"; stale=1
    fi
  else
    render "$sh" > "$bat"
    echo "wrote $bat"
  fi
done
if [ "$check" = "--check" ]; then
  [ "$stale" = 0 ] && echo "all $((${#WRAPPED[@]})) .bat wrappers up to date"
  exit $stale
fi
