#!/usr/bin/env bun
/**
 * Generate `avatars.css` from the avatar nodes.
 *
 * @module scripts/gen-avatars-css
 * @covers none — the avatar nodes are declared in `schemas/avatars.ts`, in code, so the
 *   stylesheet is generated from a module rather than from a graph directory. Whether every
 *   declared KIND has one is `check-avatar-coverage`'s question, and it is not in the gate set
 *
 * Same contract as `gen-themes-css.ts`, and for the same reason: the graph is
 * the source and the stylesheet is a rendering of it, so a colour or a glyph
 * has one home. `--check` fails when the committed file is stale.
 *
 * ## Why one stylesheet rather than 64 assets
 *
 * Sixteen kinds × two schemes × in/out of trash is 64 cells. As files they
 * would drift, and the one that fell behind would be invisible until somebody
 * opened the site in the other mode. Here the glyph is a `mask-image` and the
 * colour is `background-color`, so a scheme is a custom property and the
 * trash state is one extra selector — 64 cells out of 16 declarations.
 *
 * ## Both schemes are DERIVED from one hue, which is the point
 *
 * A kind declares a hue angle, not a colour. This builds the light pair and
 * the dark pair from it with fixed lightness targets, so a kind cannot be
 * legible in one mode and invisible in the other. That is the `y8cm` /
 * `rptk` failure, which this repo has already shipped twice by choosing two
 * colours independently and checking one.
 *
 * Exit codes: 0 written or up to date · 1 stale under `--check`.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { AVATARS, GENERIC, TRASH_OVERLAY, type Avatar } from "../schemas/avatars.js";
import { instanceRootFor, siteDirFor } from "../schemas/cat-harness.js";

/** Where the stylesheet goes. Derived from `siteDirFor`, never written down. */
export function avatarsCssPath(root: string): string {
  return join(siteDirFor(root), "assets", "css", "avatars.css");
}

/**
 * A path as a `mask-image` value.
 *
 * `#` and `<` `>` must be escaped or the data URI terminates early — `#`
 * starts a fragment, and an unescaped `<` breaks some parsers. Quotes are
 * single inside so the CSS `url("…")` can stay double.
 */
function mask(d: string): string {
  const svg =
    `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'>` +
    `<path d='${d}' fill='none' stroke='black' stroke-width='1.7' ` +
    `stroke-linecap='round' stroke-linejoin='round'/></svg>`;
  return `url("data:image/svg+xml,${svg.replace(/</g, "%3C").replace(/>/g, "%3E").replace(/#/g, "%23")}")`;
}

/**
 * The two colours a hue becomes, per scheme.
 *
 * Fixed lightness targets rather than per-kind values: a kind picks WHICH
 * colour, never HOW DARK, so no kind can be authored into the unreadable
 * corner of one scheme. Saturation drops in the trash state and lightness
 * moves toward the surface, so a discarded item reads as quieter without
 * becoming invisible — muted is not hidden.
 */
function tones(tone: number): { light: string; dark: string; lightTrash: string; darkTrash: string } {
  return {
    light: `hsl(${tone} 46% 34%)`,
    dark: `hsl(${tone} 42% 72%)`,
    lightTrash: `hsl(${tone} 16% 52%)`,
    darkTrash: `hsl(${tone} 14% 56%)`,
  };
}

function block(selector: string, entries: [string, Avatar][], pick: keyof ReturnType<typeof tones>): string {
  return entries
    .map(([kind, a]) => `${selector.replace("KIND", kind)} { background-color: ${tones(a.tone)[pick]}; }`)
    .join("\n");
}

export function renderAvatarsCss(): string {
  const entries: [string, Avatar][] = [...Object.entries(AVATARS), ["__generic", GENERIC]];

  const head = `/* GENERATED by scripts/gen-avatars-css.ts from schemas/avatars.ts — do not hand-edit.
 *
 * One avatar per declared kind, in and out of the trash, in both schemes.
 * Run \`bun run avatars:css\` after editing an avatar node;
 * \`avatars:css:check\` fails the build when this is stale.
 *
 * The glyph is a MASK and the colour is \`background-color\`, so a scheme is a
 * custom property rather than a second set of assets. Both scheme colours are
 * DERIVED from one declared hue with fixed lightness targets, so no kind can
 * be authored legible in one mode and invisible in the other.
 *
 * The trash state is the same glyph, desaturated, under the crumple overlay
 * \`d1r6\` established as the discard mark — a discarded proposal must read as
 * a proposal that was discarded, not as a different object.
 */`;

  const base = `.fa-avatar {
  display: inline-block;
  width: var(--fa-avatar-size, 1.5rem);
  height: var(--fa-avatar-size, 1.5rem);
  flex: none;
  /* The colour is painted through the glyph's shape. */
  background-color: currentColor;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-position: center;
  mask-position: center;
  -webkit-mask-size: contain;
  mask-size: contain;
}

/* The crumple, as a SECOND layer over the same box. Composited rather than
 * drawn into each glyph, so the discard mark is one declaration. */
.fa-avatar[data-fa-trash="true"] {
  -webkit-mask-image: var(--fa-avatar-glyph), ${mask(TRASH_OVERLAY)};
  mask-image: var(--fa-avatar-glyph), ${mask(TRASH_OVERLAY)};
  -webkit-mask-composite: source-over;
  mask-composite: add;
}`;

  const glyphs = entries
    .map(([kind, a]) => {
      const sel = kind === "__generic" ? ".fa-avatar" : `.fa-avatar[data-fa-kind="${kind}"]`;
      return (
        `${sel} {\n` +
        `  /* ${a.reads} */\n` +
        `  --fa-avatar-glyph: ${mask(a.glyph)};\n` +
        `  -webkit-mask-image: var(--fa-avatar-glyph);\n` +
        `  mask-image: var(--fa-avatar-glyph);\n` +
        `}`
      );
    })
    .join("\n\n");

  const sel = '.fa-avatar[data-fa-kind="KIND"]';
  const gen = ".fa-avatar";
  // The dual guard this repo uses everywhere: the explicit choice wins, and
  // the system preference applies only when nothing was chosen. One without
  // the other leaves a reader who set a scheme with the other scheme's art.
  const light = [
    `/* Light — the explicit choice, then the system default. */`,
    `:root[data-fa-scheme="light"] {`,
    block(sel, Object.entries(AVATARS), "light")
      .split("\n")
      .map((l) => `  ${l}`)
      .join("\n"),
    `  ${gen} { background-color: ${tones(GENERIC.tone).light}; }`,
    `}`,
    ``,
    `@media (prefers-color-scheme: light) {`,
    `  :root:not([data-fa-scheme="dark"]) {`,
    block(sel, Object.entries(AVATARS), "light")
      .split("\n")
      .map((l) => `    ${l}`)
      .join("\n"),
    `    ${gen} { background-color: ${tones(GENERIC.tone).light}; }`,
    `  }`,
    `}`,
  ].join("\n");

  const dark = [
    `/* Dark — the explicit choice, then the system default. */`,
    `:root[data-fa-scheme="dark"] {`,
    block(sel, Object.entries(AVATARS), "dark")
      .split("\n")
      .map((l) => `  ${l}`)
      .join("\n"),
    `  ${gen} { background-color: ${tones(GENERIC.tone).dark}; }`,
    `}`,
    ``,
    `@media (prefers-color-scheme: dark) {`,
    `  :root:not([data-fa-scheme="light"]) {`,
    block(sel, Object.entries(AVATARS), "dark")
      .split("\n")
      .map((l) => `    ${l}`)
      .join("\n"),
    `    ${gen} { background-color: ${tones(GENERIC.tone).dark}; }`,
    `  }`,
    `}`,
  ].join("\n");

  const trashSel = '.fa-avatar[data-fa-kind="KIND"][data-fa-trash="true"]';
  const trash = [
    `/* In the trash — muted, in both schemes. Muted is not hidden: the`,
    ` * lightness still clears the surface, because an unreadable discarded`,
    ` * item is a deleted one as far as a reader is concerned. */`,
    `:root[data-fa-scheme="light"] {`,
    block(trashSel, Object.entries(AVATARS), "lightTrash")
      .split("\n")
      .map((l) => `  ${l}`)
      .join("\n"),
    `}`,
    ``,
    `@media (prefers-color-scheme: light) {`,
    `  :root:not([data-fa-scheme="dark"]) {`,
    block(trashSel, Object.entries(AVATARS), "lightTrash")
      .split("\n")
      .map((l) => `    ${l}`)
      .join("\n"),
    `  }`,
    `}`,
    ``,
    `:root[data-fa-scheme="dark"] {`,
    block(trashSel, Object.entries(AVATARS), "darkTrash")
      .split("\n")
      .map((l) => `  ${l}`)
      .join("\n"),
    `}`,
    ``,
    `@media (prefers-color-scheme: dark) {`,
    `  :root:not([data-fa-scheme="light"]) {`,
    block(trashSel, Object.entries(AVATARS), "darkTrash")
      .split("\n")
      .map((l) => `    ${l}`)
      .join("\n"),
    `  }`,
    `}`,
  ].join("\n");

  return `${[head, base, glyphs, light, dark, trash].join("\n\n")}\n`;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  // THE INSTANCE this script belongs to — the one it lives in — not whatever
  // directory the gate was invoked from. Those were the same until the move
  // (bean `wggr`), after which `siteDirFor(cwd)` threw on a `harness.json`
  // that is one directory down.
  const root = instanceRootFor(import.meta.dir);
  const rel = avatarsCssPath(root);
  const path = join(root, rel);
  const next = renderAvatarsCss();
  const current = existsSync(path) ? readFileSync(path, "utf8") : undefined;
  const n = Object.keys(AVATARS).length;

  if (check) {
    if (current === next) {
      console.log(`avatars.css is up to date (${n} kinds + generic)`);
      process.exit(0);
    }
    console.error("avatars.css is stale — run `bun run avatars:css` and commit");
    process.exit(1);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  console.log(`wrote ${rel} (${n} kinds + generic, both schemes, in and out of trash)`);
}
