#!/usr/bin/env bun
/**
 * The Jekyll sidebar's navbar, written by the SAME renderer every mounted and
 * generated page uses. Bean `sjic`, issue #1260.
 *
 * @covers none — this asks whether a GENERATED INCLUDE is current, not
 * whether a declared graph is well-formed. It reads `docs/_data/harness.json`,
 * which is itself generated by `docs:harness` from the instance declarations,
 * so the graph question is asked there and asking it again here would be a
 * second answer free to disagree. `none` rather than silence, because a gate
 * that has DECIDED it audits no graph is a different fact from one that has
 * not said, and `audit:coverage` counts the latter as a gap.
 *
 * ## What this is for
 *
 * `nav_footer_custom.html` composed 392 lines of its own markup and called
 * nothing. `navbar.ts` is the renderer. PR #959 gave the two shared geometry
 * and behaviour — they can no longer disagree about a width — but `sjic`'s own
 * note is right that *"cannot disagree" is not "one renderer"*: two files still
 * decided independently what a harness row contains, and they came apart. The
 * sidebar let a reader reach `who-iris/library/` from a harness row; the rail
 * stopped at the harness.
 *
 * So the Liquid file becomes a one-line `{% include %}` and this writes what it
 * includes. The template composes no markup at all — not a tag.
 *
 * ## Why a generated INCLUDE rather than an injection pass
 *
 * `rail-standalone-pages.ts` (`oi1y`) injects the rail into finished HTML after
 * the build, and that is the right mechanism for a page Jekyll copied through
 * verbatim. It is the wrong one here: these pages already have a navigation,
 * the theme's `<nav id="site-nav">`, and the harness tabs belong INSIDE
 * `.side-bar` rather than in a second landmark beside it. `nav_footer_custom`
 * is just-the-docs' own extension point inside that element, which is why using
 * it keeps the theme pin cheap.
 *
 * `_includes/generated/todo-listing.html` is the precedent for the shape: a
 * TypeScript generator, a committed artefact, a `--check` gate, and Liquid
 * `relative_url` filters in the output.
 *
 * ## THE ONE THING THE RENDERER CANNOT DECIDE, and what is done about it
 *
 * A viewer declared `publish: "staging-only"` is a LINK on a staging preview
 * and a NOTE on the canonical deploy. That is a fact about which deploy is
 * being built, and this file is COMMITTED — so it cannot be baked here.
 *
 * It is not baked upstream either, and that was checked rather than assumed:
 * neither `docs-site.yml` nor `feature-staging.yml` re-runs `docs:harness`, so
 * `docs/_data/harness.json` is the same bytes on both deploys. `--staging` is
 * passed to `compose-docs.ts` and nowhere else. The only thing that knows is
 * `site.data.build.staging_slug`, read at Jekyll time.
 *
 * So the GENERATOR emits one Liquid conditional and the RENDERER stays free of
 * Liquid: the model is built twice, once per deploy, and each is rendered by
 * the same function. That is the bean's words exactly — one renderer, and the
 * difference DECLARED, here as two models rather than as a branch in the
 * markup path.
 *
 * **Two full copies for one row is a deliberate trade, and the number is
 * measured: 1 staging-only viewer out of 73.** The alternative is a renderer
 * that emits Liquid conditionals, which would put template control flow inside
 * the one module whose whole value is that it produces plain markup for four
 * different consumers. Bytes are cheap; a renderer that knows about Jekyll is
 * not. If that ratio ever moves — if a third of the graph becomes staging-only
 * — this trade should be re-made rather than inherited.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { siteDirFor } from "../schemas/cat-harness.js";
import { graphTypologyRowDecor } from "./lib/graph-typology-nav.js";
import { kindTitle } from "./lib/nav-label.js";
import { navMarkFields, type HarnessMark } from "./lib/harness-mark.js";
import {
  navbarOpenInputHtml,
  navbarRegionsHtml,
  type NavGroup,
  type NavItem,
  type NavbarModel,
} from "./lib/navbar.js";

const ROOT = join(dirname(new URL(import.meta.url).pathname), "..", "..");
// THE SITE ROOT IS ASKED FOR, never written down. `site-dir-single-answer`
// refuses the literal in source, and rightly: this generator writes into the
// site and a second copy of that string is a second answer to where the site
// is. It caught this file on its first run.
const INSTANCE = join(ROOT, "cat-harness");
const SITE = join(INSTANCE, siteDirFor(INSTANCE));
const DATA = join(SITE, "_data", "harness.json");
const OUT = join(SITE, "_includes", "generated", "navbar-footer.html");

/**
 * The shape this reads out of `harness.json`.
 *
 * Declared structurally rather than imported from `harness-tiles.ts` on
 * purpose: this consumes the PUBLISHED artefact, and a type imported from the
 * producer would make a field look present here that the writer had stopped
 * emitting. The gate that catches a real mismatch is `docs:harness:check`,
 * which regenerates the data.
 */
interface Visualisation {
  kind: string;
  label?: string;
  sameAs?: string;
  path?: string | null;
  note?: string;
  stagingOnly?: true;
}
export interface Harness {
  name: string;
  title?: string;
  label?: string;
  href?: string;
  tone?: number;
  mark?: HarnessMark | null;
  instantiated?: boolean;
  visualisations?: Visualisation[];
  needs?: string[];
}

/**
 * The harness rows for an IG REPOSITORY'S OWN SITE (#2235 F1), the same view
 * the rail's `--instance` gives a page it injects into (`instanceHarnesses`):
 * this instance first, then what it needs, transitively, and nothing else.
 *
 * The rows are the main site's (`docs/_data/harness.json`), so their paths
 * are the main site's. On this site the instance IS the root: a path under
 * `/<instance>/` becomes the same path at `/`; every other path is the main
 * site's page and becomes an absolute URL under `linkRoot`, which Jekyll's
 * `relative_url` leaves as written.
 */
export function instanceView(harnesses: readonly Harness[], instance: string, linkRoot: string): Harness[] {
  const byName = new Map(harnesses.map((h) => [h.name, h]));
  const reach = new Set([instance]);
  for (const queue = [instance]; queue.length > 0; ) {
    for (const n of byName.get(queue.shift()!)?.needs ?? []) {
      if (reach.has(n)) continue;
      reach.add(n);
      queue.push(n);
    }
  }
  const root = linkRoot.replace(/\/$/, "");
  const own = `/${instance}/`;
  const map = (p: string | null | undefined): string | undefined => {
    if (!p) return undefined;
    if (/^[a-z][a-z0-9+.-]*:/i.test(p)) return p;
    if (p === own.slice(0, -1) || p.startsWith(own)) return `/${p.slice(own.length)}`;
    return `${root}${p.startsWith("/") ? "" : "/"}${p}`;
  };
  return harnesses
    .filter((h) => reach.has(h.name))
    .sort((a, b) => (a.name === instance ? -1 : b.name === instance ? 1 : 0))
    .map((h) => {
      const href = h.name === instance ? "/" : map(h.href);
      const { href: _drop, ...rest } = h;
      return {
        ...rest,
        ...(href ? { href } : {}),
        instantiated: true,
        visualisations: (h.visualisations ?? []).map((v) => {
          const { path: _p, ...vr } = v;
          const path = map(v.path);
          return path ? { ...vr, path } : vr;
        }),
      };
    });
}

/**
 * One harness's own graphs, as rows nested under it.
 *
 * `staging` says which deploy is being rendered, and it changes exactly one
 * thing: whether a staging-only viewer is reachable. Everything else about the
 * row is the same on both, which is why the models differ by a boolean rather
 * than by construction.
 *
 * **A kind with no path is rendered, not dropped** — `pb04`, and the rule the
 * rest of the navbar follows. A declared graph with no published viewer is a
 * FINDING, and hiding it would answer "what is in this harness" with silence.
 * `harness-tiles.ts` has already worded the reason; this picks none of them.
 */
function graphRows(h: Harness, staging: boolean): NavItem[] {
  // ONE NAME PER DESTINATION (bean `ob3m` finding 6): the row says the label
  // `harness-tiles.ts` gave it, never the bare kind word, and a kind whose page
  // is another kind's row (`sameAs`) is not listed a second time.
  return (h.visualisations ?? []).filter((v) => v.sameAs === undefined).map((v) => {
    const label = v.label ?? kindTitle(v.kind);
    const withheld = v.stagingOnly === true && !staging;
    // The same distinct glyph and full accessible name the rail gives a kind
    // row (bean `yag0`) — one answer, from `lib/graph-typology-nav.ts`.
    // The kind's HUE is left out here: the sidebar paints these small marks
    // on its own neutral chip in the page's ink, and a dark tone behind a
    // dark-ink glyph would lose contrast. The shape and the words carry it.
    const { tone: _tone, ...decor } = graphTypologyRowDecor(v.kind, h.label ?? h.title ?? h.name);
    if (v.path && !withheld) return { href: v.path, label, ...decor };
    const note = withheld ? "staging only" : v.note;
    return { label, ...decor, ...(note ? { note } : {}) };
  });
}

/** One harness row: its mark, its label, its ⚙, and its graphs. */
function harnessRow(h: Harness, staging: boolean): NavItem {
  const label = h.label ?? h.title ?? h.name;
  const kids = graphRows(h, staging);
  return {
    ...(h.href ? { href: h.href } : {}),
    label,
    // The row's resolved mark — image or glyph — read the one way every
    // navbar surface reads it (bean `2vpn`, `lib/harness-mark.ts`).
    ...navMarkFields(h.mark, h.tone),
    // The ⚙ opens the glass's Harnesses panel with this harness chosen (#1146).
    // `docs-ui.js` handles it by delegation; with no script it does nothing and
    // the row still works.
    action: {
      data: "data-fa-harness-config",
      value: h.name,
      label: `Configuration of ${label}`,
      glyph: "⚙︎",
    },
    ...(kids.length > 0 ? { children: kids } : {}),
  };
}

/**
 * The model for one deploy.
 *
 * **No `graphs`** — the theme's own `<nav id="site-nav">` owns the middle
 * region on this surface, and an empty disclosure there would be a second,
 * emptier answer to the same question.
 *
 * **Only the INSTANTIATED harnesses.** The owner, 2026-09-22: *"get rid of
 * dependencies."* A dependency that is not instantiated here publishes no folio
 * of its own to reach; what it contributes arrives through the instances that
 * do appear, which is what inheritance means.
 *
 * **Closed on arrival** — *"harnesses start closed"* — and the count on the
 * summary still says how many there are, so folded is not hidden.
 */
function model(
  harnesses: Harness[],
  title: string,
  staging: boolean,
  openControl: "input" | "labels",
  fshGuts: boolean,
): NavbarModel {
  const shown = harnesses.filter((h) => h.instantiated === true);
  const group: NavGroup = {
    label: "Harnesses",
    icon: "▦",
    items: shown.map((h) => harnessRow(h, staging)),
    collapsible: true,
  };
  return {
    instance: title,
    hrefs: "liquid",
    openControl,
    // The theme's `.site-title` avatar IS the header here (#1757).
    head: "none",
    ...(shown.length > 0 ? { harnesses: group } : {}),
    // fsh-guts in the FIXED top (#1925, owner 2026-10-02: *"also add fsh-guts
    // icon to LHS top navbar"*), only when this instance DECLARES the
    // fsh-guts tile: a control for a trashcan nobody declared is a promise
    // with nothing behind it.
    ...(fshGuts ? { fshGuts: { label: "fsh-guts, discarded items" } } : {}),
    // Home is last in the fixed bottom, outside the disclosure, so folding the
    // harnesses away cannot take it with it — *"keep home at bottom for who
    // iris."*
    home: { href: "/", label: title, icon: "⌂" },
  };
}

const BANNER =
  "<!-- GENERATED by cat-harness/scripts/gen-navbar-include.ts. Do not hand-edit: " +
  "`bun run navbar:include` rewrites it, and `--check` fails the build if it is stale. -->";

/**
 * The file, Liquid control flow and all.
 *
 * The control flow is written HERE, by a generator, rather than in the template
 * — which is what lets `nav_footer_custom.html` be a single `{% include %}`
 * that composes not one tag. Both conditionals ask a question about the BUILD
 * that no renderer can answer:
 *
 * - `fa_nav_copy` — just-the-docs renders this extension point TWICE per page,
 *   once inside `.side-bar` and once in a `.d-md-none` block outside it. With
 *   the input in both, `id="fa-nav-open"` appeared twice on 429 of 1,283 pages
 *   (`uknu`). A Liquid `assign` inside an include sets the PAGE's context, so
 *   the counter survives from the first copy to the second and resets per page.
 * - `staging_slug` — which deploy this is. `head_custom.html` writes the same
 *   value into `fa-staging`, so the template and the client ask one question.
 *
 * `default:` collapses nil and empty, which are the same answer here: a build
 * that cannot say it is a preview is treated as canonical, which is the safe
 * direction and the one `isStagingPreview` already takes.
 */
export function render(harnesses: Harness[], title: string, fshGuts = false): string {
  const region = (staging: boolean): string =>
    navbarRegionsHtml(model(harnesses, title, staging, "labels", fshGuts));
  return (
    `${BANNER}\n` +
    `{%- assign fa_nav_copy = fa_nav_copy | default: 0 | plus: 1 -%}\n` +
    `{%- if fa_nav_copy == 1 -%}${navbarOpenInputHtml()}{%- endif -%}\n` +
    `{%- assign _fa_staging = site.data.build.staging_slug | default: '' -%}\n` +
    `{%- if _fa_staging == '' -%}\n${region(false)}\n{%- else -%}\n${region(true)}\n{%- endif -%}\n`
  );
}

function main(): void {
  const check = process.argv.includes("--check");
  const data = JSON.parse(readFileSync(DATA, "utf-8")) as {
    harnesses?: Harness[];
    title?: string;
    tiles?: { id?: string }[];
  };
  // fsh-guts is NOT emitted into `.fa-nav-top` any more: the owner put it in
  // the declared icon row, "with the others" (2026-10-02, #1925), which
  // `mountNavIconRow` draws from `navbarIcons`. One placement, not two.
  // `--instance <name> --link-root <main site URL> [--title <label>] [--out <file>]`:
  // the navbar of an IG repository's own site (#2235 F1). Written into that
  // site's composed shell, never over the committed include.
  const argv = process.argv;
  const opt = (f: string) => (argv.includes(f) ? argv[argv.indexOf(f) + 1] : undefined);
  const instance = opt("--instance");
  if (instance) {
    const linkRoot = opt("--link-root");
    const out = opt("--out");
    if (!linkRoot || !out) {
      console.error("gen-navbar-include: --instance needs --link-root and --out (the shell's _includes/generated/navbar-footer.html)");
      process.exit(2);
    }
    const rows = instanceView(data.harnesses ?? [], instance, linkRoot);
    if (!rows.some((h) => h.name === instance)) {
      console.error(`gen-navbar-include: no harness named ${instance} in ${DATA}`);
      process.exit(2);
    }
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, render(rows, opt("--title") ?? instance, false));
    console.log(`wrote ${out} — ${instance}'s own navbar: ${rows.map((h) => h.name).join(", ")}`);
    return;
  }
  const next = render(data.harnesses ?? [], data.title ?? "folio-assistant", false);

  let current: string | undefined;
  try {
    current = readFileSync(OUT, "utf-8");
  } catch {
    current = undefined;
  }
  if (current === next) {
    console.log(`navbar include up to date — ${(data.harnesses ?? []).filter((h) => h.instantiated).length} instantiated harness(es)`);
    return;
  }
  if (check) {
    console.error("docs/_includes/generated/navbar-footer.html is stale — run `bun run navbar:include` and commit");
    process.exit(1);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, next);
  console.log(`wrote ${OUT}`);
}

// Guarded so a test can import `render` without rewriting the committed include.
if (import.meta.main) main();
