/**
 * Publish the rail's stylesheet as a FILE — `assets/css/navbar.css`.
 *
 * `navbarCss()` in `lib/navbar.ts` is the rail's one stylesheet, and every
 * railed page carried it INLINED: 4.3 KB of the rail's 7.9 KB. On a thin page
 * of 1.4-3 KB (a library entry, an OpenAPI operation, a todo) that was most of
 * the page, so those pages declined the rail "until the rail is itself a shared
 * asset". This makes it one: a page declaring `folio-navbar: linked` links this
 * file instead (owner, 2026-10-05: *"1. Shared rail style first"*, bean `lnoy`).
 *
 * The file is GENERATED, never edited: `navbarCss()` stays the source, and
 * `navbar-css-file.test.ts` fails when the two differ.
 *
 *   bun run navbar:css           write it
 *   bun run navbar:css:check     exit 1 if it is stale
 *
 * @module cat-harness/scripts/gen-navbar-css
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { siteDirFor } from "../schemas/cat-harness.ts";
import { NAVBAR_CSS, navbarCss } from "./lib/navbar.ts";

const ROOT = join(import.meta.dir, "..");

/** The file's bytes: a header saying where it comes from, then `navbarCss()`. */
export function navbarCssFile(): string {
  return (
    "/* GENERATED by cat-harness/scripts/gen-navbar-css.ts from navbarCss() in\n" +
    " * cat-harness/scripts/lib/navbar.ts. Do not edit: `bun run navbar:css`. */\n" +
    navbarCss() +
    "\n"
  );
}

/** Where the file is written in this checkout. */
export function navbarCssPath(): string {
  return join(ROOT, siteDirFor(ROOT), NAVBAR_CSS);
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const path = navbarCssPath();
  const want = navbarCssFile();
  const have = existsSync(path) ? readFileSync(path, "utf-8") : undefined;
  if (check) {
    if (have === want) {
      console.log(`✓ ${NAVBAR_CSS} matches navbarCss()`);
    } else {
      console.error(`✗ ${NAVBAR_CSS} is ${have === undefined ? "missing" : "stale"} — run \`bun run navbar:css\``);
      process.exit(1);
    }
  } else {
    writeFileSync(path, want);
    console.log(`✓ wrote ${NAVBAR_CSS}`);
  }
}
