#!/usr/bin/env bun
/**
 * Generate `navbar-geometry.css` from `lib/navbar-geometry.ts`.
 *
 * @module scripts/gen-navbar-geometry-css
 *
 * Same contract as `gen-avatars-css.ts`: the module is the source and the
 * stylesheet is a rendering of it, so a width has one home. `--check` fails
 * when the committed file is stale.
 *
 * ## What this closes
 *
 * `sjic`. `navbar.ts` interpolates its numbers into the stylesheet it emits
 * for a mounted page; `docs-ui.css` is hand-authored and stated its own. They
 * disagreed — 40px against 56px at rest, 232px against 248px open — and each
 * side had a test asserting its own copy, so both were green while the two
 * navbars the owner called "the same navbar" were different widths.
 *
 * **A generated custom property is what makes that unrepeatable.** The check
 * gate is the load-bearing half: without it the file is a snapshot that goes
 * stale silently, which is the same defect with an extra step.
 *
 * ## Why custom properties rather than rewriting `docs-ui.css`
 *
 * `docs-ui.css` already reads `var(--fa-nav-collapsed)` and
 * `var(--fa-nav-open)` in nine places. Generating the two DEFINITIONS and
 * leaving every use in the authored stylesheet keeps the hand-written CSS
 * hand-written — the alternative is a generated 5,000-line file nobody may
 * edit, to own two numbers.
 *
 * Exit codes: 0 written or up to date · 1 stale under `--check`.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { instanceRootFor, siteDirFor } from "../schemas/cat-harness.js";
import { NAV_GEOMETRY, rem } from "./lib/navbar-geometry.js";

/**
 * Where the stylesheet goes. Derived from `siteDirFor`, never written down —
 * the same contract as `avatarsCssPath`, and `site-dir-single-answer` is the
 * gate that enforces it. My first draft spelled the path out and that gate
 * caught it: a literal site root is a second answer to a question the
 * declaration already answers, and it writes the file where nothing serves it
 * the moment an instance is laid out differently.
 */
export function navbarGeometryCssPath(root: string): string {
  return join(siteDirFor(root), "assets", "css", "navbar-geometry.css");
}

export function renderNavbarGeometryCss(): string {
  const g = NAV_GEOMETRY;
  return `/* GENERATED by scripts/gen-navbar-geometry-css.ts — do not edit.
 *
 * The navbar's geometry, from \`scripts/lib/navbar-geometry.ts\`. That module
 * carries the argument for every value here, including which side's numbers
 * won and why. \`navbar.ts\` interpolates the same constants into the
 * stylesheet it injects on a mounted page, so the rail and this site's sidebar
 * cannot be different widths.
 *
 * Loaded BEFORE docs-ui.css, which reads these as \`var(--fa-nav-*)\`.
 */
:root {
  /* The mark column — the avatar or glyph, and the only thing in the strip. */
  --fa-nav-mark: ${rem(g.markPx)};
  /* Gutter either side of it. DERIVED: (collapsed - mark) / 2. */
  --fa-nav-pad: ${rem(g.padPx)};
  /* At rest. Closed is NOT gone — a width, never a \`visibility: hidden\`. */
  --fa-nav-collapsed: ${rem(g.collapsedPx)};
  /* Open, at the theme's mq(md). */
  --fa-nav-open: ${rem(g.openPx)};
}

/* The theme widens its own sidebar here, with a \`min-width\` FLOOR in
 * layout.scss that a later \`width\` cannot cross. That floor is why these are
 * the numbers both surfaces adopt rather than the rail's. */
@media (min-width: ${rem(g.wideMqPx)}) {
  :root { --fa-nav-open: ${rem(g.openWidePx)}; }
}
`;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  // THE INSTANCE this script belongs to — the one it lives in — not whatever
  // directory the gate was invoked from, for the reason `gen-avatars-css.ts`
  // states: `siteDirFor(cwd)` throws on a `harness.json` one directory down.
  const root = instanceRootFor(import.meta.dir);
  const rel = navbarGeometryCssPath(root);
  const path = join(root, rel);
  const next = renderNavbarGeometryCss();
  const current = existsSync(path) ? readFileSync(path, "utf8") : undefined;

  if (check) {
    if (current === next) {
      console.log("navbar-geometry.css is up to date");
      process.exit(0);
    }
    console.error("navbar-geometry.css is stale — run `bun run navbar:geometry` and commit");
    process.exit(1);
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, next);
  console.log(`wrote ${rel} (strip ${NAV_GEOMETRY.collapsedPx}px, open ${NAV_GEOMETRY.openPx}px)`);
}
