/**
 * Publish the rail's shared assets — `assets/css/navbar.css` and
 * `assets/js/navbar.js`. Bean `lnoy`.
 *
 * Owner, 2026-10-05: *"1. Shared rail style first"*, then *"4. Option 3
 * everywhere"* — the rail drawn in the browser from shared data, so a page
 * carries ~0.1 KB of rail instead of ~21 KB of markup.
 *
 * - `navbar.css` is `navbarCss()` from `lib/navbar.ts`, verbatim.
 * - `navbar.js` is `navbar-client.ts` bundled: `renderRailRegions` and
 *   `navbarHtml`'s regions, the SAME code the build renders the rail with, so
 *   the browser cannot draw a different rail from the build's audit.
 *
 * Both are GENERATED, never edited, and committed; `navbar-assets.test.ts`
 * fails when either differs from what this writes. Bun is pinned (1.3.14,
 * `.bun-version` and every workflow), which is what makes a committed bundle
 * checkable byte for byte.
 *
 *   bun run navbar:assets           write them
 *   bun run navbar:assets:check     exit 1 if either is stale
 *
 * @module cat-harness/scripts/gen-navbar-assets
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { siteDirFor } from "../schemas/cat-harness.ts";
import { NAVBAR_JS } from "./lib/harness-rail.ts";
import { NAVBAR_CSS, navbarCss } from "./lib/navbar.ts";

const ROOT = join(import.meta.dir, "..");
const HEADER = (src: string) =>
  `/* GENERATED by cat-harness/scripts/gen-navbar-assets.ts from ${src}.\n` +
  ` * Do not edit: \`bun run navbar:assets\`. */\n`;

/** `navbar.css`'s bytes. */
export function navbarCssFile(): string {
  return HEADER("navbarCss() in cat-harness/scripts/lib/navbar.ts") + navbarCss() + "\n";
}

/** `navbar.js`'s bytes: the client entry, bundled for the browser. */
export async function navbarJsFile(): Promise<string> {
  const r = await Bun.build({
    entrypoints: [join(import.meta.dir, "navbar-client.ts")],
    target: "browser",
    minify: true,
    format: "iife",
  });
  if (!r.success) throw new Error(`navbar.js: bundle failed — ${r.logs.map(String).join("; ")}`);
  return HEADER("cat-harness/scripts/navbar-client.ts") + (await r.outputs[0]!.text());
}

/** Where each is written in this checkout. */
export function navbarAssetPaths(): { css: string; js: string } {
  const site = join(ROOT, siteDirFor(ROOT));
  return { css: join(site, NAVBAR_CSS), js: join(site, NAVBAR_JS) };
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const paths = navbarAssetPaths();
  const want = { css: navbarCssFile(), js: await navbarJsFile() };
  let stale = 0;
  for (const k of ["css", "js"] as const) {
    const have = existsSync(paths[k]) ? readFileSync(paths[k], "utf-8") : undefined;
    if (check) {
      if (have !== want[k]) {
        console.error(`✗ ${paths[k]} is ${have === undefined ? "missing" : "stale"} — run \`bun run navbar:assets\``);
        stale++;
      }
    } else {
      writeFileSync(paths[k], want[k]);
      console.log(`✓ wrote ${paths[k]}`);
    }
  }
  if (check && stale) process.exit(1);
  if (check) console.log("✓ navbar.css and navbar.js match their sources");
}
