#!/usr/bin/env bun
/**
 * The kinds the graph-kind TABLE names, and every name a row may carry.
 *
 * @module scripts/kind-table
 * @graphNode none — a reader over one authored table
 *
 * ## Why this is a module and not two functions in a test
 *
 * It was both functions in `tests/graph-kind-docs.test.ts`, which was the right
 * home while only that test asked. `kind:register` asks the same question — a new
 * kind owes a table ROW, and the row is **authored**, so the command reports it
 * rather than writing it — and a second copy of a parser over a hand-written
 * table is two answers that drift the first time a column moves. Bean `uoij`.
 *
 * Moved rather than duplicated: the test imports these, so there is still one
 * reader of the table, and its own assertions did not change.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";

import { BASE_GRAPH_KINDS, GRAPH_KIND_ALIASES, defaultGraphKinds } from "../schemas/cat-harness.js";
import { graphKindLayer } from "../schemas/graph-kind-registry.ts";
// `folio` and `glossary` are registered by CORE as a load-time side effect.
import "../schemas/folio-graph-kind.js";
import "../schemas/glossary-graph-kind.js";

/** The instance root this reader is relative to. */
export const KIND_TABLE_ROOT = join(import.meta.dir, "..");
export const KIND_TABLE_DOC = "skills/kg/kg-core/directory-conventions.md";
/** The table's header row, verbatim. Renaming a column is a deliberate edit. */
export const KIND_TABLE_HEADER = "| kind | declared by | contents | renderable |";

/**
 * The kinds the table names, read from its FIRST COLUMN only.
 *
 * Located by the header row rather than by position or by a pattern over the
 * prose: the file holds two pipe-tables and this is the one whose columns say
 * what they are. Absent, or present more than once, **THROWS** — a table a
 * caller cannot find is not an empty table, and a silent pass over nothing is
 * the failure mode this exists to prevent (#266 drifted through three green
 * merges that way).
 */
export function documentedKinds(root: string = KIND_TABLE_ROOT): string[] {
  const lines = readFileSync(join(root, KIND_TABLE_DOC), "utf8").split("\n");
  const at = lines.reduce<number[]>((acc, l, i) => (l.trim() === KIND_TABLE_HEADER ? [...acc, i] : acc), []);
  if (at.length !== 1) {
    throw new Error(
      `${KIND_TABLE_DOC}: expected exactly one graph-kind table header, found ${at.length}. ` +
        `Looked for the line: ${KIND_TABLE_HEADER}`,
    );
  }
  const out: string[] = [];
  // Skip the header and the |---|---| delimiter beneath it.
  for (let i = at[0]! + 2; i < lines.length; i++) {
    const line = lines[i]!;
    if (!line.trimStart().startsWith("|")) break;
    const first = line.split("|")[1] ?? "";
    // A cell reads `` `tools` `` or `` **`folio-assist-core`** ``; the kind is the
    // backticked token, and bold marks WHO DECLARES it in the next column.
    const kind = first.replace(/[`*]/g, "").trim();
    if (kind) out.push(kind);
  }
  return out;
}

/** Every name a table row may legitimately carry. */
export function validKinds(): Set<string> {
  return new Set([
    ...defaultGraphKinds.names(),
    ...Object.keys(BASE_GRAPH_KINDS),
    // A deprecated alias still reads, so documenting one is not an error.
    ...Object.keys(GRAPH_KIND_ALIASES),
  ]);
}

// ── The table is GENERATED (bean dmx1) ──────────────────────────────────────
//
// Owner, 2026-10-04: no central registry for subgraph types, and, asked what
// to do with this hand-kept table, "prose onto the nodes" (option 1 of 3): each
// row's `contents` moved onto its kind as `description` (a kind node's field,
// or a listed kind's entry), and the table is rendered from the kinds, grouped
// by who declares them. A row cannot drift from its kind, because it IS the kind.

export const KIND_TABLE_BEGIN = "<!-- kind-table:begin (generated by `bun run kind:table` from the declared kinds; edit the kind, not this table) -->";
export const KIND_TABLE_END = "<!-- kind-table:end -->";

/** The `declared by` cell: the owning harness for a declared kind, the layer for a listed one. */
function declaredByCell(kind: string, root: string): string {
  const file = defaultGraphKinds.declaredBy(kind);
  if (file !== undefined) {
    const rel = relative(dirname(root), file).split(sep);
    const at = rel.indexOf("kinds");
    return `**${rel.slice(0, at).join("/")}** (\`kinds/${rel.slice(at + 1).join("/")}\`)`;
  }
  const def = defaultGraphKinds.get(kind);
  return `**${graphKindLayer(kind, def)}**${def?.anyLayer ? ", and any layer" : ""}`;
}

/** The table, header to last row, from the registry: bootstrap, harness, core, then each declaring harness. */
export function renderKindTable(root: string = KIND_TABLE_ROOT): string {
  const names = defaultGraphKinds.names();
  const group = (k: string): string => {
    const file = defaultGraphKinds.declaredBy(k);
    if (file !== undefined) return `4 ${relative(dirname(root), file)}`;
    return { bootstrap: "1", harness: "2", core: "3" }[graphKindLayer(k, defaultGraphKinds.get(k))];
  };
  const ordered = names
    .map((k, i) => ({ k, i, g: group(k) }))
    .sort((a, b) => (a.g === b.g ? a.i - b.i : a.g < b.g ? -1 : 1))
    .map((x) => x.k);
  const rows = ordered.map((k) => {
    const d = defaultGraphKinds.get(k)!;
    // Escape a bare pipe; one already escaped in the prose stays as it is.
    const contents = (d.description ?? d.summary).replace(/(?<!\\)\|/g, "\\|");
    const rendered = `${d.renderable ? "**yes**" : "no"}${d.renderableNote ? ` — ${d.renderableNote}` : ""}`;
    return `| \`${k}\` | ${declaredByCell(k, root)} | ${contents} | ${rendered} |`;
  });
  return [KIND_TABLE_HEADER, "|---|---|---|---|", ...rows].join("\n");
}

/** Write the table between its markers, or (`check`) say whether it is current. Throws when the markers are not there exactly once. */
export function writeKindTable(check: boolean, root: string = KIND_TABLE_ROOT): boolean {
  const path = join(root, KIND_TABLE_DOC);
  const text = readFileSync(path, "utf8");
  const b = text.indexOf(KIND_TABLE_BEGIN);
  const e = text.indexOf(KIND_TABLE_END);
  if (b < 0 || e < b || text.indexOf(KIND_TABLE_BEGIN, b + 1) >= 0) {
    throw new Error(`${KIND_TABLE_DOC}: expected one generated kind-table region between its markers`);
  }
  // A BLANK LINE each side of the table. Without one, kramdown reads the table
  // as part of the marker comment's HTML block and publishes its rows as
  // pipes — `check:escaped-markup` caught it on the built skill page.
  const next = `${text.slice(0, b + KIND_TABLE_BEGIN.length)}\n\n${renderKindTable(root)}\n\n${text.slice(e)}`;
  if (next === text) return true;
  if (!check) writeFileSync(path, next);
  return false;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const current = writeKindTable(check);
  if (check && !current) {
    console.error(`✗ ${KIND_TABLE_DOC}: the kind table is stale. Run \`bun run kind:table\`; edit the KIND, not the table.`);
    process.exit(1);
  }
  console.log(current ? `✓ ${KIND_TABLE_DOC}: the kind table is current` : `wrote the kind table in ${KIND_TABLE_DOC}`);
}
