#!/usr/bin/env bun
/**
 * Mount every instance's rendered content under the built site.
 *
 * @module scripts/mount-instance-docs
 *
 * ## The rule this implements, in the owner's words
 *
 * 2026-09-20, first statement: *"rendered assets should be available at
 * toplevel like `<baseULR>/` for main jsut the docs pipleline, or
 * `<baseurl>/<page>` where is registered rendered page from a harness that was
 * instantiated and enbaled (by default enabled)."*
 *
 * And then the CORRECTION, the same session, which is the one this file
 * implements: *"your right… it should be `<base-url>library/who-iris`. note
 * rule on harnesses that instantiate a director like fsh-guts, docs/ library/
 * need to create a visualize for them."*
 *
 * So a mount point is keyed on the **graph kind**: a harness that instantiates
 * a directory gets a visualiser for it, and that visualiser lives at
 *
 *     <base-url>/<kind>/<instance>/
 *
 * Keying on the instance alone — which an earlier version of this file did —
 * collapses every kind an instance declares onto one path, so a folio with
 * both a library and its own docs could publish only one of them.
 *
 * ## TWO handlers register, not one, and they render different things
 *
 * Owner, 2026-09-20, looking at the deployed preview: *"`/docs/who-iris/`
 * should be the cat-harness handler default for docs. who-iris themed at
 * `/who-iris/`."*
 *
 * So each instance's content is reachable two ways, and the difference is
 * **which handler produced it**:
 *
 * | route | handler | what it is |
 * |---|---|---|
 * | `/<kind>/<instance>/` | the KIND's handler, cat-harness's | the default rendering any instance declaring that kind gets |
 * | `/<instance>/` | the INSTANCE itself | its own themed root — "default harness behaviour, themed" |
 *
 * The instance root is not a second copy of a page for its own sake: it is the
 * instance acting as a handler for its own name, which is what makes
 * `<base-url>/who-iris` mean something rather than 404. They are distinct
 * routes, so the walk below never has to choose between them — and if an
 * instance ever claims a path a kind handler already owns, it is refused and
 * named rather than silently overwriting.
 *
 * The root of the site stays the main docs pipeline, unchanged.
 *
 * ## Collisions, and the rule that settles them
 *
 * An instance may register sub-pages of its own, so two instantiated handlers
 * CAN want the same path. Owner, 2026-09-20: *"name collsion can occur
 * potentially. need resolution rule: walk path to see which instantiated
 * handler wants to process the path then stop."*
 *
 * So resolution is a **walk from the root, outermost wins, and the walk
 * stops**. A handler mounted at `/docs/` owns everything beneath it; a second
 * handler claiming `/docs/who-iris/` is not consulted, because the walk
 * already stopped. That is the opposite of longest-prefix routing, and it is
 * the right way round here: a mount point is a claim on a SUBTREE, and letting
 * a deeper handler punch through one would mean the outer instance's own
 * index could not be trusted to describe what is under it.
 *
 * **A losing claim is REFUSED and reported, never silently dropped and never
 * overwritten.** `cpSync` would happily write one instance's page over
 * another's and exit 0, and the result is a site that serves content nobody
 * can trace to a declaration. The exit code is non-zero so CI stops.
 *
 * ## Why this exists as a step rather than as more Jekyll
 *
 * Both `docs-site.yml` and `feature-staging.yml` run Jekyll with
 * `source: ./cat-harness/docs`. That is ONE directory, hardcoded — so an
 * instance that declares a `docs` graph of its own is built by nothing and
 * reachable at no URL. `who-iris/docs/` was in exactly that state the day it
 * was written: five committed, gated pages that no deployed site served.
 *
 * ## Declaration-driven, not a list
 *
 * The instances are read from their own `harness.json` declarations — any
 * directory whose graphs include the renderable `docs` kind. A hardcoded list
 * is the `check:declared-assets` defect, whose own doc comment describes
 * itself being "fixed" last time by writing down a list of two while the
 * repository had grown to eight.
 *
 * The instance whose docs Jekyll already built is SKIPPED, because it is the
 * root of the site and copying it under its own name would publish the whole
 * tree twice at two URLs — two IRIs for one page, which is the same
 * under-counting hazard `jsonld.ts` routes around one layer down.
 *
 * ## What it deliberately does not do
 *
 * It does not run Jekyll over the mounted directories. These are finished HTML
 * — `who-iris/docs/` is generated by `gen-iris-pages.ts` and gated by
 * `iris:pages:check`. Handing them to Jekyll would ask for front matter they
 * do not have and a layout they do not want.
 *
 * Usage:
 *   bun run cat-harness/scripts/mount-instance-docs.ts --site ./_site
 *   bun run cat-harness/scripts/mount-instance-docs.ts --site ./_site --built cat-harness
 */
import { cpSync, existsSync, readFileSync, readdirSync, statSync } from "fs";
import { join, resolve } from "path";
import { declarationPathIn } from "../schemas/cat-harness.js";

const REPO = resolve(import.meta.dir, "..", "..");

function arg(name: string, fallback?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

function countFiles(dir: string): number {
  let n = 0;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".")) continue;
    const p = join(dir, e.name);
    n += e.isDirectory() ? countFiles(p) : 1;
  }
  return n;
}

/**
 * Every (instance, kind, directory) an instance declares that has rendered
 * content to mount.
 *
 * Read from each instance's own `harness.json`. A hardcoded list is the
 * `check:declared-assets` defect, whose own doc comment describes itself being
 * "fixed" last time by writing down a list of two while the repository had
 * grown to eight.
 *
 * A directory is mounted when it carries an **`index.html` at its own root**.
 * **That floor is load-bearing, and a looser one was measured wrong.** The
 * first version accepted any `.html` anywhere beneath, and immediately mounted
 * `who-iris/uploads/` at `/uploads/who-iris/` — because the IRIS capture
 * contains a saved copy of the DSpace item page. `uploads/` is a raw intake
 * queue, and publishing it under a URL that promises a visualiser is worse
 * than publishing nothing.
 *
 * Requiring an index at the root says something stronger and exactly right:
 * somebody has built the visualiser the owner's rule calls for, and it has a
 * front door. Until then the kind is absent from the site, which is honest,
 * rather than present and serving a directory listing of source files.
 */
/** One mountable directory, as `mountable()` reports it. */
export interface Mountable {
  name: string;
  kind: string;
  dir: string;
  instanceRoot: boolean;
}

/**
 * Both routes per mountable, and which instance roots nobody chose.
 *
 * An instance's content publishes at `/<kind>/<instance>/` for every
 * renderable kind it declares, and ONCE at `/<instance>/` — its themed root,
 * per the owner's 2026-09-20 ruling that *"`/docs/who-iris/` should be the
 * cat-harness handler default for docs. who-iris themed at `/who-iris/`."*
 *
 * **Which kind answers at the root is now DECLARED.** This used to take the
 * first by sort order while the comment doing it claimed the choice was "the
 * instance's own business" — it was the alphabet's. who-iris made that
 * concrete the day it declared both `docs` and `library`: `docs` sorts first,
 * so the themed root would have served the documentation, contradicting the
 * very ruling it implemented. `instanceRoot: true` on the directory decides it.
 *
 * With several renderable kinds and none marked, the root is returned as
 * UNDETERMINED. The deterministic order still picks one, because a site has to
 * serve something at that URL — but the caller reports that nobody chose it,
 * rather than letting a silent pick read as a decision. That is the same
 * third-state rule the rest of this repository keeps: could-not-determine is
 * never rendered as a choice.
 */
export function withRoutes<T extends Mountable>(
  found: readonly T[],
): { candidates: (T & { route: string })[]; undetermined: { name: string; kinds: string[]; serving: string }[] } {
  const byInstance = new Map<string, T[]>();
  for (const m of found) byInstance.set(m.name, [...(byInstance.get(m.name) ?? []), m]);

  const undetermined: { name: string; kinds: string[]; serving: string }[] = [];
  for (const [name, ms] of byInstance) {
    if (ms.length > 1 && !ms.some((m) => m.instanceRoot)) {
      undetermined.push({ name, kinds: ms.map((m) => m.kind), serving: ms[0]!.kind });
    }
  }

  const declaredRoot = new Set(found.filter((m) => m.instanceRoot).map((m) => m.name));
  const rooted = new Set<string>();
  const candidates = found.flatMap((m) => {
    const byKind = { ...m, route: `${m.kind}/${m.name}` };
    if (rooted.has(m.name)) return [byKind];
    // A declared root waits for its own entry rather than letting whichever
    // kind comes first claim the route.
    if (declaredRoot.has(m.name) && !m.instanceRoot) return [byKind];
    rooted.add(m.name);
    return [byKind, { ...m, route: m.name }];
  });
  return { candidates, undetermined };
}

function mountable(): Mountable[] {
  const out: Mountable[] = [];
  for (const e of readdirSync(REPO, { withFileTypes: true })) {
    if (!e.isDirectory() || e.name.startsWith(".") || e.name === "node_modules") continue;
    const decl = declarationPathIn(join(REPO, e.name));
    if (decl === undefined) continue;
    if (!existsSync(decl)) continue;
    let d: { name?: string; directories?: { path?: string; graphs?: string[]; instanceRoot?: boolean }[] };
    try {
      d = JSON.parse(readFileSync(decl, "utf-8"));
    } catch {
      // A declaration that does not parse is a FINDING, not a skip — but it is
      // not this script's finding. `kg:schema:check` owns it; here it is noise.
      continue;
    }
    for (const entry of d.directories ?? []) {
      if (!entry.path) continue;
      const abs = join(REPO, e.name, entry.path);
      if (!existsSync(abs) || !statSync(abs).isDirectory()) continue;
      if (!existsSync(join(abs, "index.html"))) continue;
      for (const kind of entry.graphs ?? []) {
        out.push({ name: d.name ?? e.name, kind, dir: abs, instanceRoot: entry.instanceRoot === true });
      }
    }
  }
  return out.sort((a, b) => (a.kind + a.name).localeCompare(b.kind + b.name));
}



/**
 * Apply the owner's resolution rule to a set of claims.
 *
 * Exported for `mount-instance-docs.test.ts`, which is how the rule is
 * asserted without a filesystem: a routing rule tested only through `cpSync`
 * is a rule whose failing case nobody writes down.
 */
export function resolve_<T extends { route: string }>(
  candidates: T[],
): { mounts: T[]; refused: (T & { ownedBy: string })[] } {
  // Shortest route first — that IS the walk order. Ties broken by name so the
  // outcome does not depend on directory-read order, which varies by
  // filesystem and would make a collision report irreproducible.
  const ordered = [...candidates].sort((a, b) => {
    const d = a.route.split("/").length - b.route.split("/").length;
    return d !== 0 ? d : a.route.localeCompare(b.route);
  });

  const owned: string[] = [];
  const mounts: T[] = [];
  const refused: (T & { ownedBy: string })[] = [];

  for (const c of ordered) {
    // Walk from the root. `a/b` is owned by `a` — and by `a/b` itself, which
    // is the exact-duplicate case and is a collision too.
    const owner = owned.find((o) => c.route === o || c.route.startsWith(`${o}/`));
    if (owner !== undefined) {
      refused.push({ ...c, ownedBy: owner });
      continue;
    }
    owned.push(c.route);
    mounts.push(c);
  }
  return { mounts, refused };
}

function main(): number {
  const site = arg("site");
  if (!site) {
    console.error("usage: mount-instance-docs.ts --site <dir> [--built <instance-name>]");
    return 2;
  }
  const siteAbs = resolve(REPO, site);
  if (!existsSync(siteAbs)) {
    console.error(`--site ${site} does not exist. Run the site build first.`);
    return 1;
  }
  // Which instance Jekyll already rendered AT THE ROOT. Named rather than
  // guessed: the workflows pass `source: ./cat-harness/docs`, and a script
  // that inferred "the first one" would silently double-publish the day the
  // root instance changes.
  const built = arg("built", "cat-harness");

  const found = mountable().filter((m) => {
    if (m.name === built && m.kind === "docs") {
      console.log(`  skip ${m.kind}/${m.name} — already built at the site root`);
      return false;
    }
    return true;
  });

  const { candidates, undetermined } = withRoutes(found);
  for (const u of undetermined) {
    console.error(
      `  ? /${u.name}/ is UNDETERMINED — ${u.kinds.length} renderable kinds (${u.kinds.join(", ")}) ` +
        `and none declares \`instanceRoot\`. Serving ${u.serving} because the order is deterministic, ` +
        `not because anything chose it.`,
    );
  }

  const { mounts, refused } = resolve_(candidates);

  for (const m of mounts) {
    cpSync(m.dir, join(siteAbs, m.route), { recursive: true });
  }

  if (mounts.length === 0 && refused.length === 0) {
    console.log("mount-instance-docs: nothing declared has rendered content to mount.");
    return 0;
  }
  console.log(`mount-instance-docs: ${mounts.length} mount(s)`);
  for (const m of mounts) {
    console.log(`  ${m.dir.slice(REPO.length + 1)}  ->  /${m.route}/  (${countFiles(m.dir)} file(s))`);
  }

  if (refused.length) {
    console.error(`\n${refused.length} claim(s) REFUSED — a path already owned by another handler:`);
    for (const r of refused) {
      console.error(`  /${r.route}/  (${r.dir.slice(REPO.length + 1)})`);
      console.error(`      the walk stops at /${r.ownedBy}/, which owns this subtree`);
    }
    console.error(
      "\nResolution rule: walk the path from the root; the first instantiated handler that\n" +
        "wants it processes it, and the walk stops. Give one of the two a distinct mount point.",
    );
    return 1;
  }
  return 0;
}

if (import.meta.main) process.exit(main());
