#!/usr/bin/env bun
/**
 * Mount every instance's rendered content under the built site.
 *
 * @module scripts/mount-instance-docs
 *
 * ## The rule this implements, in the owner's words
 *
 * 2026-09-20, first statement: *"rendered assets should be available at
 * toplevel like `<baseULR>/` for main jsut the docs pipleline, or
 * `<baseurl>/<page>` where is registered rendered page from a harness that was
 * instantiated and enbaled (by default enabled)."*
 *
 * And then the CORRECTION, the same session, which is the one this file
 * implements: *"your right… it should be `<base-url>library/who-iris`. note
 * rule on harnesses that instantiate a director like fsh-guts, docs/ library/
 * need to create a visualize for them."*
 *
 * So a mount point is keyed on the **graph kind**: a harness that instantiates
 * a directory gets a visualiser for it, and that visualiser lives at
 *
 *     <base-url>/<kind>/<instance>/
 *
 * Keying on the instance alone — which an earlier version of this file did —
 * collapses every kind an instance declares onto one path, so a folio with
 * both a library and its own docs could publish only one of them.
 *
 * ## TWO handlers register, not one, and they render different things
 *
 * Owner, 2026-09-20, looking at the deployed preview: *"`/docs/who-iris/`
 * should be the cat-harness handler default for docs. who-iris themed at
 * `/who-iris/`."*
 *
 * So each instance's content is reachable two ways, and the difference is
 * **which handler produced it**:
 *
 * | route | handler | what it is |
 * |---|---|---|
 * | `/<kind>/<instance>/` | the KIND's handler, cat-harness's | the default rendering any instance declaring that kind gets |
 * | `/<instance>/` | the INSTANCE itself | its own themed root — "default harness behaviour, themed" |
 *
 * The instance root is not a second copy of a page for its own sake: it is the
 * instance acting as a handler for its own name, which is what makes
 * `<base-url>/who-iris` mean something rather than 404. They are distinct
 * routes, so the walk below never has to choose between them — and if an
 * instance ever claims a path a kind handler already owns, it is refused and
 * named rather than silently overwriting.
 *
 * The root of the site stays the main docs pipeline, unchanged.
 *
 * ## Collisions, and the rule that settles them
 *
 * An instance may register sub-pages of its own, so two instantiated handlers
 * CAN want the same path. Owner, 2026-09-20: *"name collsion can occur
 * potentially. need resolution rule: walk path to see which instantiated
 * handler wants to process the path then stop."*
 *
 * So resolution is a **walk from the root, outermost wins, and the walk
 * stops**. A handler mounted at `/docs/` owns everything beneath it; a second
 * handler claiming `/docs/who-iris/` is not consulted, because the walk
 * already stopped. That is the opposite of longest-prefix routing, and it is
 * the right way round here: a mount point is a claim on a SUBTREE, and letting
 * a deeper handler punch through one would mean the outer instance's own
 * index could not be trusted to describe what is under it.
 *
 * **A losing claim is REFUSED and reported, never silently dropped and never
 * overwritten.** `cpSync` would happily write one instance's page over
 * another's and exit 0, and the result is a site that serves content nobody
 * can trace to a declaration. The exit code is non-zero so CI stops.
 *
 * ## Why this exists as a step rather than as more Jekyll
 *
 * Both `docs-site.yml` and `feature-staging.yml` run Jekyll with
 * `source: ./cat-harness/docs`. That is ONE directory, hardcoded — so an
 * instance that declares a `docs` graph of its own is built by nothing and
 * reachable at no URL. `who-iris/docs/` was in exactly that state the day it
 * was written: five committed, gated pages that no deployed site served.
 *
 * ## Declaration-driven, not a list
 *
 * The instances are read from their own `harness.json` declarations — any
 * directory whose graphs include the renderable `docs` kind. A hardcoded list
 * is the `check:declared-assets` defect, whose own doc comment describes
 * itself being "fixed" last time by writing down a list of two while the
 * repository had grown to eight.
 *
 * The instance whose docs Jekyll already built is SKIPPED, because it is the
 * root of the site and copying it under its own name would publish the whole
 * tree twice at two URLs — two IRIs for one page, which is the same
 * under-counting hazard `jsonld.ts` routes around one layer down.
 *
 * ## What it deliberately does not do
 *
 * It does not run Jekyll over the mounted directories. These are finished HTML
 * — `who-iris/docs/` is generated by `gen-iris-pages.ts` and gated by
 * `iris:pages:check`. Handing them to Jekyll would ask for front matter they
 * do not have and a layout they do not want.
 *
 * Usage:
 *   bun run cat-harness/scripts/mount-instance-docs.ts --site ./_site
 *   bun run cat-harness/scripts/mount-instance-docs.ts --site ./_site --built cat-harness
 */
import { cpSync, existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, relative, resolve, sep } from "path";

import { WithheldSchema } from "../schemas/withheld.js";
import { declarationPathIn, visualisationsOf } from "../schemas/cat-harness.js";
import { injectRail, type NavItem } from "./lib/harness-rail.js";

const REPO = resolve(import.meta.dir, "..", "..");

function arg(name: string, fallback?: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

function countFiles(dir: string): number {
  let n = 0;
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith(".")) continue;
    const p = join(dir, e.name);
    n += e.isDirectory() ? countFiles(p) : 1;
  }
  return n;
}

/**
 * Every (instance, kind, directory) an instance declares that has rendered
 * content to mount.
 *
 * Read from each instance's own `harness.json`. A hardcoded list is the
 * `check:declared-assets` defect, whose own doc comment describes itself being
 * "fixed" last time by writing down a list of two while the repository had
 * grown to eight.
 *
 * A directory is mounted when it carries an **`index.html` at its own root**.
 * **That floor is load-bearing, and a looser one was measured wrong.** The
 * first version accepted any `.html` anywhere beneath, and immediately mounted
 * `who-iris/uploads/` at `/uploads/who-iris/` — because the IRIS capture
 * contains a saved copy of the DSpace item page. `uploads/` is a raw intake
 * queue, and publishing it under a URL that promises a visualiser is worse
 * than publishing nothing.
 *
 * Requiring an index at the root says something stronger and exactly right:
 * somebody has built the visualiser the owner's rule calls for, and it has a
 * front door. Until then the kind is absent from the site, which is honest,
 * rather than present and serving a directory listing of source files.
 */
/** One mountable directory, as `mountable()` reports it. */
export interface Mountable {
  name: string;
  kind: string;
  dir: string;
  instanceRoot: boolean;
  /**
   * The directory's declared visualiser, repo-relative, when it has one.
   *
   * `coverage.visualiser` on the declaring entry, normalised through
   * `visualisationsOf` so a bare string and a list of visualisations reach
   * here the same shape. Absent when the directory declares none, which is a
   * real answer and the common one.
   */
  visualiser?: string;
}

/**
 * Both routes per mountable, and which instance roots nobody chose.
 *
 * An instance's content publishes at `/<kind>/<instance>/` for every
 * renderable kind it declares, and ONCE at `/<instance>/` — its themed root,
 * per the owner's 2026-09-20 ruling that *"`/docs/who-iris/` should be the
 * cat-harness handler default for docs. who-iris themed at `/who-iris/`."*
 *
 * **Which kind answers at the root is now DECLARED.** This used to take the
 * first by sort order while the comment doing it claimed the choice was "the
 * instance's own business" — it was the alphabet's. who-iris made that
 * concrete the day it declared both `docs` and `library`: `docs` sorts first,
 * so the themed root would have served the documentation, contradicting the
 * very ruling it implemented. `instanceRoot: true` on the directory decides it.
 *
 * With several renderable kinds and none marked, the root is returned as
 * UNDETERMINED. The deterministic order still picks one, because a site has to
 * serve something at that URL — but the caller reports that nobody chose it,
 * rather than letting a silent pick read as a decision. That is the same
 * third-state rule the rest of this repository keeps: could-not-determine is
 * never rendered as a choice.
 */
export function withRoutes<T extends Mountable>(
  found: readonly T[],
): { candidates: (T & { route: string })[]; undetermined: { name: string; kinds: string[]; serving: string }[] } {
  const byInstance = new Map<string, T[]>();
  for (const m of found) byInstance.set(m.name, [...(byInstance.get(m.name) ?? []), m]);

  const undetermined: { name: string; kinds: string[]; serving: string }[] = [];
  for (const [name, ms] of byInstance) {
    if (ms.length > 1 && !ms.some((m) => m.instanceRoot)) {
      undetermined.push({ name, kinds: ms.map((m) => m.kind), serving: ms[0]!.kind });
    }
  }

  const declaredRoot = new Set(found.filter((m) => m.instanceRoot).map((m) => m.name));
  const rooted = new Set<string>();
  const candidates = found.flatMap((m) => {
    const byKind = { ...m, route: `${m.kind}/${m.name}` };
    if (rooted.has(m.name)) return [byKind];
    // A declared root waits for its own entry rather than letting whichever
    // kind comes first claim the route.
    if (declaredRoot.has(m.name) && !m.instanceRoot) return [byKind];
    rooted.add(m.name);
    return [byKind, { ...m, route: m.name }];
  });
  return { candidates, undetermined };
}

/**
 * How many `..` a mounted page needs to reach the site root.
 *
 * The mount's route depth PLUS the file's own depth beneath it, and getting
 * that wrong is the defect this function exists to name. The first version
 * used the route depth alone and argued for it — `/library/who-iris/` is two
 * segments deep whatever directory it was copied from, which is true of the
 * mount's INDEX and false of every page below. `smart-trust/` mounts one deep
 * and holds `artifact/*.html` one deeper, so 57 of 188 rail links pointed at a
 * directory that does not exist.
 *
 * EXPORTED so the test binds to this expression rather than restating it. The
 * first test did restate it, and when the bug was planted back into the caller
 * that test went on passing — it was documenting the arithmetic while guarding
 * nothing. Only the integration check over the built tree caught it.
 *
 * @param route      the mount's route, e.g. `library/who-iris`
 * @param fileUnder  the file's path beneath the mount, e.g. `artifact/x.html`
 */
export function toRootFor(route: string, fileUnder: string): string {
  const under = fileUnder.includes("/") ? fileUnder.split("/").length - 1 : 0;
  return new Array(route.split("/").length + under).fill("..").join("/");
}

/**
 * Where the Jekyll-built pages come from, repo-relative — e.g. `cat-harness/docs`.
 *
 * Read off the built instance's own declaration (its non-repository-scoped
 * `docs` directory) rather than written down here. The workflows pass that
 * same directory as Jekyll's `source:`, so a page committed at
 * `<prefix>/x/y/index.html` is published at `/x/y/`; hardcoding the prefix
 * would be a second copy of a fact the declaration already carries, free to
 * disagree with it the day the directory moves.
 *
 * `undefined` when the built instance declares no docs directory. That is the
 * third state and it is not the same as "the visualiser does not resolve" —
 * the caller reports it and falls back, rather than treating an unanswerable
 * question as a no.
 */
export function publishedDocsPrefix(repo: string, built: string): string | undefined {
  const decl = declarationPathIn(join(repo, built));
  if (decl === undefined || !existsSync(decl)) return undefined;
  let d: { directories?: { path?: string; graphKinds?: string[]; scope?: string }[] };
  try {
    d = JSON.parse(readFileSync(decl, "utf-8"));
  } catch {
    return undefined;
  }
  const entry = (d.directories ?? []).find(
    (x) => x.path && x.scope !== "repository" && (x.graphKinds ?? []).includes("docs"),
  );
  return entry === undefined ? undefined : join(built, entry.path!);
}

/**
 * A declared visualiser's URL on the built site, relative to the site root.
 *
 * **This is what the rail's per-kind link should point at, and pointing it at
 * the mount route instead is the defect this function exists for.** The owner,
 * looking at the deployed rail: *"clicking on doc/ or library/ under who-iris
 * navbar did nothing … under library/ the 3 assets listed. are those
 * interfaces not done?"* They were done. `/library/who-iris/` mounts
 * `who-iris/library/` verbatim, and that directory's `index.html` is the IRIS
 * replica home — the very page `/who-iris/` already serves. So the link
 * navigated correctly to a byte-identical document, which is indistinguishable
 * from a link that did nothing.
 *
 * The library visualiser that DOES list the three materialized items is
 * declared on that directory as `coverage.visualiser` and published by Jekyll
 * at `/cat-harness/library/who-iris/`. It is not copied to the mount route:
 * its own `fetch` of the L1 projection is written relative to where it sits,
 * so a copy two segments shallower would reach past the site root and report a
 * corpus it could not load.
 *
 * `undefined` when the declared path does not sit under the published tree —
 * a visualiser that exists but is not published is a finding, and the caller
 * names it rather than quietly linking somewhere else.
 *
 * @param visualiser  repo-relative path from `coverage.visualiser`
 * @param docsPrefix  what `publishedDocsPrefix` returned
 */
export function visualiserHref(visualiser: string, docsPrefix: string): string | undefined {
  const path = visualiser.replace(/\\/g, "/");
  const prefix = `${docsPrefix.replace(/\/+$/, "")}/`;
  if (!path.startsWith(prefix)) return undefined;
  const rest = path.slice(prefix.length);
  if (rest === "") return undefined;
  // An index is the directory's front door, so it addresses as the directory.
  // Any other file addresses as itself — appending a slash to `a/b.html` would
  // invent a directory that is not there.
  if (rest === "index.html") return "";
  if (rest.endsWith("/index.html")) return `${rest.slice(0, -"index.html".length)}`;
  return rest;
}

/**
 * EVERY graph this instance declares — the navbar's scrollable middle.
 *
 * Owner, 2026-09-21: *"there shuold be all the harness controlled dirs/graphs"*.
 *
 * The navbar used to list only the MOUNTED kinds — the ones whose directory
 * carries an `index.html`. For who-iris that is two of six: `library` and
 * `docs` are published, while `catalogue`, `uploads`, `skills` and `themes`
 * are declared and have no viewer. Listing two answered *"what is in this
 * KG"* with a shorter and wronger list than the declaration gives.
 *
 * So all six appear, and the four without a viewer appear WITHOUT AN HREF.
 * `harness-tiles` already words the distinction exactly right — *"declared and
 * not rendered is a GAP, not a dead link"* — and `pb04` is why the gap must
 * not be drawn as a link: a dead link invites a click and then reads as "this
 * site is broken", which is a worse answer than "nothing renders this yet".
 *
 * Deduped on the KIND rather than the directory. Two entries may declare the
 * same kind (an override and its default), and a navbar that listed `library`
 * twice would be reporting the declaration's shape rather than the graph's.
 *
 * A KIND WITH NO HREF SAYS WHY, when the site can tell it — see
 * {@link publishedGraphs}. Greying the row was the whole of the signal until
 * 2026-09-23, which made "declared and not built" a fact carried by contrast
 * and by nothing else, on the one surface where the sidebar template at least
 * had a `title`. Absent from `site` is the honest third state and renders as
 * it always did: a grey row with no claim about why.
 *
 * ## TWO WITNESSES, AND THE MOUNT TABLE IS ASKED FIRST (`pk2s`)
 *
 * `linked` still wins wherever it has an answer, and that order is the
 * owner's rather than a tie-break: a mount is the instance PRESENTING ITSELF
 * (`/who-iris/`), and the handler's viewer is cat-harness's default rendering
 * of the same graph (`/cat-harness/library/who-iris/`). *"cliking shoud go to
 * folio view, not the schema viweer."*
 *
 * `site` is consulted only where the mount table is SILENT — and it is silent
 * about every handler-published viewer by construction, because `mountable()`
 * requires an `index.html` that a data directory does not have. That silence
 * used to render as a grey row over a page that exists; two of who-iris's
 * six kinds were in exactly that state. {@link publishedGraphs} carries the
 * measurement.
 *
 * @param linked  href per kind from the MOUNT TABLE, already relative to the
 *   page being rendered. The instance's own route, and preferred.
 * @param site  what the published site knows for the kinds the mount table
 *   says nothing about — a handler's href, or the reason there is none.
 */
export function declaredGraphs(
  instanceDirName: string,
  linked: ReadonlyMap<string, string>,
  site: ReadonlyMap<string, GraphFallback> = new Map(),
): NavItem[] {
  const decl = declarationPathIn(join(REPO, instanceDirName));
  if (decl === undefined || !existsSync(decl)) return [];
  let d: { directories?: { graphKinds?: string[] }[] };
  try {
    d = JSON.parse(readFileSync(decl, "utf-8"));
  } catch {
    // Not this script's finding — `kg:schema:check` owns an unparseable
    // declaration. Here it is an empty middle, and the caller still renders
    // the instance root and the harnesses.
    return [];
  }
  const seen = new Set<string>();
  const out: NavItem[] = [];
  for (const entry of d.directories ?? []) {
    for (const kind of entry.graphKinds ?? []) {
      if (seen.has(kind)) continue;
      seen.add(kind);
      const fallback = site.get(kind);
      const href = linked.get(kind) ?? fallback?.href;
      // A row that opens owes no explanation, and `publishedGraphs` never
      // returns both — but the guard stays, because `href` may come from the
      // mount table while the note came from the site, and those two are not
      // the pair that function makes exclusive.
      const note = href ? undefined : fallback?.note;
      out.push({
        label: kind,
        icon: kind.slice(0, 1).toUpperCase(),
        ...(href ? { href } : {}),
        ...(note ? { note } : {}),
      });
    }
  }
  return out.sort((a, b) => a.label.localeCompare(b.label));
}

/**
 * The INSTANTIATED harnesses, for the navbar's fixed bottom.
 *
 * Owner, 2026-09-21: *"keep the navba rmenu/tab of the active/instantiated
 * harnsesss from folio-asst at bottom of navbar in en aexpanable menu. use
 * avatar/themes of the hanreses"*.
 *
 * Read from `<built>/docs/_data/harness.json`, which `sync-docs-harness.ts`
 * generates from the declarations and `docs:harness:check` gates. A hardcoded
 * list here would be the `check:declared-assets` defect, and it would go stale
 * the first time an instance is instantiated — which happened twice this week.
 *
 * `undefined`, not `[]`, when the file is missing or will not parse. The
 * caller then OMITS the region rather than rendering an empty disclosure
 * labelled "Harnesses", which would read as a site with no harnesses instead
 * of as a navbar that could not find out. Third state, said by absence.
 *
 * **Avatars come from the data, and today almost none are there** — `icon` is
 * declared for `cat-harness` alone. That is `603s`'s subject, in flight on PR
 * #791; when it lands the avatars arrive through this same field and nothing
 * here changes, which is the test of whether the boundary was drawn in the
 * right place. Until then an item falls back to its initial.
 *
 * @param toRoot the calling page's path back to the site root, since every
 *   href in `harness.json` is site-absolute and a mounted page is not at the
 *   root.
 */
/** Where a kind opens, or why it does not. Never both — see the loop below. */
export type GraphFallback = { href?: string; note?: string };

/**
 * WHAT THE PUBLISHED SITE KNOWS about each of an instance's declared kinds —
 * where it opens, or why it does not.
 *
 * Read from the same `harness.json` {@link instantiatedHarnesses} reads, and
 * for the same reason: `harness-tiles.ts` already separates staging-only,
 * render-exempt, built-but-unreachable and nobody-built-it in order to word
 * four different findings, and a table here would be a fifth answer free to
 * disagree with those four. This function looks the answer up; it decides
 * nothing.
 *
 * EMPTY, not `undefined`, when the file is missing or will not parse — and
 * that is a deliberate difference from `instantiatedHarnesses`, which uses
 * absence to make the caller omit a whole region. Here there is nothing to
 * omit: the graph rows come from the DECLARATION and are rendered either way.
 * A missing file costs the reasons, not the rows, and a row with no reason is
 * exactly what this surface shipped until today.
 *
 * Keyed by kind within one instance, because that is how `declaredGraphs`
 * asks. Two harnesses may both declare `library`, so the instance is part of
 * the question and never assumed.
 *
 * ## Why it carries the HREF too, as of `pk2s`
 *
 * It read only the reasons until 2026-09-23, and the rail then greyed two
 * rows this same file believed were published: who-iris's `catalogue` and
 * `uploads`. Settled against `gh-pages` rather than against either
 * generator — `cat-harness/catalogue/who-iris/index.html` is 23,534 bytes
 * there and `cat-harness/library/who-iris/index.html` is 20,204 — so the
 * rail was losing two WORKING links.
 *
 * **Neither producer was wrong.** They answer different questions, and the
 * caller was asking the one that cannot see a handler's viewer:
 *
 * | producer | answers | `catalogue` |
 * |---|---|---|
 * | the mount table | did we copy this instance's own RENDERED directory? | no |
 * | `harness-tiles` | is there a PUBLISHED VIEWER for this kind? | yes |
 *
 * `mountable()` requires an `index.html`, rightly — a directory with no
 * rendered page has nothing to mount — and who-iris's `catalogue/`,
 * `uploads/`, `skills/` and `themes/` have none, because they hold DATA. The
 * page that renders who-iris's catalogue is the cat-harness HANDLER's, laid
 * down by Jekyll at `/cat-harness/catalogue/who-iris/`. It is not a mount and
 * can never become one, so the mount table is invisible to it by
 * construction.
 *
 * That is the split `harness_details.html` already states in its own words:
 * *"`/who-iris/` is who-iris presenting itself, `/library/who-iris/` is the
 * cat-harness handler's default rendering of its library."* The rail's graph
 * rows are meant to reach the second, and until now reached it only where a
 * mount happened to coincide — which is the whole of why `library` linked and
 * `catalogue` did not.
 *
 * **This is still not the hardcoded list the caller's comment forbids.**
 * `harness.json` is generated and presence-checked; the rule it states — a
 * kind gains a link the moment it gains a viewer — is the rule being kept
 * here, against a witness that can actually see one.
 */
export function publishedGraphs(built: string, instanceName: string, toRoot: string): Map<string, GraphFallback> {
  const out = new Map<string, GraphFallback>();
  const prefix = publishedDocsPrefix(REPO, built);
  if (prefix === undefined) return out;
  const data = join(REPO, prefix, "_data", "harness.json");
  if (!existsSync(data)) return out;
  let d: { harnesses?: { name?: string; visualisations?: { kind?: string; path?: string; note?: string }[] }[] };
  try {
    d = JSON.parse(readFileSync(data, "utf-8"));
  } catch {
    return out;
  }
  const h = (d.harnesses ?? []).find((x) => x.name === instanceName);
  for (const v of h?.visualisations ?? []) {
    if (!v.kind) continue;
    // EXACTLY ONE OF THE TWO, because they are the two halves of one answer:
    // a kind either opens somewhere or owes a reason it does not. A row
    // carrying both would be a working link captioned "no viewer yet", which
    // is the stale-note case the previous guard was written for and which
    // this shape makes unrepresentable rather than merely checked.
    //
    // The path is SITE-ABSOLUTE in `harness.json` and a mounted page is not at
    // the root, so it is re-based exactly as `instantiatedHarnesses` re-bases
    // a harness href. Composing it any other way here would be a second answer
    // to "where does this page live".
    if (v.path) out.set(v.kind, { href: `${toRoot}${v.path}` });
    else if (v.note) out.set(v.kind, { note: v.note });
  }
  return out;
}

export function instantiatedHarnesses(built: string, toRoot: string): NavItem[] | undefined {
  // The site root is READ, never composed. `join(REPO, built, "docs", ...)`
  // was the first version and `check:declared-paths` refused it -- rightly,
  // and pointedly, because `publishedDocsPrefix` exists a few lines up in this
  // same file and was written this session for exactly this. A literal
  // `"docs"` is a second answer to "where does this instance publish", free to
  // disagree with the declaration the moment the directory moves.
  const prefix = publishedDocsPrefix(REPO, built);
  if (prefix === undefined) return undefined;
  const data = join(REPO, prefix, "_data", "harness.json");
  if (!existsSync(data)) return undefined;
  let d: { harnesses?: { name?: string; label?: string; title?: string; href?: string | null; instantiated?: boolean; tone?: number; icon?: { src?: string; title?: string; region?: { x: number; y: number; w: number; h: number } } | null }[] };
  try {
    d = JSON.parse(readFileSync(data, "utf-8"));
  } catch {
    return undefined;
  }
  if (!Array.isArray(d.harnesses)) return undefined;
  return d.harnesses
    .filter((h) => h.instantiated === true)
    .map((h) => {
      const label = h.label ?? h.title ?? h.name ?? "?";
      // A site-absolute href has to be re-based for a page that is not at the
      // root. `/who-iris/` from `/docs/who-iris/index.html` is `../../who-iris/`.
      const href = h.href ? `${toRoot}${h.href}` : undefined;
      const avatar = h.icon?.src
        ? {
            src: `${toRoot}${h.icon.src}`,
            ...(h.icon.title ? { title: h.icon.title } : {}),
            // `603s`'s declared crop, when the icon image carries one.
            // `harness-tiles.ts` puts it here; nothing in this file decides a
            // box, which is the point of declaring it.
            ...(h.icon.region ? { region: h.icon.region } : {}),
          }
        : undefined;
      return {
        label,
        ...(href ? { href } : {}),
        ...(avatar ? { avatar } : {}),
        ...(h.tone ? { tone: h.tone } : {}),
      };
    });
}

/**
 * Inject the harness rail into every mounted HTML page.
 *
 * The rail's LINKS ARE DERIVED FROM THE MOUNT TABLE, never listed: an instance
 * that declares a third renderable kind gets a third entry with no edit here,
 * and an instance whose route changes cannot end up with a rail pointing at
 * the old one. That is the same rule `mountable()` follows one function down,
 * and for the same reason its own comment gives — a hardcoded list is the
 * `check:declared-assets` defect.
 *
 * `toRoot` is the route's depth PLUS the file's own depth below the mount, and
 * getting that wrong is the defect this comment replaces. The first version
 * used the route depth alone and argued for it — `/library/who-iris/` is two
 * segments deep whatever directory it was copied from, which is true of the
 * mount's INDEX and false of every page beneath it. `smart-trust/` mounts one
 * segment deep and contains `artifact/*.html` one deeper again, so 57 of 188
 * rail links pointed at a directory that does not exist. Caught by resolving
 * every emitted href against the built tree, not by reading the code.
 */
function injectRails<T extends { name: string; kind: string; route: string; visualiser?: string }>(
  siteAbs: string,
  mounts: readonly T[],
  docsPrefix: string | undefined,
  built: string,
): { injected: number; skipped: string[]; unpublished: { route: string; visualiser: string }[] } {
  const byInstance = new Map<string, T[]>();
  for (const m of mounts) byInstance.set(m.name, [...(byInstance.get(m.name) ?? []), m]);

  const htmlUnder = (dir: string): string[] => {
    const out: string[] = [];
    const walk = (d: string): void => {
      for (const e of readdirSync(d, { withFileTypes: true })) {
        if (e.name.startsWith(".")) continue;
        const p = join(d, e.name);
        if (e.isDirectory()) walk(p);
        else if (e.name.endsWith(".html")) out.push(p);
      }
    };
    if (existsSync(dir)) walk(dir);
    return out;
  };

  let injected = 0;
  const skipped: string[] = [];

  /**
   * Where a kind's link goes: its DECLARED visualiser when that visualiser is
   * published, and the mount route otherwise.
   *
   * Computed once per mount rather than per file, because the answer does not
   * depend on the page — only `toRoot` does.
   */
  const unpublished: { route: string; visualiser: string }[] = [];
  const target = new Map<string, string>();
  for (const o of mounts) {
    if (o.route === o.name) continue; // the instance's own themed root is itself
    if (o.visualiser === undefined || docsPrefix === undefined) continue;
    const href = visualiserHref(o.visualiser, docsPrefix);
    if (href === undefined) {
      // Declared, and not under the published tree. Named rather than silently
      // falling back to the mount route, which is how `/library/who-iris/`
      // came to look like a dead link in the first place.
      unpublished.push({ route: o.route, visualiser: o.visualiser });
      continue;
    }
    target.set(o.route, href);
  }

  for (const m of mounts) {
    const mountAbs = join(siteAbs, m.route);

    for (const file of htmlUnder(mountAbs)) {
      const toRoot = toRootFor(m.route, file.slice(mountAbs.length + 1));
      // Every route this instance answers at, so the rail can move between
      // them -- the owner's "with who-iris and then link to docs on side in
      // navbar". Rebuilt per file because `toRoot` is per file.
      // The instance's own themed root, first — it is the instance rather
      // than one of its graphs, so it is not inside the graphs group.
      const own = (byInstance.get(m.name) ?? []).filter((o) => o.route === o.name);
      const root: NavItem[] = own.map((o) => ({
        href: `${toRoot}/${o.route}/`,
        label: o.name,
        icon: "◆",
        current: o.route === m.route,
      }));

      // Which KINDS are actually published, and where. Built from the mount
      // table, so a kind gains a link the moment it gains a viewer and loses
      // one the moment it does not — never from a list here.
      const linked = new Map<string, string>();
      for (const o of byInstance.get(m.name) ?? []) {
        if (o.route === o.name) continue;
        const visual = target.get(o.route);
        linked.set(o.kind, `${toRoot}/${visual ?? `${o.route}/`}`);
      }

      const links: NavItem[] = declaredGraphs(m.name, linked, publishedGraphs(built, m.name, toRoot));

      const harnesses = instantiatedHarnesses(built, toRoot);
      const before = readFileSync(file, "utf-8");
      const after = injectRail(before, {
        instance: m.name,
        toRoot,
        ...(root[0] ? { root: root[0] } : {}),
        links,
        ...(harnesses ? { harnesses } : {}),
      });
      if (after === undefined) {
        skipped.push(file.slice(siteAbs.length + 1));
        continue;
      }
      writeFileSync(file, after);
      injected++;
    }
  }
  return { injected, skipped, unpublished };
}

/**
 * Pages the SITE publishes that Jekyll never laid out — bean `oi1y`.
 *
 * ## The gap, and why it is not the mount gap
 *
 * {@link injectRails} walks MOUNT ROUTES. A page that is neither a mount nor a
 * generated viewer falls between both: Jekyll copies a committed `.html`
 * through verbatim, so it inherits no layout and therefore no sidebar, and
 * nothing else puts one on it.
 *
 * A wireframe directory is the clearest case, because it holds both halves:
 * `as-is.html` beside `intent.md`, same subject, same directory. The `.md` is
 * laid out and wears the theme's sidebar; the `.html` wears nothing — **no
 * navigation and no outward link at all**, not even back to the wireframe it
 * belongs to. Measured on the published site: 23 wireframe pages and 10 under
 * `bootstrap/`.
 *
 * ## Why a pass and not 33 edits
 *
 * That is `edx7`'s argument, one directory over: hand-editing the committed
 * files fixes today's 33 and leaves the 34th wireframe to forget. These are
 * hand-authored — `check-wireframes.ts` validates them and writes nothing — so
 * `edx7`'s `emit` fixture cannot reach them either. What is left is the
 * mechanism this file already implements for mounts: inject after the build.
 *
 * ## The objection that a drawing should not wear real chrome
 *
 * Six of the 23 DRAW a sidebar as part of the mockup, which puts a real rail
 * beside a drawn one — the shape of the IRIS-replica case, where folio
 * chrome on a replica is the opposite of what a replica is for.
 *
 * It does not apply, and the repository settled it before this pass existed:
 * `navbar/intent.md` also depicts and discusses the navbar, **and wears the
 * theme sidebar**, and nobody has called that wrong. A replica impersonates
 * somebody else's site; a wireframe is this site documenting itself, and the
 * drawing is content inside the page rather than a claim about what the page
 * is.
 *
 * ## Already-navigated pages are LEFT ALONE, and both navigations count
 *
 * A page carrying the theme's `<nav id="site-nav">` is not missing anything,
 * and neither is one already carrying `<nav class="fa-nav">`. Conflating those
 * two is what made the measurement behind this function wrong four times
 * running: `docs-ui.css` styles the theme's sidebar with `fa-nav-*` class
 * names, so a substring test for `fa-nav` reports a themed page as railed —
 * and reports a page that merely MENTIONS `.fa-nav-toggle` in prose as railed
 * too, which is what the navbar wireframe does.
 */
const NAVIGATED = /<nav class="fa-nav"|id="site-nav"/;

/**
 * Where this pass does NOT go — **empty, and that is the answer rather than an
 * oversight**.
 *
 * `api/` held the only entry. TypeDoc's 1816 pages already carry a toolbar, a
 * module list and a search dialog, so a second navigation there was a LAYOUT
 * question rather than a missing-navigation defect, and it was kept out of the
 * first pass so the question could be answered where a reviewer sees it.
 *
 * **It was answered by rendering, not by argument.** A real published TypeDoc
 * page was railed locally and both versions opened in a browser at 1280px:
 *
 * | | harness rail | TypeDoc toolbar | horizontal scroll |
 * |---|---|---|---|
 * | before | — | x=0, w=1280 | none |
 * | after | x=0, **w=56** | x=56, w=1224 | none |
 *
 * The rail renders as its 56px COLLAPSED STRIP and the toolbar reflows beside
 * it; `scrollWidth` equals `innerWidth` in both, so nothing is pushed off the
 * page. TypeDoc's module list keeps its own column to the right of the strip.
 * Two navigations, neither obscuring the other.
 *
 * The constant stays rather than being deleted, because the NEXT family that
 * needs excluding should find a documented place to say so and a test that
 * makes the exclusion visible — which is what an empty array with this comment
 * provides and a removed one does not.
 */
const NOT_THIS_PASS: readonly string[] = [];

export function railStandalonePages(
  siteAbs: string,
  built: string,
  instanceName: string,
  mountRoutes: readonly string[],
): { injected: number; alreadyNavigated: number; skipped: string[] } {
  const skipped: string[] = [];
  let injected = 0;
  let alreadyNavigated = 0;

  const owned = (rel: string): boolean =>
    mountRoutes.some((r) => rel === r || rel.startsWith(`${r}/`)) ||
    NOT_THIS_PASS.some((r) => rel === r || rel.startsWith(`${r}/`)) ||
    rel === "STAGING" ||
    rel.startsWith("STAGING/");

  const walk = (dir: string): void => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name.startsWith(".")) continue;
      const abs = join(dir, e.name);
      const rel = abs.slice(siteAbs.length + 1);
      if (e.isDirectory()) {
        if (!owned(rel)) walk(abs);
        continue;
      }
      if (!e.name.endsWith(".html") || owned(rel)) continue;

      const before = readFileSync(abs, "utf-8");
      if (NAVIGATED.test(before)) {
        alreadyNavigated++;
        continue;
      }
      // `..` per directory the page sits under; the filename is not one.
      const depth = rel.split("/").length - 1;
      const toRoot = depth === 0 ? "." : new Array(depth).fill("..").join("/");
      const links = declaredGraphs(instanceName, new Map(), publishedGraphs(built, instanceName, toRoot));
      const harnesses = instantiatedHarnesses(built, toRoot);
      const after = injectRail(before, {
        instance: instanceName,
        toRoot,
        links,
        ...(harnesses ? { harnesses } : {}),
      });
      if (after === undefined) {
        skipped.push(rel);
        continue;
      }
      writeFileSync(abs, after);
      injected++;
    }
  };
  if (existsSync(siteAbs)) walk(siteAbs);
  return { injected, alreadyNavigated, skipped };
}

/**
 * The routes the MOUNT pass owns, computed by the pipeline that owns them.
 *
 * `rail-standalone-pages.ts` must leave these alone, because {@link injectRails}
 * has already railed them with a PER-INSTANCE model; a second rail there would
 * carry the ROOT instance's graphs instead of the mounted instance's.
 *
 * It is derived rather than guessed, and the first version guessed. It took a
 * directory in the site to be a mount when a same-named `<name>/<name>.json`
 * existed in the repository — which is true of `bootstrap`, an instance that
 * declares no renderable docs and is therefore **never mounted**. The guess
 * excluded exactly the ten pages the pass was extended to reach.
 *
 * `mountable()` requires a rendered `index.html`, `withRoutes` assigns the
 * route and `resolve_` refuses a collision. Asking them is one answer; a
 * predicate over filenames is a second one, free to disagree.
 */
export function mountRoutes(built: string): string[] {
  const found = mountable().filter((m) => !(m.name === built && m.kind === "docs"));
  const { candidates } = withRoutes(found);
  return resolve_(candidates).mounts.map((m) => m.route);
}

function mountable(): Mountable[] {
  const out: Mountable[] = [];
  for (const e of readdirSync(REPO, { withFileTypes: true })) {
    if (!e.isDirectory() || e.name.startsWith(".") || e.name === "node_modules") continue;
    const decl = declarationPathIn(join(REPO, e.name));
    if (decl === undefined) continue;
    if (!existsSync(decl)) continue;
    let d: {
      name?: string;
      directories?: {
        id?: string;
        path?: string;
        graphKinds?: string[];
        instanceRoot?: boolean;
        composed?: boolean;
        coverage?: Parameters<typeof visualisationsOf>[0];
      }[];
    };
    try {
      d = JSON.parse(readFileSync(decl, "utf-8"));
    } catch {
      // A declaration that does not parse is a FINDING, not a skip — but it is
      // not this script's finding. `kg:schema:check` owns it; here it is noise.
      continue;
    }
    for (const entry of d.directories ?? []) {
      if (!entry.path) continue;
      // COMPOSED directories belong to Jekyll, not to this script.
      //
      // `compose-docs.ts` lays them into the Jekyll SOURCE at
      // `_docs/<instance>/`, so mounting the same directory into `_site`
      // afterwards would publish two documents at one URL -- the composed page
      // and the raw source -- with the later copy winning by timing.
      //
      // Skipped by DECLARATION rather than by shape. Today a composed
      // directory holds `index.md` and the `index.html` floor below would drop
      // it anyway; that is a coincidence of one file extension, and a
      // composed directory that happened to carry an `index.html` would be
      // double-published while looking fine.
      if (entry.composed === true) continue;
      const abs = join(REPO, e.name, entry.path);
      if (!existsSync(abs) || !statSync(abs).isDirectory()) continue;
      if (!existsSync(join(abs, "index.html"))) continue;
      // The directory's own declared visualiser, if it has one. Read here
      // rather than re-derived later: the declaration is the only place that
      // knows, and a second answer is free to disagree with it.
      const visualiser = visualisationsOf(entry.coverage, entry.id ?? entry.path)[0]?.ref;
      for (const kind of entry.graphKinds ?? []) {
        out.push({
          name: d.name ?? e.name,
          kind,
          dir: abs,
          instanceRoot: entry.instanceRoot === true,
          ...(visualiser === undefined ? {} : { visualiser }),
        });
      }
    }
  }
  return out.sort((a, b) => (a.kind + a.name).localeCompare(b.kind + b.name));
}



/**
 * Apply the owner's resolution rule to a set of claims.
 *
 * Exported for `mount-instance-docs.test.ts`, which is how the rule is
 * asserted without a filesystem: a routing rule tested only through `cpSync`
 * is a rule whose failing case nobody writes down.
 */
/**
 * The name of the file a mounted directory may carry to say what must NOT be
 * published from it.
 *
 * Bean `cw35`: the mount copies a directory wholesale, so a publication whose
 * licence refuses redistribution (its catalogue gates say so) was still served
 * BY URL — its cover and extracted text — after every link to it was removed.
 * The platform cannot know an instance's licence rules and must not learn
 * them; the instance's own generator writes this list from its own data, and
 * the mount honours it for every instance alike.
 */
export const WITHHELD_FILE = "withheld.json";

/**
 * The paths (relative to `dir`) that must not be copied to the site.
 *
 * Absent file → nothing withheld. A file that is present but unreadable or
 * malformed THROWS: "could not tell what to withhold" must never become
 * "publish everything", which is the one failure this list exists to stop.
 */
export function withheldPaths(dir: string): string[] {
  const f = join(dir, WITHHELD_FILE);
  if (!existsSync(f)) return [];
  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(f, "utf-8"));
  } catch (e) {
    throw new Error(`${f} is not valid JSON (${(e as Error).message}) — refusing to mount rather than publish what it withholds`);
  }
  const parsed = WithheldSchema.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `${f} is not a valid folio-withheld/v1 list (${parsed.error.issues[0]?.message ?? "invalid"}) — ` +
        `refusing to mount rather than publish what it withholds`,
    );
  }
  return parsed.data.paths.map((p) => p.path.replace(/^\.?\/+/, "").replace(/\/+$/, ""));
}

/** A `cpSync` filter that drops every withheld path, and everything beneath it. */
export function withheldFilter(dir: string, withheld: readonly string[]): (src: string) => boolean {
  return (src) => {
    const rel = relative(dir, src).split(sep).join("/");
    return !withheld.some((w) => rel === w || rel.startsWith(`${w}/`));
  };
}

export function resolve_<T extends { route: string }>(
  candidates: T[],
): { mounts: T[]; refused: (T & { ownedBy: string })[] } {
  // Shortest route first — that IS the walk order. Ties broken by name so the
  // outcome does not depend on directory-read order, which varies by
  // filesystem and would make a collision report irreproducible.
  const ordered = [...candidates].sort((a, b) => {
    const d = a.route.split("/").length - b.route.split("/").length;
    return d !== 0 ? d : a.route.localeCompare(b.route);
  });

  const owned: string[] = [];
  const mounts: T[] = [];
  const refused: (T & { ownedBy: string })[] = [];

  for (const c of ordered) {
    // Walk from the root. `a/b` is owned by `a` — and by `a/b` itself, which
    // is the exact-duplicate case and is a collision too.
    const owner = owned.find((o) => c.route === o || c.route.startsWith(`${o}/`));
    if (owner !== undefined) {
      refused.push({ ...c, ownedBy: owner });
      continue;
    }
    owned.push(c.route);
    mounts.push(c);
  }
  return { mounts, refused };
}

function main(): number {
  const site = arg("site");
  if (!site) {
    console.error("usage: mount-instance-docs.ts --site <dir> [--built <instance-name>]");
    return 2;
  }
  const siteAbs = resolve(REPO, site);
  if (!existsSync(siteAbs)) {
    console.error(`--site ${site} does not exist. Run the site build first.`);
    return 1;
  }
  // Which instance Jekyll already rendered AT THE ROOT. Named rather than
  // guessed: the workflows pass `source: ./cat-harness/docs`, and a script
  // that inferred "the first one" would silently double-publish the day the
  // root instance changes.
  // Non-optional: `arg` returns `string | undefined` even with a fallback, and
  // an undefined instance name would make `publishedDocsPrefix` unanswerable
  // for a reason that is a typing artefact rather than a fact about the repo.
  const built = arg("built", "cat-harness") ?? "cat-harness";

  const found = mountable().filter((m) => {
    if (m.name === built && m.kind === "docs") {
      console.log(`  skip ${m.kind}/${m.name} — already built at the site root`);
      return false;
    }
    return true;
  });

  const { candidates, undetermined } = withRoutes(found);
  for (const u of undetermined) {
    console.error(
      `  ? /${u.name}/ is UNDETERMINED — ${u.kinds.length} renderable kinds (${u.kinds.join(", ")}) ` +
        `and none declares \`instanceRoot\`. Serving ${u.serving} because the order is deterministic, ` +
        `not because anything chose it.`,
    );
  }

  const { mounts, refused } = resolve_(candidates);

  for (const m of mounts) {
    const withheld = withheldPaths(m.dir);
    cpSync(m.dir, join(siteAbs, m.route), { recursive: true, filter: withheldFilter(m.dir, withheld) });
    if (withheld.length) {
      console.log(`  /${m.route}/: withheld ${withheld.length} path(s) named by its ${WITHHELD_FILE}: ${withheld.join(", ")}`);
    }
  }

  // THE HARNESS'S OWN NAVIGATION, put back on pages Jekyll never sees.
  //
  // These directories are copied verbatim and deliberately not run through
  // Jekyll (see the note above), so they inherit no `side-bar` — measured on
  // the published site: the root `index.html` has one, `/who-iris/` and
  // `/smart-trust/` have none. The rail is injected here rather than emitted
  // by each instance's generator because it is the HARNESS's navigation: one
  // implementation, and a new instance gets it without writing any.
  //
  // Injected AFTER the copy, never into the committed source, so an instance's
  // own gate still checks the page its generator produced.
  const docsPrefix = publishedDocsPrefix(REPO, built);
  if (docsPrefix === undefined) {
    // Could-not-determine, said out loud. Every per-kind rail link falls back
    // to its mount route, which is correct for a directory that declares no
    // visualiser and WRONG for one that does — so this is a finding, not a
    // quiet default.
    console.error(
      `  ? ${built} declares no docs directory, so no visualiser can be addressed. ` +
        `Rail links fall back to mount routes.`,
    );
  }
  const railed = injectRails(siteAbs, mounts, docsPrefix, built);
  for (const u of railed.unpublished) {
    console.error(
      `  ? /${u.route}/ declares the visualiser ${u.visualiser}, which is not under ` +
        `${docsPrefix}/ and therefore is not published. The rail links the mount route instead.`,
    );
  }

  if (mounts.length === 0 && refused.length === 0) {
    console.log("mount-instance-docs: nothing declared has rendered content to mount.");
    return 0;
  }
  console.log(`mount-instance-docs: ${mounts.length} mount(s), harness rail on ${railed.injected} page(s)`);
  if (railed.skipped.length) {
    // Named, never summed into a total. A page with no <body> is not a page
    // this rail belongs on, and a count alone could not be told from a bug.
    console.log(`  ${railed.skipped.length} file(s) took no rail (no <body> — fragment, stub or html by extension only):`);
    for (const f of railed.skipped.slice(0, 5)) console.log(`      ${f}`);
    if (railed.skipped.length > 5) console.log(`      … and ${railed.skipped.length - 5} more`);
  }
  // {@link railStandalonePages} is NOT called here, and that is the fix rather
  // than an omission. It runs from `rail-standalone-pages.ts` as a LAST step,
  // because this script runs at line 284 of `docs-site.yml` while
  // `publish-instance-files.ts` writes bootstrap's pages at line 426 — so a
  // call here walks the site before ten of its subjects exist. Measured on a
  // staged build: 23 wireframes railed, 10 bootstrap pages missed, and the
  // fixture could not see it because a fixture is always finished.

  for (const m of mounts) {
    // SOURCE count, said as such: since bean `cw35` a mount may withhold paths,
    // and printing the source total beside the route read as "this many were
    // published" (1,377 printed for a /who-iris/ that received 131).
    const w = withheldPaths(m.dir).length;
    console.log(
      `  ${m.dir.slice(REPO.length + 1)}  ->  /${m.route}/  (${countFiles(m.dir)} file(s) in source` +
        `${w ? `, ${w} withheld path(s) not copied` : ""})`,
    );
  }

  if (refused.length) {
    console.error(`\n${refused.length} claim(s) REFUSED — a path already owned by another handler:`);
    for (const r of refused) {
      console.error(`  /${r.route}/  (${r.dir.slice(REPO.length + 1)})`);
      console.error(`      the walk stops at /${r.ownedBy}/, which owns this subtree`);
    }
    console.error(
      "\nResolution rule: walk the path from the root; the first instantiated handler that\n" +
        "wants it processes it, and the walk stops. Give one of the two a distinct mount point.",
    );
    return 1;
  }
  return 0;
}

if (import.meta.main) process.exit(main());
