/**
 * Orphan subject pages — finding them, and the ownership test that makes
 * deleting one defensible.
 *
 * @module scripts/viewer-prune
 * @graphNode none — a helper for the viewer generators, not a schema
 *
 * ## The defect this closes
 *
 * Bean `ankg`, found live rather than hypothesised. #604 renamed
 * `folio-assist-sci/` to `folio-assistant-sci/`; subject slugs are derived
 * from the entry's PATH, so regeneration correctly wrote the new page — and
 * left the old one standing, serving a subject no declaration describes, at a
 * URL nothing links to.
 *
 * **`--check` was structurally blind to it.** It inspects the files it is
 * ABOUT TO WRITE, so a file the generator no longer writes is outside what it
 * looks at: it can find a page that is wrong, never one that should not exist.
 * That is the `yl5w` shape pointed the other way — there a claim resolved to
 * no file, here a file answers to no claim.
 *
 * ## Ownership comes from the FILE, never from the directory
 *
 * This is the load-bearing part, and it is
 * [`deletion-requires-confirmation`](../skills/folio-core/deletion-requires-confirmation.md)
 * applied to the tool most tempted to break it: an agent does not remove a
 * durable artefact it did not create. "Everything under this directory is
 * mine" is an assumption; "this file says it was generated by me" is a check.
 *
 * So a candidate is pruned only when its own bytes identify it, and anything
 * else — a hand-authored page, a stray file, something another tool put there
 * — is REPORTED and left. The directory scopes the SEARCH; the file decides
 * the DELETE.
 *
 * The shape is `prunableStickies` in `ensure-landing-sticky.ts`, whose third
 * filter is exactly this: it keeps only candidates that parse as the thing it
 * writes. Reused rather than reinvented, per the bean.
 *
 * It is a MODULE rather than a private helper on purpose. Bean `y90d`
 * anticipated this one as `orphanSubjectPages` inside `gen-schema-viz.ts` and
 * told the next generator not to write a fourth shape — then wrote a third
 * (`prunableDashboards`, #642) because there was nothing importable. A helper
 * that lives inside the generator it serves cannot be the thing anybody
 * reuses. Consolidating all three onto this module is bean `s8nu`; it is not
 * done here because #642 is live on that file.
 *
 * ## Two signatures, because the orphans predate the marker
 *
 * New pages carry {@link viewerMarker}. Pages written before it do not, and an
 * orphan is never rewritten — so it would never acquire the marker and would
 * never become prunable. A marker-only test would therefore be unable to
 * remove the very file that motivated this module. The legacy pair
 * (`DATA_HREF` and `SCOPE`, the two constants only these generators emit)
 * closes that gap without a migration.
 */
import { existsSync, readFileSync, readdirSync, rmSync, statSync } from "node:fs";
import { join } from "node:path";

/** The tag a generated viewer page carries, so ownership is checkable. */
export const VIEWER_MARKER = "folio:generated-viewer";

/**
 * The provenance comment a generator emits into its pages.
 *
 * Named with the GENERATOR rather than just "generated", so a page says which
 * tool owns it. Two generators publishing under one root would otherwise each
 * read the other's output as its own to delete.
 */
export function viewerMarker(generator: string): string {
  return `<!-- ${VIEWER_MARKER}: ${generator} — regenerate with its script; do not hand-edit -->`;
}

/**
 * Does this page's own content identify it as written by `generator`?
 *
 * Three states collapse to two here on purpose: "mine" and "not mine". An
 * unreadable file is NOT mine — a file we cannot inspect is precisely the one
 * not to delete.
 */
export function isGeneratedViewer(html: string, generator: string): boolean {
  if (html.includes(viewerMarker(generator))) return true;
  // Legacy: written before the marker existed. Both constants together, since
  // either alone is a weaker claim than this deletes on.
  return html.includes("var DATA_HREF = ") && html.includes("var SCOPE = ");
}

/** One orphan, and why it is one. */
export interface Orphan {
  /** Subject directory name, relative to the pages root. */
  subject: string;
  /** Absolute path of the page. */
  path: string;
  /**
   * `owned` — this generator wrote it, so it is prunable.
   * `foreign` — something else did, so it is reported and LEFT.
   */
  kind: "owned" | "foreign";
}

/**
 * Subject directories under `pagesRoot` that no longer answer to a subject.
 *
 * `wanted` is the set of subjects the generator is publishing this run. A
 * directory not in it is a candidate; whether it is prunable is then decided
 * by {@link isGeneratedViewer} on the page's own bytes.
 *
 * Returns both kinds, because a foreign orphan is a FINDING rather than
 * silence: something is published under this generator's root that this
 * generator did not write, and a reader deserves to know rather than have it
 * quietly skipped.
 */
export function findOrphans(
  pagesRoot: string,
  wanted: readonly string[],
  generator: string,
): Orphan[] {
  if (!existsSync(pagesRoot)) return [];
  const keep = new Set(wanted);
  const out: Orphan[] = [];

  for (const name of readdirSync(pagesRoot).sort()) {
    if (keep.has(name)) continue;
    const dir = join(pagesRoot, name);
    let isDir = false;
    try {
      isDir = statSync(dir).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;

    const page = join(dir, "index.html");
    if (!existsSync(page)) continue;

    let html: string;
    try {
      html = readFileSync(page, "utf8");
    } catch {
      // Unreadable is not "not mine proven" — it is "could not determine", and
      // the safe reading of that is to leave it and say so.
      out.push({ subject: name, path: page, kind: "foreign" });
      continue;
    }
    out.push({
      subject: name,
      path: page,
      kind: isGeneratedViewer(html, generator) ? "owned" : "foreign",
    });
  }
  return out;
}

/**
 * Delete the owned orphans, and return what was removed.
 *
 * Removes the SUBJECT DIRECTORY rather than only its `index.html`, because a
 * page left as an empty directory is still a URL that resolves — and only
 * after the ownership test has passed on the page inside it.
 */
export function pruneOrphans(pagesRoot: string, orphans: readonly Orphan[]): string[] {
  const removed: string[] = [];
  for (const o of orphans) {
    if (o.kind !== "owned") continue;
    rmSync(join(pagesRoot, o.subject), { recursive: true, force: true });
    removed.push(o.subject);
  }
  return removed;
}
