classDiagram
  direction TB
  namespace smart_trust__smart_trust_docs {
    class n_smart_trust_smart_trust_docs_docs["docs: no node schema"] {
      <<could not determine>>
    }
    class n_smart_trust_smart_trust_docs_ig_pages["ig-pages: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_trust_smart_trust_docs_docs" fa_uml_kind_docs
  cssClass "n_smart_trust_smart_trust_docs_docs" fa_uml_undetermined
  cssClass "n_smart_trust_smart_trust_docs_ig_pages" fa_uml_kind_ig_pages
  cssClass "n_smart_trust_smart_trust_docs_ig_pages" fa_uml_undetermined
