classDiagram
  direction TB
  namespace smart_trust__smart_trust_openapi {
    class smart_trust_smart_trust_openapi_folio_openapi_source_v1_folio_openapi_source_v1["folio-openapi-source/v1"] {
      <<json: OpenApiProvenanceSchema>>
      $schema [1] 'folio-openapi-source/v1'
      id [1] string
      file [1] string
      source [1] object
      bytes [1] integer
      openapi [1] string
      title [1] string
      version [1] string
      operations [1] integer
      materialization [1] object
    }
  }
  cssClass "smart_trust_smart_trust_openapi_folio_openapi_source_v1_folio_openapi_source_v1" fa_uml_kind_openapi
