classDiagram
  direction TB
  namespace smart_trust__smart_trust_scripts {
    class n_smart_trust_smart_trust_scripts_code["code: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_smart_trust_smart_trust_scripts_code" fa_uml_kind_code
  cssClass "n_smart_trust_smart_trust_scripts_code" fa_uml_undetermined
